import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'vite';
import {blankProfile,blankSnapshot} from '../host/instance-runtime/blank.mjs';
import {canonicalJson} from '../host/instance-runtime/bytes.mjs';
import {createInstanceRepository} from '../host/instance-runtime/index.mjs';
import {ANIMATIC_NS} from '../host/instance-runtime/animatic-service.mjs';
import {ANIMATIC_RECOVERY_NS} from '../host/instance-runtime/animatic-recovery.mjs';
test('real recovery API queues inspection only, binds job/epoch CAS, replays idempotently and respects Origin/read-only',{timeout:30000},async()=>{
 const root=path.resolve(import.meta.dirname,'..'),parent=path.join(root,'tests/.test-tmp');await mkdir(parent,{recursive:true});const temporary=await mkdtemp(path.join(parent,'animatic-recovery-api-')),profile=blankProfile(),fixture=blankSnapshot(profile),dbPath=path.join(temporary,'test.sqlite'),repo=createInstanceRepository({dbPath,instanceId:profile.instanceId,profile});await repo.writeTransaction(tx=>tx.publishRelease({...fixture,expectedReleaseId:null}));const meta=await repo.getMetadata(),sceneId='scene:recovery',jobId='render:crashed',job={jobId,sceneId,status:'RUNNING',instanceId:meta.instanceId,runtimeEpoch:'origin-before-restore',createdAt:'2026-09-08',timelineRevisionId:'frozen:timeline'},jobRow=await repo.writeTransaction(tx=>tx.putAux({namespace:ANIMATIC_NS.jobs,key:jobId,bytes:canonicalJson(job),expectedRevisionId:null}));
 const keys=['REVIEW_INSTANCE_DB','REVIEW_INSTANCE_ID','REVIEW_INSTANCE_ROOT','REVIEW_INSTANCE_READ_ONLY','REVIEW_REMOTE_READ_ONLY','REVIEW_SITE_ROOT','REVIEW_EXPORT_DIR','REVIEW_ALLOWED_ORIGINS'],env=Object.fromEntries(keys.map(k=>[k,process.env[k]]));Object.assign(process.env,{REVIEW_INSTANCE_DB:dbPath,REVIEW_INSTANCE_ID:profile.instanceId,REVIEW_INSTANCE_ROOT:'',REVIEW_INSTANCE_READ_ONLY:'',REVIEW_REMOTE_READ_ONLY:'',REVIEW_SITE_ROOT:root,REVIEW_EXPORT_DIR:'',REVIEW_ALLOWED_ORIGINS:'http://localhost'});
 const server=await createServer({root,configFile:false,logLevel:'error',cacheDir:path.join(temporary,'cache'),server:{middlewareMode:true,hmr:false},appType:'custom'});let store;
 try{store=await server.ssrLoadModule('/app/api/v8/_store.ts');const route=await server.ssrLoadModule('/app/api/instance/shot-production/animatics/route.ts'),body={action:'reconcile',sceneId,jobId,expectedJobRevisionId:jobRow.revisionId,expectedRuntimeEpoch:meta.runtimeEpoch,expectedReleaseId:meta.releaseId},call=(headers,change={})=>route.POST(new Request('http://localhost/api/instance/shot-production/animatics',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({...body,...change})})),before=await repo.exportState();
  assert.equal((await call({})).status,403);assert.equal((await call({Origin:'http://localhost'})).status,428);assert.equal((await call({Origin:'http://localhost','If-Match':'stale','Idempotency-Key':'reconcile:stale'})).status,412);
  const headers={Origin:'http://localhost','If-Match':(await store.operationalSnapshot()).mutationEtag,'Idempotency-Key':'reconcile:exact'};for(const change of [{expectedJobRevisionId:'wrong'},{expectedRuntimeEpoch:'wrong'},{expectedReleaseId:'wrong'}])assert.equal((await call(headers,change)).status,409);assert.deepEqual(await repo.exportState(),before);
  const queued=await call(headers);assert.equal(queued.status,200);const receipt=await queued.json();assert.equal(receipt.status,'QUEUED');assert.equal(receipt.automaticRetry,false);assert.ok(receipt.reconciliationId);const after=await repo.exportState();assert.equal(JSON.parse((await repo.getAux(ANIMATIC_NS.jobs,jobId)).bytes).status,'RUNNING');assert.equal((await repo.listAux(ANIMATIC_RECOVERY_NS.jobs)).length,1);assert.equal((await repo.listAux(ANIMATIC_NS.revisions)).length,0);assert.deepEqual((await repo.readView()).eventsByKind,before.eventsByKind||{});
  const replay=await call({...headers,'If-Match':(await store.operationalSnapshot()).mutationEtag});assert.equal(replay.status,200);assert.deepEqual(await replay.json(),receipt);assert.deepEqual(await repo.exportState(),after);
  const get=await route.GET(new Request('http://localhost/api/instance/shot-production/animatics?sceneId='+sceneId));assert.equal(get.status,200);const state=await get.json();assert.equal(state.runtimeEpoch,meta.runtimeEpoch);assert.equal(state.jobs[0].jobRevisionId,jobRow.revisionId);assert.equal(state.jobs[0].pendingReconciliation.reconciliationId,receipt.reconciliationId);
  process.env.REVIEW_INSTANCE_READ_ONLY='1';assert.equal((await call({})).status,405);assert.deepEqual(await repo.exportState(),after);
 }finally{process.env.REVIEW_INSTANCE_READ_ONLY='';await(await store?.instanceRepository())?.close();await repo.close();await server.close();for(const key of keys){if(env[key]===undefined)delete process.env[key];else process.env[key]=env[key];}await rm(temporary,{recursive:true,force:true});}
});
