import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
const site=fileURLToPath(new URL('../',import.meta.url)),media={familyId:'board',versionId:'board@V001',sha256:'a'.repeat(64)};
const content={schemaVersion:'1.0',sceneId:'scene:one',shotPlanRevisionId:'plan:one',fps:24,width:1920,height:1080,shots:[{shotId:'shot:A',durationFrames:48,panels:[{id:'panel:A',media,startFrame:0,endFrame:48,motion:'PUSH_IN'}],beats:[{id:'beat:A',frame:12,label:'迟疑'}]},{shotId:'shot:B',durationFrames:24,panels:[{id:'panel:B',media,startFrame:0,endFrame:24,motion:'STILL'}],beats:[]}],audio:[],cards:[]};
async function fixture(page:Page,{readOnly=true,serverReadOnly=false,empty=false,stale=false,status='SUCCEEDED',failure=''}={}){
 const writes:Record<string,unknown>[]=[],errors:string[]=[],unexpected:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const state={runtimeEpoch:'epoch:current',sceneId:'scene:one',releaseId:'release:one',revisionId:'head:one',timelineRevisionId:empty?null:'timeline:one',content:empty?null:content,hashes:{timelineHash:'d'.repeat(64),totalFrames:72},impact:[],readOnly:serverReadOnly,stale,blockers:empty?['正式镜头计划尚未建立']:[],availableMedia:[{...media,path:'media/board.png',label:'正式粗分镜',kind:'IMAGE',mediaUrl:'/media/animatic/board.png'}],requiredCards:[],jobs:empty?[]:[{jobId:'job:one',jobRevisionId:'job-revision:one',pendingReconciliation:null as null|{reconciliationId:string;status:string},status,timelineRevisionId:'timeline:one',result:{mediaUrl:'/media/animatic/preview.mp4',versionId:'preview@V001',sha256:'e'.repeat(64)}}],lock:null,basis:empty?null:{sceneId:'scene:one',shotPlanRevisionId:stale?'plan:current':'plan:one',shots:[{shotId:stale?'shot:current':'shot:A',durationFrames:48,title:'当前设计'},...(!stale?[{shotId:'shot:B',durationFrames:24,title:'第二镜'}]:[])]}};
 const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{AnimaticWorkspace}from'./app/animatic-workspace';createRoot(document.getElementById('root')).render(<main style={{maxWidth:1050,margin:'auto'}}><AnimaticWorkspace sceneId="scene:one" readOnly={${readOnly}}/></main>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:site,sourcefile:'animatic-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-animatic',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname==='/api/v8/operations/snapshot')return route.fulfill({json:{mutationEtag:'"current"'}});if(url.pathname==='/api/instance/shot-production/animatics'){if(request.method()==='GET')return route.fulfill({json:state});const body=request.postDataJSON();writes.push(body);if(readOnly||serverReadOnly)return route.fulfill({status:405,json:{error:'只读'}});if(failure==='4xx')return route.fulfill({status:409,json:{error:'当前依据已变化'}});let receipt;if(body.action==='save'){state.content=body.content;state.stale=false;state.timelineRevisionId='timeline:new';state.revisionId='head:new';receipt={timelineRevisionId:'timeline:new',revisionId:'head:new'};}else if(body.action==='render'){state.jobs=[{jobId:'job:new',jobRevisionId:'job-revision:new',pendingReconciliation:null,status:'QUEUED',timelineRevisionId:state.timelineRevisionId||'',result:{mediaUrl:'',versionId:'',sha256:''}}];receipt={jobId:'job:new',status:'QUEUED'};}else{state.jobs[0].pendingReconciliation={reconciliationId:'check:one',status:'QUEUED'};receipt={reconciliationId:'check:one',status:'QUEUED',automaticRetry:false};}
 if(failure==='500')return route.fulfill({status:500,json:{error:'lost after commit'}});if(failure==='malformed')return route.fulfill({status:200,contentType:'application/json',body:'{broken'});if(failure==='network')return route.abort();if(failure==='empty')return route.fulfill({json:{timelineRevisionId:'',revisionId:'',reconciliationId:'',status:'QUEUED',automaticRetry:false}});return route.fulfill({json:receipt});}unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,json:{error:'UNEXPECTED'}});});
 await page.route('**/media/animatic/**',route=>route.request().url().endsWith('.png')?route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')}):route.fulfill({status:204}));
 await page.route('**/__animatic',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="root"></div><script>${js.replaceAll('</script','<\/script')}</script></body></html>`}));await page.goto('/__animatic');return{writes,errors,unexpected};
}
test('read-only timeline retains images, frame navigation, motion and video without enabling edits or review claims',async({page})=>{
 const f=await fixture(page);await expect(page.getByRole('img',{name:'shot:A 粗分镜'})).toBeVisible();await expect(page.getByRole('spinbutton',{name:'镜长（帧）'}).first()).toBeDisabled();await expect(page.getByRole('button',{name:'保存时间线新修订'})).toBeDisabled();await expect(page.getByRole('button',{name:'生成审阅预演'})).toBeDisabled();await expect(page.locator('video')).toHaveAttribute('src','/media/animatic/preview.mp4');await page.getByRole('button',{name:'shot:B 24 帧 · 1.000 秒'}).click();await expect(page.getByRole('img',{name:'shot:B 粗分镜'})).toBeVisible();await expect(page.getByRole('slider',{name:'预演播放位置'})).toHaveValue('48');await page.getByRole('button',{name:'播放草稿'}).click();await expect(page.getByText('待正式审阅锁时',{exact:true})).toBeVisible();expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);
});
test('server-enforced read-only also disables authoring when the containing workspace is editable',async({page})=>{
 const f=await fixture(page,{readOnly:false,serverReadOnly:true});await expect(page.getByRole('spinbutton',{name:'镜长（帧）'}).first()).toBeDisabled();await expect(page.getByRole('button',{name:'添加动作点'}).first()).toBeDisabled();await expect(page.getByRole('button',{name:'生成审阅预演'})).toBeDisabled();expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);
});
test('empty read-only scene does not invent a shot denominator or expose initialization',async({page})=>{
 const f=await fixture(page,{empty:true});await expect(page.getByText('正式镜头计划尚未建立',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'从当前镜头计划建立预演草稿'})).toHaveCount(0);await expect(page.locator('video')).toHaveCount(0);expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);
});
test('stale timeline explicitly starts current plan, saves a new revision and queues it without rebinding old panels',async({page})=>{
 const f=await fixture(page,{readOnly:false,stale:true});await expect(page.getByRole('spinbutton',{name:'镜长（帧）'}).first()).toBeDisabled();await page.getByRole('button',{name:'按当前镜头计划新建预演草稿'}).click();await expect(page.getByRole('spinbutton',{name:'镜长（帧）'})).toBeEnabled();await expect(page.getByRole('img')).toHaveCount(0);await page.getByRole('spinbutton',{name:'镜长（帧）'}).fill('60');await page.getByRole('button',{name:'保存时间线新修订'}).click();await expect(page.getByRole('button',{name:'生成审阅预演'})).toBeEnabled();await page.getByRole('button',{name:'生成审阅预演'}).click();await expect(page.getByText('等待预演工作器')).toBeVisible();expect(f.writes).toHaveLength(2);expect(f.writes[0]).toMatchObject({action:'save',expectedRevisionId:'head:one',content:{shotPlanRevisionId:'plan:current',shots:[{shotId:'shot:current',durationFrames:60,panels:[]}]}});expect(f.writes[1]).toMatchObject({action:'render',expectedRevisionId:'head:new',timelineRevisionId:'timeline:new'});expect(f.errors).toEqual([]);
});
for(const failure of ['500','malformed','network','empty'])test(`uncertain save ${failure} requires explicit reread and retains local edit`,async({page})=>{
 const f=await fixture(page,{readOnly:false,failure});await page.getByRole('spinbutton',{name:'镜长（帧）'}).first().fill('60');await page.getByRole('button',{name:'保存时间线新修订'}).click();await expect(page.getByText('提交结果待核查；请先重读当前时间线与任务，确认后再操作。')).toBeVisible();await expect(page.getByRole('button',{name:'保存时间线新修订'})).toBeDisabled();await expect(page.getByRole('button',{name:'生成审阅预演'})).toBeDisabled();await page.getByRole('button',{name:'重读当前时间线与任务（保留草稿）'}).click();await expect(page.getByRole('button',{name:'保存时间线新修订'})).toBeEnabled();await expect(page.getByRole('spinbutton',{name:'镜长（帧）'}).first()).toHaveValue('60');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('explicit 4xx retains editable draft without claiming an unknown submission',async({page})=>{
 const f=await fixture(page,{readOnly:false,failure:'4xx'});await page.getByRole('spinbutton',{name:'镜长（帧）'}).first().fill('60');await page.getByRole('button',{name:'保存时间线新修订'}).click();await expect(page.getByText('当前依据已变化',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'保存时间线新修订'})).toBeEnabled();await expect(page.getByRole('button',{name:'重读当前时间线与任务（保留草稿）'})).toHaveCount(0);expect(f.writes).toHaveLength(1);
});
for(const status of ['RUNNING','RESULT_UNKNOWN'])test(`${status} exposes precise recovery and waits for worker without retry`,async({page})=>{
 const f=await fixture(page,{readOnly:false,status,failure:'empty'});await page.getByRole('button',{name:'核查任务结果'}).click();await expect(page.getByRole('button',{name:'核查任务结果'})).toBeDisabled();await page.getByRole('button',{name:'重读当前时间线与任务（保留草稿）'}).click();await expect(page.getByText('等待受控工作器核查；不会自动重新渲染。')).toBeVisible();await expect(page.getByRole('button',{name:'核查任务结果'})).toHaveCount(0);await expect(page.getByRole('button',{name:'生成审阅预演'})).toBeDisabled();expect(f.writes).toEqual([{action:'reconcile',sceneId:'scene:one',jobId:'job:one',expectedJobRevisionId:'job-revision:one',expectedRuntimeEpoch:'epoch:current',expectedReleaseId:'release:one'}]);expect(f.errors).toEqual([]);
});
test('read-only stale and unknown timeline exposes no rebind or recovery write',async({page})=>{
 const f=await fixture(page,{stale:true,status:'RESULT_UNKNOWN'});await expect(page.getByRole('button',{name:'按当前镜头计划新建预演草稿'})).toHaveCount(0);await expect(page.getByRole('button',{name:'核查任务结果'})).toHaveCount(0);expect(f.writes).toEqual([]);
});
test('malformed reread cannot clear UNKNOWN or replace the local draft; a subsequent valid reread recovers',async({page})=>{
 const f=await fixture(page,{readOnly:false,failure:'500'});await page.getByRole('spinbutton',{name:'镜长（帧）'}).first().fill('60');await page.getByRole('button',{name:'保存时间线新修订'}).click();const reread=page.getByRole('button',{name:'重读当前时间线与任务（保留草稿）'});await expect(reread).toBeVisible();await page.route('**/api/instance/shot-production/animatics?sceneId=*',route=>route.fulfill({json:{sceneId:'scene:one',releaseId:'release:one',jobs:[]}}),{times:1});await reread.click();await expect(page.getByText('时间线回执无效，请继续重读；草稿与待核状态已保留')).toBeVisible();await expect(reread).toBeVisible();await expect(page.getByRole('button',{name:'保存时间线新修订'})).toBeDisabled();await expect(page.getByRole('button',{name:'生成审阅预演'})).toBeDisabled();await expect(page.getByRole('spinbutton',{name:'镜长（帧）'}).first()).toHaveValue('60');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);await reread.click();await expect(reread).toHaveCount(0);await expect(page.getByRole('button',{name:'保存时间线新修订'})).toBeEnabled();await expect(page.getByRole('spinbutton',{name:'镜长（帧）'}).first()).toHaveValue('60');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
