import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'vite';
import {blankProfile,blankSnapshot} from '../host/instance-runtime/blank.mjs';
import {createInstanceRepository} from '../host/instance-runtime/index.mjs';
import {animaticHashes,selectAnimaticLockForShot} from '../host/instance-runtime/animatic-model.mjs';
import {publicAnimaticExport} from '../scripts/instance-hosted-export.mjs';
import {hostedEventProjection} from '../scripts/export-hosted-material-events.mjs';
const sceneId='scene:animatic',input={familyId:'board',versionId:'board@V001',sha256:'a'.repeat(64)};
const content={schemaVersion:'1.0',sceneId,shotPlanRevisionId:'plan:one',fps:24,width:1920,height:1080,shots:[{shotId:'shot:A',durationFrames:48,panels:[{id:'panel:A',media:input,startFrame:0,endFrame:48,motion:'PUSH_IN'}],beats:[]}],audio:[],cards:[]};
const mediaRow=(b,extension='png',metadata={authorityDomain:'FORMAL'})=>({mediaId:b.familyId,versionId:b.versionId,sha256:b.sha256,relativePath:'media/'+b.versionId+'.'+extension,availability:'PRESENT',byteSize:5,aliases:[],metadata});
function publicFixture(){const output={familyId:'animatic',versionId:'animatic@V001',sha256:'b'.repeat(64)},registrationEventId='event:render',rows=[mediaRow(input),mediaRow(output,'mp4')],model={assetFamilies:[],assetVersions:rows.map(r=>({id:r.versionId,familyId:r.mediaId,sha256:r.sha256,path:r.relativePath})),workItems:[],shotPlanSetRevisions:[{id:'plan:one',scopeId:sceneId,scopeRole:'CURRENT'}],animaticTimelines:[{sceneId,timelineRevisionId:'timeline:one',content,hashes:animaticHashes(content)}],animaticRenderJobs:[{jobId:'job:one',sceneId,timelineRevisionId:'timeline:one',timelineHash:animaticHashes(content).timelineHash,status:'SUCCEEDED',createdAt:'2026-09-08',workItemId:'work:animatic',workerId:'/private/worker',error:'internal diagnostic',inputBindings:[input],expectedOutput:{id:'eo:one'},registrationVerified:true,result:{...output,registrationEventId,relativePath:rows[1].relativePath,byteSize:5,frameCount:48,fps:24,width:1920,height:1080}}],animaticLocks:[{sceneId,renderJobId:'job:one',timelineRevisionId:'timeline:one',scopeRole:'CURRENT',fullSceneCurrent:true,applicableShotIds:['shot:A']}]};return{model,rows,output};}
test('public process export keeps exact media and strips private inputs and worker diagnostics',()=>{
 const {model,rows}=publicFixture(),result=publicAnimaticExport(model,rows);assert.equal(result.media.length,2);assert.equal(result.model.animaticLocks.length,1);assert.match(result.model.animaticRenderJobs[0].result.mediaUrl,/^\/media\/animatic\//);assert.equal('workerId' in result.model.animaticRenderJobs[0],false);assert.equal('error' in result.model.animaticRenderJobs[0],false);assert.equal(result.model.assetVersions[0].mediaUrl,result.model.publicProductionMedia[0].mediaUrl);
 rows[0].metadata.sourceRole='ORIGINAL_SOURCE';const privateResult=publicAnimaticExport(model,rows);assert.equal(privateResult.media.length,0);assert.equal(privateResult.model.animaticTimelines.length,0);assert.equal(privateResult.model.animaticLocks.length,0);
});
test('public manifest is registered JSON with exact proof and no fabricated model request',async()=>{
 const {model,rows}=publicFixture(),manifest={familyId:'manifest',versionId:'manifest@V001',sha256:'c'.repeat(64)},row=mediaRow(manifest,'json'),job={jobId:'manifest:one',status:'SUCCEEDED',registrationVerified:true,workItemId:'work:manifest',expectedOutput:{id:'eo:manifest'},inputBindings:[input],manifestHash:'d'.repeat(64),content:{schemaVersion:'1.0',inputBindings:[input]},result:{...manifest,relativePath:row.relativePath,byteSize:5,registrationEventId:'event:manifest'},workerId:'SECRET',error:'SECRET'};model.shotProductionManifestJobs=[job];rows.push(row);const projected=publicAnimaticExport(model,rows);assert.equal(projected.model.shotProductionManifestJobs.length,1);assert.match(projected.model.shotProductionManifestJobs[0].result.mediaUrl,/\.json$/);assert.equal(JSON.stringify(projected.model.shotProductionManifestJobs).includes('SECRET'),false);
 const profile=blankProfile(),snapshot=blankSnapshot(profile).snapshot;Object.assign(snapshot.productionModel,projected.model,{materialWorkItems:[],publicExportMediaBindings:projected.media.map(m=>({familyId:m.mediaId,versionId:m.versionId,sha256:m.sha256}))});const proof={eventId:'event:manifest',executorKind:'DETERMINISTIC_MANIFEST',...manifest,manifestJobId:job.jobId,manifestHash:job.manifestHash},review={eventId:'review:manifest',subjectType:'WORK_PRODUCT',...manifest,action:'APPROVE_AND_RELEASE',shotProductionEvidence:{observedVideoIds:['animatic@V001']}};const bundle=await hostedEventProjection({snapshot,profile,eventsByKind:{'asset-version':[proof,{...proof,eventId:'mismatched:sha',sha256:'0'.repeat(64)},{eventId:'private:candidate',familyId:manifest.familyId,versionId:'private:version'}],review:[review,{...review,eventId:'mismatched:review',versionSha256:'0'.repeat(64)},{eventId:'private:review',subjectType:'WORK_PRODUCT',familyId:manifest.familyId,versionId:'private:version'}]}});assert.deepEqual(bundle.events['asset-version'],[proof]);assert.deepEqual(bundle.events.review,[review]);assert.deepEqual(bundle.events['execution-request'],[]);
});
test('per-shot lock selection chooses latest applicable proof without requiring a unique scene lock',()=>{
 const slice=animaticHashes(content).shotSlices[0],base={sceneId,shotPlanRevisionId:'plan:one',scopeRole:'CURRENT',shotSlices:[slice]},old={...base,lockedAt:'2026-09-07',reviewEventId:'old'},latest={...base,lockedAt:'2026-09-08',reviewEventId:'latest',applicableShotIds:['shot:B']};assert.equal(selectAnimaticLockForShot([old,latest],{sceneId,shotPlanRevisionId:'plan:one',shotId:'shot:A'}).lock.reviewEventId,'old');latest.applicableShotIds=['shot:A'];assert.equal(selectAnimaticLockForShot([old,latest],{sceneId,shotPlanRevisionId:'plan:one',shotId:'shot:A'}).slice.durationFrames,48);assert.equal(selectAnimaticLockForShot([old,latest],{sceneId,shotPlanRevisionId:'plan:one',shotId:'shot:A'}).lock.reviewEventId,'latest');
});
test('real API preserves blank instance, enforces Origin/CAS and serves frozen read-only timeline media',async()=>{
 const root=path.resolve(import.meta.dirname,'..'),parent=path.join(root,'tests/.test-tmp');await mkdir(parent,{recursive:true});const temporary=await mkdtemp(path.join(parent,'animatic-api-')),profile=blankProfile(),fixture=blankSnapshot(profile),dbPath=path.join(temporary,'test.sqlite'),repo=createInstanceRepository({dbPath,instanceId:profile.instanceId,profile});await repo.writeTransaction(tx=>tx.publishRelease({...fixture,expectedReleaseId:null}));
 const keys=['REVIEW_INSTANCE_DB','REVIEW_INSTANCE_ID','REVIEW_INSTANCE_ROOT','REVIEW_INSTANCE_READ_ONLY','REVIEW_REMOTE_READ_ONLY','REVIEW_SITE_ROOT','REVIEW_EXPORT_DIR','REVIEW_ALLOWED_ORIGINS'],env=Object.fromEntries(keys.map(k=>[k,process.env[k]]));Object.assign(process.env,{REVIEW_INSTANCE_DB:dbPath,REVIEW_INSTANCE_ID:profile.instanceId,REVIEW_INSTANCE_ROOT:'',REVIEW_INSTANCE_READ_ONLY:'',REVIEW_REMOTE_READ_ONLY:'',REVIEW_SITE_ROOT:root,REVIEW_EXPORT_DIR:'',REVIEW_ALLOWED_ORIGINS:'http://localhost'});
 const server=await createServer({root,configFile:false,logLevel:'error',cacheDir:path.join(temporary,'cache'),server:{middlewareMode:true},appType:'custom'});let store;
 try{store=await server.ssrLoadModule('/app/api/v8/_store.ts');const api=await server.ssrLoadModule('/app/api/instance/shot-production/animatics/route.ts'),before=await repo.exportState(),get=await api.GET(new Request('http://localhost/api/instance/shot-production/animatics?sceneId='+sceneId));assert.equal(get.status,200);const empty=await get.json();assert.equal(empty.content,null);assert.equal(empty.basis,null);assert.ok(empty.blockers.length);
  const request=headers=>new Request('http://localhost/api/instance/shot-production/animatics',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({action:'lock',sceneId})});assert.equal((await api.POST(request({}))).status,403);assert.equal((await api.POST(request({Origin:'http://localhost'}))).status,428);assert.equal((await api.POST(request({Origin:'http://localhost','If-Match':'"stale"','Idempotency-Key':'test:animatic:api'}))).status,412);const operational=await store.operationalSnapshot();assert.equal((await api.POST(request({Origin:'http://localhost','If-Match':operational.mutationEtag,'Idempotency-Key':'test:animatic:lock'}))).status,422);const siblings=[];for(const [endpoint,body] of [['/app/api/instance/shot-production/route.ts',{action:'unsupported',sceneId}],['/app/api/instance/shot-production/recipes/route.ts',{action:'unsupported',workItemId:'work:missing'}]]){const route=await server.ssrLoadModule(endpoint),call=headers=>route.POST(new Request('http://localhost'+endpoint.replace('/app','').replace('/route.ts',''),{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}));assert.equal((await call({})).status,403,endpoint);assert.equal((await call({Origin:'http://localhost'})).status,428,endpoint);assert.equal((await call({Origin:'http://localhost','If-Match':'"stale"','Idempotency-Key':'test:animatic:sibling'})).status,412,endpoint);assert.equal((await call({Origin:'http://localhost','If-Match':operational.mutationEtag,'Idempotency-Key':'test:animatic:unsupported'})).status,422,endpoint);siblings.push(call);}process.env.REVIEW_INSTANCE_READ_ONLY='1';assert.equal((await api.POST(request({}))).status,405);for(const call of siblings)assert.equal((await call({})).status,405);assert.deepEqual(await repo.exportState(),before);
  process.env.REVIEW_REMOTE_READ_ONLY='1';process.env.REVIEW_SITE_ROOT=temporary;await mkdir(path.join(temporary,'app'),{recursive:true});await writeFile(path.join(temporary,'app/review-data.generated.json'),JSON.stringify(fixture.snapshot));const {model,rows}=publicFixture(),publicModel=publicAnimaticExport(model,rows).model,{productionModel,...core}=fixture.snapshot;publicModel.publicExportMediaBindings=[{familyId:'animatic',versionId:'animatic@V001',sha256:'b'.repeat(64)}];await mkdir(path.join(temporary,'public/runtime'),{recursive:true});for(const [filename,value] of Object.entries({'review-data-core.generated.json':core,'review-data-production-a.generated.json':{snapshotId:core.snapshotId,productionModel:{...productionModel,...publicModel}},'review-data-production-b.generated.json':{snapshotId:core.snapshotId,productionModel:{}}}))await writeFile(path.join(temporary,'public/runtime',filename),JSON.stringify(value));const frozen=await api.GET(new Request('http://localhost/api/instance/shot-production/animatics?sceneId='+sceneId));assert.equal(frozen.status,200);const data=await frozen.json();assert.equal(data.readOnly,true);assert.equal(data.content.shots[0].durationFrames,48);assert.equal(data.jobs.length,1);assert.equal(data.availableMedia.length,2);assert.deepEqual(data.impact,[]);const publicState=store.projectOperationalState(await store.reviewData(),[],[],[]);assert.equal(publicState.assetVersionsById[input.versionId].canFlowDownstream,false);assert.ok(publicState.assetVersionsById[input.versionId].flowBlockReasons.includes('PUBLIC_MEDIA_NOT_EXPORTED'));assert.equal(publicState.assetVersionsById['animatic@V001'].flowBlockReasons.includes('PUBLIC_MEDIA_NOT_EXPORTED'),false);assert.equal((await api.POST(request({}))).status,405);for(const call of siblings)assert.equal((await call({})).status,405);
 }finally{process.env.REVIEW_SITE_ROOT=root;process.env.REVIEW_REMOTE_READ_ONLY='';process.env.REVIEW_INSTANCE_READ_ONLY='';(await store?.instanceRepository())?.close();repo.close();await server.close();for(const key of keys){if(env[key]===undefined)delete process.env[key];else process.env[key]=env[key];}await rm(temporary,{recursive:true,force:true});}
});
test('public media allowlist rejects private, trial, original and unknown registrations including same-SHA aliases',()=>{
 const cases=[{authorityDomain:'PRIVATE'},{authorityDomain:'LOCAL_TRIAL'},{authorityDomain:'FORMAL',visibility:'PRIVATE'},{authorityDomain:'FORMAL',sourceRole:'ORIGINAL_SOURCE'},{authorityDomain:'FORMAL',private:true},{authorityDomain:'FORMAL',countsTowardFormalProject:false},{authorityDomain:'FORMAL',trialScopeId:'trial:one'},{authorityDomain:'UNKNOWN'},{}];
 for(const metadata of cases){const direct=publicFixture();direct.rows[0].metadata=metadata;assert.equal(publicAnimaticExport(direct.model,direct.rows).media.length,0,JSON.stringify(metadata));const alias=publicFixture();alias.rows.push({...mediaRow({familyId:'other',versionId:'other@V001',sha256:input.sha256}),metadata});assert.equal(publicAnimaticExport(alias.model,alias.rows).media.length,0,'same SHA '+JSON.stringify(metadata));const process={assetVersions:direct.model.assetVersions,workItems:[{scopeRole:'CURRENT',activeInCurrentProduction:true,shotProductionPlanId:'production:one',outputAssetRef:input.familyId,deliverableKey:'STORYBOARD'}]};assert.equal(publicAnimaticExport(process,direct.rows).media.length,0,'current process '+JSON.stringify(metadata));}
 const privateAlias=publicFixture();privateAlias.rows.push({...mediaRow({familyId:'alias',versionId:'alias@V001',sha256:input.sha256}),aliases:['/media/private/board.png']});assert.equal(publicAnimaticExport(privateAlias.model,privateAlias.rows).media.length,0);
 for(const authorityDomain of ['FORMAL','IMPORTED_EVIDENCE']){const allowed=publicFixture();allowed.rows[0].metadata={authorityDomain,visibility:'PUBLIC'};assert.equal(publicAnimaticExport(allowed.model,allowed.rows).media.length,2);}
});
