import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {animaticHash,animaticHashes,animaticImpact,validateAnimaticTimeline} from '../host/instance-runtime/animatic-model.mjs';
import {readAnimaticState,saveAnimaticTimeline,enqueueAnimaticRender,claimAnimaticRender,finishAnimaticRender,applyAnimaticProjection,animaticCandidateMatchesJob,ANIMATIC_NS,lockAnimaticTimeline,reconcileAnimaticLocks} from '../host/instance-runtime/animatic-service.mjs';
import {createInstanceRepository} from '../host/instance-runtime/index.mjs';
import {blankProfile,blankSnapshot} from '../host/instance-runtime/blank.mjs';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {animaticProcess,renderAnimatic} from '../host/instance-runtime/animatic-render.mjs';

const media={familyId:'family:board',versionId:'family:board@V001',sha256:'a'.repeat(64)};
const panel=(id,durationFrames=24)=>({shotId:id,durationFrames,panels:[{id:'panel:'+id,media,startFrame:0,endFrame:durationFrames,motion:'STILL'}],beats:[]});
const timeline=()=>({schemaVersion:'1.0',sceneId:'scene:test',shotPlanRevisionId:'plan:one',fps:24,width:1920,height:1080,shots:[panel('shot:A'),panel('shot:B'),panel('shot:C')],audio:[],cards:[]});
test('frame validation rejects gaps, duplicates, stale scope and injected render parameters',()=>{
 const v=timeline();assert.equal(validateAnimaticTimeline(v,{sceneId:v.sceneId,shotPlanRevisionId:v.shotPlanRevisionId,shotIds:v.shots.map(s=>s.shotId)}).shots.length,3);
 for(const mutate of [x=>{x.shots[0].durationFrames=2.5;},x=>{x.shots[1].shotId=x.shots[0].shotId;},x=>{x.shots[0].panels[0].startFrame=1;},x=>{x.filter='movie=/etc/passwd';},x=>{x.fps=25;}]){const bad=structuredClone(v);mutate(bad);assert.throws(()=>validateAnimaticTimeline(bad));}
 assert.throws(()=>validateAnimaticTimeline(v,{shotIds:['historic:one']}));
});
test('local timing avoids cascading after one duration edit; adjacency and overlays stay independent',()=>{
 const v=timeline(),next=structuredClone(v);next.shots[0].durationFrames=48;next.shots[0].panels[0].endFrame=48;
 const hashes=animaticHashes(v),changed=animaticHashes(next);assert.equal(hashes.shotSlices[1].timingHash,changed.shotSlices[1].timingHash);assert.equal(hashes.shotSlices[2].timingHash,changed.shotSlices[2].timingHash);assert.deepEqual(animaticImpact(v,next).map(s=>s.shotId),['shot:A']);
 const reordered=structuredClone(v);[reordered.shots[1],reordered.shots[2]]=[reordered.shots[2],reordered.shots[1]];assert.equal(animaticImpact(v,reordered).filter(s=>s.boundaryChanged).length,3);
 const overlay=structuredClone(v);overlay.cards.push({id:'card:one',shotId:'shot:B',startFrame:0,endFrame:12,textLines:['人物','当场身份'],fontMedia:media,style:{x:96,y:54,fontSize:40,color:'#ffffff'},specRevisionId:'spec:one',specHash:'b'.repeat(64)});const delta=animaticImpact(v,overlay);assert.equal(delta[0].overlayChanged,true);assert.equal(delta[0].visualChanged,false);assert.equal(delta[0].timingChanged,false);
});
test('cross-cut dialogue contributes only its actual local overlap and temporary audio is explicit',()=>{
 const v=timeline();v.audio.push({id:'audio:one',anchorShotId:'shot:A',offsetFrames:12,sourceInFrames:0,durationFrames:36,media,role:'DIALOGUE',temporary:true,volume:1,muted:false,lineIds:['line:one']});validateAnimaticTimeline(v);const n=structuredClone(v);n.audio[0].sourceInFrames=12;const impact=animaticImpact(v,n);assert.deepEqual(impact.map(s=>s.shotId),['shot:A','shot:B']);assert.equal(animaticHashes(v).shotSlices[2].timingHash,animaticHashes(n).shotSlices[2].timingHash);
});

async function fixture(t){
 const parent=path.resolve('tests/.test-tmp');await mkdir(parent,{recursive:true});const root=await mkdtemp(path.join(parent,'animatic-'));await mkdir(path.join(root,'media'));await mkdir(path.join(root,'data'));const profile=blankProfile({title:'预演隔离验收'}),repo=await createInstanceRepository({dbPath:path.join(root,'data/test.sqlite'),instanceId:profile.instanceId,profile});const snapshot=blankSnapshot(profile),v=timeline(),model=snapshot.snapshot.productionModel;
 const content={sceneId:v.sceneId,shots:v.shots.map((s,i)=>({shotId:s.shotId,sceneId:v.sceneId,order:i+1}))},hash=animaticHash(content);Object.assign(model,{shotPlanSetRevisions:[{id:v.shotPlanRevisionId,episodeUid:'episode:one',scopeId:v.sceneId,scopeRole:'CURRENT',sourceOperationId:'op:one',sourceSyncState:'SUCCEEDED',content,contentHash:hash,episodeNarrativeReleaseId:'release:episode'}],episodeNarrativeReleases:[{id:'release:episode',episodeUid:'episode:one',scopeRole:'CURRENT',sourceSyncState:'SOURCE_CURRENT',reviewInput:{scenes:[{id:v.sceneId,contentHash:'scenehash'}]}}],sceneScriptRevisions:[{sceneId:v.sceneId,scopeRole:'CURRENT',episodeNarrativeReleaseId:'release:episode',contentHash:'scenehash'}],scopeLocks:[{scopeType:'SCENE',scopeId:v.sceneId,lockPurpose:'SHOT_PLAN_SET',lockState:'LOCKED',denominatorState:'KNOWN',shotPlanSetRevisionId:v.shotPlanRevisionId,shotPlanSetRevisionHash:hash,shotIds:v.shots.map(s=>s.shotId)}],shots:v.shots.map(s=>({id:s.shotId,sceneId:v.sceneId,scopeRole:'CURRENT',shotPlanSetRevisionId:v.shotPlanRevisionId,shotPlanSetRevisionHash:hash})),assetFamilies:[{id:media.familyId,label:'测试粗分镜',kind:'IMAGE',currentVersionId:media.versionId,canFlowDownstream:true}],assetVersions:[{id:media.versionId,familyId:media.familyId,sha256:media.sha256,path:'media/board.png',canFlowDownstream:true}],workItems:[{id:'work:animatic',scopeId:v.sceneId,scopeRole:'CURRENT',deliverableKey:'ANIMATIC',outputAssetRef:'family:animatic'}],expectedOutputs:[{id:'expected:animatic',familyId:'family:animatic',targetPath:'media/_review_pending/animatic/V001.mp4',expectationState:'PLANNED',scopeRole:'CURRENT'}]});
 model.workItems.push(...v.shots.map(s=>({id:'work:board:'+s.shotId,sceneId:v.sceneId,shotId:s.shotId,scopeRole:'CURRENT',deliverableKey:'STORYBOARD',outputAssetRef:media.familyId})));
 await repo.writeTransaction(async tx=>{await tx.publishRelease({...snapshot,expectedReleaseId:null,sourceRevisionIds:[]});await tx.registerMedia({mediaId:media.familyId,versionId:media.versionId,relativePath:'media/board.png',sha256:media.sha256,byteSize:4,metadata:{authorityDomain:'FORMAL'}});});
 t.after(async()=>{await repo.close();await rm(root,{recursive:true,force:true});});return{root,repo,v,model};
}
test('immutable saves, CAS, idempotency, frozen render inputs and stale queued jobs',async t=>{
 const {repo,v,model}=await fixture(t),state=await repo.readTransaction(tx=>readAnimaticState(tx,{sceneId:v.sceneId,model}));const input={action:'save',sceneId:v.sceneId,expectedReleaseId:state.releaseId,expectedRevisionId:null,requestId:'request:save:one',content:v};const saved=await repo.writeTransaction(tx=>saveAnimaticTimeline(tx,input,{model}));assert.deepEqual(await repo.writeTransaction(tx=>saveAnimaticTimeline(tx,input,{model})),saved);await assert.rejects(repo.writeTransaction(tx=>saveAnimaticTimeline(tx,{...input,requestId:'request:save:stale'},{model})),/已变化/);
 const queued=await repo.writeTransaction(tx=>enqueueAnimaticRender(tx,{action:'render',sceneId:v.sceneId,timelineRevisionId:saved.timelineRevisionId,expectedRevisionId:saved.revisionId,expectedReleaseId:state.releaseId,requestId:'request:render:one'},{model}));assert.equal(queued.status,'QUEUED');assert.equal((await repo.listAux(ANIMATIC_NS.revisions)).length,1);
 const update=structuredClone(v);update.shots[0].beats.push({id:'beat:one',frame:0,label:'停顿'});await repo.writeTransaction(tx=>saveAnimaticTimeline(tx,{...input,expectedRevisionId:saved.revisionId,requestId:'request:save:two',content:update},{model}));await assert.rejects(repo.writeTransaction(tx=>claimAnimaticRender(tx,queued.jobId,'worker:one')),/时间线已变化/);
});
test('candidate proof requires completed job and registered SHA; lock rejects fabricated reviews',async t=>{
 const {repo,v,model}=await fixture(t),state=await repo.readTransaction(tx=>readAnimaticState(tx,{sceneId:v.sceneId,model})),saved=await repo.writeTransaction(tx=>saveAnimaticTimeline(tx,{sceneId:v.sceneId,expectedReleaseId:state.releaseId,expectedRevisionId:null,requestId:'save:test:proof',content:v},{model})),queue=await repo.writeTransaction(tx=>enqueueAnimaticRender(tx,{sceneId:v.sceneId,timelineRevisionId:saved.timelineRevisionId,expectedRevisionId:saved.revisionId,expectedReleaseId:state.releaseId,requestId:'render:test:proof'},{model})),claim=await repo.writeTransaction(tx=>claimAnimaticRender(tx,queue.jobId,'worker:one'));
 const result={relativePath:'media/_review_pending/animatic/V001.mp4',sha256:'b'.repeat(64),byteSize:64,frameCount:72,fps:24,width:1920,height:1080};await repo.writeTransaction(tx=>finishAnimaticRender(tx,{jobId:queue.jobId,jobRevisionId:claim.jobRevisionId,workerId:'worker:one',result},{model}));const projection=await repo.readTransaction(tx=>applyAnimaticProjection(tx,model)),events=(await repo.readView()).eventsByKind['asset-version'];assert.equal(animaticCandidateMatchesJob(events[0],projection.animaticRenderJobs),true);assert.equal(animaticCandidateMatchesJob({...events[0],sha256:'c'.repeat(64)},projection.animaticRenderJobs),false);await assert.rejects(repo.writeTransaction(tx=>lockAnimaticTimeline(tx,{sceneId:v.sceneId,timelineRevisionId:saved.timelineRevisionId,renderJobId:queue.jobId,reviewEventId:'forged:review'})),/正式放行/);
 const review=await repo.writeTransaction(tx=>tx.appendEvent({kind:'review',idempotencyKey:'review:animatic',requestHash:'f'.repeat(64),eventSchemaVersion:'2.2',payload:{schemaVersion:'2.2',subjectType:'WORK_PRODUCT',subjectId:'work:animatic',workItemId:'work:animatic',productionGateId:'ANIMATIC_LOCK',scopeType:'SCENE',scopeId:v.sceneId,versionId:events[0].versionId,versionSha256:result.sha256,familyId:'family:animatic',action:'APPROVE_AND_RELEASE',applicationStatus:'APPLIED',effect:'APPLIED',canFlowDownstream:true,adoptionIntent:'ADOPT_THIS_VERSION',reviewContextRef:'context:one',contextHash:'d'.repeat(64)}}));await repo.writeTransaction(tx=>lockAnimaticTimeline(tx,{sceneId:v.sceneId,timelineRevisionId:saved.timelineRevisionId,renderJobId:queue.jobId,reviewEventId:review.event.eventId}));
 const changed=structuredClone(v);changed.shots[0].durationFrames=48;changed.shots[0].panels[0].endFrame=48;const second=await repo.writeTransaction(tx=>saveAnimaticTimeline(tx,{sceneId:v.sceneId,expectedReleaseId:state.releaseId,expectedRevisionId:saved.revisionId,requestId:'save:test:next',content:changed},{model}));const nextModel=await repo.readTransaction(tx=>applyAnimaticProjection(tx,model));assert.deepEqual(nextModel.animaticLocks[0].applicableShotIds,['shot:B','shot:C']);assert.equal(nextModel.animaticLocks[0].fullSceneCurrent,false);
 const runtime={assetVersionsById:{[media.versionId]:model.assetVersions[0],[events[0].versionId]:{id:events[0].versionId,familyId:'family:animatic',sha256:result.sha256,canFlowDownstream:true}},assetFamiliesById:{[media.familyId]:model.assetFamilies[0],'family:animatic':{id:'family:animatic',currentVersionId:events[0].versionId,canFlowDownstream:true}}};assert.deepEqual(reconcileAnimaticLocks(nextModel,runtime)[0].applicableShotIds,['shot:B','shot:C']);nextModel.workItems.push({id:'new:line',sceneId:v.sceneId,shotId:'shot:B',scopeRole:'CURRENT',deliverableKey:'DIALOGUE_DRY',lineId:'new:line',outputAssetRef:'new:audio'});assert.deepEqual(reconcileAnimaticLocks(nextModel,runtime)[0].applicableShotIds,['shot:C']);nextModel.workItems.pop();
 const nextQueue=await repo.writeTransaction(tx=>enqueueAnimaticRender(tx,{sceneId:v.sceneId,timelineRevisionId:second.timelineRevisionId,expectedRevisionId:second.revisionId,expectedReleaseId:state.releaseId,requestId:'render:test:next'},{model:nextModel})),job=JSON.parse((await repo.getAux(ANIMATIC_NS.jobs,nextQueue.jobId)).bytes);assert.equal(job.expectedOutput.targetPath,'media/_review_pending/animatic/V002.mp4');assert.equal(job.parentVersionId,events[0].versionId);assert.equal(job.parentVersionSha256,result.sha256);const slots=await repo.readTransaction(tx=>applyAnimaticProjection(tx,model));assert.equal(slots.expectedOutputs.find(s=>s.id==='expected:animatic').scopeRole,'HISTORICAL');assert.equal(slots.expectedOutputs.find(s=>s.id==='expected:animatic:V002').scopeRole,'CURRENT');assert.equal((await repo.getMedia('family:animatic',events[0].versionId)).sha256,result.sha256);
 await repo.writeTransaction(tx=>tx.appendEvent({kind:'review',idempotencyKey:'review:animatic:reopen',requestHash:'1'.repeat(64),eventSchemaVersion:'2.2',payload:{schemaVersion:'2.2',subjectType:'WORK_PRODUCT',workItemId:'work:animatic',versionId:events[0].versionId,applicationStatus:'APPLIED',effect:'APPLIED',action:'REQUEST_REVISION',canFlowDownstream:false}}));const reopened=await repo.readTransaction(tx=>applyAnimaticProjection(tx,model));assert.equal(reopened.animaticLocks[0].scopeRole,'HISTORICAL');assert.deepEqual(reopened.animaticLocks[0].applicableShotIds,[]);
});
test('real ffmpeg render conserves frame count and refuses output overwrite',async t=>{
 const {root,repo}=await fixture(t),source=path.join(root,'media','real.png');await animaticProcess('ffmpeg',['-nostdin','-v','error','-f','lavfi','-i','color=c=navy:s=64x36','-frames:v','1','-n',source]);const bytes=await readFile(source),input={familyId:'family:real',versionId:'family:real@V001',sha256:sha256(bytes)};await repo.writeTransaction(tx=>tx.registerMedia({mediaId:input.familyId,versionId:input.versionId,relativePath:'media/real.png',sha256:input.sha256,byteSize:bytes.length,metadata:{authorityDomain:'FORMAL'}}));const v=timeline();v.shots=v.shots.slice(0,2).map((s,i)=>({...s,durationFrames:6,panels:[{...s.panels[0],media:input,endFrame:6,motion:i?'PULL_OUT':'PUSH_IN'}]}));const job={jobId:'animatic_render_render-test',inputBindings:[{...input,relativePath:'media/real.png',byteSize:bytes.length}],expectedOutput:{targetPath:'media/_review_pending/render-test/V001.mp4'}};const result=await renderAnimatic({repository:repo,instanceRoot:root,job,content:v});assert.equal(result.frameCount,12);assert.equal(result.fps,24);assert.equal(result.observed,false);assert.equal(sha256(await readFile(path.join(root,result.relativePath))),result.sha256);await assert.rejects(renderAnimatic({repository:repo,instanceRoot:root,job,content:v}),/EEXIST/);
});
test('real render mixes delayed dialogue and enforces the exact-font renderer capability',async t=>{
 const {root,repo}=await fixture(t),fontPaths=['/System/Library/Fonts/Supplemental/Arial.ttf','/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'];let fontBytes;for(const file of fontPaths){try{fontBytes=await readFile(file);break;}catch{}}
 if(!fontBytes){t.skip('No synthetic test TTF is installed');return;}
 await animaticProcess('ffmpeg',['-nostdin','-v','error','-f','lavfi','-i','color=c=navy:s=64x36','-frames:v','1','-n',path.join(root,'media/synthetic.png')]);await animaticProcess('ffmpeg',['-nostdin','-v','error','-f','lavfi','-i','sine=frequency=440:duration=1:sample_rate=48000','-n',path.join(root,'media/synthetic.wav')]);await writeFile(path.join(root,'media/synthetic.ttf'),fontBytes);
 const bindings=[];for(const extension of ['png','wav','ttf']){const relativePath='media/synthetic.'+extension,bytes=await readFile(path.join(root,relativePath)),binding={familyId:'synthetic:'+extension,versionId:'synthetic:'+extension+'@V001',sha256:sha256(bytes)};await repo.writeTransaction(tx=>tx.registerMedia({mediaId:binding.familyId,versionId:binding.versionId,relativePath,sha256:binding.sha256,byteSize:bytes.length,metadata:{authorityDomain:'FORMAL'}}));bindings.push({...binding,relativePath,byteSize:bytes.length});}
 const exact=b=>({familyId:b.familyId,versionId:b.versionId,sha256:b.sha256}),v=timeline();v.shots=[panel('shot:A',48)];v.shots[0].panels[0].media=exact(bindings[0]);v.audio=[{id:'audio:synthetic',anchorShotId:'shot:A',offsetFrames:12,sourceInFrames:0,durationFrames:24,media:exact(bindings[1]),role:'DIALOGUE',temporary:true,volume:0.5,muted:false,lineIds:['line:synthetic']}];v.cards=[{id:'card:synthetic',shotId:'shot:A',startFrame:0,endFrame:24,textLines:['Test character','Synthetic scene'],fontMedia:exact(bindings[2]),style:{x:120,y:800,fontSize:48,color:'#ffffff'},specRevisionId:'spec:synthetic',specHash:'e'.repeat(64)}];
 const job={jobId:'animatic_render_synthetic-av',inputBindings:bindings,expectedOutput:{targetPath:'media/_review_pending/synthetic-av/V001.mp4'}};if(!/\bdrawtext\b/.test(await animaticProcess('ffmpeg',['-hide_banner','-filters']))){await assert.rejects(renderAnimatic({repository:repo,instanceRoot:root,job,content:v}),/缺少 drawtext/);v.cards=[];t.diagnostic('Host FFmpeg has no drawtext; card rendering fails closed, audio is rendered and verified.');}const result=await renderAnimatic({repository:repo,instanceRoot:root,job,content:v});assert.equal(result.frameCount,48);const probe=JSON.parse(await animaticProcess('ffprobe',['-v','error','-select_streams','a:0','-show_entries','stream=sample_rate,codec_name','-of','json',path.join(root,result.relativePath)]));assert.equal(probe.streams[0].sample_rate,'48000');assert.equal(probe.streams[0].codec_name,'aac');assert.equal(result.observed,false);
 assert.equal(sha256(await readFile(path.join(root,result.relativePath))),result.sha256);
});
