import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm,rename,symlink,utimes,stat,open} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {openArchiveRowsFile} from '../host/instance-runtime/archive-file-reader.mjs';
import {writeArchiveFile,readArchiveFile,ARCHIVE_FILE_FORMAT} from '../host/instance-runtime/archive-file.mjs';
import {canonicalSha256} from '../host/instance-runtime/archive-integrity.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),base=path.join(here,'.test-tmp'),readerUrl=new URL('../host/instance-runtime/archive-file-reader.mjs',import.meta.url).href;
test('abort during a disk read rejects before yielding any row',async t=>{
 const root=await temporary(t),file=path.join(root,'abort-after-read');await writeArchiveFile(file,fixture());
 const probe=await open(file,'r'),prototype=Object.getPrototypeOf(probe),original=prototype.read;await probe.close();
 const controller=new AbortController(),reason=Error('cancelled during read');let intercept=false,reader,iterator;
 prototype.read=async function(...args){const result=await original.apply(this,args);if(intercept&&args[3]>0){intercept=false;controller.abort(reason);}return result;};
 try{reader=await openArchiveRowsFile(file,{signal:controller.signal});intercept=true;iterator=reader.iterate('a');await assert.rejects(iterator.next(),error=>error===reason);assert(controller.signal.aborted);}
 finally{prototype.read=original;await iterator?.return();await reader?.close();}
});
async function temporary(t){await mkdir(base,{recursive:true});const root=await mkdtemp(path.join(base,'archive-reader-'));t.after(()=>rm(root,{recursive:true,force:true}));return root;}
function fixture(){const body={schemaVersion:1,applicationId:123,instanceId:'INSTANCE',sequence:[{name:'events',seq:2}],mediaIncluded:false,tables:{a:[{id:'1',text:'中文\nquote"\\',data:{encoding:'base64',bytes:Buffer.from('资料').toString('base64')}},{id:'2',value:0,nullable:null}],empty:[],z:[{id:'3',deleted:1}]}};return {...body,exportSha256:canonicalSha256(body)};}
async function readAll(reader){const tables={};for(const table of reader.tableNames){tables[table]=[];for await(const row of reader.iterate(table))tables[table].push(row);}return {...reader.header,tables};}
test('indexed reads match the actual old writer and reader and can be repeated without keeping row bodies',async t=>{const root=await temporary(t),file=path.join(root,'archive.jsonl'),archive=fixture(),proof=await writeArchiveFile(file,archive),reader=await openArchiveRowsFile(file,{expectedFileSha256:proof.sha256});try{assert.deepEqual(await readAll(reader),await readArchiveFile(file,ARCHIVE_FILE_FORMAT));assert.deepEqual(await readAll(reader),archive);assert.equal(reader.rows,3);assert.equal(reader.file.bytes,proof.bytes);assert.equal(reader.file.sha256,proof.sha256);assert(Object.isFrozen(reader.header.sequence));await reader.assertUnchanged();}finally{await reader.close();}await assert.rejects(reader.assertUnchanged(),{code:'ARCHIVE_CLOSED'});});
test('legacy table interleaving, CRLF and a final record without newline remain supported',async t=>{const root=await temporary(t),file=path.join(root,'interleaved'),a=fixture(),{tables,...header}=a;const lines=[{format:ARCHIVE_FILE_FORMAT,header,tableNames:['z','empty','a']},{table:'a',row:tables.a[0]},{table:'z',row:tables.z[0]},{table:'a',row:tables.a[1]},{end:true,rows:3}].map(JSON.stringify).join('\r\n');await writeFile(file,lines);const r=await openArchiveRowsFile(file);try{assert.deepEqual(await readAll(r),await readArchiveFile(file,ARCHIVE_FILE_FORMAT));}finally{await r.close();}});
for(const [name,mutate] of [
 ['missing end',lines=>lines.slice(0,-1)],
 ['extra blank record',lines=>[...lines,'']],
 ['record after end',lines=>[...lines,JSON.stringify({table:'a',row:{id:'late'}})]],
 ['wrong total',lines=>[...lines.slice(0,-1),JSON.stringify({end:true,rows:99})]],
 ['unknown table',lines=>[lines[0],JSON.stringify({table:'missing',row:{id:'x'}}),...lines.slice(2)]],
 ['array row',lines=>[lines[0],JSON.stringify({table:'a',row:[]}),...lines.slice(2)]],
 ['duplicate table header',lines=>{const h=JSON.parse(lines[0]);h.tableNames.push(h.tableNames[0]);return[JSON.stringify(h),...lines.slice(1)];}],
 ['nested tables header',lines=>{const h=JSON.parse(lines[0]);h.header.tables={};return[JSON.stringify(h),...lines.slice(1)];}],
 ])test(name+' fails closed',async t=>{const root=await temporary(t),file=path.join(root,'bad'),valid=path.join(root,'valid');await writeArchiveFile(valid,fixture());const lines=(await readFile(valid,'utf8')).trimEnd().split('\n');await writeFile(file,mutate(lines).join('\n')+'\n');await assert.rejects(openArchiveRowsFile(file),{code:'ARCHIVE_STRUCTURE'});});
test('file, row and row-index limits reject completely instead of truncating',async t=>{const root=await temporary(t),file=path.join(root,'limits');await writeArchiveFile(file,fixture());await assert.rejects(openArchiveRowsFile(file,{maxBytes:10}),{code:'ARCHIVE_LIMIT'});await assert.rejects(openArchiveRowsFile(file,{maxRowBytes:10}),{code:'ARCHIVE_LIMIT'});await assert.rejects(openArchiveRowsFile(file,{maxRows:1}),{code:'ARCHIVE_LIMIT'});await assert.rejects(openArchiveRowsFile(file,{expectedFileSha256:'0'.repeat(64)}),{code:'ARCHIVE_HASH'});});
test('invalid UTF8 never becomes replacement characters',async t=>{const root=await temporary(t),file=path.join(root,'utf8');await writeFile(file,Buffer.from([0x7b,0x22,0x78,0x22,0x3a,0x22,0xff,0x22,0x7d,0x0a]));await assert.rejects(openArchiveRowsFile(file),{code:'ARCHIVE_STRUCTURE'});});
test('symlinks and pathname replacement cannot retarget a frozen reader',async t=>{const root=await temporary(t),file=path.join(root,'file'),alias=path.join(root,'alias');await writeArchiveFile(file,fixture());await symlink(file,alias);await assert.rejects(openArchiveRowsFile(alias),{code:'ARCHIVE_PATH'});const r=await openArchiveRowsFile(file);try{await rename(file,file+'.original');await writeFile(file,await readFile(file+'.original'));await assert.rejects(r.assertUnchanged(),{code:'ARCHIVE_CHANGED'});}finally{await r.close();}});
test('same-size edits with restored mtime are rejected; bodies are reread from the held descriptor',async t=>{const root=await temporary(t),file=path.join(root,'changed');await writeArchiveFile(file,fixture());const before=await stat(file),r=await openArchiveRowsFile(file);try{const bytes=await readFile(file),changed=Buffer.from(bytes);changed[changed.indexOf(Buffer.from('INSTANCE'))]=0x58;await writeFile(file,changed);await utimes(file,before.atime,before.mtime);await assert.rejects(r.assertUnchanged(),{code:'ARCHIVE_CHANGED'});await assert.rejects(async()=>{for await(const row of r.iterate('a'))void row;},{code:'ARCHIVE_CHANGED'});}finally{await r.close();}});
test('iterators are sequential and early return releases ownership',async t=>{const root=await temporary(t),file=path.join(root,'iterators');await writeArchiveFile(file,fixture());const r=await openArchiveRowsFile(file);try{const a=r.iterate('a');assert.equal((await a.next()).value.id,'1');await assert.rejects(r.iterate('z').next(),{code:'ARCHIVE_READ_BUSY'});await assert.rejects(r.close(),{code:'ARCHIVE_READ_BUSY'});await a.return();const z=r.iterate('z');assert.equal((await z.next()).value.id,'3');await z.return();assert.deepEqual(await readAll(r),fixture());}finally{await r.close();}});
test('multi-byte Unicode and long rows survive buffer boundaries without quadratic concatenation',async t=>{const root=await temporary(t),file=path.join(root,'unicode'),a=fixture();a.tables.a[0].text='界'.repeat(200000)+'😀';const {exportSha256,...body}=a;void exportSha256;a.exportSha256=canonicalSha256(body);await writeArchiveFile(file,a);const r=await openArchiveRowsFile(file);try{assert.deepEqual(await readAll(r),await readArchiveFile(file,ARCHIVE_FILE_FORMAT));}finally{await r.close();}});
test('abort before open or between passes never permits a continued read',async t=>{const root=await temporary(t),file=path.join(root,'abort');await writeArchiveFile(file,fixture());const ac=new AbortController();ac.abort();await assert.rejects(openArchiveRowsFile(file,{signal:ac.signal}),{name:'AbortError'});const bc=new AbortController(),r=await openArchiveRowsFile(file,{signal:bc.signal});try{bc.abort();await assert.rejects(async()=>{for await(const row of r.iterate('a'))void row;},{name:'AbortError'});}finally{await r.close();}});
test('2GiB structural NDJSON file is indexed and read in a 64MiB child heap', {skip:process.env.REVIEW_LARGE_ARCHIVE_READER_TEST!=='1',timeout:180000},async t=>{
 const root=await temporary(t),file=path.join(root,'large-structural-fixture.jsonl');
 const code=`import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import {openArchiveRowsFile} from ${JSON.stringify(readerUrl)};const file=${JSON.stringify(file)},h=await fs.open(file,'wx'),hash=createHash('sha256');let bytes=0;const put=async v=>{const b=Buffer.from(JSON.stringify(v)+'\\n');await h.writeFile(b);hash.update(b);bytes+=b.length;};await put({format:${JSON.stringify(ARCHIVE_FILE_FORMAT)},header:{schemaVersion:1,applicationId:123,instanceId:'STRUCTURAL_ONLY_NOT_BUSINESS_VERIFIED',exportSha256:'0'.repeat(64)},tableNames:['payload']});for(let i=0;i<1536;i++)await put({table:'payload',row:{id:i,text:'a'.repeat(1536*1024)}});await put({end:true,rows:1536});await h.close();const r=await openArchiveRowsFile(file,{expectedFileSha256:hash.digest('hex')});let count=0,peak=process.memoryUsage().rss;try{for await(const row of r.iterate('payload')){if(row.id!==count++||row.text.length!==1536*1024)throw Error('Row changed');peak=Math.max(peak,process.memoryUsage().rss);}console.log(JSON.stringify({bytes,count,peak,structuralOnly:true,businessShaVerified:false}));}finally{await r.close();}`;
 const result=await new Promise((resolve,reject)=>{const child=spawn(process.execPath,['--max-old-space-size=64','--input-type=module','-e',code],{stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);child.once('error',reject);child.once('close',code=>code===0?resolve(JSON.parse(out)):reject(Error('Large reader failed '+code+': '+err)));});
 assert(result.bytes>2*1024**3);assert.equal(result.count,1536);assert(result.peak<300*1024**2);console.log(JSON.stringify(result));
});
