import test from 'node:test';import assert from 'node:assert/strict';
import {mkdir,mkdtemp,rm,writeFile} from 'node:fs/promises';import {readFileSync} from 'node:fs';
import path from 'node:path';import {fileURLToPath}from'node:url';import{createHash}from'node:crypto';import ts from 'typescript';
import{validateArchiveRows,assertArchiveRowsUnchanged,openArchiveRowsWithBinding,MAX_DECLARED_ARCHIVE_BYTES,decodeArchiveRow,assertArchiveFileBinding}from'../host/instance-runtime/archive-stream-validation.mjs';
import{createArchiveStreamValidator,encodeArchiveRow}from'../host/instance-runtime/postgres.mjs';
import{ARCHIVE_FILE_FORMAT,writeArchiveFile,hashArchiveRows}from'../host/instance-runtime/archive-file.mjs';
import{canonicalJson,sha256}from'../host/instance-runtime/bytes.mjs';import{canonicalSha256,archiveRowHashes}from'../host/instance-runtime/archive-integrity.mjs';
import{SCHEMA_VERSION,APPLICATION_ID}from'../host/instance-runtime/schema.mjs';import{BUSINESS_TABLES}from'../host/instance-runtime/postgres-schema.mjs';
import{retirementManifestFromArchive,validateRetirementBackupManifest,validateRetirementBackupManifestFromFrozenRows}from'../host/instance-runtime/media-retirement-transfer.mjs';
import{verifyBackup}from'../scripts/instance-transfer.mjs';
import{RETIREMENT_NAMESPACES as NS,manifestHash,targetSetHash}from'../host/instance-runtime/media-retirement.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),base=path.join(here,'.test-tmp');
async function temp(t){await mkdir(base,{recursive:true});const p=await mkdtemp(path.join(base,'stream-'));t.after(()=>rm(p,{recursive:true,force:true}));return p;}
const cp=x=>structuredClone(x),encoded=b=>({encoding:'base64',bytes:b.toString('base64')});
function fixture(){const tables=Object.fromEntries(BUSINESS_TABLES.map(t=>[t,[]])),body=Buffer.from('{"source":"original"}'),snapshot=Buffer.from('{"snapshotId":"snapshot"}'),event=Buffer.from('{"eventId":"event","eventKind":"TEST","idempotencyKeyHash":null}');
 tables.repository_meta=[{singleton:1,instance_id:'fixture',runtime_epoch:'old-epoch',repository_revision:7,current_release_id:'release',created_at:'date'}];
 tables.record_revisions=[{revision_id:'r1',namespace:'settings',record_key:'profile',revision_number:1,previous_revision_id:null,content_bytes:encoded(body),content_sha256:sha256(body),media_type:'application/json',metadata_json:'{}',deleted:0,created_at:'date'}];
 tables.record_heads=[{namespace:'settings',record_key:'profile',revision_id:'r1'}];tables.document_aliases=[];
 tables.releases=[{release_id:'release',snapshot_id:'snapshot',snapshot_bytes:encoded(snapshot),snapshot_sha256:sha256(snapshot),recipes_bytes:encoded(snapshot),recipes_sha256:sha256(snapshot),source_revision_ids_json:'["r1"]',profile_revision_id:'r1',created_at:'date'}];
 tables.domain_events=[{storage_sequence:3,event_id:'event',authority_domain:'FORMAL',event_kind:'TEST',original_sequence:null,recorded_at:'date',event_bytes:encoded(event),event_sha256:sha256(event),idempotency_key_hash:null,request_hash:null,raw_request_hash:null,source_ref_json:'null'}];
 const archive={schemaVersion:SCHEMA_VERSION,applicationId:APPLICATION_ID,instanceId:'fixture',sequence:[{name:'domain_events',seq:9}],mediaIncluded:false,tables};return{...archive,exportSha256:canonicalSha256(archive)};}
function memoryReader(archive,{onPass,invalidIdentity=false}={}){const {tables,...header}=cp(archive);let checks=0,pass=0;return{format:ARCHIVE_FILE_FORMAT,header,tableNames:Object.keys(tables),rows:Object.values(tables).reduce((n,t)=>n+t.length,0),file:{sha256:'a'.repeat(64),bytes:1024},async assertUnchanged(){checks++;if(invalidIdentity)throw Object.assign(Error('changed'),{code:'ARCHIVE_CHANGED'});},async*iterate(table){if(table===[...Object.keys(tables)].sort()[0]){pass++;onPass?.(pass,tables,header);}for(const row of tables[table])yield cp(row);},stats:()=>({checks,pass})};}
test('real small NDJSON preflight equals oldexportSHA and seven row multisets,retains no ordinary bodies',async t=>{const a=fixture(),root=await temp(t),file=path.join(root,'archive'),binding=await writeArchiveFile(file,a),reader=await openArchiveRowsWithBinding(file,binding);try{const p=await validateArchiveRows(reader,{instanceId:'fixture',createValidator:createArchiveStreamValidator});assert.equal(p.exportSha256,a.exportSha256);assert.deepEqual(p.rowHashes,archiveRowHashes(a));assert.equal(p.sequenceHigh,9);assert.equal(p.frozenRetirement.tables.record_revisions.length,0);assert(!Object.hasOwn(p.frozenRetirement.tables,'releases'));assert(Object.isFrozen(p.rowHashes.record_revisions));const again=await validateArchiveRows(reader,{instanceId:'fixture',createValidator:createArchiveStreamValidator,collectRetirement:false});assertArchiveRowsUnchanged(p,again);}finally{await reader.close();}});
test('exact physical bounds reject badhex,over16GiB,missingpair,under/overdeclared size andwrongSHA',async t=>{const a=fixture(),root=await temp(t),file=path.join(root,'archive'),p=await writeArchiveFile(file,a);assert.equal(MAX_DECLARED_ARCHIVE_BYTES,16*1024**3);for(const b of[{sha256:'bad',bytes:p.bytes},{sha256:p.sha256,bytes:MAX_DECLARED_ARCHIVE_BYTES+1},{bytes:p.bytes},{sha256:p.sha256},{sha256:p.sha256,bytes:p.bytes-1},{sha256:p.sha256,bytes:p.bytes+1},{sha256:'0'.repeat(64),bytes:p.bytes}])await assert.rejects(openArchiveRowsWithBinding(file,b));});
test('full source or semantic failure before onRow transaction phase',async()=>{for(const mutate of[a=>{a.exportSha256='0'.repeat(64);},a=>{a.tables.record_revisions[0].content_sha256='0'.repeat(64);},a=>{a.tables.record_heads[0].revision_id='missing';},a=>{a.tables.releases[0].source_revision_ids_json='["missing"]';}]){const a=fixture();mutate(a);await assert.rejects(validateArchiveRows(memoryReader(a),{instanceId:'fixture',createValidator:createArchiveStreamValidator}));}await assert.rejects(validateArchiveRows(memoryReader(fixture(),{invalidIdentity:true}),{instanceId:'fixture',createValidator:createArchiveStreamValidator}),{code:'ARCHIVE_CHANGED'});});
test('betweenpass metadata/body/file drift cannot satisfy second proof',async()=>{const first=await validateArchiveRows(memoryReader(fixture()),{instanceId:'fixture',createValidator:createArchiveStreamValidator});for(const field of['file','metadata','rowHashes','header','sequenceHigh','rows']){const after=cp(first);if(field==='file')after.file.sha256='b'.repeat(64);else if(field==='metadata')after.metadata.repository_revision++;else if(field==='rowHashes')after.rowHashes.record_heads.push('b'.repeat(64));else if(field==='header')after.header.mediaIncluded=true;else after[field]++;assert.throws(()=>assertArchiveRowsUnchanged(first,after),{code:'ARCHIVE_CHANGED'});}});
test('retirement frozen manifest matchesold adapter andrejects identity/media/files/overlay drift',async()=>{const a=fixture(),scan=await validateArchiveRows(memoryReader(a),{instanceId:'fixture',createValidator:createArchiveStreamValidator}),overlay=await retirementManifestFromArchive(a),manifest={instanceId:'fixture',releaseId:'release',repositoryRevision:7,media:[],files:[],mediaRetirement:overlay};assert.deepEqual(await validateRetirementBackupManifest(a,manifest),await validateRetirementBackupManifestFromFrozenRows(scan.frozenRetirement,manifest));for(const mutate of[m=>{m.instanceId='other';},m=>{m.releaseId='other';},m=>{m.repositoryRevision++;},m=>{m.media.push({media_id:'x',version_id:'v'});},m=>{m.files.push({path:'media/x'});},m=>{m.mediaRetirement={};}]){const m=cp(manifest);mutate(m);await assert.rejects(validateRetirementBackupManifestFromFrozenRows(scan.frozenRetirement,m));}});

const core=new URL('../',import.meta.url),pgSource=readFileSync(new URL('../host/instance-runtime/postgres.mjs',import.meta.url),'utf8');
function declaration(name){const ast=ts.createSourceFile('postgres.mjs',pgSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert(node);return node.getText(ast).replace(/^export /,'');}
const ensure=(ok,code,message)=>{if(!ok)throw Object.assign(Error(message),{code});},number=x=>{const n=Number(x);ensure(Number.isSafeInteger(n),'INTEGER_RANGE','bad integer');return n;};
function imported({reader,failInsert=false,changeAfterInsert=false,wrongMeta=false}={}){const log=[],a=fixture(),rows=Object.fromEntries(BUSINESS_TABLES.map(t=>[t,[]]));let committed=false,rolledBack=false,opened=false,closed=false;const c={async query(sql,args=[]){log.push(sql);if(sql.startsWith('SELECT column_name'))return{rows:Object.keys(a.tables[args[1]][0]||({document_aliases:{alias:0,document_id:0},media_versions:{media_id:0,version_id:0,relative_path:0,sha256:0,byte_size:0,availability:0,metadata_json:0,created_at:0},media_aliases:{alias:0,media_id:0,version_id:0}})[args[1]]).map(column_name=>({column_name}))};if(sql.startsWith('INSERT INTO ')){if(failInsert)throw Error('insert failed');const [,table,columns]=sql.match(/^INSERT INTO ([a-z_]+)\(([^)]+)\)/);rows[table].push(Object.fromEntries(columns.split(',').map((k,i)=>[k,args[i]])));return{rows:[]};}if(sql.startsWith('UPDATE repository_meta')){rows.repository_meta[0].runtime_epoch=args[0];rows.repository_meta[0].repository_revision++;if(wrongMeta)rows.repository_meta[0].instance_id='other';return{rows:[]};}if(sql.startsWith('SELECT * FROM repository_meta'))return{rows:rows.repository_meta};if(sql.startsWith('SELECT setval')){assert.deepEqual(args,[9,true]);return{rows:[]};}throw Error('Unexpected SQL '+sql);}};
 const bindings={RepositoryError:class extends Error{constructor(code,message){super(message);this.code=code;}},ensure,number,readOnlyProcess:()=>false,validateArchiveRows,createArchiveStreamValidator,decodeArchiveRow,assertArchiveRowsUnchanged,canonicalJson,encodeArchiveRow,restoredRuntimeEpoch:()=> 'RESTORED:new-epoch',randomUUID:()=> 'new',BUSINESS_TABLES,
  postgresConnection:async()=>{opened=true;log.push('CONNECT');return{};},emptySchema:async(_connection,callback)=>{log.push('EMPTY_TARGET_BEGIN');try{await callback(c);if(changeAfterInsert)throw Error('precommit identity changed');committed=true;log.push('COMMIT');}catch(e){rolledBack=true;log.push('ROLLBACK');throw e;}},
  PgUnit:class{constructor(client){this.client=client;}},verifyRestoredRows:async(unit,id,hashes,meta)=>{assert.equal(unit.client,c);assert.equal(id,'fixture');assert(!committed);assert.deepEqual(archiveRowHashes({tables:Object.fromEntries(Object.entries(rows).map(([t,r])=>[t,r.map(encodeArchiveRow)]))}),hashes);assert.deepEqual(encodeArchiveRow(rows.repository_meta[0]),meta);log.push('PRECOMMIT_VERIFIED');},
  openPostgresRepository:async()=>({instanceId:'fixture',async writeTransaction(fn){await fn({readRelease:async()=>null});},async close(){closed=true;}}),rebuildQueryModel:()=>{throw Error('unexpected fixture rebuild');},parse:b=>JSON.parse(Buffer.from(b)),
  verifyImportedRepository:async(repo,expectedHashes,meta)=>{assert(committed);assert.deepEqual(expectedHashes,archiveRowHashes(a));assert.equal(meta.runtime_epoch,'RESTORED:new-epoch');assert.equal(meta.repository_revision,8);return{status:'POSTGRES_IMPORT_VERIFIED',originalBytesPreserved:true,businessIdsPreserved:true,metadata:{runtimeEpoch:meta.runtime_epoch},integrity:{ok:true}};},
 };const run=Function(...Object.keys(bindings),declaration('importPostgresRows')+';return importPostgresRows;')(...Object.values(bindings));return{run:()=>run({reader,instanceId:'fixture'}),stats:()=>({log,committed,rolledBack,opened,closed})};}
test('actual importRows function usespreflight→singleemptytx→rowINSERT→secondproof→metadata→04de finalverify',async()=>{const r=memoryReader(fixture()),h=imported({reader:r}),repo=await h.run();assert.equal(h.stats().committed,true);assert.equal(r.stats().pass,2);assert.equal(repo.importVerification.streamedSource.semanticPasses,2);assert.equal(repo.importVerification.streamedSource.exportSha256,fixture().exportSha256);assert(h.stats().log.indexOf('CONNECT')<h.stats().log.indexOf('EMPTY_TARGET_BEGIN'));assert.equal(h.stats().log.filter(x=>x==='COMMIT').length,1);assert(!h.stats().log.some(x=>/exportState|readArchiveFile/.test(x)));await repo.close();assert.equal(h.stats().closed,true);});
test('preflight corruption opensno target; midpass corruption/insertion/metadata errors rollbacks',async()=>{const invalid=fixture();invalid.exportSha256='0'.repeat(64);const before=imported({reader:memoryReader(invalid)});await assert.rejects(before.run());assert.equal(before.stats().opened,false);for(const options of[{failInsert:true},{wrongMeta:true},{changeAfterInsert:true}]){const h=imported({reader:memoryReader(fixture()),...options});await assert.rejects(h.run());assert.equal(h.stats().committed,false);assert.equal(h.stats().rolledBack,true);}const r=memoryReader(fixture(),{onPass(pass,tables){if(pass===2)tables.repository_meta[0].created_at='changed';}}),h=imported({reader:r});await assert.rejects(h.run());assert.equal(h.stats().committed,false);assert.equal(h.stats().rolledBack,true);});

test('actual interleaved CRLF/no-finalLF NDJSON produces original logicalhash andschema proof',async t=>{const a=fixture(),{tables,...header}=a,root=await temp(t),file=path.join(root,'interleaved'),rows=[...BUSINESS_TABLES].reverse().flatMap(table=>tables[table].map(row=>({table,row}))),text=[{format:ARCHIVE_FILE_FORMAT,header,tableNames:BUSINESS_TABLES},...rows,{end:true,rows:rows.length}].map(JSON.stringify).join('\r\n');await writeFile(file,text);const r=await openArchiveRowsWithBinding(file,{sha256:sha256(text),bytes:Buffer.byteLength(text)});try{const p=await validateArchiveRows(r,{instanceId:'fixture',createValidator:createArchiveStreamValidator});assert.equal(p.exportSha256,a.exportSha256);}finally{await r.close();}});
test('16MiB lazy controlled source can rescan without retaining ordinary row payloads',async()=>{const a=fixture(),count=32,bytes=512*1024,{tables,...header}=a;let peakRows=0,live=0;const names=Object.keys(tables),payloads=[];for(let i=0;i<count;i++){const b=Buffer.from('x'.repeat(bytes));payloads.push({revision_id:'large'+i,namespace:'documents',record_key:'large'+i,revision_number:1,previous_revision_id:null,content_sha256:sha256(b),media_type:'text/plain',metadata_json:'{}',deleted:0,created_at:'date'});}const iterate=async function*(t){for(const r of tables[t])yield cp(r);if(t==='record_revisions')for(const base of payloads){live++;peakRows=Math.max(peakRows,live);try{yield{...base,content_bytes:encoded(Buffer.from('x'.repeat(bytes)))};}finally{live--;}}if(t==='record_heads')for(const r of payloads)yield{namespace:r.namespace,record_key:r.record_key,revision_id:r.revision_id};};const {exportSha256:unused,...logical}=header;void unused;const h=await hashArchiveRows(logical,names,iterate),r={format:ARCHIVE_FILE_FORMAT,header:{...logical,exportSha256:h.exportSha256},tableNames:names,rows:h.rows,file:{sha256:'a'.repeat(64),bytes:count*bytes},iterate,assertUnchanged:async()=>{}};const p=await validateArchiveRows(r,{instanceId:'fixture',createValidator:createArchiveStreamValidator});assert.equal(p.frozenRetirement.tables.record_revisions.length,0);assert.equal(p.rowHashes.record_revisions.length,count+1);assert.equal(peakRows,1);assert.equal(live,0);});

const transferSource=readFileSync(new URL('../scripts/instance-transfer.mjs',import.meta.url),'utf8');
function transferDeclaration(name){const ast=ts.createSourceFile('transfer.mjs',transferSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert(node);return node.getText(ast).replace(/^export /,'');}
test('real restoreRows orchestration validatesbeforetarget,streams scratch,passes exactfile binding andchecks childproof',async()=>{
 for(const mode of ['ok','manifest','copy','child']){const a=fixture(),r=memoryReader(a),scan=await validateArchiveRows(r,{instanceId:'fixture',createValidator:createArchiveStreamValidator}),overlay=await retirementManifestFromArchive(a),manifest={instanceId:'fixture',releaseId:'release',repositoryRevision:7,media:[],files:[],mediaRetirement:overlay};let targets=0,created=0,unlinks=0;const log=[];if(mode==='manifest')manifest.repositoryRevision++;
  const bindings={validateArchiveRows,validateRetirementBackupManifestFromFrozenRows,path,randomUUID:()=> 'new',postgresNames:()=>({volume:'NEW_ISOLATED_VOLUME'}),canonicalJson,ARCHIVE_FILE_FORMAT,assertArchiveFileBinding,
   verifyFile:async()=>{},newTarget:async()=>{targets++;log.push('target');return'/isolated';},mkdir:async()=>{},copyVerified:async()=>{},writeFile:async()=>{},
   writeArchiveRowsFile:async(_file,args)=>{if(mode==='copy')throw Error('scratch write failed');assert(!('tables'in args));assert.equal(args.exportSha256,scan.exportSha256);const again=await hashArchiveRows(args.header,args.tableNames,args.iterate);assert.equal(again.exportSha256,scan.exportSha256);log.push('scratch');return{format:ARCHIVE_FILE_FORMAT,sha256:'c'.repeat(64),bytes:2048};},
   ensurePostgres:async()=>{created++;log.push('new-pg');},runPostgresMaintenance:async(_target,args,options)=>{assert(args.includes('--file-sha'));assert.equal(args[args.indexOf('--file-sha')+1],'c'.repeat(64));assert.equal(args[args.indexOf('--file-bytes')+1],'2048');assert.equal(options.nodeHeapMiB,512);return Buffer.from(JSON.stringify(mode==='child'?{status:'FAILED'}:{status:'RESTORED_VERIFIED',originalBytesPreserved:true,businessIdsPreserved:true,integrity:{ok:true}}));},unlink:async()=>{unlinks++;},
  };const restore=Function(...Object.keys(bindings),transferDeclaration('restoreArchiveRowsWithMedia')+';return restoreArchiveRowsWithMedia;')(...Object.values(bindings));if(mode==='ok'){const result=await restore('/source','/isolated',manifest,r);assert.equal(result.streamedSource,true);assert.equal(unlinks,1);assert.deepEqual(log,['target','scratch','new-pg']);}else{await assert.rejects(restore('/source','/isolated',manifest,r));assert.equal(unlinks,0);if(mode==='manifest')assert.equal(targets,0);if(mode==='copy')assert.equal(created,0);}
 }
});

test('actual verifyBackup entry validates a real small NDJSON+manifest without object archive or database',async t=>{const a=fixture(),root=await temp(t);await mkdir(path.join(root,'data'));const db=await writeArchiveFile(path.join(root,'data/repository.jsonl'),a),overlay=await retirementManifestFromArchive(a),body={schemaVersion:'2.0',kind:'REVIEW_INSTANCE_BACKUP',instanceId:'fixture',releaseId:'release',repositoryRevision:7,database:{path:'data/repository.jsonl',...db},media:[],files:[],mediaRetirement:overlay},manifest={...body,manifestSha256:sha256(canonicalJson(body))};await writeFile(path.join(root,'backup-manifest.json'),JSON.stringify(manifest));const result=await verifyBackup(root);assert.equal(result.status,'BACKUP_VERIFIED');assert.equal(result.streamed,true);assert.equal(result.exportSha256,a.exportSha256);});
test('restorePostgresBackup selects stream only forNDJSON andclosesreader oncallbackfailure; legacy staysobject',async()=>{for(const mode of['stream','error','legacy']){let opened=0,closed=0,whole=0;const archive=fixture(),bindings={validatedBackup:async()=>({manifest:{schemaVersion:'2.0',database:{format:mode==='legacy'?'REVIEW_REPOSITORY_ARCHIVE_1':ARCHIVE_FILE_FORMAT}},database:'/fixture'}),ARCHIVE_FILE_FORMAT,openArchiveRowsWithBinding:async()=>{opened++;return{close:async()=>closed++};},restoreArchiveRowsWithMedia:async()=>{if(mode==='error')throw Error('restore failed');return{streamed:true};},restoreArchiveWithMedia:async(_s,_o,_m,a)=>{assert.equal(a,archive);return{legacy:true};},readArchiveFile:async()=>{whole++;return archive;}};const fn=Function(...Object.keys(bindings),transferDeclaration('restorePostgresBackup')+';return restorePostgresBackup;')(...Object.values(bindings));if(mode==='error')await assert.rejects(fn('/source','/target'));else await fn('/source','/target');assert.equal(whole,mode==='legacy'?1:0);assert.equal(opened,mode==='legacy'?0:1);assert.equal(closed,opened);}});

test('actualCLI routing never fullreadsPostgresNDJSON; SQLite/legacy compatibility andcleanup remain',async()=>{
 const code=readFileSync(new URL('../scripts/instance-pg-transfer.mjs',import.meta.url),'utf8'),ast=ts.createSourceFile('cli.mjs',code,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),body=ast.statements.filter(n=>!ts.isImportDeclaration(n)).map(n=>n.getText(ast)).join('\n'),AsyncFunction=Object.getPrototypeOf(async()=>{}).constructor;
 for(const mode of['ok','import-error','missing-bytes','leading-zero','legacy-binding','legacy','sqlite']){let whole=0,streams=0,closedReader=0,closedRepo=0,printed=0;const values={instance:'/instance',file:'/source',format:mode.startsWith('legacy')?'REVIEW_REPOSITORY_ARCHIVE_1':ARCHIVE_FILE_FORMAT};if(!['legacy','sqlite'].includes(mode)){values['file-sha']='a'.repeat(64);if(mode!=='missing-bytes')values['file-bytes']=mode==='leading-zero'?'01024':'1024';}const repo={importVerification:{status:'POSTGRES_IMPORT_VERIFIED',originalBytesPreserved:true,businessIdsPreserved:true,metadata:{runtimeEpoch:'RESTORED'},integrity:{ok:true}},close:async()=>closedRepo++},bindings={parseArgs:()=>({values,positionals:['import']}),isRestoredRuntime:()=>true,ARCHIVE_FILE_FORMAT,resolveInstance:()=>({instanceId:'fixture',backend:mode==='sqlite'?'sqlite':'postgres'}),openArchiveRowsWithBinding:async(_f,b)=>{assert.deepEqual(b,{sha256:'a'.repeat(64),bytes:1024});streams++;return{close:async()=>closedReader++};},importPostgresRows:async()=>{if(mode==='import-error')throw Error('import error');return repo;},readArchiveFile:async()=>{whole++;return{};},importRepositoryState:async()=>repo,writeFile:async()=>{},backupPostgresInstance:async()=>assert.fail('backup'),console:{log:()=>printed++}};const run=new AsyncFunction(...Object.keys(bindings),body);if(['ok','legacy','sqlite'].includes(mode))await run(...Object.values(bindings));else await assert.rejects(run(...Object.values(bindings)));assert.equal(whole,['legacy','sqlite'].includes(mode)?1:0);assert.equal(printed,['ok','legacy','sqlite'].includes(mode)?1:0);assert.equal(closedReader,streams);assert.equal(closedRepo,['ok','legacy','sqlite'].includes(mode)?1:0);}
});

test('frozen manifest preservesold quarantine/purge/shared/pending andcorruptauthority behavior',async()=>{const source=readFileSync(new URL('tests/media-retirement-transfer.test.mjs',core),'utf8'),prelude=source.slice(source.indexOf('const canonical ='),source.indexOf("test('ACTIVE")),functions=Function('createHash','manifestHash','targetSetHash','NS','retirementManifestFromArchive',prelude+';return{fixture,seal};')(createHash,manifestHash,targetSetHash,NS,retirementManifestFromArchive),outcome=async fn=>{try{return{value:await fn()};}catch(e){return{code:e.code,message:e.message};}},subset=a=>({instanceId:a.instanceId,tables:{repository_meta:a.tables.repository_meta,record_heads:a.tables.record_heads,record_revisions:a.tables.record_revisions,media_versions:a.tables.media_versions,media_aliases:a.tables.media_aliases}});
 for(const phase of['ACTIVE','QUARANTINED','PURGED','QUARANTINE_INTENT','PURGE_INTENT','RESULT_UNKNOWN']){const a=functions.fixture(phase,true),parsed=await outcome(()=>retirementManifestFromArchive(a)),manifest={instanceId:a.instanceId,releaseId:'release-fixed',repositoryRevision:7,media:cp(a.tables.media_versions),files:parsed.value?.files||[],mediaRetirement:parsed.value};assert.deepEqual(await outcome(()=>validateRetirementBackupManifest(a,manifest)),await outcome(()=>validateRetirementBackupManifestFromFrozenRows(subset(a),manifest)));}
 for(const mutate of[a=>a.tables.record_heads.pop(),a=>{a.tables.record_revisions.at(-1).deleted=1;},a=>a.tables.media_aliases.push({...a.tables.media_aliases[0],alias:'extra'})]){const a=functions.fixture('PURGED'),overlay=await retirementManifestFromArchive(a),manifest={instanceId:a.instanceId,releaseId:'release-fixed',repositoryRevision:7,media:cp(a.tables.media_versions),files:overlay.files,mediaRetirement:overlay};mutate(a);functions.seal(a);const old=await outcome(()=>validateRetirementBackupManifest(a,manifest)),fresh=await outcome(()=>validateRetirementBackupManifestFromFrozenRows(subset(a),manifest));assert(old.code);assert.deepEqual(fresh,old);}
});

test('Git restore invokesrows restore only withinlive fully-verified callback,propagatesfailure',async()=>{const source=readFileSync(new URL('../scripts/instance-git-export.mjs',import.meta.url),'utf8'),ast=ts.createSourceFile('git.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='restoreGitSnapshot');assert(node);const code=node.getText(ast).replace(/^export /,'');assert(!code.includes('readGitSnapshot('));assert(!code.includes('restoreArchiveWithMedia('));for(const failure of[false,true]){let alive=false,closed=false,invocations=0;const bindings={withVerifiedGitSnapshot:async(_s,_r,callback)=>{alive=true;try{return await callback({manifest:{core:{commit:'frozen-core'}},reader:{header:{}},mediaRoot:'/media',frozenRetirement:{},rowHashes:{}});}finally{alive=false;closed=true;}},restoreArchiveRowsWithMedia:async(_s,_o,_m,reader)=>{assert(alive);assert(reader.header);invocations++;if(failure)throw Error('import failed');return{status:'RESTORED_VERIFIED'};}};const restore=Function(...Object.keys(bindings),code+';return restoreGitSnapshot;')(...Object.values(bindings));if(failure)await assert.rejects(restore('/snapshot','/repository','/new-target'));else{const r=await restore('/snapshot','/repository','/new-target');assert.equal(r.status,'GIT_BUSINESS_RESTORED_VERIFIED');assert.equal(r.privateConversationHistoryRestored,false);assert.equal(r.fullBackup,false);}assert.equal(invocations,1);assert(closed&&!alive);}});
