import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
import type {AssetContextWorkspace} from '../host/instance-runtime/asset-context-revalidation-service.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const target={familyId:'AF-LEGACY',versionId:'AF-LEGACY@V001',sha256:'a'.repeat(64)};
const flags={modelCalls:0,formalAdoptionPerformed:false,contextRevalidationPerformed:false};
type Options={hosted?:boolean;readOnly?:boolean;unsupported?:boolean;unknownSave?:boolean;unknownPublish?:boolean;committed?:boolean;invalidReceipt?:boolean;wrongSha?:boolean};
async function fixture(page:Page,options:Options={}){
 const w={...target,protocol:'ASSET_CONTEXT_REVALIDATION_V1',supported:true,readOnly:!!options.readOnly,releaseId:'release-one',basisHash:'b'.repeat(64),revalidationId:'ACTX-one',sourceVersion:{...target},legacyAdoptionProof:{},domainContext:{},reviewSpec:{hash:'c'.repeat(64),criteria:[{id:'identity',label:'身份',question:'原图身份是否适用于当前关系？',allowNA:false}]},head:null,draftHeadRevisionId:null,draft:null,staleDraft:null,blockers:[],jobs:[]} as unknown as AssetContextWorkspace;
 const writes:Array<Record<string,unknown>>=[],errors:string[]=[],unexpected:string[]=[];let reads=0;
 const entry=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{RuntimeModeProvider}from'./app/runtime-mode';import{AssetContextRevalidationEditor}from'./app/asset-context-revalidation-editor';function Harness(){const[show,setShow]=useState(true);return <RuntimeModeProvider hostedReadOnly={${!!options.hosted}}><button onClick={()=>setShow(!show)}>切换素材卡</button>{show&&<AssetContextRevalidationEditor target={${JSON.stringify(target)}} mediaToken="m_fixture"/>}</RuntimeModeProvider>};createRoot(document.getElementById('root')).render(<Harness/>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'context-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-context',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles;
 const js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const r=route.request(),url=new URL(r.url());
  if(url.pathname==='/__context')return route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>${css}</style></head><body><div id="root"></div><script>${js}</script></body></html>`});
  if(url.pathname==='/api/v8/media/m_fixture')return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=','base64')});
  if(url.pathname==='/api/v8/operations/snapshot')return route.fulfill({json:{mutationEtag:'"context-etag"'}});
  if(url.pathname==='/api/instance/asset-context-revalidation'){
   if(r.method()==='GET'){reads++;return options.unsupported?route.fulfill({status:404,json:{error:'not found'}}):route.fulfill({json:{...w,...(options.wrongSha?{sha256:'f'.repeat(64)}:{})}});}
   const b=r.postDataJSON();writes.push(b);expect(r.headers()['if-match']).toBe('"context-etag"');expect(r.headers()['idempotency-key']).toMatch(/^asset-context:/);
   if(b.action==='save'){if(!options.unknownSave||options.committed){w.draftHeadRevisionId='draft-one';w.draft={...target,revalidationId:w.revalidationId,revisionId:'draft-one',baseReleaseId:w.releaseId,basisHash:w.basisHash,content:b.content};}return options.unknownSave?route.fulfill({status:503,json:{error:'保存连接中断'}}):route.fulfill({json:{...flags,revisionId:'draft-one'}});}
   if(b.action==='preview')return route.fulfill({json:{...flags,previewHash:'d'.repeat(64),revalidation:{schemaVersion:'ASSET_CONTEXT_REVALIDATION_SOURCE_V1',revalidationId:w.revalidationId,baseReleaseId:w.releaseId,draftRevisionId:w.draft!.revisionId,basis:{source:target,current:{reviewSpec:w.reviewSpec}},content:w.draft!.content}}});
   if(b.action==='publish'){if(!options.unknownPublish||options.committed)w.jobs=[{jobId:'job-one',requestId:r.headers()['idempotency-key'],status:'QUEUED'}];return options.unknownPublish?route.fulfill({status:503,json:{error:'登记连接中断'}}):route.fulfill({json:{...flags,jobId:'job-one',status:options.invalidReceipt?'FAILED':'QUEUED'}});}
  }
  unexpected.push(r.method()+' '+url.pathname);return route.fulfill({status:418,body:'unexpected request'});
 });await page.goto('http://127.0.0.1:4309/__context');return {w,writes,errors,unexpected,reads:()=>reads};
}
async function open(page:Page){await page.getByRole('button',{name:'复核原图在当前关系中的适用性',exact:true}).click();await expect(page.getByRole('textbox',{name:'原图观察与当前适用范围'})).toBeVisible();}
async function author(page:Page){await open(page);await expect(page.getByRole('combobox',{name:'判断',exact:true})).toHaveValue('');await page.getByRole('checkbox',{name:'已查看此版本原图'}).check();await page.getByRole('combobox',{name:'判断',exact:true}).selectOption('PASS');await page.getByRole('textbox',{name:'判断依据'}).fill('实际看原图，身份满足当前关系。');await page.getByRole('textbox',{name:'原图观察与当前适用范围'}).fill('实际原图保留原群体身份，新增成员关系不代表单人成套形象已通过。');}
async function preview(page:Page){await page.getByRole('button',{name:'保存复核草稿'}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await page.getByRole('button',{name:'预览关系复核',exact:true}).click();await expect(page.getByRole('heading',{name:'待登记关系复核'})).toBeVisible();}
test('original observation and explicit criteria produce only a new context review request',async({page})=>{const f=await fixture(page);await author(page);await preview(page);await page.getByRole('button',{name:'确认登记当前关系复核'}).click();await expect(page.getByRole('status')).toContainText('排队登记');expect(f.writes.map(w=>w.action)).toEqual(['save','preview','publish']);expect(f.writes[0]).toMatchObject({...target,expectedBasisHash:f.w.basisHash,content:{observedVersionId:target.versionId,observedSha256:target.sha256}});expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);});
test('unknown save remains blocked after reread and reload without another request',async({page})=>{const f=await fixture(page,{unknownSave:true});await author(page);await page.getByRole('button',{name:'保存复核草稿'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');await page.reload();await open(page);await expect(page.getByRole('status')).toContainText('原请求结果尚未核实');await expect(page.getByRole('button',{name:'保存复核草稿'})).toBeDisabled();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
test('lost save receipt reconciles the exact committed draft and asks for original observation again',async({page})=>{const f=await fixture(page,{unknownSave:true,committed:true});await author(page);await page.getByRole('button',{name:'保存复核草稿'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');await page.getByRole('button',{name:'重读原图与复核记录'}).click();await expect(page.getByRole('status')).toContainText('已找到原保存请求');await expect(page.getByRole('checkbox',{name:'已查看此版本原图'})).not.toBeChecked();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
for(const committed of [false,true])test('unknown publish preserves original request '+committed,async({page})=>{const f=await fixture(page,{unknownPublish:true,committed});await author(page);await preview(page);await page.getByRole('button',{name:'确认登记当前关系复核'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');await page.getByRole('button',{name:'重读原图与复核记录'}).click();await expect(page.getByRole('status')).toContainText(committed?'已找到原登记任务':'原请求结果尚未核实');await expect(page.getByRole('button',{name:'保存复核草稿'})).toBeDisabled();expect(f.writes).toHaveLength(3);expect(f.errors).toEqual([]);});
test('invalid publish receipt cannot claim success',async({page})=>{const f=await fixture(page,{invalidReceipt:true});await author(page);await preview(page);await page.getByRole('button',{name:'确认登记当前关系复核'}).click();await expect(page.getByRole('status')).toContainText('回执不完整');await expect(page.getByRole('button',{name:'确认登记当前关系复核'})).toBeDisabled();expect(f.writes).toHaveLength(3);});
test('changed context preserves prose but clears all prior decisions',async({page})=>{const f=await fixture(page);await author(page);f.w.basisHash='f'.repeat(64);f.w.releaseId='release-two';await page.getByRole('button',{name:'重读原图与复核记录'}).click();await expect(page.getByRole('status')).toContainText('依据已变化');await expect(page.getByRole('textbox',{name:'原图观察与当前适用范围'})).toHaveValue(/新增成员关系/);await expect(page.getByRole('combobox',{name:'判断',exact:true})).toHaveValue('');await expect(page.getByRole('checkbox',{name:'已查看此版本原图'})).not.toBeChecked();await page.getByText('依据变化前的本地观察稿（1）',{exact:true}).click();await expect(page.locator('pre').filter({hasText:'实际看原图，身份满足当前关系。'})).toBeVisible();await page.reload();await open(page);await page.getByText('依据变化前的本地观察稿（1）',{exact:true}).click();await expect(page.locator('pre').filter({hasText:'实际看原图，身份满足当前关系。'})).toBeVisible();expect(f.writes).toEqual([]);});
test('incomplete local observations survive unmount with no write',async({page})=>{const f=await fixture(page);await open(page);await page.getByRole('textbox',{name:'原图观察与当前适用范围'}).fill('尚未完成的观察');await page.getByRole('button',{name:'切换素材卡'}).click();await page.getByRole('button',{name:'切换素材卡'}).click();await open(page);await expect(page.getByRole('textbox',{name:'原图观察与当前适用范围'})).toHaveValue('尚未完成的观察');await expect(page.getByRole('combobox',{name:'判断',exact:true})).toHaveValue('');expect(f.writes).toEqual([]);});
test('read-only and hosted boundaries do not permit writes or private reads',async({page})=>{let f=await fixture(page,{readOnly:true});await open(page);await expect(page.getByRole('combobox',{name:'判断',exact:true})).toBeDisabled();expect(f.writes).toEqual([]);await page.unrouteAll({behavior:'wait'});f=await fixture(page,{hosted:true});await expect(page.getByRole('button',{name:'复核原图在当前关系中的适用性',exact:true})).toHaveCount(0);expect(f.reads()).toBe(0);expect(f.unexpected).toEqual([]);});
for(const mode of ['unsupported','wrongSha'] as const)test(mode+' runtime never falls back to old ASSET approval',async({page})=>{const f=await fixture(page,{[mode]:true});await page.getByRole('button',{name:'复核原图在当前关系中的适用性',exact:true}).click();await expect(page.getByRole('status')).toContainText(mode==='unsupported'?'尚未支持':'回执不完整');await expect(page.getByRole('button',{name:'保存复核草稿'})).toHaveCount(0);expect(f.writes).toEqual([]);expect(f.unexpected).toEqual([]);});

test('failure to preserve stale local observations cannot submit old decisions against a new basis',async({page})=>{const f=await fixture(page);await author(page);await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.endsWith(':stale-drafts'))throw new DOMException('quota','QuotaExceededError');return original.call(this,key,value);};});f.w.basisHash='f'.repeat(64);f.w.releaseId='release-two';await page.getByRole('button',{name:'重读原图与复核记录'}).click();await expect(page.getByRole('status')).toContainText('已停止提交');await expect(page.getByRole('button',{name:'保存复核草稿'})).toBeDisabled();await expect(page.getByRole('combobox',{name:'判断',exact:true})).toBeDisabled();expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);});
