import{test,expect,type Page}from'@playwright/test';
import{buildSync}from'esbuild';
import{readFileSync}from'node:fs';
import path from'node:path';
import{fileURLToPath}from'node:url';
import{defaultConfiguration}from'../host/instance-runtime/configuration-model.mjs';
import{blankProfile}from'../host/instance-runtime/blank.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
async function fixture(page:Page,{reverse=false}={}){
 const profile=blankProfile({title:'布局验证'}),configuration=defaultConfiguration(profile),writes:string[]=[],errors:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.abort());
 await page.route('**/api/**',route=>{const request=route.request(),url=new URL(request.url());if(request.method()!=='GET'){writes.push(request.method()+' '+url.pathname);return route.fulfill({status:405,json:{error:'No writes in layout review'}});}if(url.pathname==='/api/instance/profile')return route.fulfill({json:profile});if(url.pathname==='/api/instance/configuration')return route.fulfill({json:{initialized:true,revisionId:'configuration:one',releaseId:'release:one',configuration,bindings:[],draft:{revisionId:'draft:one',configuration,upgradeKeys:[],published:false}}});if(url.pathname==='/api/assistant/v1/conversations')return route.fulfill({json:{conversations:[],bridge:{online:false},pagination:{}}});return route.fulfill({status:404,json:{error:'Outside layout fixture'}});});
 const entry=`import React from'react';import{createRoot}from'react-dom/client';import{SystemConfigurationWorkspace}from'./app/system-configuration-workspace';import{InstanceProfileProvider}from'./app/instance-context';import{AssistantContextProvider}from'./app/assistant/context-provider';import{CodexConversationDock}from'./app/codex-conversation-dock';function App(){return <InstanceProfileProvider><AssistantContextProvider><main className="assistant-page"><section className="system-management workspace-view"><header className="management-heading"><h1>系统管理</h1></header><nav className="management-tabs"><button>使用与初始化</button><button className="active">系统配置</button><button>数据与运行</button></nav><SystemConfigurationWorkspace/></section></main><CodexConversationDock/><nav className="mobile-nav" aria-label="移动主导航">{['当前','故事','设定','素材','制作','管理'].map(n=><button key={n}>{n}</button>)}</nav></AssistantContextProvider></InstanceProfileProvider>}createRoot(document.getElementById('root')).render(<App/>);`;
 const out=buildSync({stdin:{contents:entry,resolveDir:root,loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-layout',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles;
 const js=out.find(f=>f.path.endsWith('.js'))!.text,bundled=out.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n'),global=readFileSync(path.join(root,'app/globals.css'),'utf8'),management=readFileSync(path.join(root,'app/system-management.css'),'utf8');
 const configurationCss=readFileSync(path.join(root,'app/system-configuration.css'),'utf8');
 const css=global+'\n'+bundled+'\n'+(reverse?configurationCss+'\n'+management:management+'\n'+configurationCss);
 await page.route('**/__configuration-layout**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><meta name="viewport" content="width=device-width, initial-scale=1"><style>'+css+'</style><div id="root"></div><script>'+js.replaceAll('</script','<\\/script')+'</script>'}));
 await page.goto('/__configuration-layout?view=system');await expect(page.getByRole('region',{name:'系统配置编辑器'})).toBeVisible();await expect(page.getByRole('button',{name:'项目 Codex',exact:true})).toBeVisible();return{writes,errors};
}
async function unobstructed(page:Page){return page.evaluate(()=>{const rect=(s:string)=>{const e=document.querySelector(s)!;const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};const overlap=(a:ReturnType<typeof rect>,b:ReturnType<typeof rect>)=>Math.max(0,Math.min(a.right,b.right)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y));const badge=rect('.configuration-heading'),nav=rect('.configuration-tabs'),footer=rect('.configuration-footer'),tools=rect('.review-floating-tools');return{badgeNavOverlap:overlap(badge,nav),footerToolsOverlap:overlap(footer,tools),badge,nav,footer,tools,overflow:document.documentElement.scrollWidth>innerWidth,actionHitTests:[...document.querySelectorAll<HTMLButtonElement>('.configuration-actions button')].map(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return e===hit||e.contains(hit)})};});}
for(const width of [390,1440])for(const reverse of [false,true])test(`${width}px badge and configuration actions remain clear with ${reverse?'reversed':'normal'} CSS loading`,async({page},info)=>{
 await page.setViewportSize({width,height:width===390?844:1000});const f=await fixture(page,{reverse});
 const tabs=page.getByRole('navigation',{name:'系统配置分组'});await expect(tabs.getByRole('button')).toHaveCount(5);
 let boxes=await unobstructed(page);expect(boxes.badgeNavOverlap).toBe(0);expect(boxes.overflow).toBe(false);
 if(width===390){const initial=await page.evaluate(()=>{const footer=document.querySelector('.configuration-footer')!,editor=document.querySelector('.configuration-editor')!;return{position:getComputedStyle(footer).position,footerTop:footer.getBoundingClientRect().top,editorBottom:editor.getBoundingClientRect().bottom}});expect(initial.position).toBe('static');expect(initial.footerTop).toBeGreaterThanOrEqual(initial.editorBottom);await page.screenshot({path:info.outputPath('configuration-390-initial.png')});}
 for(const name of ['资料与设定','素材与制作','审阅标准','AI与界面','项目与画面']){await tabs.getByRole('button',{name,exact:true}).click();await expect(tabs.getByRole('button',{name,exact:true})).toHaveAttribute('aria-pressed','true');}
 await expect(page.locator('.configuration-field-help')).toHaveCount(7);
 for(const name of ['故事名称','审阅台名称','画幅','宽度（像素）','高度（像素）','帧率'])await expect(page.getByLabel(name,{exact:true})).toHaveAttribute('aria-describedby',/configuration-technical-.+-help/);
 await expect(page.getByLabel('内部画面基线确认状态',{exact:true})).toHaveAttribute('aria-describedby','configuration-technical-picture-confirmation-help');
 for(const name of ['目标平台','目标受众','编码','色彩','响度','目标交付规格确认状态'])await expect(page.getByLabel(name,{exact:true})).toHaveCount(0);
 await expect(page.getByText('画面基线发布不会改写已生成文件的实际参数。',{exact:true})).toBeVisible();
 await page.getByLabel('故事名称',{exact:true}).fill('仅本地未保存布局稿');await expect(page.getByText('未保存草稿',{exact:true})).toBeVisible();await tabs.getByRole('button',{name:'资料与设定',exact:true}).click();await tabs.getByRole('button',{name:'项目与画面',exact:true}).click();await expect(page.getByLabel('故事名称',{exact:true})).toHaveValue('仅本地未保存布局稿');
 await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));boxes=await unobstructed(page);expect(boxes.footerToolsOverlap).toBe(0);expect(boxes.actionHitTests.every(Boolean)).toBe(true);expect(boxes.overflow).toBe(false);if(width===1440){expect(boxes.footer.height).toBeLessThan(96);await expect(page.locator('.configuration-footer')).toHaveCSS('position','sticky');}
 const publishColors=await page.locator('.configuration-publish').evaluate(e=>{const s=getComputedStyle(e);return{foreground:s.color,background:s.backgroundColor}});expect(publishColors.foreground).not.toBe(publishColors.background);expect(publishColors.background).not.toBe('rgba(0, 0, 0, 0)');
 await page.screenshot({path:info.outputPath('configuration-'+width+'.png'),fullPage:false});expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);console.log(JSON.stringify({width,reverse,boxes,publishColors}));
});
