import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const file=new URL('../app/production-workbench.tsx',import.meta.url),source=readFileSync(file,'utf8'),ast=ts.createSourceFile(file.pathname,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const names=['currentShotDesignNavigation','productionPhases','productionGates'];
const code=names.map(name=>{const found=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.equal(found.length,1);return found[0].getText(ast)}).join('\n');
const module={exports:{}};new Function('module','exports',ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(module,module.exports);const navigate=module.exports.currentShotDesignNavigation;
function fixture(){return {shots:[{id:'permanent-scene-B-SH004',sceneId:'permanent-scene-B',episodeUid:'permanent-episode-B',scopeRole:'CURRENT',activeInCurrentProduction:true,shotPlanSetRevisionId:'formal-plan-B',workPackageRefs:[]}],scenes:[{id:'permanent-scene-B',episodeUid:'permanent-episode-B',scopeRole:'CURRENT'}],episodes:[{episodeUid:'permanent-episode-B',scopeRole:'CURRENT',sceneIds:['permanent-scene-B']}],workPackages:[],productionPhases:[{id:'PREVIS'}],productionGates:[{id:'SHOT_PLAN_INPUT_LOCK',phaseId:'PREVIS'}]}}
test('current formal design without work opens exact scene and shot without creating a lock or execution target',()=>{const model=fixture(),before=JSON.stringify(model),result=navigate(model,{shotId:model.shots[0].id});assert.deepEqual(result,{sceneId:'permanent-scene-B',episodeUid:'permanent-episode-B',context:{shotId:'permanent-scene-B-SH004',workPackageId:'',workItemId:null,familyId:null,versionId:null,phaseId:'PREVIS',gateId:'SHOT_PLAN_INPUT_LOCK'}});assert.equal(JSON.stringify(model),before)});
test('paged DISCOVERED parents can contain a current adopted shot without promoting their production scope',()=>{const model=fixture();model.scenes[0].scopeRole='DISCOVERED';model.episodes[0].scopeRole='DISCOVERED';const before=JSON.stringify(model);assert.equal(navigate(model,{shotId:model.shots[0].id})?.context.shotId,model.shots[0].id);assert.equal(JSON.stringify(model),before);model.shots[0].activeInCurrentProduction=false;assert.equal(navigate(model,{shotId:model.shots[0].id}),null)});
test('historical, proposed, inactive and unadopted shots never become current design navigation',()=>{for(const patch of [{scopeRole:'HISTORICAL'},{scopeRole:'PROPOSAL'},{activeInCurrentProduction:false},{shotPlanSetRevisionId:null}]){const m=fixture();Object.assign(m.shots[0],patch);assert.equal(navigate(m,{shotId:m.shots[0].id}),null)}});
test('duplicate IDs and display labels cannot select a permanent shot',()=>{const m=fixture();assert.equal(navigate(m,{shotId:'SH004'}),null);m.shots.push({...m.shots[0]});assert.equal(navigate(m,{shotId:m.shots[0].id}),null)});
test('contradictory parent episode or scene never borrows another scene',()=>{for(const field of ['scene','episode','membership']){const m=fixture();if(field==='scene')m.scenes[0].episodeUid='different';if(field==='episode')m.episodes[0].scopeRole='HISTORICAL';if(field==='membership')m.episodes[0].sceneIds=[];assert.equal(navigate(m,{shotId:m.shots[0].id}),null)}});
test('existing work and explicit work/media targets retain their ordinary resolver',()=>{const m=fixture();for(const key of ['workPackageId','workItemId','familyId','versionId','legacyStage'])assert.equal(navigate(m,{shotId:m.shots[0].id,[key]:'specific-target'}),null);m.workPackages.push({id:'current-work'});m.shots[0].workPackageRefs=['current-work'];assert.equal(navigate(m,{shotId:m.shots[0].id}),null)});
test('only real configured gates and matching phases can be requested',()=>{const m=fixture();assert.equal(navigate(m,{shotId:m.shots[0].id,gateId:'MADE_UP'}),null);assert.equal(navigate(m,{shotId:m.shots[0].id,phaseId:'OTHER'}),null);assert(navigate(m,{shotId:m.shots[0].id,gateId:'SHOT_PLAN_INPUT_LOCK',phaseId:'PREVIS'}));m.productionPhases=[];assert.equal(navigate(m,{shotId:m.shots[0].id}),null)});
