const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),{test}=require('node:test');
class E {constructor(tag){Object.assign(this,{tag,children:[],dataset:{},attrs:{},value:'',isConnected:true,style:{},classList:{add(){},remove(){},toggle(){}}})} append(...n){this.children.push(...n)} prepend(...n){this.children.unshift(...n)} replaceChildren(...n){this.children=n} setAttribute(k,v){this.attrs[k]=v} insertBefore(n,r){this.children.splice(this.children.indexOf(r),0,n)} all(){return this.children.flatMap(n=>[n,...n.all()])} get childElementCount(){return this.children.length} querySelectorAll(){return []} addEventListener(){}}
const row=(object_id,kind,payload={},id=object_id+'-r1')=>({object_id,id,current_revision:id,kind,version:1,payload:{title:object_id,...payload}}),ref=r=>({object_id:r.object_id,revision_id:r.id});
function fixture(dir=process.env.ENTITY_ROUTE_SOURCE||path.join(__dirname,'../review_desk/static')){const entity=row('entity','ENTITY',{entity_type:'prop'}),form=row('state','STATE',{entity:ref(entity),state_model:'complete-v1'}),need=row('need','REQUIREMENT',{scope:ref(form),media_type:'image'}),asset=row('asset','ASSET',{components:[{id:'original',role:'original',mime:'image/png',sha256:'old-bytes'}],production:{object_id:'call',revision_id:'call-r1'},candidate_requirements:[ref(need)],subjects:[ref(entity)]}),current={...need,id:'need-r2',version:2},records=[entity,form,current,asset],data={entity,states:[form],media:[{id:'asset:original',record:asset,state:null}],requirements:[current],comment_records:[asset,need],comment_targets:[asset,need].map(ref),material_versions:{need:[{number:2,plan:current,members:[current],results:[]},{number:1,plan:need,members:[need,asset],results:[asset]}]}};const host=new E('main'),requests=[];
const c={state:{workspace:'settings.workspace',screenplays:[],comments:[],productionRecords:records},URL,URLSearchParams,location:{href:'http://fixture/?workspace=settings.workspace&production_object=asset&production_entity=entity&entity_state=state&production_revision=asset-r1'},document:{querySelectorAll:()=>[]},isProduction:()=>true,renderComments(){},toast(){},el:t=>new E(t),nodeText:(t,_cl,text,p)=>{const e=new E(t);e.textContent=text;p.append(e);return e}};
c.$=s=>s==='#production-view'?host:host.all().find(e=>e.id===s.slice(1));c.Option=function(text,value){const e=new E('option');e.textContent=text;e.value=value;return e};c.history={replaceState(_a,_b,url){c.location.href=String(url)}};c.api=async url=>{requests.push(url);if(url==='/api/production')return {records};if(url.includes('/entity-review?'))return structuredClone(data);const p=new URL(url,'http://fixture').searchParams;return {record:[...records,need].find(r=>r.object_id===p.get('object_id')&&(!p.get('revision_id')||r.id===p.get('revision_id'))),history:[],uses:[]}};
vm.createContext(c);for(const n of ['production.js','material-review.js','entity-review.js'])vm.runInContext(fs.readFileSync(path.join(dir,n),'utf8'),c);c.renderProductionReader=()=>{};c.paintProductionReview=()=>{};c.productionEntityIcon=()=>new E('svg');return {c,data,asset,entity,form,need,current,records,requests};}

const params=f=>new URL(f.c.location.href).searchParams;
test('actual settings load preserves exact older asset and real round while active entity remains current',async()=>{
 const f=fixture();await f.c.loadProductionWorkspace();assert.equal(f.c.state.productionSelected.id,f.asset.id);assert.equal(params(f).get('production_revision'),f.asset.id);assert.equal(f.c.state.entityReview.selectedMaterialRounds.need,1);assert.equal(params(f).get('material_id'),'need');assert.equal(params(f).get('material_round'),'1');assert.equal(f.c.state.entityReview.unassignedOpen,true);assert.equal(f.c.state.entityReview.entity.id,f.entity.id);
});
test('withdrawn entity and omitted state retain their exact old materials after refresh',async()=>{
 const f=fixture();f.entity.payload.status='withdrawn';f.form.payload.status='withdrawn';f.data.states=[];f.data.requirements=[];await f.c.loadProductionWorkspace();assert.equal(f.c.state.productionSelected.id,f.asset.id);assert.equal(f.c.state.productionChildDetail.record.id,f.form.id);assert.equal(f.c.state.entityReview.unassignedOpen,true);const url=f.c.location.href;await f.c.loadProductionWorkspace();assert.equal(f.c.location.href,url);assert.equal(f.c.state.entityReview.selectedMaterialRounds.need,1);
});
test('actual round change serializes card identity and reload restores that real round',async()=>{
 const f=fixture();f.c.location.href='http://fixture/?workspace=settings.workspace&production_entity=entity&production_object=entity';await f.c.loadProductionWorkspace();f.c.switchMaterialRound(f.c.state.entityReview,'need',1);assert.equal(params(f).get('material_round'),'1');assert.equal(params(f).get('production_revision'),f.asset.id);await f.c.loadProductionWorkspace();assert.equal(f.c.state.productionSelected.id,f.asset.id);assert.equal(f.c.state.entityReview.selectedMaterialRounds.need,1);
});
test('accurate historical CALL is restored with its material scope, not a different latest call',async()=>{
 const f=fixture(),call=row('call','CALL',{format:'production-call-v1'});f.records.push(call);f.data.comment_records.push(call);f.data.material_versions.need[1].members.push(call);f.data.materialContexts={[f.asset.id]:{call,requirements:[f.need]}};f.c.location.href='http://fixture/?workspace=settings.workspace&production_entity=entity&entity_state=state&production_object=call&production_revision=call-r1';await f.c.loadProductionWorkspace();assert.equal(f.c.state.productionSelected.id,call.id);assert.equal(params(f).get('material_round'),'1');assert.equal(f.c.state.entityReview.unassignedOpen,true);
});
test('shared exact member restores the explicitly named card and round rather than the first card',async()=>{
 const f=fixture(),other=row('other','REQUIREMENT',{scope:ref(f.form),media_type:'image'});f.data.material_versions.other=[{number:2,plan:other,members:[other,f.asset],results:[f.asset]}];f.c.location.href+='&material_id=other&material_round=2';await f.c.loadProductionWorkspace();assert.equal(f.c.state.entityReview.selectedMaterialRounds.other,2);assert.equal(f.c.state.materialCommentCard.material_id,'other');assert.equal(params(f).get('material_id'),'other');assert.equal(params(f).get('material_round'),'2');
});
test('wrong owner, wrong explicit card and unavailable round never silently change the requested URL',async()=>{
 for(const mode of ['owner','missing-owner','card','round']){const f=fixture();if(mode==='owner'){f.data.material_versions={};f.data.media=[];f.data.comment_records=[]}else if(mode==='missing-owner')f.c.location.href=f.c.location.href.replace('production_entity=entity','production_entity=missing');else f.c.location.href+=mode==='card'?'&material_id=unrelated':'&material_round=99';const before=f.c.location.href;await assert.rejects(f.c.loadProductionWorkspace(),/不属于|不可用|不存在/);assert.equal(f.c.location.href,before);assert.equal(f.c.state.entityReview,undefined);}
});
test('unrelated external record kinds remain outside settings and cannot become an entity material',async()=>{
 const f=fixture(),foreign=row('assembly','ASSEMBLY');f.records.push(foreign);f.c.location.href='http://fixture/?workspace=settings.workspace&production_entity=entity&production_object=assembly';await f.c.loadProductionWorkspace();assert.notEqual(f.c.state.productionSelected.object_id,foreign.object_id);assert.equal(f.requests.some(u=>u.includes('object_id=assembly')),false);
});
test('legacy exact media without material rounds remains readable without fabricating a version',async()=>{
 const f=fixture();delete f.data.material_versions;f.data.requirements=[];await f.c.loadProductionWorkspace();assert.equal(f.c.state.productionSelected.id,f.asset.id);assert.equal(f.c.state.entityReview.unassignedOpen,true);assert.equal(params(f).get('material_round'),null);assert.equal(params(f).get('material_id'),null);assert.equal(params(f).get('production_revision'),f.asset.id);
});
test('late entity route response cannot override a newer record or workspace',async()=>{
 for(const mode of ['record','workspace']){const f=fixture(),read=f.c.api;let release;f.c.api=async url=>url.includes('entity-review?')?new Promise(r=>release=()=>r(structuredClone(f.data))):read(url);const pending=f.c.openProductionRecord(f.asset.object_id,f.asset.id);await new Promise(r=>setImmediate(r));if(mode==='record')vm.runInContext('productionReadEpoch++',f.c);else f.c.state.workspace='story.workspace';release();await pending;assert.equal(f.c.state.entityReview,undefined);assert.equal(f.c.state.productionSelected,undefined);}
});
test('same asset present in two rounds keeps the explicit round and immutable API data',async()=>{
 const f=fixture();f.data.material_versions.need[0].members.push(f.asset);f.data.material_versions.need[0].results.push(f.asset);f.c.location.href+='&material_round=1&material_id=need';const before=JSON.stringify(f.data);await f.c.loadProductionWorkspace();assert.equal(f.c.state.entityReview.selectedMaterialRounds.need,1);assert.equal(JSON.stringify(f.data),before);await f.c.loadProductionWorkspace();assert.equal(f.c.state.entityReview.selectedMaterialRounds.need,1);
});
test('historical same-object asset renders its exact original, without inheriting newer crop or range',async()=>{
 const f=fixture(),newer={...f.asset,id:'asset-r2',version:2,payload:{...f.asset.payload,components:[{...f.asset.payload.components[0],sha256:'new-bytes'}]}};f.asset.current_revision=newer.id;f.records.splice(f.records.indexOf(f.asset),1,newer);f.data.media[0]={id:'placement',record:newer,state:null,component_id:'original',crop:{x:.2,y:.2,width:.5,height:.5}};f.data.material_versions.need[0].members.push(newer);f.data.material_versions.need[0].results.push(newer);const read=f.c.api;f.c.api=async url=>url.includes('object_id=asset&revision_id=asset-r1')?{record:f.asset,history:[],uses:[]}:read(url);await f.c.loadProductionWorkspace();const data=f.c.state.entityReview,items=f.c.entityReviewMaterialItems(data,data.media),models=f.c.entityReviewMaterialModels([],items,data);assert.equal(models[0].candidates[0].record.id,f.asset.id);assert.equal(models[0].candidates[0].component.sha256,'old-bytes');assert.equal(models[0].candidates[0].crop,null);
});
test('returning to entity/state content clears obsolete card and round URL context',async()=>{
 const f=fixture();await f.c.loadProductionWorkspace();f.c.selectEntityReviewState(f.form);assert.equal(params(f).get('material_round'),null);assert.equal(params(f).get('material_id'),null);assert.equal(params(f).get('production_object'),f.form.object_id);assert.equal(params(f).get('production_revision'),null);
});

test('actual unassigned renderer respects a verified second shared card in both empty/result directions',async()=>{
 for(const selectedHasResult of [true,false]){const f=fixture(),other=row('other','REQUIREMENT',{scope:ref(f.form),media_type:'image',status:'withdrawn'});f.data.requirements=[];f.current.payload.status='withdrawn';f.data.material_versions.need[0].members.push(f.asset);f.data.material_versions.need[0].results=selectedHasResult?[]:[f.asset];f.data.material_versions.other=[{number:3,plan:other,members:selectedHasResult?[other,f.asset]:[other],results:selectedHasResult?[f.asset]:[]},{number:2,plan:other,members:[other,f.asset],results:[f.asset]}];if(!selectedHasResult){f.records.push(other);f.c.location.href=f.c.location.href.replace('production_object=asset','production_object=other').replace('production_revision=asset-r1','production_revision=other-r1')}f.c.location.href+='&material_id=other&material_round=3';await f.c.loadProductionWorkspace();const rendered=[];f.c.materialMedia=(_p,item)=>rendered.push(item.record.id);f.c.renderActualGeneration=()=>{};f.c.renderGenerationRecipe=()=>{};const parent=new E('section');f.c.renderEntityReviewMedia(parent,f.c.state.entityReview.media,null);assert.deepEqual(parent.all().filter(n=>n.dataset.materialKey).map(n=>n.dataset.materialKey),['other']);assert.deepEqual(rendered,selectedHasResult?[f.asset.id]:[]);}
});
test('foreign or no-longer-member card memory cannot redirect unassigned material rendering',async()=>{
 for(const mode of ['foreign-data','wrong-member']){const f=fixture(),other=row('other','REQUIREMENT',{media_type:'image'});f.data.material_versions.other=[{number:3,plan:other,members:mode==='wrong-member'?[other]:[other,f.asset],results:[f.asset]}];await f.c.loadProductionWorkspace();const data=f.c.state.entityReview;f.c.state.materialCommentCard={data:mode==='foreign-data'?{}:data,material_id:'other',number:3};const models=f.c.entityReviewMaterialModels([],f.c.entityReviewMaterialItems(data,data.media),data);assert.equal(models[0].material_id,'need');}
});
test('legacy CALL uses the actual media context and keeps its exact comment target without invented rounds',async()=>{
 const f=fixture(),call=row('call','CALL',{format:'production-call-v1'});delete f.data.material_versions;f.data.materialContexts={[f.asset.id]:{call,requirements:[f.need]}};f.records.push(call);f.c.location.href='http://fixture/?workspace=settings.workspace&production_entity=entity&production_object=call&production_revision=call-r1';await f.c.loadProductionWorkspace();assert.equal(f.c.state.productionSelected.id,call.id);assert.equal(f.c.state.entityReview.historicalCall.id,call.id);assert.ok(f.c.state.entityReview.comment_targets.some(t=>t.object_id===call.object_id&&t.revision_id===call.id));assert.equal(params(f).get('material_round'),null);
});

test('empty current round restores its visible retained card on reload without showing previous results',async()=>{
 const f=fixture();f.entity.payload.status='withdrawn';f.current.payload.status='withdrawn';f.data.states=[];f.data.requirements=[];await f.c.loadProductionWorkspace();f.c.switchMaterialRound(f.c.state.entityReview,'need',2);const url=f.c.location.href;await f.c.loadProductionWorkspace();assert.equal(f.c.location.href,url);assert.equal(f.c.state.productionSelected.id,f.current.id);assert.equal(f.c.state.entityReview.selectedMaterialRounds.need,2);assert.equal(f.c.state.entityReview.unassignedOpen,true);const shown=[];f.c.materialMedia=(_p,item)=>shown.push(item.record.id);f.c.renderActualGeneration=()=>{};f.c.renderGenerationRecipe=()=>{};const parent=new E('section');f.c.renderEntityReviewMedia(parent,f.c.state.entityReview.media,null);assert.deepEqual(parent.all().filter(n=>n.dataset.materialKey).map(n=>n.dataset.materialKey),['need']);assert.deepEqual(shown,[]);assert.equal(f.c.state.entityReview.material_versions.need[1].results[0].id,f.asset.id);
});
test('an associated empty card does not open unrelated unassigned media',async()=>{
 const f=fixture();f.data.media[0].state=ref(f.form);const unrelated=row('unrelated','ASSET',{components:[{id:'original',role:'original',mime:'image/png',sha256:'unrelated'}]});f.data.media.push({id:'unrelated',record:unrelated,state:null});f.c.location.href=f.c.location.href.replace('production_object=asset','production_object=need').replace('production_revision=asset-r1','production_revision=need-r2')+'&material_id=need&material_round=2';await f.c.loadProductionWorkspace();assert.notEqual(f.c.state.entityReview.unassignedOpen,true);assert.equal(f.c.state.productionSelected.id,f.current.id);
});
