import test from 'node:test';
import {prepareImageConfigurationFixture} from './image-technical-fixture.mjs';
import assert from 'node:assert/strict';
import {materialProductionFixture,imageRequirementId,audioRequirementId,legacyObjects} from './material-production-fixture.mjs';
import {getConfiguration,previewConfiguration,publishConfiguration} from '../host/instance-runtime/configuration-service.mjs';
import {getMaterialProductionWorkspace,saveMaterialProductionDraft,previewMaterialProduction,enqueueMaterialProduction,applyMaterialProductionJob} from '../host/instance-runtime/material-production-service.mjs';
import {defaultImagePurposeProfiles,resolveImageTechnicalSpec} from '../host/instance-runtime/image-technical-spec.mjs';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {preserveMaterialProductionProjection} from '../host/instance-runtime/material-production-preservation.mjs';
const api={projectOperationalState:snapshot=>({assetFamiliesById:Object.fromEntries(snapshot.productionModel.assetFamilies.map(f=>[f.id,f])),assetVersionsById:{}})};
async function configurationInput(repo,keys=[],mutate=c=>c){const state=await repo.readTransaction(getConfiguration),configuration=structuredClone(state.configuration);configuration.schemaVersion='2.1';configuration.technical.imagePurposeProfiles=defaultImagePurposeProfiles();const input={configuration:mutate(configuration),expectedReleaseId:state.releaseId,expectedConfigurationRevisionId:state.revisionId,upgradeKeys:keys};return input;}
async function publish(repo,input){const preview=await repo.readTransaction(tx=>previewConfiguration(tx,input));return repo.writeTransaction(tx=>publishConfiguration(tx,{...input,previewHash:preview.previewHash,requestId:crypto.randomUUID()}));}
test('controlled image configuration upgrade preserves all old bindings, history, exact project canvas and source bytes',async t=>{
 const f=await prepareImageConfigurationFixture(await materialProductionFixture(t)),before=await f.repo.readView(),historical=await f.repo.readRelease(),current=await f.repo.readTransaction(getConfiguration);
 assert.equal(current.bindings.find(r=>r.key==='material:'+imageRequirementId).imageTechnicalUpgradeEligible,true);assert.equal(current.bindings.find(r=>r.key==='material:'+audioRequirementId).imageTechnicalUpgradeEligible,false);
 await publish(f.repo,await configurationInput(f.repo,[],c=>{const type=c.taxonomy.categories.flatMap(c=>c.types).find(t=>t.id==='identity');type.reviewProfileId='material-instance-neutral';c.reviewProfiles.push({...structuredClone(c.reviewProfiles.find(p=>p.id==='material-image')),id:type.reviewProfileId,label:'自定义内容标准'});return c;}));const defaultsOnly=await f.repo.readView();assert.deepEqual(defaultsOnly.snapshot.productionModel.materialRequirements.find(r=>r.id===imageRequirementId).configurationBinding,before.snapshot.productionModel.materialRequirements.find(r=>r.id===imageRequirementId).configurationBinding);
 const customDefaults=await f.repo.readTransaction(getConfiguration),customRow=customDefaults.bindings.find(r=>r.key==='material:'+imageRequirementId);assert.equal(customRow.defaultProfileId,'material-instance-neutral');assert.equal(customRow.imageTechnicalUpgradeEligible,true);
 const input=await configurationInput(f.repo,['material:'+imageRequirementId]),unchanged=await f.repo.exportState();await assert.rejects(publish(f.repo,{...input,expectedReleaseId:'stale'}),/发布已变化/);assert.deepEqual(await f.repo.exportState(),unchanged);
 await publish(f.repo,input);const after=await f.repo.readView(),req=after.snapshot.productionModel.materialRequirements.find(r=>r.id===imageRequirementId);
 assert.equal(req.configurationBinding.technicalSpec.purpose,'BASE_REFERENCE');assert.equal(req.configurationBinding.reviewSpec.profileId,'material-instance-neutral');assert.deepEqual(after.snapshot.productionModel.systemConfiguration.config.technical.picture,current.configuration.technical.picture);
 assert.deepEqual(legacyObjects(after),legacyObjects(before));assert.deepEqual(after.eventsByKind,before.eventsByKind);assert.deepEqual((await f.repo.readRelease(historical.releaseId)).snapshotBytes,historical.snapshotBytes);
 assert.equal((await f.repo.readTransaction(getConfiguration)).bindings.find(r=>r.key==='material:'+imageRequirementId).imageTechnicalUpgradeEligible,false);
});
test('new material source freezes typed spec across producer, EO and definition; compiler preserves exact bytes',async t=>{
 const f=await prepareImageConfigurationFixture(await materialProductionFixture(t));await publish(f.repo,await configurationInput(f.repo,['material:'+imageRequirementId]));
 const w=await f.repo.readTransaction(tx=>getMaterialProductionWorkspace(tx,{requirementId:imageRequirementId,api}));const saved=await f.repo.writeTransaction(tx=>saveMaterialProductionDraft(tx,{requirementId:imageRequirementId,expectedReleaseId:w.releaseId,expectedDraftRevisionId:w.draftHeadRevisionId,content:{model:'image-fixture',prompt:'Neutral protocol fixture',negativePrompt:'',parameters:{},inputBindings:[]}},{api}));
 const p=await f.repo.readTransaction(tx=>previewMaterialProduction(tx,{requirementId:imageRequirementId,draftRevisionId:saved.revisionId},{api}));const job=await f.repo.writeTransaction(tx=>enqueueMaterialProduction(tx,{requirementId:imageRequirementId,draftRevisionId:saved.revisionId,previewHash:p.previewHash,requestId:'typed-first'},{api}));
 const result=await f.repo.writeTransaction(tx=>applyMaterialProductionJob(tx,{jobId:job.jobId,api})),view=await f.repo.readView(),model=view.snapshot.productionModel,definition=view.recipes.executionDefinitions.find(d=>d.id===result.definitionId),binding=resolveImageTechnicalSpec(model,{familyId:result.familyId,expectedOutputId:result.expectedOutputId,definition});assert.equal(binding.technicalSpec.purpose,'BASE_REFERENCE');
 const row=model.materialProductionPlans[0],doc=await f.repo.readDocumentRevision(row.sourceRevisionId),source=JSON.parse(doc.bytes);assert.equal(sha256(doc.bytes),row.sourceSha256);for(const key of ['assetFamily','expectedOutput','materialWorkItem','executionDefinition'])assert.deepEqual(source[key].technicalSpec,binding.technicalSpec);
 const documents=[];for(const revisionId of view.sourceRevisionIds)documents.push(await f.repo.readDocumentRevision(revisionId));const blank=structuredClone(view.snapshot);for(const key of ['materialProductionPlans','materialWorkItems','expectedOutputs','assetFamilies'])blank.productionModel[key]=(blank.productionModel[key]||[]).filter(r=>![row.id,row.workItemId,row.expectedOutputId,row.familyId].includes(r.id));
 const {snapshot:restored}=preserveMaterialProductionProjection({snapshot:blank,recipes:view.recipes,baseSnapshot:view.snapshot,baseRecipes:view.recipes,documents});assert.deepEqual(restored.productionModel.assetFamilies.find(r=>r.id===row.familyId),model.assetFamilies.find(r=>r.id===row.familyId));assert.equal(canonicalJson(restored.productionModel.materialWorkItems.find(r=>r.id===row.workItemId)),canonicalJson(source.materialWorkItem));
 const downgrade=await configurationInput(f.repo,['material:'+imageRequirementId],c=>{c.schemaVersion='2.0';delete c.technical.imagePurposeProfiles;return c;});await assert.rejects(f.repo.readTransaction(tx=>previewConfiguration(tx,downgrade)),/冻结规格/);assert.equal((await f.repo.listMedia()).length,0);
});
test('an already provisioned legacy image cannot get typed standards through ordinary configuration upgrade',async t=>{
 const f=await prepareImageConfigurationFixture(await materialProductionFixture(t));const input=await configurationInput(f.repo,['material:'+imageRequirementId]);await f.repo.writeTransaction(async tx=>{const view=await tx.readView(),snapshot=structuredClone(view.snapshot),req=snapshot.productionModel.materialRequirements.find(r=>r.id===imageRequirementId);req.plannedAssetFamilyId='existing-family';await tx.publishRelease({snapshot,recipes:view.recipes,expectedReleaseId:view.releaseId,sourceRevisionIds:view.sourceRevisionIds});});
 const fresh=await configurationInput(f.repo,input.upgradeKeys),before=await f.repo.exportState();await assert.rejects(f.repo.readTransaction(tx=>previewConfiguration(tx,fresh)),/尚未首次建族/);assert.deepEqual(await f.repo.exportState(),before);
});
