import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
async function fixture(page:Page,readonly=false){
 const errors:string[]=[],requests:string[]=[];
 const configuration={schemaVersion:'2.0',technical:{picture:{aspectRatio:'16:9',width:1920,height:1080,fps:24,confirmation:'CONFIRMED'}}};
 const spec={schemaVersion:'IMAGE_TECHNICAL_SPEC_V1',purpose:'PRODUCTION_FRAME',mediaType:'IMAGE',dimensionPolicy:'EXACT_PROJECT_CANVAS',formats:['PNG'],intrinsicFps:'NOT_APPLICABLE',frameCount:1,canvas:{aspectRatio:'16:9',width:3840,height:2160,fps:25,confirmation:'CONFIRMED'}};
 const state={configuration,bindings:[{key:'new',title:'尚未建档的背景图',imageTechnicalUpgradeEligible:true},{key:'old',title:'已有采用图片',imageTechnicalUpgradeEligible:false},{key:'fixed',title:'固定高分辨率关键帧',imageTechnicalUpgradeEligible:false,technicalSpec:spec,technicalSpecHash:'a'.repeat(64)}]};
 const entry=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{ImagePurposeConfiguration}from'./app/image-purpose-configuration';function Harness(){const[c,setC]=useState(${JSON.stringify(configuration)}),[keys,setKeys]=useState(['unrelated-review-upgrade']);return <><ImagePurposeConfiguration config={c} state={${JSON.stringify(state)}} readonly={${readonly}} onEdit={fn=>{const next=structuredClone(c);fn(next);setC(next);}} upgradeKeys={keys} onUpgrade={setKeys}/><output aria-label="当前配置选择">{JSON.stringify({config:c,upgradeKeys:keys})}</output></>};createRoot(document.getElementById('root')).render(<Harness/>);`;
 const js=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'purpose-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles[0].text;
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.pathname==='/__purpose')return route.fulfill({contentType:'text/html',body:`<!doctype html><html><body><div id="root"></div><script>${js}</script></body></html>`});requests.push(u.pathname);return route.fulfill({status:418,body:'unexpected'});});await page.goto('http://127.0.0.1:4309/__purpose');return {errors,requests};
}
test('typed stages require explicit opt-in and per-object upgrade selection',async({page})=>{const f=await fixture(page);await expect(page.getByRole('checkbox')).toHaveCount(0);await expect(page.getByRole('status',{name:'当前配置选择'})).toContainText('"schemaVersion":"2.0"');await page.getByRole('button',{name:'启用分阶段图像规格'}).click();await expect(page.getByText('已启用（待保存、预览及发布）',{exact:false})).toBeVisible();await page.getByText('为尚未建档的图片需求启用新规格（1）',{exact:true}).click();const checkbox=page.getByRole('checkbox',{name:'尚未建档的背景图'});await expect(checkbox).not.toBeChecked();await expect(page.getByRole('checkbox',{name:'已有采用图片'})).toHaveCount(0);await checkbox.check();const output=page.getByRole('status',{name:'当前配置选择'});await expect(output).toContainText('"upgradeKeys":["unrelated-review-upgrade","new"]');await expect(output).toContainText('"entityTypes":[');await checkbox.uncheck();await expect(output).toContainText('"upgradeKeys":["unrelated-review-upgrade"]');expect(f.errors).toEqual([]);expect(f.requests).toEqual([]);});
test('fixed historical image spec displays its own canvas rather than current global values',async({page})=>{const f=await fixture(page);await page.getByText('已有图片的固定规格（1）',{exact:true}).click();await expect(page.getByText('目标画布 3840 × 2160 像素，画幅 16:9。',{exact:true})).toBeVisible();await expect(page.getByText('单张 PNG 静态图片，无自身帧率。进入 25 fps 时间线。',{exact:true})).toBeVisible();expect(f.requests).toEqual([]);});
test('read-only configuration exposes fixed specs without an enable action',async({page})=>{const f=await fixture(page,true);await expect(page.getByRole('button',{name:'启用分阶段图像规格'})).toHaveCount(0);await page.getByText('已有图片的固定规格（1）',{exact:true}).click();await expect(page.getByRole('heading',{name:'正式关键帧规格'})).toBeVisible();expect(f.errors).toEqual([]);expect(f.requests).toEqual([]);});
