import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createServer} from 'node:net';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {docker} from '../scripts/instance-postgres.mjs';
import {requestFreeze,installFreezeMarker,verifyFreezeProof,assertFrozenStart,authorizeFrozenStart,clearFreezeMarker} from '../scripts/instance-freeze-proof.mjs';
const base=path.resolve('.test-tmp');await mkdir(base,{recursive:true});const fixture=await mkdtemp(path.join(base,'freeze-proof-')),root=path.join(fixture,'instance');await mkdir(path.join(root,'runtime/locks'),{recursive:true});const instanceId='freeze-'+randomUUID(),project='review-freeze-'+randomUUID(),server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));let container,unplanned;const checks=[];
try{
 const bootstrap=Buffer.from(JSON.stringify({schemaVersion:'1.0',instanceId,database:'data/review.sqlite'})+'\n');await writeFile(path.join(root,'instance.json'),bootstrap);
 const id=(await docker(['run','-d','--name',project,'--label','com.docker.compose.project='+project,'--label','com.docker.compose.service=review-site','--publish',`127.0.0.1:${port}:3000`,'--mount',`type=bind,source=${root}/instance.json,target=/instance/instance.json,readonly`,'node:22-bookworm-slim','node','-e','setInterval(()=>{},1000)'])).toString().trim();container=id;
 const info=JSON.parse(await docker(['inspect',id]))[0],owner={schemaVersion:'1.0',containerId:id,imageId:info.Image,instanceId,hostRoot:root,composeProject:project},ownerBytes=Buffer.from(JSON.stringify(owner));await writeFile(path.join(root,'runtime/storage-owner.json'),ownerBytes);
 const captureBody={schemaVersion:'1.0',kind:'SQLITE_CUTOVER_FREEZE_CAPTURE',sourceRoot:root,port,instanceId,composeProject:project,sourceOwnerHash:sha256(ownerBytes),sourceBootstrapSha256:sha256(bootstrap),oldContainers:[{id,name:project,imageId:info.Image,service:'review-site',running:true,instanceRoot:root}],hostProcesses:[],protectedContainers:[]},capture={...captureBody,captureSha256:sha256(canonicalJson(captureBody))},captureFile=path.join(fixture,'capture.json');await writeFile(captureFile,JSON.stringify(capture));
 const proofBody={schemaVersion:'1.0',kind:'SQLITE_CUTOVER_FREEZE',status:'FROZEN_VERIFIED',captureFile,captureSha256:capture.captureSha256,...Object.fromEntries(['sourceRoot','port','instanceId','composeProject','sourceOwnerHash','sourceBootstrapSha256','oldContainers','hostProcesses','protectedContainers'].map(k=>[k,capture[k]])),metadata:{instanceId,runtimeEpoch:randomUUID(),repositoryRevision:1}},proof={...proofBody,proofSha256:sha256(canonicalJson(proofBody))},file=path.join(fixture,'proof.json');await writeFile(file,JSON.stringify(proof));
 const requested=await requestFreeze(root);await assert.rejects(assertFrozenStart(root),/normal start\/deploy is blocked/);checks.push('pending freeze blocks start before a completed proof exists');
 await assert.rejects(installFreezeMarker(file,{requestId:requested.requestId}),/restarted or replaced/);await docker(['stop','--time','1',id]);await installFreezeMarker(file,{requestId:requested.requestId});await verifyFreezeProof(file,{sourceRoot:root,port});checks.push('only exact stopped original IDs, image, marker, bootstrap and HostConfig port verify');
 await assert.rejects(verifyFreezeProof(file,{sourceRoot:fixture}),/different root/);await assert.rejects(verifyFreezeProof(file,{port:port+1}),/different root/);checks.push('freeze cannot authorize another root or port');
 unplanned=(await docker(['create','--label','com.docker.compose.project='+project+'-other','--label','com.docker.compose.service=review-site','--mount',`type=bind,source=${root}/instance.json,target=/instance/instance.json,readonly`,'node:22-bookworm-slim','node','-e','setInterval(()=>{},1000)'])).toString().trim();await assert.rejects(verifyFreezeProof(file),/unplanned Compose owner/);await docker(['rm',unplanned]);unplanned=null;checks.push('different Compose project cannot introduce another same-root review owner before marker publication');

 const tampered=path.join(fixture,'tampered.json');await writeFile(tampered,JSON.stringify({...proof,oldContainers:[{...proof.oldContainers[0],running:false}]}));await assert.rejects(verifyFreezeProof(tampered),/Invalid explicit freeze proof/);checks.push('original running flags cannot be changed in the proof');
 const pgBytes=Buffer.from(JSON.stringify({schemaVersion:'2.0',instanceId,database:{kind:'postgres'}})+'\n'),softwareCommit='a'.repeat(40);await writeFile(path.join(root,'instance.json'),pgBytes);const plan={sourceRoot:root,freeze:{file,proofSha256:proof.proofSha256},stableFiles:{stageBootstrapSha256:sha256(pgBytes)},softwareCommit,planSha256:'b'.repeat(64)};await authorizeFrozenStart(plan);
 await assert.rejects(assertFrozenStart(root),/normal start\/deploy is blocked/);await assert.rejects(assertFrozenStart(root,{freezeSha:'c'.repeat(64),port,softwareCommit}),/normal start\/deploy is blocked/);await assertFrozenStart(root,{freezeSha:proof.proofSha256,port,softwareCommit});checks.push('only matching freeze SHA, planned PG bytes, port and exact software can start');
 await docker(['start',id]);await assert.rejects(assertFrozenStart(root,{freezeSha:proof.proofSha256,port,softwareCommit}),/restarted or replaced/);await docker(['stop','--time','1',id]);checks.push('guard recheck catches an owner restarted while a build was running');
 await assert.rejects(clearFreezeMarker(root,'d'.repeat(64)),/another freeze/);await clearFreezeMarker(root,proof.proofSha256);await assertFrozenStart(root);checks.push('only exact successful cutover or rollback can clear its own freeze marker');
 const start=await readFile(new URL('../scripts/instance-start.mjs',import.meta.url),'utf8'),cutover=await readFile(new URL('../scripts/instance-cutover.mjs',import.meta.url),'utf8');assert.ok(start.indexOf('await assertFrozenStart(runtime.root',start.indexOf("'build',"))<start.indexOf("[...baseArgs, 'up'"));assert.ok(cutover.includes('freeze:plan.freeze?.file')&&cutover.includes('oldContainers:frozenProof?frozenProof.oldContainers'));checks.push('start rechecks after build; fresh cutover keeps original running states and exact proof');
 console.log(JSON.stringify({status:'PASS',checks},null,2));
}finally{if(unplanned)await docker(['rm','-f',unplanned]).catch(()=>{});if(container)await docker(['rm','-f',container]).catch(()=>{});await rm(fixture,{recursive:true});}
