import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {domainHash} from '../host/instance-runtime/domain-model.mjs';
import {executionDefinitionHash} from '../host/instance-runtime/execution-definition-hash.mjs';
import {materialProductionRebaseIdentity} from '../host/instance-runtime/material-production-rebase-identity.mjs';
import {materialProductionRebaseClosures} from '../host/instance-runtime/material-production-rebase-preservation.mjs';
import {materialProductionRevisionClosures} from '../host/instance-runtime/material-production-revision-preservation.mjs';

const SCHEMA='MATERIAL_PRODUCTION_REQUIREMENT_REBASE_V1';
const clone=v=>structuredClone(v);
function fixture({ordinaryPrefix=false,historicalInstance=false}={}){
 const pid='MP-PLAN-neutral',fid='family-neutral',wid='work-neutral',rid='requirement-neutral',repId='rep-neutral',iid='instance-neutral',documents=[];
 const scope=[{scopeType:'SCENE',scopeId:'scene-neutral',revisionId:'scene-revision'}];
 const before={demand:{id:rid,title:'中性原子图',representationId:repId,mediaType:'IMAGE',category:'prop',reuseScope:'SCENE',scope,evidence:[],acceptanceCriteria:['身份可辨。']},representation:{id:repId,entityId:'entity-neutral',stateId:null,type:'PROP_STATE',label:'中性表现',dimensions:{},assetFamilyIds:[fid],requirementIds:[rid],authority:'A',evidence:[]},entity:{id:'entity-neutral',type:'PROP',name:'中性对象',aliases:[],description:'中性',authority:'A',evidence:[]},state:null};
 const after=clone(before);after.demand.acceptanceCriteria.push('当前局部遮挡可辨。');
 const graph=r=>({schemaVersion:'1.0',entities:[r.entity],states:[],representations:[r.representation],relations:[],requirements:[r.demand]});
 function doc(body,revisionId,path,sourceRole,metadata={}){const bytes=Buffer.from(canonicalJson(body)),d={revisionId,sha256:sha256(bytes),bytes,deleted:false,aliases:[path],metadata:{sourceRole,...metadata}};documents.push(d);return d;}
 const oldGraph=graph(before),newGraph=graph(after),oldRef={revisionId:'graph-before',sha256:domainHash(oldGraph)},newRef={revisionId:'graph-after',sha256:domainHash(newGraph)};
 const contexts=[],outputs=[],definitions=[],prompts=[];
 const config={reviewSpec:{hash:'a'.repeat(64),criteria:[{id:'criterion-neutral',label:'技术清晰'}]}},req=r=>({id:rid,title:r.demand.title,representationRef:repId,entityRef:r.entity.id,stateRef:r.representation.stateId,mediaType:r.demand.mediaType,category:r.demand.category,reuseScope:r.demand.reuseScope,scopeBindings:r.demand.scope,sourceBindings:r.demand.evidence,acceptanceProfile:r.representation.type,sourceKind:'DOMAIN_GRAPH',requirementClass:'REQUIRED',requirementHash:domainHash({demand:r.demand,representation:r.representation}),assetFamilyRefs:[fid],acceptanceCriteria:r.demand.acceptanceCriteria,reviewSpec:config.reviewSpec,configurationBinding:config,materialWorkItemRef:wid,plannedAssetFamilyId:fid});
 const req1=req(before),req2=req(after),firstPath='story/material-production/plans/'+pid+'.json';
 const output={id:'EO-001',familyId:fid,materialProductionPlanId:pid,targetPath:'media/_review_pending/material-production/'+fid+'/V001.png',plannedVersionLabel:'V001',legacyVersionId:'EO-001',expectationState:'PLANNED',realizedVersionId:null,sourceRef:firstPath,executionDefinitionRef:'DEF-001'};
 const family={id:fid,kind:'IMAGE',materialProductionPlanId:pid,ownerRef:wid,reviewOwner:'MATERIAL',requirementRefs:[rid],versionRefs:[],expectedOutputRefs:[output.id],currentExpectedOutputId:output.id,domainContext:{hash:'d'.repeat(64)},reviewSpec:config.reviewSpec};
 const ctx={id:'CTX-001',schemaVersion:'2.0',scopeType:'PROJECT',scopeId:historicalInstance?'instance-original-history':iid,requirementId:rid,requirementHash:req1.requirementHash};ctx.contextHash=domainHash(ctx);
 const work={id:wid,materialProductionPlanId:pid,requirementRef:rid,requirementHash:req1.requirementHash,outputAssetRef:fid,inputAssetRefs:[],executionDefinitionRef:'DEF-001',promptRef:'DEF-001:r1',reviewContextRef:ctx.id,configurationBinding:config,reviewSpec:config.reviewSpec};
 const def={id:'DEF-001',currentRevisionId:'DEF-001:r1',definitionHashSchemaVersion:'SHOT_PRODUCTION_SOURCE_V1',executorKind:'MODEL_CALL',workItemRef:wid,materialProductionPlanId:pid,materialRequirementRef:rid,materialRequirementHash:req1.requirementHash,upload:{items:[],rawText:''},prompt:{main:'中性原母版。'},model:{branch:'test-provider'},parameters:{width:1024},output:{assetFamilyRef:fid,expectedOutputRef:output.id,path:output.targetPath,mediaType:'IMAGE'},parentVersionId:null};def.definitionHash=executionDefinitionHash(def);
 const pr={id:def.currentRevisionId,executionDefinitionId:def.id,definitionHash:def.definitionHash,prompt:def.prompt};
 const first={schemaVersion:'MATERIAL_PRODUCTION_PLAN_V1',id:pid,basis:before,graphBinding:{afterRepresentation:before.representation},requirementAfter:req1,assetFamily:family,materialWorkItem:work,expectedOutput:output,executionDefinition:def,promptRevision:pr,workContext:ctx};
 const firstDoc=doc(first,'source-first',firstPath,'MATERIAL_PRODUCTION_PLAN');
 const plan={id:pid,requirementId:rid,representationId:repId,familyId:fid,workItemId:wid,expectedOutputId:output.id,definitionId:def.id,requirementHash:req1.requirementHash,graphRevisionId:oldRef.revisionId,graphSha256:oldRef.sha256,sourcePath:firstPath,sourceRevisionId:firstDoc.revisionId,sourceSha256:firstDoc.sha256};
 const initial={plan,body:first,doc:firstDoc};
 function install(body,d){const envelope={sourceRef:body.sourcePath||firstPath,sourceRevisionId:d.revisionId,sourceSha256:d.sha256};outputs.push(clone(body.expectedOutput));definitions.push({...clone(body.executionDefinition),...envelope});prompts.push({...clone(body.promptRevision),...envelope});if(body.workContext)contexts.push(clone(body.workContext));}
 install(first,firstDoc);
 const domainSources={},rowDomainSources={};
 for(const [name,ref,g]of [['before',oldRef,oldGraph],['after',newRef,newGraph]]){const p='story/material-production/domain-bases/'+ref.revisionId+'.json',d=doc(g,'source-'+name,p,'MATERIAL_PRODUCTION_DOMAIN_BASIS',{graphRevisionId:ref.revisionId,graphSha256:ref.sha256,instanceId:name==='before'&&historicalInstance?'instance-original-history':iid});domainSources[name]={path:p,sha256:d.sha256,graphRevisionId:ref.revisionId,graphSha256:ref.sha256};rowDomainSources[name]={...domainSources[name],revisionId:d.revisionId};}
 function successor(previous,number,rebaseId,isRebase=false){
  const currentRequirement=isRebase?req2:previous.requirementAfter,currentRows=currentRequirement.requirementHash===req1.requirementHash?before:after,currentGraphRef=currentRows===before?oldRef:newRef;
  const id=(isRebase?'MP-REBASE-':'MP-RECIPE-')+String(number).repeat(24),definitionId='DEF-00'+number,path='story/material-production/'+(isRebase?'requirement-rebases/':'recipes/')+id+'.json',label='V00'+number;
  const candidate={eventId:'candidate-'+number,versionId:fid+'@'+previous.expectedOutput.plannedVersionLabel,familyId:fid,sha256:String(number).repeat(64),runId:'run-'+number,executionRequestId:'request-'+number,executionDefinitionId:previous.executionDefinition.id,callPackageHash:previous.executionDefinition.definitionHash,expectedOutputId:previous.expectedOutput.id,path:previous.expectedOutput.targetPath};
  const rev={materialProductionPlanId:pid,familyId:fid,workItemId:wid,definitionId:previous.executionDefinition.id,definitionHash:previous.executionDefinition.definitionHash,expectedOutputId:previous.expectedOutput.id,expectedOutputHash:domainHash(previous.expectedOutput),parentVersionId:candidate.versionId,parentVersionSha256:candidate.sha256,parentCandidate:{eventId:candidate.eventId,sha256:domainHash(candidate)},plannedVersionLabel:label,instanceId:iid,runtimeEpoch:'epoch-neutral',requestHeads:[],runHeads:[],...(!isRebase&&rebaseId?{rebaseId}:{})};
  const basis={...clone(currentRows),requirementHash:currentRequirement.requirementHash,graphRef:currentGraphRef,revision:rev,...(isRebase?{mode:'REQUIREMENT_REBASE'}:{})};
  const eo={...clone(previous.expectedOutput),id:'EO-00'+number,targetPath:'media/_review_pending/material-production/'+fid+'/'+label+'.png',plannedVersionLabel:label,sourceRef:path,executionDefinitionRef:definitionId};
  const definition={...clone(previous.executionDefinition),id:definitionId,currentRevisionId:definitionId+':r1',materialRequirementHash:currentRequirement.requirementHash,...(rebaseId?{materialProductionRequirementRebaseId:rebaseId}:{}),prompt:{main:'中性当前状态。'},output:{assetFamilyRef:fid,expectedOutputRef:eo.id,path:eo.targetPath,mediaType:'IMAGE'},parentVersionId:candidate.versionId,parentVersionSha256:candidate.sha256};definition.definitionHash=executionDefinitionHash(definition);
  const prompt={id:definition.currentRevisionId,executionDefinitionId:definition.id,definitionHash:definition.definitionHash,prompt:definition.prompt};
  const body={schemaVersion:isRebase?SCHEMA:'MATERIAL_PRODUCTION_RECIPE_V1',id,sourcePath:path,materialProductionPlanId:pid,requirementId:rid,representationId:repId,basis,basisHash:domainHash(basis),previousDefinitionId:previous.executionDefinition.id,previousExpectedOutputId:previous.expectedOutput.id,parentVersionId:candidate.versionId,parentVersionSha256:candidate.sha256,parentCandidate:candidate,requirementBefore:isRebase?req1:currentRequirement,requirementAfter:currentRequirement,assetFamily:{...clone(previous.assetFamily),currentExpectedOutputId:eo.id,expectedOutputRefs:[...previous.assetFamily.expectedOutputRefs,eo.id]},materialWorkItem:{...clone(previous.materialWorkItem),requirementHash:currentRequirement.requirementHash,executionDefinitionRef:definition.id,promptRef:prompt.id,...(rebaseId?{materialProductionRequirementRebaseId:rebaseId}:{})},executionDefinition:definition,promptRevision:prompt,expectedOutput:eo,inputBindings:[],authoringContent:{inputBindings:[]}};
  if(isRebase){body.mode='REQUIREMENT_REBASE';body.operationEventSequence=10;const identity=materialProductionRebaseIdentity({before,after});body.rebase={before,after,...identity,previousBaseline:{sourcePath:firstPath,sourceRevisionId:firstDoc.revisionId,sourceSha256:firstDoc.sha256,requirementHash:plan.requirementHash},graphRef:newRef,domainSources,acknowledgement:{confirmed:true,beforeHash:identity.beforeHash,afterHash:identity.afterHash,note:'明确按当前局部状态重新制作。'}};const c={id:'CTX-002',schemaVersion:'2.0',scopeType:'PROJECT',scopeId:iid,semanticStatus:'AUTHORED_DRAFT',reviewable:true,requirementId:rid,requirementHash:req2.requirementHash,representationId:repId,sourceRefs:[path],binding:{requirementId:rid,requirementHash:req2.requirementHash,domainContextHash:family.domainContext.hash,bindingStatus:'CURRENT',mismatchReasons:[]},judgment:{purpose:{class:'A',text:req2.title,evidenceRefs:[path]},acceptanceCriteria:req2.acceptanceCriteria},materialProductionRequirementRebaseId:id};c.contextHash=domainHash(c);body.workContext=c;body.materialWorkItem.reviewContextRef=c.id;}
  const d=doc(body,'source-'+number,path,isRebase?'MATERIAL_PRODUCTION_REQUIREMENT_REBASE':'MATERIAL_PRODUCTION_RECIPE');install(body,d);
  const row={id,materialProductionPlanId:pid,requirementId:rid,representationId:repId,familyId:fid,workItemId:wid,expectedOutputId:eo.id,definitionId:definition.id,definitionHash:definition.definitionHash,previousDefinitionId:body.previousDefinitionId,previousExpectedOutputId:body.previousExpectedOutputId,parentVersionId:candidate.versionId,parentVersionSha256:candidate.sha256,requirementHash:currentRequirement.requirementHash,basisHash:body.basisHash,sourcePath:path,sourceRevisionId:d.revisionId,sourceSha256:d.sha256,...(rebaseId?{rebaseId}:{}),...(isRebase?{schemaVersion:SCHEMA,domainSources:rowDomainSources}:{})};return {body,row,doc:d};
 }
 const prefix=ordinaryPrefix?successor(first,2,null):null,number=ordinaryPrefix?3:2,rebaseId='MP-REBASE-'+String(number).repeat(24),second=successor(prefix?.body||first,number,rebaseId,true),third=successor(second.body,number+1,rebaseId);
 const model={materialProductionPlans:[plan],materialProductionRecipeRevisions:[...(prefix?[prefix.row]:[]),second.row,third.row],materialWorkItems:[clone(third.body.materialWorkItem)],assetFamilies:[clone(third.body.assetFamily)],expectedOutputs:outputs,reviewContexts:contexts,assetVersions:[]},recipes={executionDefinitions:definitions,promptRevisions:prompts};
 return {model,recipes,documents,initialClosures:[initial],validateLegacySegment:materialProductionRevisionClosures,second,third,first,plan};
}
const run=f=>materialProductionRebaseClosures(f);
const rejects=f=>assert.throws(()=>run(f),e=>e.code==='MATERIAL_PRODUCTION_SOURCE_CONFLICT');
function editBody(f,index,fn){const row=f.model.materialProductionRecipeRevisions[index],d=f.documents.find(d=>d.revisionId===row.sourceRevisionId),body=JSON.parse(Buffer.from(d.bytes).toString());fn(body);d.bytes=Buffer.from(canonicalJson(body));d.sha256=sha256(d.bytes);row.sourceSha256=d.sha256;for(const r of [...f.recipes.executionDefinitions,...f.recipes.promptRevisions])if(r.sourceRevisionId===d.revisionId)r.sourceSha256=d.sha256;return body;}

test('a new rebase plus ordinary successor validates through the actual legacy callback and preserves all original source bytes',()=>{
 const f=fixture(),before=canonicalJson(f.model),sources=f.documents.map(d=>sha256(d.bytes));const p=run(f);assert.equal(p.revisions.length,2);assert.equal(p.anchors.length,1);assert.equal(p.anchors[0].plan.id,f.plan.id);assert.equal(p.anchors[0].plan.expectedOutputId,f.plan.expectedOutputId);assert.equal(p.anchors[0].plan.requirementHash,f.second.row.requirementHash);assert.deepEqual(p.contextIds,['CTX-001','CTX-002']);assert.equal(canonicalJson(f.model),before);assert.deepEqual(f.documents.map(d=>sha256(d.bytes)),sources);
});

for(const [label,change]of[
 ['missing rebase doc',f=>f.documents=f.documents.filter(d=>d.revisionId!==f.second.row.sourceRevisionId)],['rebase doc byte corruption',f=>f.second.doc.bytes=Buffer.from('{}')],['wrong source role',f=>f.second.doc.metadata.sourceRole='MATERIAL_PRODUCTION_RECIPE'],['wrong alias',f=>f.second.doc.aliases=['elsewhere']],['unknown row schema',f=>f.second.row.schemaVersion='FUTURE_UNKNOWN'],['duplicate successor',f=>f.model.materialProductionRecipeRevisions.push(clone(f.third.row))],['disconnected predecessor',f=>f.third.row.previousDefinitionId='not-in-chain'],['definition parent SHA',f=>f.recipes.executionDefinitions[1].parentVersionSha256='0'.repeat(64)],['missing old context',f=>f.model.reviewContexts.shift()],['changed new context',f=>f.model.reviewContexts[1].judgment.acceptanceCriteria=['replacement']],['missing domain evidence',f=>f.documents=f.documents.filter(d=>d.revisionId!=='source-before')],['foreign domain evidence instance',f=>f.documents.find(d=>d.revisionId==='source-after').metadata.instanceId='other-instance'],['changed domain original revision',f=>f.documents.find(d=>d.revisionId==='source-before').metadata.graphRevisionId='different'],['stripped ordinary marker',f=>delete f.third.row.rebaseId],['changed current work baseline',f=>f.model.materialWorkItems[0].requirementHash=f.plan.requirementHash],['lost original output',f=>f.model.expectedOutputs.shift()],
])test('source preservation rejects '+label,()=>{const f=fixture();change(f);rejects(f);});

for(const [label,mutate]of[
 ['silent original baseline swap',b=>b.rebase.previousBaseline.requirementHash='0'.repeat(64)],['missing operation watermark',b=>delete b.operationEventSequence],['invalid operation watermark',b=>b.operationEventSequence=-1],['unacknowledged semantic diff',b=>b.rebase.acknowledgement.confirmed=false],['invented diff',b=>b.rebase.changes=[]],['permanent entity drift',b=>b.rebase.after.entity.id='other'],['scope widening',b=>b.rebase.after.demand.scope.push({scopeType:'SCENE',scopeId:'other',revisionId:'r'})],['original review standard changed',b=>b.requirementAfter.reviewSpec={hash:'f'.repeat(64)}],['parent candidate path wrong',b=>b.parentCandidate.path='elsewhere.png'],['unknown proof protocol field',b=>b.rebase.bypass=true],['domain copy points other original',b=>b.rebase.domainSources.after.graphRevisionId='wrong'],
])test('rehashing the source envelope cannot authorize '+label,()=>{const f=fixture();editBody(f,0,mutate);rejects(f);});

test('no-rebase paths delegate untouched to the old verifier without additional source assumptions',()=>{
 const model={materialProductionRecipeRevisions:[],materialWorkItems:[]},recipes={executionDefinitions:[]},documents=[],initialClosures=[{body:{workContext:{id:'old-context'}}}];let calls=0;
 const actual=materialProductionRebaseClosures({model,recipes,documents,initialClosures,validateLegacySegment:input=>{calls++;assert.equal(input.model,model);assert.equal(input.recipes,recipes);assert.equal(input.documents,documents);assert.equal(input.initialClosures,initialClosures);return [];}});assert.equal(calls,1);assert.equal(actual.anchors,initialClosures);assert.deepEqual(actual.contextIds,['old-context']);
});


test('rehashing all definition and source envelopes cannot alter a frozen producer property',()=>{
 const f=fixture(),row=f.second.row,d=f.second.doc,body=JSON.parse(Buffer.from(d.bytes).toString());body.executionDefinition.executorKind='OTHER';body.executionDefinition.definitionHash=executionDefinitionHash(body.executionDefinition);body.promptRevision.definitionHash=body.executionDefinition.definitionHash;row.definitionHash=body.executionDefinition.definitionHash;d.bytes=Buffer.from(canonicalJson(body));d.sha256=sha256(d.bytes);row.sourceSha256=d.sha256;
 Object.assign(f.recipes.executionDefinitions[1],body.executionDefinition,{sourceSha256:d.sha256});Object.assign(f.recipes.promptRevisions[1],body.promptRevision,{sourceSha256:d.sha256});rejects(f);
});

test('rehashing the complete source cannot present different criteria than its proven domain demand',()=>{
 const f=fixture();editBody(f,0,b=>{b.requirementAfter.acceptanceCriteria=['not the proven demand'];b.workContext.judgment.acceptanceCriteria=b.requirementAfter.acceptanceCriteria;const rest={...b.workContext};delete rest.contextHash;b.workContext.contextHash=domainHash(rest);});rejects(f);
});


test('ordinary prefix, rebase, and ordinary successor retain one unbranched original plan with separately verified segments',()=>{
 const f=fixture({ordinaryPrefix:true}),calls=[];const original=f.validateLegacySegment;f.validateLegacySegment=input=>{calls.push({ids:input.model.materialProductionRecipeRevisions.map(r=>r.id),ancestors:input.verifiedAncestors.map(a=>a.definitionId)});return original(input);};
 const p=run(f);assert.equal(p.revisions.length,3);assert.equal(calls.length,2);assert.deepEqual(calls.map(c=>c.ids.length),[1,1]);assert.deepEqual(calls[0].ancestors,['DEF-001']);assert.deepEqual(calls[1].ancestors,['DEF-001','DEF-002','DEF-003']);assert.equal(p.anchors[0].plan.id,f.plan.id);assert.equal(f.model.expectedOutputs.at(-1).plannedVersionLabel,'V004');
});

// Defensive historical-source binding, not a claim that cross-instance restore
// is supported. Standard restore keeps instanceId and changes runtimeEpoch.
test('before domain copy binds the original semantic source instance, independently of the new authoring instance',()=>{
 const f=fixture({historicalInstance:true});assert.equal(run(f).revisions.length,2);
 f.documents.find(d=>d.revisionId==='source-before').metadata.instanceId='instance-neutral';rejects(f);
});
