import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),site=path.resolve(here,'..'),require=createRequire(path.join(site,'package.json')),ts=require('typescript');
const helperSource=fs.readFileSync(path.join(site,'app/material-daily-versions.ts'),'utf8');
const compiled=ts.transpileModule(helperSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS},reportDiagnostics:true});assert.deepEqual(compiled.diagnostics,[]);
const module={exports:{}};new Function('module','exports',compiled.outputText)(module,module.exports);
const {isDeletedMaterialVersion,exactMaterialVersion,dailyMaterialVersionRefs,pendingMaterialExpectedOutputs,resolveExactMaterialSelection}=module.exports;
function fixture(){const family={id:'family',currentVersionId:'family@V001',versionRefs:['family@V001','family@AUDIT-006','family@V002']};return{family,model:{assetVersions:[{id:'family@V001',familyId:'family',outputState:'PRESENT',lifecycleState:'RELEASED',historyRole:'CURRENT',path:'one.png',sha256:'1'.repeat(64)},{id:'family@AUDIT-006',familyId:'family',outputState:'DELETED',lifecycleState:'DELETED_AUDIT',historyRole:'DELETED_AUDIT',path:null,sha256:null},{id:'family@V002',familyId:'family',outputState:'PRESENT',lifecycleState:'REVIEW_PENDING',historyRole:'CURRENT',path:'two.png',sha256:'2'.repeat(64)}]}};}
test('only precise deleted version disappears from daily refs, current and pending versions remain ordered',()=>{const f=fixture(),before=structuredClone(f);assert.deepEqual(dailyMaterialVersionRefs(f.model,f.family),['family@V001','family@V002']);assert.deepEqual(f,before);assert.equal(f.family.currentVersionId,'family@V001');});
for(const key of ['outputState','historyRole','lifecycleState'])test('explicit deletion marker alone is sufficient: '+key,()=>{const f=fixture(),v=f.model.assetVersions[1];for(const field of ['outputState','historyRole','lifecycleState'])v[field]='UNKNOWN';v[key]=key==='outputState'?'DELETED':'DELETED_AUDIT';assert.equal(isDeletedMaterialVersion(v),true);assert.equal(dailyMaterialVersionRefs(f.model,f.family).includes(v.id),false);});
for(const state of ['UNKNOWN','EVIDENCE_ONLY','REVIEW_PENDING','REVISION_REQUIRED','DO_NOT_USE','SUPERSEDED'])test(state+' is not inferred to mean physically deleted',()=>{const f=fixture(),v=f.model.assetVersions[1];v.outputState=state;v.lifecycleState=state;v.historyRole=state;assert.equal(isDeletedMaterialVersion(v),false);assert(dailyMaterialVersionRefs(f.model,f.family).includes(v.id));});
test('unloaded exact ID placeholder is not silently classified deleted',()=>{const f=fixture();f.model.assetVersions.splice(1,1);assert.equal(exactMaterialVersion(f.model,f.family,'family@AUDIT-006'),null);assert(dailyMaterialVersionRefs(f.model,f.family).includes('family@AUDIT-006'));});
test('duplicate or foreign-family identity fails exact resolution, not name-based removal',()=>{const f=fixture(),v=f.model.assetVersions[1];f.model.assetVersions.push({...v,familyId:'other'});assert.equal(exactMaterialVersion(f.model,f.family,v.id),null);assert(dailyMaterialVersionRefs(f.model,f.family).includes(v.id));f.model.assetVersions.splice(1,1);assert.equal(exactMaterialVersion(f.model,f.family,v.id),null);});
test('outside family versionRefs cannot become a selectable version',()=>{const f=fixture();f.family.versionRefs=f.family.versionRefs.filter(id=>!id.includes('AUDIT'));assert.equal(exactMaterialVersion(f.model,f.family,'family@AUDIT-006'),null);});
test('unknown family produces no fabricated default or version IDs',()=>{assert.deepEqual(dailyMaterialVersionRefs(fixture().model,null),[]);});
const latestSource=fs.readFileSync(path.join(site,'app/material-version-history.tsx'),'utf8');
const tree=ts.createSourceFile('material-version-history.tsx',latestSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),functions=tree.statements.filter(node=>ts.isFunctionDeclaration(node)&&['versionOrdinal','latestMaterialVersion'].includes(node.name?.text)).map(node=>node.getText(tree).replace(/^export /,'')).join('\n');assert.equal(tree.statements.filter(node=>ts.isFunctionDeclaration(node)&&['versionOrdinal','latestMaterialVersion'].includes(node.name?.text)).length,2);
const actualLatest=new Function('dailyMaterialVersionRefs','exactMaterialVersion',ts.transpileModule(functions,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText+'\nreturn latestMaterialVersion;')(dailyMaterialVersionRefs,exactMaterialVersion);
test('actual latest function will not choose a deleted numerically newer version or mutate history',()=>{const f=fixture();f.model.assetVersions[1].id='family@V999';f.family.versionRefs[1]='family@V999';const before=structuredClone(f);assert.equal(actualLatest(f.model,f.family).id,'family@V002');assert.deepEqual(f,before);});
test('actual latest function returns null when every exact version has deletion marker',()=>{const f=fixture();for(const v of f.model.assetVersions)v.outputState='DELETED';assert.equal(actualLatest(f.model,f.family),null);});

function realizedFixture(){const f=fixture();f.family.expectedOutputRefs=['expected-realized','expected-pending'];f.model.expectedOutputs=[{id:'expected-realized',familyId:f.family.id,expectationState:'REALIZED',realizedVersionId:'family@V001',realizedVersionSha256:'1'.repeat(64)},{id:'expected-pending',familyId:f.family.id,expectationState:'PLANNED',realizedVersionId:null}];return f;}
test('realized EO is removed only from pending choices and its exact deep link keeps original version and SHA, not latest',()=>{const f=realizedFixture(),before=structuredClone(f);assert.deepEqual(pendingMaterialExpectedOutputs(f.model,f.family).map(x=>x.id),['expected-pending']);assert.deepEqual(resolveExactMaterialSelection(f.model,f.family,'expected-realized'),{version:f.model.assetVersions[0],expected:null});assert.equal(resolveExactMaterialSelection(f.model,f.family,'expected-pending').expected.id,'expected-pending');assert.deepEqual(f,before);});
const brokenExpectedCases={unknown:()=>{},'wrong expected family':f=>{f.model.expectedOutputs[0].familyId='other';},'duplicate expected ID':f=>{f.model.expectedOutputs.push({...f.model.expectedOutputs[0]});},'outside expected refs':f=>{f.family.expectedOutputRefs=[];},'missing realized version':f=>{f.model.expectedOutputs[0].realizedVersionId='unknown';},'outside version refs':f=>{f.family.versionRefs=f.family.versionRefs.filter(x=>x!=='family@V001');},'wrong version family':f=>{f.model.assetVersions[0].familyId='other';},'duplicate realized version':f=>{f.model.assetVersions.push({...f.model.assetVersions[0]});},'missing realized SHA':f=>{delete f.model.expectedOutputs[0].realizedVersionSha256;},'mismatched realized SHA':f=>{f.model.expectedOutputs[0].realizedVersionSha256='3'.repeat(64);},'missing actual path':f=>{f.model.assetVersions[0].path=null;},'deleted realized file':f=>{f.model.assetVersions[0].outputState='DELETED';},'contradictory planned state':f=>{f.model.expectedOutputs[0].expectationState='PLANNED';}};
for(const [label,mutate] of Object.entries(brokenExpectedCases))test('explicit EO fails closed without latest fallback: '+label,()=>{const f=realizedFixture();mutate(f);assert.deepEqual(resolveExactMaterialSelection(f.model,f.family,label==='unknown'?'unknown':'expected-realized'),{version:null,expected:null});assert.equal(f.family.currentVersionId,'family@V001');});
