import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
async function fixture(page:Page,{readOnly=false,hosted=false,unknown=false,conflict=false,invalidReread=false,emptyReceipt=false,jobStatus='QUEUED'}={}){
 const writes:Array<Record<string,unknown>>=[],errors:string[]=[],unexpected:string[]=[];let draft:{revisionId:string;content:unknown}|null=null,reads=0;
 const input={familyId:'MASTER',versionId:'MASTER@V1',sha256:'a'.repeat(64),label:'人物干净母版',kind:'IMAGE'};
 const entry=`import React from'react';import{createRoot}from'react-dom/client';import{RuntimeModeProvider}from'./app/runtime-mode';import{MaterialProductionSetupEditor}from'./app/material-production-setup-editor';createRoot(document.getElementById('root')).render(<RuntimeModeProvider hostedReadOnly={${hosted}}><MaterialProductionSetupEditor requirementId="REQ-NEW"/></RuntimeModeProvider>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'material-setup-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-material-setup',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());
  if(url.pathname==='/api/v8/operations/snapshot'&&request.method()==='GET')return route.fulfill({json:{mutationEtag:'"material-etag"'}});
  if(url.pathname==='/api/instance/material-production'){
   if(request.method()==='GET'){expect(url.searchParams.get('requirementId')).toBe('REQ-NEW');reads++;return route.fulfill({json:invalidReread&&reads>1?{releaseId:'RELEASE',readOnly,availableInputs:[],blockers:[],jobs:[]}:{releaseId:'RELEASE',basisHash:'b'.repeat(64),currentRegistration:null,readOnly,draftHeadRevisionId:draft?.revisionId||null,draft,defaults:{model:'',prompt:'',negativePrompt:'',parameters:{},inputBindings:[]},availableInputs:[input],blockers:[],jobs:[]}});}
   const body=request.postDataJSON();writes.push(body);expect(request.headers()['if-match']).toBe('"material-etag"');expect(request.headers()['idempotency-key']).toMatch(/^material-setup:/);
   if(emptyReceipt)return route.fulfill({json:{revisionId:''}});if(unknown)return route.fulfill({status:503,json:{error:'建档提交后连接中断'}});if(conflict)return route.fulfill({status:409,json:{error:'素材需求版本已改变'}});
   if(body.action==='save'){draft={revisionId:'DRAFT-1',content:body.content};return route.fulfill({json:{revisionId:'DRAFT-1'}});}
   if(body.action==='preview')return route.fulfill({json:{previewHash:'c'.repeat(64),plan:{requirementId:'REQ-NEW',basisHash:'b'.repeat(64),inputBindings:(draft?.content as {inputBindings:unknown}).inputBindings},modelCalls:0}});
   if(body.action==='publish')return route.fulfill({json:{jobId:'JOB-1',status:jobStatus,modelCalls:0}});
  }unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,json:{error:'unexpected'}});
 });
 await page.route('**/__material-setup',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>${css}</style></head><body><div id="root"></div><script>${js}</script></body></html>`}));await page.goto('/__material-setup');return{writes,errors,unexpected,input};
}
async function author(page:Page){await page.getByRole('button',{name:'建立素材制作资料',exact:true}).click();await page.getByRole('textbox',{name:'模型ID',exact:true}).fill('GPT-IMG-2');await page.getByRole('textbox',{name:'完整主提示词',exact:true}).fill('按母版身份制作雨夜状态，湿发与衣料清晰，保持面部特征。');await page.getByRole('textbox',{name:'完整负面提示词',exact:true}).fill('避免现代物品、文字和身份漂移。');await page.getByRole('checkbox',{name:/人物干净母版/}).check();}
test('new requirement setup binds adopted exact inputs and publishes its preview without generating media',async({page})=>{const f=await fixture(page);await author(page);await page.getByRole('button',{name:'保存制作资料草稿'}).click();await expect(page.getByRole('button',{name:'预览素材制作资料'})).toBeEnabled();expect(f.writes[0]).toMatchObject({action:'save',requirementId:'REQ-NEW',expectedReleaseId:'RELEASE',expectedDraftRevisionId:null,content:{model:'GPT-IMG-2',inputBindings:[{familyId:f.input.familyId,versionId:f.input.versionId,sha256:f.input.sha256}]}});expect(Object.keys(f.writes[0].content as object).sort()).toEqual(['inputBindings','model','negativePrompt','parameters','prompt']);await page.getByRole('button',{name:'预览素材制作资料'}).click();await expect(page.getByRole('heading',{name:'待登记制作资料'})).toBeVisible();await page.getByRole('button',{name:'确认建立制作资料'}).click();await expect(page.getByRole('status')).toContainText('任务已排队');expect(f.writes[2]).toMatchObject({action:'publish',draftRevisionId:'DRAFT-1',previewHash:'c'.repeat(64)});expect(f.writes.map(w=>w.action)).toEqual(['save','preview','publish']);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);});
test('CAS conflict keeps edits and does not retry',async({page})=>{const f=await fixture(page,{conflict:true});await author(page);await page.getByRole('button',{name:'保存制作资料草稿'}).click();await expect(page.getByRole('status')).toContainText('素材需求版本已改变');await expect(page.getByRole('textbox',{name:'完整主提示词',exact:true})).toHaveValue(/按母版身份/);expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
for(const invalidReread of [false,true])test(`unknown result blocks resubmission and ${invalidReread?'invalid reread stays blocked':'valid reread keeps draft'}`,async({page})=>{const f=await fixture(page,{unknown:true,invalidReread});await author(page);await page.getByRole('button',{name:'保存制作资料草稿'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('button',{name:'保存制作资料草稿'})).toBeDisabled();await page.getByRole('button',{name:'重读制作资料与任务'}).click();await expect(page.getByRole('status')).toContainText(invalidReread?'制作资料回执不完整':'本次编辑仍保留');await expect(page.getByRole('textbox',{name:'完整主提示词',exact:true})).toHaveValue(/按母版身份/);if(invalidReread)await expect(page.getByRole('button',{name:'保存制作资料草稿'})).toBeDisabled();else await expect(page.getByRole('button',{name:'保存制作资料草稿'})).toBeEnabled();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
test('read-only instance prevents editing and hosted mirror has no setup action',async({page})=>{let f=await fixture(page,{readOnly:true});await page.getByRole('button',{name:'建立素材制作资料',exact:true}).click();await expect(page.getByRole('textbox',{name:'模型ID',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'保存制作资料草稿'})).toBeDisabled();expect(f.writes).toEqual([]);await page.unrouteAll({behavior:'wait'});f=await fixture(page,{hosted:true});await expect(page.getByRole('button',{name:'建立素材制作资料',exact:true})).toHaveCount(0);expect(f.unexpected).toEqual([]);expect(f.writes).toEqual([]);});

test('empty revision receipt cannot release the unknown submission guard',async({page})=>{const f=await fixture(page,{emptyReceipt:true});await author(page);await page.getByRole('button',{name:'保存制作资料草稿'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('button',{name:'保存制作资料草稿'})).toBeDisabled();expect(f.writes).toHaveLength(1);});
test('a failed job status is not reported as queued',async({page})=>{const f=await fixture(page,{jobStatus:'FAILED'});await author(page);await page.getByRole('button',{name:'保存制作资料草稿'}).click();await page.getByRole('button',{name:'预览素材制作资料'}).click();await page.getByRole('button',{name:'确认建立制作资料'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('button',{name:'确认建立制作资料'})).toBeDisabled();expect(f.writes).toHaveLength(3);});
