import test from 'node:test';
import assert from 'node:assert/strict';
import {domainHash} from '../host/instance-runtime/domain-model.mjs';
import {projectDomainGraph} from '../host/instance-runtime/domain-projection.mjs';
import {executionDefinitionHash} from '../host/instance-runtime/execution-definition-hash.mjs';
import {inspectMaterialRequirementReplacementExecution as inspect,assertMaterialRequirementReplacementExecution as guard,REPLACEMENT_EXECUTION_JOB_NAMESPACES} from '../host/instance-runtime/material-requirement-replacement-execution.mjs';
import {replacementFixture} from './fixtures/material-requirement-replacement.mjs';

function fixture(){
 const f=replacementFixture(),snapshot=projectDomainGraph({productionModel:{assetFamilies:[],materialRequirements:[]}},f.before,{revisionId:'graph-r1',sha256:domainHash(f.before)}),m=snapshot.productionModel;
 const requirement=m.materialRequirements.find(r=>r.id==='old-broad');
 const work={id:'material-work',requirementRef:requirement.id,requirementHash:requirement.requirementHash,outputAssetRef:'original-family',executionDefinitionRef:'definition-1',scopeRole:'CURRENT',activeInCurrentProduction:true};
 m.materialWorkItems=[work];m.assetFamilies=[{id:'original-family',ownerRef:work.id}];m.workItems=[];m.expectedOutputs=[];m.shotPlanSetRevisions=[];m.shotProductionPlans=[];requirement.materialWorkItemRef=work.id;
 const view={snapshot,recipes:{executionDefinitions:[]},eventsByKind:{'execution-request':[],run:[],'asset-version':[]}},aux=new Map(),media=new Map(),aliases=new Map();let sequence=0;
 function definition(id,w=work){const d={id,workItemRef:w.id,executorKind:'MODEL_CALL',upload:{items:[]},output:{assetFamilyRef:w.outputAssetRef,expectedOutputRef:'eo:'+id,path:'media/_review_pending/'+w.outputAssetRef+'/'+id+'.png'}};d.definitionHash=executionDefinitionHash(d);view.recipes.executionDefinitions.push(d);m.expectedOutputs.push({id:d.output.expectedOutputRef,familyId:d.output.assetFamilyRef,targetPath:d.output.path});return d;}
 const d=definition('definition-1');
 function event(kind,body){const e={eventId:'event-'+(++sequence),eventSequence:sequence,snapshotHash:'old-snapshot',...body};view.eventsByKind[kind].push(e);return e;}
 function request(def=d,fields={}){return event('execution-request',{executionRequestId:'request:'+def.id,workItemId:def.workItemRef,familyId:def.output.assetFamilyRef,executionDefinitionId:def.id,callPackageHash:def.definitionHash,inputBindings:[],inputBindingsHash:domainHash([]),requestState:'CLAIMED',maxOutputs:1,...fields});}
 function run(q,status,fields={}){return event('run',{runId:'run:'+q.executionRequestId,executionRequestId:q.executionRequestId,executionDefinitionId:q.executionDefinitionId,callPackageHash:q.callPackageHash,inputBindingsHash:q.inputBindingsHash,runState:status,...fields});}
 function candidate(q,r,def=d){const c=event('asset-version',{runId:r.runId,executionRequestId:q.executionRequestId,executionDefinitionId:def.id,callPackageHash:def.definitionHash,familyId:def.output.assetFamilyRef,expectedOutputId:def.output.expectedOutputRef,versionId:def.output.assetFamilyRef+'@'+def.id,path:def.output.path,sha256:'a'.repeat(64)});const row={mediaId:c.familyId,versionId:c.versionId,sha256:c.sha256,relativePath:'media/blobs/a.png',metadata:{authorityDomain:'FORMAL',registrationEventId:c.eventId}};media.set(c.familyId+'/'+c.versionId,row);aliases.set(c.path,{...row});return c;}
 function job(namespace,content){aux.set(namespace,[...(aux.get(namespace)||[]),{key:content.jobId||'job',revisionId:'aux-r1',sha256:domainHash(content),bytes:Buffer.from(JSON.stringify(content))}]);}
 const tx={readView:async()=>view,listEvents:async()=>Object.entries(view.eventsByKind).flatMap(([eventKind,rows])=>rows.map(e=>({...e,eventKind}))),getMetadata:async()=>({instanceId:'fixture-instance',runtimeEpoch:3}),getMedia:async(f,v)=>media.get(f+'/'+v),resolveMedia:async(p,{versionId,sha256})=>{const row=aliases.get(p);return row?.versionId===versionId&&row.sha256===sha256?row:null;},listAux:async n=>aux.get(n)||[]};
 return {...f,m,work,d,view,tx,definition,event,request,run,candidate,job,media,aliases,input:{nextGraph:f.after}};
}
const has=(result,code)=>result.reasons.some(r=>r.startsWith(code));

for(const state of ['AUTHORIZED','CLAIMED'])test('unconsumed '+state+' blocks only exact affected work',async()=>{const f=fixture();f.request(f.d,{requestState:state});const result=await inspect(f.tx,f.input);assert.ok(has(result,'REPLACEMENT_AUTHORIZATION_UNCONSUMED'));assert.deepEqual(result.currentWorkIds,[f.work.id]);await assert.rejects(guard(f.tx,f.input),e=>e.code==='DOMAIN_CONFLICT'&&e.impact.reasons.length>0);});
for(const state of ['PLANNED','SUBMITTED','RUNNING','RESULT_UNKNOWN','SUCCEEDED'])test('unresolved '+state+' fails closed across release boundaries',async()=>{const f=fixture(),q=f.request();f.run(q,state,{snapshotHash:'different-historical-release',runtimeEpoch:1});assert.ok(has(await inspect(f.tx,f.input),'REPLACEMENT_RUN_PENDING'));});
for(const state of ['FAILED','CANCELLED'])test('confirmed '+state+' with no output allows fresh replacement',async()=>{const f=fixture(),q=f.request();f.run(q,state);assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);});
test('explicitly cancelled unused authorization is terminal',async()=>{const f=fixture();f.request(f.d,{requestState:'CANCELLED'});assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);});
test('registered exact success closes an old claim without changing source adoption or events',async()=>{const f=fixture(),q=f.request(),r=f.run(q,'SUCCEEDED');f.candidate(q,r);const before=JSON.stringify(f.view);assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);assert.equal(JSON.stringify(f.view),before);});
for(const [name,mutate]of[
 ['missing registry',f=>f.media.clear()],['wrong physical alias',f=>{for(const v of f.aliases.values())v.relativePath='other.png';}],['wrong registration proof',f=>{for(const v of f.media.values())v.metadata.registrationEventId='other';}],['wrong output',f=>f.view.eventsByKind['asset-version'][0].expectedOutputId='other'],['wrong candidate SHA',f=>f.view.eventsByKind['asset-version'][0].sha256='b'.repeat(64)],['failed run with output',f=>f.view.eventsByKind.run[0].runState='FAILED']
])test('candidate '+name+' cannot prove completion',async()=>{const f=fixture(),q=f.request(),r=f.run(q,'SUCCEEDED');f.candidate(q,r);mutate(f);assert.ok((await inspect(f.tx,f.input)).reasons.length);});
test('old UNKNOWN is retained when a newer unrelated request succeeded and registered',async()=>{const f=fixture(),old=f.definition('definition-old');const q=f.request(old);f.run(q,'RESULT_UNKNOWN');const now=f.request(),r=f.run(now,'SUCCEEDED');f.candidate(now,r);const result=await inspect(f.tx,f.input);assert.equal(result.requestHeads.length,2);assert.ok(has(result,'REPLACEMENT_RUN_PENDING'));});
test('latest per-request and per-run sequence permits real terminal correction; duplicate sequence is ambiguous',async()=>{const f=fixture(),q=f.request(),r=f.run(q,'RESULT_UNKNOWN');f.run(q,'FAILED',{runId:r.runId});assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);f.view.eventsByKind.run[1].eventSequence=r.eventSequence;assert.ok(has(await inspect(f.tx,f.input),'REPLACEMENT_EVENT_HEAD_UNKNOWN'));});
test('unrelated work, foreign project run, and original adopted image as mother do not block',async()=>{const f=fixture();const w={id:'other-work',requirementRef:'other-requirement',requirementHash:'c'.repeat(64),outputAssetRef:'other-family',inputAssetRefs:['original-family'],scopeRole:'CURRENT'};f.m.materialWorkItems.push(w);f.m.materialRequirements.push({id:'other-requirement',requirementHash:w.requirementHash});f.m.assetFamilies.push({id:'other-family',ownerRef:w.id});const d=f.definition('other-def',w),q=f.request(d,{instanceId:'other-project'});f.run(q,'RESULT_UNKNOWN');f.job('material-usage-jobs',{jobId:'source-usage',requirementId:'other-leaf',source:{familyId:'original-family'},status:'QUEUED'});assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);});
for(const [label,mutate]of[
 ['definition hash',f=>f.d.definitionHash='0'.repeat(64)],['work hash',f=>f.work.requirementHash='0'.repeat(64)],['family owner',f=>f.m.assetFamilies[0].ownerRef='wrong'],['expected output absent',f=>f.m.expectedOutputs=[]],['expected output path changed',f=>f.m.expectedOutputs[0].targetPath='other'],['request input',f=>f.view.eventsByKind['execution-request'][0].inputBindings=[{}]],['request instance',f=>f.view.eventsByKind['execution-request'][0].authorizationRuntime={instanceId:'foreign'}],['conflicting work identity',f=>f.m.workItems.push({...f.work,outputAssetRef:'wrong'})]
])test('affected '+label+' ambiguity fails closed',async()=>{const f=fixture();f.request(f.d,{requestState:'CANCELLED'});mutate(f);assert.ok((await inspect(f.tx,f.input)).reasons.length);});

function addShots(f,{semantic=false}={}){
 const req=f.m.materialRequirements[0],content={sceneId:'scene-a',shots:[{shotId:'shot-a',sceneId:'scene-a',materialRequirementRefs:[req.id]},{shotId:'shot-b',sceneId:'scene-a',materialRequirementRefs:['other']} ]};
 const frozen=semantic?{schemaVersion:'3.0',semanticPolicy:'SHOT_DESIGN_REQUIREMENT_SEMANTICS_V1',bindings:[{requirementId:req.id,demand:f.before.requirements[0],requirement:{id:req.id},conditions:{representation:{value:Object.fromEntries(Object.entries(f.before.representations[0]).filter(([k])=>k!=='assetFamilyIds'))}}}]}:{schemaVersion:'2.0',bindings:[{requirementId:req.id,requirementHash:req.requirementHash}]};
 f.m.shotPlanSetRevisions.push({id:'design',scopeRole:'CURRENT',scopeId:'scene-a',content,contentHash:domainHash(content),materialRequirementSet:frozen});
 const pc={shotPlanRevisionId:'design',shots:[{shotId:'shot-a',inputs:[]}]};const works=[{id:'shot-work',shotId:'shot-a'},{id:'unaffected-shot',shotId:'shot-b'},{id:'animatic-work',shotId:null}].map(w=>({...w,sceneId:'scene-a',outputAssetRef:'family:'+w.id,shotProductionPlanId:'earlier-reused-plan',scopeRole:'CURRENT'}));f.m.workItems.push(...works);f.m.shotProductionPlans.push({id:'production',sceneId:'scene-a',scopeRole:'CURRENT',content:pc,contentHash:domainHash(pc),workItemIds:works.map(w=>w.id)});return works;
}
for(const semantic of [false,true])test('current shot '+(semantic?'V3 semantic':'V2 exact hash')+' basis scopes local and scene work, keeping reuse membership',async()=>{const f=fixture();addShots(f,{semantic});const downstream={id:'downstream',sceneId:'scene-a',outputAssetRef:'downstream-family',inputAssetRefs:['family:shot-work'],scopeRole:'CURRENT'};f.m.workItems.push(downstream);const result=await guard(f.tx,f.input);assert.deepEqual(result.currentPlanIds,['design']);assert.deepEqual(result.currentProductionPlanIds,['production']);assert.deepEqual(result.currentWorkIds,['animatic-work','downstream','material-work','shot-work']);});
test('unknown current shot requirement basis blocks instead of skipping affected scene',async()=>{const f=fixture();addShots(f);f.m.shotPlanSetRevisions[0].materialRequirementSet.bindings[0].requirementHash='0'.repeat(64);assert.ok(has(await inspect(f.tx,f.input),'REPLACEMENT_SHOT_PLAN_REQUIREMENT_BASIS_UNKNOWN'));});
for(const namespace of REPLACEMENT_EXECUTION_JOB_NAMESPACES)test(namespace+' pending exact scene/requirement is inspected in the same transaction',async()=>{const f=fixture();addShots(f);f.job(namespace,{jobId:'pending',sceneId:'scene-a',status:'RESULT_UNKNOWN',runtimeEpoch:1,instanceId:'fixture-instance'});f.job(namespace,{jobId:'unrelated',sceneId:'other-scene',status:'RUNNING'});const result=await inspect(f.tx,f.input);assert.deepEqual(result.hostJobs.map(j=>j.jobId),['pending']);assert.ok(has(result,'REPLACEMENT_HOST_JOB_PENDING'));});
for(const status of ['SUCCEEDED','FAILED','CANCELLED','RECONCILED_UNREGISTERED'])test('terminal host '+status+' does not block',async()=>{const f=fixture();f.job('material-production-jobs',{jobId:'done',requirementId:'old-broad',status});assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);});
test('host task without resolvable ownership is explicit unknown, not silently ignored',async()=>{const f=fixture();f.job('shot-production-jobs',{jobId:'unknown',status:'QUEUED'});assert.ok(has(await inspect(f.tx,f.input),'REPLACEMENT_HOST_JOB_SCOPE_UNKNOWN'));});
test('already effective replacement is no new execution fence and has no event or AUX dependency',async()=>{const f=fixture();const tx={readView:async()=>({snapshot:{productionModel:{domainGraph:f.after}}})};assert.deepEqual((await inspect(tx,{nextGraph:f.after})).reasons,[]);});

test('a current plan consuming the old root through an explicit ALL component is affected',async()=>{
 const f=fixture();addShots(f);f.m.materialRequirements.push({id:'existing-aggregate',composition:{schemaVersion:'1.0',mode:'ALL',requiredComponents:[{id:'old',requirementId:'old-broad'}]}});
 const plan=f.m.shotPlanSetRevisions[0];plan.content.shots[0].materialRequirementRefs=['existing-aggregate'];plan.contentHash=domainHash(plan.content);plan.materialRequirementSet.bindings=[{requirementId:'existing-aggregate',requiredComponents:[{binding:plan.materialRequirementSet.bindings[0]}]}];
 const result=await guard(f.tx,f.input);assert.ok(result.currentWorkIds.includes('shot-work'));assert.deepEqual(result.currentPlanIds,['design']);
});

test('nonempty canonical reference bindings must match the frozen definition exactly',async()=>{
 const f=fixture(),input={order:1,path:'media/reference.png',assetFamilyRef:'reference-family',assetVersionRef:'reference-family@V001',sha256:'b'.repeat(64)};f.d.upload.items=[input];f.d.definitionHash=executionDefinitionHash(f.d);
 const q=f.request(f.d,{inputBindings:[input],inputBindingsHash:domainHash([input])});f.run(q,'FAILED');assert.deepEqual((await guard(f.tx,f.input)).reasons,[]);
 q.inputBindings=[{...input,assetVersionRef:'wrong'}];assert.ok(has(await inspect(f.tx,f.input),'REPLACEMENT_REQUEST_INPUTS_UNKNOWN'));
});

test('retired work on the same exact design/root keeps old UNKNOWN in the execution fence',async()=>{
 const f=fixture(),oldWorks=addShots(f),w=oldWorks.find(w=>w.id==='shot-work'),d=f.definition('old-shot-definition',w),q=f.request(d);f.run(q,'RESULT_UNKNOWN');
 const oldPlan=f.m.shotProductionPlans[0];oldPlan.scopeRole='HISTORICAL';for(const w of oldWorks){w.scopeRole='HISTORICAL';w.activeInCurrentProduction=false;}
 const next=oldWorks.map(w=>({...w,id:'new:'+w.id,outputAssetRef:'new:'+w.outputAssetRef,shotProductionPlanId:'new-production',scopeRole:'CURRENT',activeInCurrentProduction:true}));f.m.workItems.push(...next);f.m.shotProductionPlans.push({...oldPlan,id:'new-production',scopeRole:'CURRENT',workItemIds:next.map(w=>w.id)});
 const result=await inspect(f.tx,f.input);assert.ok(has(result,'REPLACEMENT_RUN_PENDING'));assert.equal(result.runHeads.length,1);assert.ok(result.historicalWorkIds.includes(w.id));assert.ok(!result.currentWorkIds.includes(w.id));assert.ok(result.currentWorkIds.includes('new:'+w.id));
});
