import test from 'node:test';
import assert from 'node:assert/strict';
import {validUsageSelection,validUsageWorkspace,validUsageReceipt,reconcileUsagePending,validUsagePending} from '../app/material-usage-client.mjs';
import {materialUsageClientFixture} from './material-usage-client-fixture.mjs';
const clone=structuredClone;
function fixture(){const f=materialUsageClientFixture();f.workspace.draft=f.draft;f.workspace.draftHeadRevisionId=f.draft.revisionId;f.pending={action:'save',target:f.target,requestId:'request:one',basisHash:f.workspace.basisHash,releaseId:f.workspace.releaseId,oldDraftRevisionId:null,content:clone(f.body.content)};return f;}
test('usage selection and exact workspace are distinct supported contracts',()=>{const f=fixture();assert.equal(validUsageSelection(f.selection,f.target.requirementId),f.selection);assert.equal(validUsageWorkspace(f.workspace,f.target),f.workspace);assert.throws(()=>validUsageWorkspace(f.selection,f.target));assert.throws(()=>validUsageSelection({...f.selection,protocol:'legacy'},f.target.requirementId),/尚未支持/);});
test('source selector rejects duplicate family and arbitrary image URL',()=>{const f=fixture();f.selection.eligibleSources.push(clone(f.selection.eligibleSources[0]));assert.throws(()=>validUsageSelection(f.selection,f.target.requirementId));f.selection.eligibleSources.pop();f.selection.eligibleSources[0].mediaUrl='https://untrusted.example/redirect';assert.throws(()=>validUsageSelection(f.selection,f.target.requirementId));});
test('mismatched version or changed requirement cannot become the selected workspace',()=>{const f=fixture();for(const key of ['requirementId','versionId','sha256']){const changed=clone(f.workspace);changed[key]='different';assert.throws(()=>validUsageWorkspace(changed,f.target));}const changed=clone(f.workspace);changed.requirement.reviewSpec.hash='f'.repeat(64);assert.throws(()=>validUsageWorkspace(changed,f.target));});
test('preview receipt must show saved content and the exact source and target',()=>{const f=fixture();assert.equal(validUsageReceipt(f.receipt,'preview',f.workspace),f.receipt);for(const change of [r=>r.usage.content.decision.action='DO_NOT_USE',r=>r.usage.basis.source.sha256='d'.repeat(64),r=>r.usage.basis.requirement.requirementId='other']){const r=clone(f.receipt);change(r);assert.throws(()=>validUsageReceipt(r,'preview',f.workspace));}});
test('response cannot claim model invocation or original adoption and malformed receipt is not success',()=>{const f=fixture();for(const patch of [{modelCalls:1},{formalAdoptionPerformed:true},{formalUsageReviewPerformed:true},{revisionId:''}])assert.throws(()=>validUsageReceipt({modelCalls:0,formalAdoptionPerformed:false,formalUsageReviewPerformed:false,revisionId:'draft:new',...patch},'save',f.workspace));assert.throws(()=>validUsageReceipt({modelCalls:0,formalAdoptionPerformed:false,formalUsageReviewPerformed:false,jobId:'job:one',status:'FAILED'},'publish',f.workspace));});
test('unknown save recovers only a newer exact-content draft on the same frozen basis',()=>{const f=fixture();assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,true);for(const change of [w=>{w.draft=null;w.draftHeadRevisionId=null;},w=>w.draft.content.purposeNote+=' changed',w=>{w.releaseId='release:new';w.draft.baseReleaseId=w.releaseId;},w=>{w.basisHash='d'.repeat(64);w.draft.basisHash=w.basisHash;}]){const w=clone(f.workspace);change(w);assert.equal(reconcileUsagePending(f.pending,w).confirmed,false);}f.pending.oldDraftRevisionId=f.draft.revisionId;assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,false);});
test('unknown publish ignores other jobs and does not clear solely after a valid GET',()=>{const f=fixture();f.pending.action='publish';assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,false);f.workspace.jobs=[{jobId:'job:one',requestId:'different:request',status:'SUCCEEDED'}];assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,false);f.workspace.jobs[0].requestId=f.pending.requestId;assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,true);f.workspace.jobs.push({...f.workspace.jobs[0],jobId:'job:two'});assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,false);});
test('pending storage cannot lose the exact target or invent an action',()=>{const f=fixture();assert.equal(validUsagePending(f.pending,f.target.requirementId),f.pending);assert.throws(()=>validUsagePending({...f.pending,action:'preview'},f.target.requirementId));assert.throws(()=>validUsagePending(f.pending,'another:requirement'));});
test('a saved head moved to stale by another release proves save success without making it previewable',()=>{const f=fixture();f.workspace.staleDraft={...f.workspace.draft,reason:'unrelated release'};f.workspace.draft=null;f.workspace.releaseId='release:after';const result=reconcileUsagePending(f.pending,f.workspace);assert.equal(result.confirmed,true);assert.equal(result.stale,true);assert.equal(f.workspace.draft,null);f.workspace.draftHeadRevisionId='another:draft';assert.equal(reconcileUsagePending(f.pending,f.workspace).confirmed,false);});
