import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
import {materialUsageClientFixture} from './material-usage-client-fixture.mjs';
import type {MaterialUsageWorkspace} from '../host/instance-runtime/material-usage-service.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
type Options={hosted?:boolean;readOnly?:boolean;unsupported?:boolean;unknownSave?:boolean;unknownPublish?:boolean;commitUnknown?:boolean;invalidReceipt?:boolean;conflict?:boolean;badSource?:boolean};
async function fixture(page:Page,options:Options={}){
 const f=materialUsageClientFixture(),workspace=structuredClone(f.workspace) as unknown as MaterialUsageWorkspace,writes:Array<Record<string,unknown>>=[],errors:string[]=[],unexpected:string[]=[];let apiReads=0;
 const entry=`import React,{useState} from'react';import{createRoot}from'react-dom/client';import{RuntimeModeProvider}from'./app/runtime-mode';import{MaterialUsageEditor}from'./app/material-usage-editor';function Harness(){const [shown,setShown]=useState(true);return <RuntimeModeProvider hostedReadOnly={${!!options.hosted}}><button onClick={()=>setShown(!shown)}>切换素材卡</button>{shown&&<MaterialUsageEditor requirementId="REQ-EMPTY"/>}</RuntimeModeProvider>};createRoot(document.getElementById('root')).render(<Harness/>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'material-usage-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-material-usage',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());
  if(url.pathname==='/__material-usage')return route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>${css}</style></head><body><div id="root"></div><script>${js}</script></body></html>`});
  if(url.pathname==='/api/v8/media/m_fixture'&&request.method()==='GET')return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=','base64')});
  if(url.pathname==='/api/v8/operations/snapshot'&&request.method()==='GET')return route.fulfill({json:{mutationEtag:'"usage-etag"'}});
  if(url.pathname==='/api/instance/material-usage'){
   if(request.method()==='GET'){apiReads++;if(options.unsupported)return route.fulfill({status:404,json:{error:'not found'}});if(!url.searchParams.has('familyId'))return route.fulfill({json:{...f.selection,readOnly:!!options.readOnly}});return route.fulfill({json:{...workspace,readOnly:!!options.readOnly,...(options.badSource?{sourceVersion:{...workspace.sourceVersion,sha256:'0'.repeat(64)}}:{})}});}
   const body=request.postDataJSON();writes.push(body);expect(request.headers()['if-match']).toBe('"usage-etag"');expect(request.headers()['idempotency-key']).toMatch(/^material-usage:/);
   if(options.conflict)return route.fulfill({status:412,json:{error:'当前素材版本已变化'}});
   const flags={modelCalls:0,formalAdoptionPerformed:false,formalUsageReviewPerformed:false};
   if(body.action==='save'){
    if(!options.unknownSave||options.commitUnknown){workspace.draft={...f.draft,content:body.content};workspace.draftHeadRevisionId=f.draft.revisionId;}
    if(options.unknownSave)return route.fulfill({status:503,json:{error:'保存后连接中断'}});
    return route.fulfill({json:{...flags,revisionId:f.draft.revisionId}});
   }
   if(body.action==='preview')return route.fulfill({json:{...f.receipt,usage:{...f.body,content:workspace.draft!.content}}});
   if(body.action==='publish'){
    if(!options.unknownPublish||options.commitUnknown)workspace.jobs=[{jobId:'job:usage',requestId:request.headers()['idempotency-key'],status:'QUEUED'}];
    if(options.unknownPublish)return route.fulfill({status:503,json:{error:'登记后连接中断'}});
    return route.fulfill({json:{...flags,jobId:'job:usage',status:options.invalidReceipt?'FAILED':'QUEUED'}});
   }
  }
  unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,body:'unexpected request'});
 });await page.goto('http://127.0.0.1:4309/__material-usage');return {f,workspace,writes,errors,unexpected,reads:()=>apiReads};
}
async function open(page:Page){await page.getByRole('button',{name:'复用已通过图片',exact:true}).click();await page.getByRole('combobox',{name:'选择图片',exact:true}).selectOption('IMAGE-TEST');await expect(page.getByRole('textbox',{name:'这张图片如何满足当前需求'})).toBeVisible();}
async function author(page:Page){await open(page);await expect(page.getByRole('combobox',{name:'用途结论',exact:true})).toHaveValue('');for(const label of ['这张图片如何满足当前需求','原图观察记录','项目内部使用依据','审阅说明'])await page.getByRole('textbox',{name:label,exact:true}).fill(label+'：用于当前明确空态，并保持同一原图。');await page.getByRole('checkbox',{name:'已查看这个版本的原图'}).check();for(const group of ['用途','连续性']){const section=page.getByRole('group',{name:group,exact:true});await expect(section.getByRole('combobox',{name:'判断',exact:true})).toHaveValue('');await section.getByRole('combobox',{name:'判断',exact:true}).selectOption('PASS');await section.getByRole('textbox',{name:'判断依据'}).fill('已核对原图，满足这一项明确需求。');}await page.getByRole('combobox',{name:'用途结论',exact:true}).selectOption('APPROVE_AND_RELEASE');}
async function saveAndPreview(page:Page){await page.getByRole('button',{name:'保存用途审阅草稿'}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await page.getByRole('button',{name:'预览用途审阅',exact:true}).click();await expect(page.getByRole('heading',{name:'待登记用途审阅'})).toBeVisible();}
test('explicit original observation and per-criterion decisions publish a new usage only',async({page})=>{const f=await fixture(page);await author(page);await expect(page.getByRole('img',{name:'本次用途审阅的原图'})).toBeVisible();await saveAndPreview(page);await page.getByRole('button',{name:'确认登记用途审阅'}).click();await expect(page.getByRole('status')).toContainText('已排队登记');expect(f.writes.map(w=>w.action)).toEqual(['save','preview','publish']);expect(f.writes[0]).toMatchObject({...f.f.target,expectedReleaseId:f.f.workspace.releaseId,expectedBasisHash:f.f.workspace.basisHash,expectedDraftRevisionId:null,content:{observation:{originalViewed:true,versionId:f.f.target.versionId,sha256:f.f.target.sha256}}});expect(f.unexpected).toEqual([]);expect(f.errors).toEqual([]);});
test('unknown uncommitted save stays blocked after reread and browser reload',async({page})=>{const f=await fixture(page,{unknownSave:true});await author(page);await page.getByRole('button',{name:'保存用途审阅草稿'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');await page.getByRole('button',{name:'重读图片与用途审阅'}).click();await expect(page.getByRole('status')).toContainText('尚未找到');await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toBeDisabled();page.once('dialog',d=>d.accept());await page.reload();await page.getByRole('button',{name:'复用已通过图片',exact:true}).click();await expect(page.getByRole('status')).toContainText('上次提交结果待核查');await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toBeDisabled();await expect(page.getByRole('textbox',{name:'这张图片如何满足当前需求'})).toHaveValue(/当前明确空态/);expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
test('lost save receipt recovers only the exact committed draft',async({page})=>{const f=await fixture(page,{unknownSave:true,commitUnknown:true});await author(page);await page.getByRole('button',{name:'保存用途审阅草稿'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');await page.getByRole('button',{name:'重读图片与用途审阅'}).click();await expect(page.getByRole('status')).toContainText('已核回保存的同一份草稿');await expect(page.getByRole('button',{name:'预览用途审阅',exact:true})).toBeEnabled();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
for(const commitUnknown of [false,true])test(`unknown publish ${commitUnknown?'finds original request id':'cannot clear without original request id'}`,async({page})=>{const f=await fixture(page,{unknownPublish:true,commitUnknown});await author(page);await saveAndPreview(page);await page.getByRole('button',{name:'确认登记用途审阅'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');await page.getByRole('button',{name:'重读图片与用途审阅'}).click();await expect(page.getByRole('status')).toContainText(commitUnknown?'已核回原请求':'尚未找到');await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toBeDisabled();expect(f.writes).toHaveLength(3);expect(f.errors).toEqual([]);});
test('invalid publish receipt does not claim success',async({page})=>{const f=await fixture(page,{invalidReceipt:true});await author(page);await saveAndPreview(page);await page.getByRole('button',{name:'确认登记用途审阅'}).click();await expect(page.getByRole('status')).toContainText('回执不完整');await expect(page.getByRole('button',{name:'确认登记用途审阅'})).toBeDisabled();expect(f.writes).toHaveLength(3);});
test('CAS rejection keeps review content without automatic retry',async({page})=>{const f=await fixture(page,{conflict:true});await author(page);await page.getByRole('button',{name:'保存用途审阅草稿'}).click();await expect(page.getByRole('status')).toContainText('当前素材版本已变化');await expect(page.getByRole('textbox',{name:'这张图片如何满足当前需求'})).toHaveValue(/当前明确空态/);await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toBeEnabled();expect(f.writes).toHaveLength(1);});
test('read-only workspace disables review and hosted mode makes no private API request',async({page})=>{let f=await fixture(page,{readOnly:true});await page.getByRole('button',{name:'复用已通过图片',exact:true}).click();await expect(page.getByRole('combobox',{name:'选择图片'})).toBeDisabled();expect(f.writes).toEqual([]);await page.unrouteAll({behavior:'wait'});f=await fixture(page,{hosted:true});await expect(page.getByRole('button',{name:'复用已通过图片',exact:true})).toHaveCount(0);expect(f.reads()).toBe(0);expect(f.unexpected).toEqual([]);});
test('old server reports unsupported and never falls back to ASSET adoption',async({page})=>{const f=await fixture(page,{unsupported:true});await page.getByRole('button',{name:'复用已通过图片',exact:true}).click();await expect(page.getByRole('status')).toContainText('尚未支持');await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toHaveCount(0);expect(f.writes).toEqual([]);expect(f.unexpected).toEqual([]);});
test('different source SHA in workspace fails closed',async({page})=>{const f=await fixture(page,{badSource:true});await page.getByRole('button',{name:'复用已通过图片',exact:true}).click();await page.getByRole('combobox',{name:'选择图片',exact:true}).selectOption('IMAGE-TEST');await expect(page.getByRole('status')).toContainText('回执不完整');await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toHaveCount(0);expect(f.writes).toEqual([]);});
test('switching away and remounting restores an incomplete local draft without sending a save',async({page})=>{const f=await fixture(page);await open(page);await page.getByRole('textbox',{name:'这张图片如何满足当前需求'}).fill('尚未完成的独立用途观察');await page.getByRole('button',{name:'切换素材卡'}).click();await page.getByRole('button',{name:'切换素材卡'}).click();await page.getByRole('button',{name:'复用已通过图片',exact:true}).click();await expect(page.getByRole('status')).toContainText('已恢复本地未保存草稿');await expect(page.getByRole('textbox',{name:'这张图片如何满足当前需求'})).toHaveValue('尚未完成的独立用途观察');await expect(page.getByRole('checkbox',{name:'已查看这个版本的原图'})).not.toBeChecked();await expect(page.getByRole('combobox',{name:'用途结论',exact:true})).toHaveValue('');expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);});
test('an unrelated release after a lost save receipt recovers the stale head and requires fresh decisions',async({page})=>{const f=await fixture(page,{unknownSave:true,commitUnknown:true});await author(page);await page.getByRole('button',{name:'保存用途审阅草稿'}).click();await expect(page.getByRole('status')).toContainText('结果待核查');f.workspace.staleDraft={...f.workspace.draft!,reason:'another source publication'};f.workspace.draft=null;f.workspace.releaseId='release:unrelated';await page.getByRole('button',{name:'重读图片与用途审阅'}).click();await expect(page.getByRole('status')).toContainText('已核回保存成功；依据已变化');await expect(page.getByRole('combobox',{name:'用途结论',exact:true})).toHaveValue('');await expect(page.getByRole('textbox',{name:'这张图片如何满足当前需求'})).toHaveValue(/当前明确空态/);await expect(page.getByRole('button',{name:'保存用途审阅草稿'})).toBeEnabled();await expect(page.getByRole('button',{name:'预览用途审阅',exact:true})).toBeDisabled();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
test('rereading a changed standard preserves dirty text and makes the new criteria editable',async({page})=>{const f=await fixture(page);await author(page);f.workspace.basisHash='d'.repeat(64);f.workspace.reviewSpec={...f.workspace.reviewSpec,hash:'e'.repeat(64),criteria:[{id:'new:criterion',label:'新用途标准',question:'符合更新后的当前用途？',required:true,allowNA:false,noteRequiredOnFail:true}]};f.workspace.requirement.reviewSpec=f.workspace.reviewSpec;await page.getByRole('button',{name:'重读图片与用途审阅'}).click();await expect(page.getByRole('status')).toContainText('依据已变化');await expect(page.getByRole('textbox',{name:'这张图片如何满足当前需求'})).toHaveValue(/当前明确空态/);const group=page.getByRole('group',{name:'新用途标准',exact:true});await expect(group.getByRole('combobox',{name:'判断',exact:true})).toHaveValue('');await group.getByRole('combobox',{name:'判断',exact:true}).selectOption('PASS');await expect(group.getByRole('combobox',{name:'判断',exact:true})).toHaveValue('PASS');await expect(page.getByRole('combobox',{name:'用途结论',exact:true})).toHaveValue('');expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);});
