import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {apiFixture} from './fixtures/legacy-audio-candidate-api.mjs';
import {legacyFamily,legacyWork,wav,audioRequirementId} from './material-legacy-audio-fixture.mjs';
import {changeDomain} from './material-production-fixture.mjs';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {domainHash} from '../host/instance-runtime/domain-model.mjs';
import {legacyAudioCandidateProof,assertLegacyAudioCandidatePreservation} from '../host/instance-legacy-audio-candidate-proof.mjs';
import {preserveLegacyAudioProjection} from '../host/instance-runtime/material-legacy-audio-preservation.mjs';

const options={skip:process.env.REVIEW_TEST_POSTGRES!=='1',timeout:180000};
test('isolated PostgreSQL legacy voice revision creates clean master metadata and preserves actual V001 source, parameters, candidate and usage history',options,async t=>{
 const f=await apiFixture(t,{legacyMetadata:{PIPELINE_STAGE:'P06',SCENE:'S-OLD',SCENE_SCOPE:'OLD_BATCH',TEST_LINE_ID:'S-OLD-L01',SCRIPT_VERSION:'old script',VOICE_PROFILE_STATUS:'P07_CANDIDATE'},legacyRequirementScope:{reuseScope:'SHOT_SET',sceneIds:['S-OLD'],episodeUids:['EP-OLD']}});
 const initial=await f.repo.readView(),definition=initial.recipes.executionDefinitions.find(d=>d.workItemRef===legacyWork),first={result:{familyId:legacyFamily,workItemId:legacyWork},recipe:definition};
 const machine=await f.repo.getPublishedDocument(definition.source.jsonPath),originalAsset=JSON.parse(machine.bytes).assets.find(a=>a.asset_id===legacyFamily),v1=await f.register(first,await f.beginRun(first),wav(0),{parentVersionId:null});await f.review(first,v1,'REQUEST_REVISION');
 const before=await f.repo.readView(),oldCandidate=before.eventsByKind['asset-version'][0],oldReview=before.eventsByKind.review[0],req=before.snapshot.productionModel.materialRequirements.find(r=>r.id===audioRequirementId),oldEvidence=await f.evidence(legacyFamily,v1);
 const second=await f.provision(await f.workspace(),'固定试音两遍，约半秒间隙。This is an isolated master test, not scene dialogue.'),plan=second.plan,meta=plan.seedAsset.metadata;
 assert.equal(plan.metadataSchemaVersion,'VOICE_IDENTITY_MASTER_METADATA_V1');assert.equal(second.recipe.pipelineStageCode,'MATERIAL_PREP');assert.equal(meta.SUBJECT_ID,'character:letter-writer');assert.equal(meta.VOICE_ID,originalAsset.metadata.VOICE_ID);
 for(const key of ['SCENE','LINE_ID','TEST_LINE_ID','SCRIPT_VERSION','CONTINUITY_VERSION'])assert.equal(meta[key],'NA');assert.equal(JSON.stringify(meta).includes('S-OLD'),false);assert.equal(JSON.stringify(meta).includes('EP-OLD'),false);assert.equal(meta.SCENE_SCOPE,'VOICE_IDENTITY_MASTER');
 assert.deepEqual(meta.PRODUCTION_BINDING.productionScope,{scopeType:'ASSET_FAMILY',scopeId:legacyFamily});assert.equal(meta.PRODUCTION_BINDING.requirementRecordHash,domainHash(req));assert.deepEqual(meta.PRODUCTION_BINDING.dialogueBindings,[]);assert.deepEqual(meta.PARENT_ASSETS,[v1.versionId]);assert.equal(meta.PARENT_VERSION_SHA256,v1.sha256);
 assert.equal(meta.PROMPT_SOURCE,plan.sourcePath);assert.equal(meta.PROMPT_VERSION,second.recipe.currentRevisionId);assert.equal(meta.PRODUCTION_BINDING.output.expectedOutputId,second.recipe.output.expectedOutputRef);assert.equal(meta.PRODUCTION_BINDING.output.path,second.recipe.output.path);
 for(const key of ['model','references','audio_config','delivery','watermark'])assert.deepEqual(plan.seedAsset[key],originalAsset[key]);assert.equal(second.recipe.seedAssetSha256,domainHash(plan.seedAsset));
 const published=await f.repo.readView();assert.deepEqual(published.snapshot.productionModel.materialRequirements.find(r=>r.id===audioRequirementId),req);assert.deepEqual(await f.repo.readDocumentRevision(machine.revisionId),machine);assert.deepEqual(published.recipes.executionDefinitions.find(d=>d.id===definition.id),definition);assert.deepEqual(published.eventsByKind['asset-version'][0],oldCandidate);assert.deepEqual(published.eventsByKind.review[0],oldReview);assert.deepEqual(await f.evidence(legacyFamily,v1),oldEvidence);
 if(process.env.LEGACY_AUDIO_METADATA_QA_DIR){const dir=process.env.LEGACY_AUDIO_METADATA_QA_DIR;await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'seed-asset.json'),JSON.stringify(plan.seedAsset,null,2)+'\n',{flag:'wx'});await writeFile(path.join(dir,'seed-asset.canonical.json'),canonicalJson(plan.seedAsset),{flag:'wx'});await writeFile(path.join(dir,'definition.json'),JSON.stringify(second.recipe,null,2)+'\n',{flag:'wx'});await writeFile(path.join(dir,'hash-proof.json'),JSON.stringify({scope:'ISOLATED_SYNTHETIC_POSTGRES_FIXTURE_NO_PROVIDER',seedAssetSha256:second.recipe.seedAssetSha256,canonicalBytesSha256:sha256(canonicalJson(plan.seedAsset)),metadataSchemaVersion:plan.metadataSchemaVersion},null,2)+'\n',{flag:'wx'});}
 const v2=await f.register(second,await f.beginRun(second),wav(1));assert.equal(v2.versionId,legacyFamily+'@V002');
 const input=await f.repo.readTransaction(async tx=>{const v=await tx.readView(),activeMedia=await tx.listMedia(),pinnedMediaHashes={};for(const m of activeMedia){assert.equal(sha256(await readFile(path.join(f.root,m.relativePath))),m.sha256);for(const alias of [m.relativePath,...m.aliases||[],m.metadata?.sourcePath,m.metadata?.legacyVersion?.path].filter(Boolean))pinnedMediaHashes[alias]=m.sha256;}return {documents:await Promise.all(v.sourceRevisionIds.map(id=>tx.readDocumentRevision(id))),events:Object.values(v.eventsByKind).flat(),baseRelease:await tx.readRelease(),activeMedia,pinnedMediaHashes,compiler:{eventDirectory:'events'}};});
 const proof=legacyAudioCandidateProof(input),snapshot=JSON.parse(input.baseRelease.snapshotBytes),recipes=JSON.parse(input.baseRelease.recipesBytes),restored=preserveLegacyAudioProjection({snapshot:initial.snapshot,recipes:initial.recipes,baseSnapshot:snapshot,baseRecipes:recipes,documents:input.documents});
 assert.equal(assertLegacyAudioCandidatePreservation({proof,...restored,events:input.events}).baseCandidateVersionsCreated,0);assert.deepEqual(restored.recipes.executionDefinitions.find(d=>d.id===definition.id),definition);assert.equal(restored.recipes.executionDefinitions.find(d=>d.id===second.recipe.id).seedAssetSha256,second.recipe.seedAssetSha256);assert.equal(sha256(await readFile(path.join(f.root,'media/_review_pending/'+legacyFamily+'/FIXTURE_VOICE_MASTER_V001.wav'))),v1.sha256);
 const wrong=structuredClone(input);wrong.events.find(e=>e.eventKind==='asset-version'&&e.versionId===v2.versionId).parentVersionSha256='0'.repeat(64);assert.throws(()=>legacyAudioCandidateProof(wrong),{code:'SOURCE_LEGACY_AUDIO_CANDIDATE_BINDING'});
 await f.review(second,v2,'REQUEST_REVISION');
 const graph=(await f.repo.readView()).snapshot.productionModel.domainGraph,rep=graph.representations.find(r=>r.assetFamilyIds.includes(legacyFamily)),entity={id:'character:another-voice',name:'Different permanent character',type:'CHARACTER',aliases:[],description:'Synthetic source ownership conflict.',authority:'A',evidence:[]};
 await changeDomain(f.repo,'SETTINGS',[{collection:'entities',id:entity.id,beforeHash:null,value:entity}]);const changed=await f.repo.exportState();await assert.rejects(()=>changeDomain(f.repo,'MATERIAL',[{collection:'representations',id:rep.id,beforeHash:domainHash(rep),value:{...rep,entityId:entity.id}}]),/永久身份不能换绑/);assert.deepEqual(await f.repo.exportState(),changed);assert.equal(f.externalCalls(),0);
});
