import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
const url=new URL('../host/instance-modern-event-validator.mjs',import.meta.url);
const {readFrozenModernEventInput,digest,canonical}=await import(url);
const bridgeUrl=new URL('../host/instance-modern-event-bridge.mjs',import.meta.url);
const {serializeModernEventInput}=await import(bridgeUrl);
const value={snapshotId:'快照:只读',blocks:[{text:'人物推开门，看见一封信。🧭 北侧未发生镜像。'}],number:123};
test('every possible byte split preserves exact Unicode snapshot canonical hash',async()=>{const bytes=Buffer.from(canonical(value));for(let i=1;i<bytes.length;i++){const actual=await readFrozenModernEventInput(Readable.from([bytes.subarray(0,i),bytes.subarray(i)]));assert.deepEqual(actual,value);assert.equal(digest(actual),digest(value));}});
test('one-byte chunks preserve a multi-byte CJK character and a four-byte emoji',async()=>{const bytes=Buffer.from(JSON.stringify(value));const actual=await readFrozenModernEventInput(Readable.from([...bytes].map(byte=>Buffer.from([byte]))));assert.deepEqual(actual,value);});
test('previous per-chunk string conversion demonstrably corrupts frozen content',()=>{const bytes=Buffer.from(canonical(value)),start=bytes.indexOf(Buffer.from('人物'));const broken=bytes.subarray(0,start+1).toString()+bytes.subarray(start+1).toString();assert.notEqual(digest(JSON.parse(broken)),digest(value));assert(broken.includes('\uFFFD'));});
test('invalid JSON remains a hard failure',async()=>{await assert.rejects(readFrozenModernEventInput(Readable.from([Buffer.from('{"snapshot":')])));});
test('the hash assertion still detects a semantically changed snapshot after valid transport',async()=>{const changed={...value,snapshotId:'不同快照'},decoded=await readFrozenModernEventInput(Readable.from([Buffer.from(JSON.stringify(changed))]));assert.notEqual(digest(decoded),digest(value));});
test('child transport preserves exact original scriptBlock field order and byte-sensitive excerpt SHA',async()=>{
 const input={events:[{content:{scriptBlocks:[{id:'block:one',type:'dialogue',speaker:'人物',performanceNote:'停顿',text:'请看此信。'}]}}]};
 const blocks=input.events[0].content.scriptBlocks,expected=digest(JSON.stringify(blocks)),bytes=Buffer.from(serializeModernEventInput(input));
 const decoded=await readFrozenModernEventInput(Readable.from([...bytes].map(byte=>Buffer.from([byte]))));
 assert.deepEqual(Object.keys(decoded.events[0].content.scriptBlocks[0]),Object.keys(blocks[0]));
 assert.equal(digest(JSON.stringify(decoded.events[0].content.scriptBlocks)),expected);
 assert.equal(digest(decoded),digest(input),'canonical whole-event binding is independently preserved');
 const oldWire=JSON.parse(canonical(input));assert.equal(digest(oldWire),digest(input));assert.notEqual(digest(JSON.stringify(oldWire.events[0].content.scriptBlocks)),expected,'old canonical wire demonstrably broke the historical excerpt byte contract');
});
