import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
async function fixture(page:Page,{legacy=false,mismatch='',readOnly=false,preservePrompt=false,materialRevision=false,missingParent=false}={}){
 const familyId=legacy?'OLD-IMAGE':(materialRevision?'MP-AF-':'SP-AF-')+'a'.repeat(24),id=legacy?'EXPECTED_OUTPUT:OLD-IMAGE@V001':(materialRevision?'MP-EO-':'SP-EO-')+'a'.repeat(24),targetPath=legacy?'production/generated/images/_review_pending/OLD-IMAGE/V001.png':'media/_review_pending/'+(materialRevision?'material-production/':'shot-production/')+familyId+(materialRevision?'/V002.png':'/V001.png');
 const output={id,familyId,targetPath,plannedVersionLabel:materialRevision?'V002':'V001',legacyVersionId:legacy?familyId+'@V001':id,expectationState:'PLANNED',realizedVersionId:null};
 const recipe={id:'CALL-EXACT',title:'本镜图像调用包',pipelineStageCode:'P07',executorKind:'MODEL_CALL',definitionHash:'d'.repeat(64),currentRevisionId:'CALL-EXACT:r1',upload:{rawText:'',items:[]},model:{branch:'codex:gpt-image-2',rawRule:'codex:gpt-image-2',resolution:'EXPLICIT_PARAMETERS'},parametersRaw:'{"width":1024,"height":1024}',prompt:{main:preservePrompt?'  精确主提示词\n':'精确主提示词',negative:preservePrompt?null:'精确排除要求',negativeApplication:'APPLY_WITH_MAIN_PROMPT'},output:{path:targetPath,mediaType:'IMAGE',assetFamilyRef:familyId,expectedOutputRef:id},declaredGate:'READY_TO_START',rawSourceBlock:'fixture'};
 if(materialRevision)Object.assign(recipe,{materialProductionPlanId:'MP-PLAN-'+'a'.repeat(24),...(missingParent?{}:{parentVersionId:familyId+'@V001'})});
 const context={snapshotId:'SNAPSHOT',mutationEtag:'"etag"',shotId:'SHOT',workPackageId:'PACKAGE',workItemId:'WORK',familyId,parentVersionId:null,canAuthorize:true,authorizeReason:'ready',expectedOutput:mismatch==='missing'?null:{...output,...(mismatch==='family'?{familyId:'OTHER'}:{}),...(mismatch==='path'?{targetPath:targetPath.replace('V001','V999')}:{}),...(mismatch==='id'?{id:'OTHER'}:{})}};
 const entry=`import React from'react';import{createRoot}from'react-dom/client';import{RecipePanel}from'./app/production-workbench';import{RuntimeModeProvider}from'./app/runtime-mode';createRoot(document.getElementById('root')).render(<RuntimeModeProvider hostedReadOnly={${readOnly}}><RecipePanel expanded definitionRef="CALL-EXACT" recipe={${JSON.stringify(recipe)}} error="" executionContext={${JSON.stringify(context)}}/></RuntimeModeProvider>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'native-import.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-native-import',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text;
 const writes:Array<Record<string,unknown>>=[],unexpected:string[]=[],errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname==='/api/v8/operations/snapshot'&&request.method()==='GET')return route.fulfill({json:{snapshotId:'SNAPSHOT',mutationEtag:'"exact-etag"'}});if(url.pathname==='/api/v8/imports'&&request.method()==='POST'){writes.push(request.postDataJSON());return route.fulfill({status:201,json:{eventId:'candidate-test',versionId:familyId+'@V001'}});}unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,json:{error:'unexpected API'}});});
 await page.route('**/__native-import',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><body><div id="root"></div><script>${js}</script></body></html>`}));await page.goto('/__native-import');await page.getByText('登记已有候选结果',{exact:true}).click();
 return{writes,unexpected,errors,recipe,output};
}
async function fillRun(page:Page){await page.getByRole('textbox',{name:'Run ID（必填）',exact:true}).fill('run_exact');await page.getByRole('textbox',{name:'Execution Request ID（必填）',exact:true}).fill('xreq_exact');}
for(const legacy of [false,true])test(`${legacy?'legacy':'native'} controlled target is fixed and the real import control sends exact ExpectedOutput and recipe`,async({page})=>{
 const f=await fixture(page,{legacy});const target=page.getByRole('textbox',{name:'已冻结的候选目标路径',exact:true});await expect(target).toHaveValue(f.output.targetPath);await expect(target).toHaveAttribute('readonly','');await fillRun(page);await page.getByRole('button',{name:'预检并登记已有结果',exact:true}).click();await expect(page.getByText(/候选已登记为/)).toBeVisible();
 expect(f.writes).toHaveLength(1);expect(f.writes[0]).toMatchObject({snapshotId:'SNAPSHOT',familyId:f.output.familyId,expectedOutputId:f.output.id,path:f.output.targetPath,executionDefinitionId:f.recipe.id,callPackageHash:f.recipe.definitionHash,actualPrompt:f.recipe.prompt,executionRequestId:'xreq_exact',runId:'run_exact',parentVersionId:null,inputBindings:[]});expect(f.unexpected).toEqual([]);expect(f.errors).toEqual([]);
});
for(const mismatch of ['missing','id','path','family'])test(`import blocks ${mismatch} ExpectedOutput without posting`,async({page})=>{const f=await fixture(page,{mismatch});await fillRun(page);await page.getByRole('button',{name:'预检并登记已有结果',exact:true}).click();await expect(page.getByText(mismatch==='missing'?'当前工作项缺少精确预期产物，请刷新并核对当前目标。':'当前预期产物与调用包不一致，请刷新并核对当前目标。',{exact:true})).toBeVisible();expect(f.writes).toEqual([]);expect(f.unexpected).toEqual([]);expect(f.errors).toEqual([]);});
test('read-only native import cannot submit',async({page})=>{const f=await fixture(page,{readOnly:true});await expect(page.getByRole('button',{name:'远端镜像不可登记候选',exact:true})).toBeDisabled();expect(f.writes).toEqual([]);expect(f.unexpected).toEqual([]);expect(f.errors).toEqual([]);});

test('unchanged actualPrompt preserves frozen whitespace and null values for CODEX exact hash',async({page})=>{const f=await fixture(page,{preservePrompt:true});await fillRun(page);await page.getByRole('button',{name:'预检并登记已有结果',exact:true}).click();await expect(page.getByText(/候选已登记为/)).toBeVisible();expect(f.writes[0].actualPrompt).toEqual(f.recipe.prompt);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);});
test('native material successor imports with the recipe parent even when navigation has no parent',async({page})=>{const f=await fixture(page,{materialRevision:true});await fillRun(page);await page.getByRole('button',{name:'预检并登记已有结果',exact:true}).click();await expect(page.getByText(/候选已登记为/)).toBeVisible();expect(f.writes[0]).toMatchObject({expectedOutputId:f.output.id,path:f.output.targetPath,parentVersionId:f.output.familyId+'@V001'});expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);});
test('native material import rejects a missing frozen parent before posting',async({page})=>{const f=await fixture(page,{materialRevision:true,missingParent:true});await fillRun(page);await page.getByRole('button',{name:'预检并登记已有结果',exact:true}).click();await expect(page.getByText('基础素材调用包缺少精确父版本依据，请重新读取制作资料。',{exact:true})).toBeVisible();expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);});
