import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
// Pure in-memory repository. No SQLite/PG server, filesystem mutation or renderer.
const root=process.cwd(),require=createRequire(path.join(root,'package.json')),ts=require('typescript');
const host=rel=>import(pathToFileURL(path.join(root,'host/instance-runtime',rel)));
const {blankProfile,blankSnapshot}=await host('blank.mjs');
const {canonicalJson,sha256}=await host('bytes.mjs');
const animatic=await host('animatic-service.mjs');
const {animaticHash}=await host('animatic-model.mjs');
function ast(file){const source=fs.readFileSync(path.join(root,file),'utf8');return{source,node:ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS)};}
const index=ast('host/instance-runtime/index.mjs'),postgres=ast('host/instance-runtime/postgres.mjs');
const functionCode=name=>index.node.statements.find(s=>ts.isFunctionDeclaration(s)&&s.name?.text===name).getText(index.node).replace(/^export /,'');
const ensure=(ok,code,message)=>{if(!ok)throw Object.assign(Error(message),{code});};
const text=(value,label)=>{ensure(typeof value==='string'&&value.length>0&&value.length<=4096&&!value.includes('\0'),'INVALID_INPUT',label);return value;};
const helpers=Function('ensure','text','canonicalJson','sha256',functionCode('projectionFingerprintNamespaces')+'\n'+functionCode('projectionFingerprintRows')+'\nreturn {projectionFingerprintNamespaces,projectionFingerprintRows};')(ensure,text,canonicalJson,sha256);
function fingerprintMethod(input,className){const cl=input.node.statements.find(s=>ts.isClassDeclaration(s)&&s.name?.text===className),method=cl.members.find(m=>m.name?.getText(input.node)==='getProjectionFingerprint');assert.ok(method);return Function('projectionFingerprintNamespaces','projectionFingerprintRows','return ({'+method.getText(input.node)+'}).getProjectionFingerprint;')(helpers.projectionFingerprintNamespaces,helpers.projectionFingerprintRows);}
const sqliteFingerprint=fingerprintMethod(index,'ReadUnit'),pgFingerprint=fingerprintMethod(postgres,'PgUnit');
const metadataRow=m=>({media_id:m.mediaId,version_id:m.versionId,relative_path:m.relativePath,sha256:m.sha256,byte_size:m.byteSize,availability:m.availability,metadata_json:canonicalJson(m.metadata)});
function databaseRows(repo,sql,params){repo.queries.push({sql,params});assert.doesNotMatch(sql,/content_bytes|SELECT\s+\*/i);if(sql.includes('FROM record_heads')){const namespaces=params.flat();assert.ok(namespaces.every(n=>n.startsWith('aux:')));return[...repo.aux.values()].filter(r=>namespaces.includes(r.namespace)).map(r=>({namespace:r.namespace,record_key:r.key,revision_id:r.revisionId})).reverse();}if(sql.includes('FROM media_versions'))return repo.media.map(metadataRow).reverse();if(sql.includes('FROM media_aliases'))return repo.media.flatMap(m=>m.aliases.map(alias=>({alias,media_id:m.mediaId,version_id:m.versionId}))).reverse();assert.fail('Unexpected query '+sql);}
class MemoryRepository {
 constructor(snapshot,recipes){this.snapshot=snapshot;this.recipes=recipes;this.aux=new Map();this.media=[];this.events=[];this.sequence=0;this.repositoryRevision=0;this.releaseId='release:'+randomUUID();this.runtimeEpoch='epoch:one';this.instanceId=snapshot.instance.instanceId;this.transactionMode=null;this.queries=[];this.auxReads=0;this.fingerprintReads=0;this.depth=0;}
 get inTransaction(){return this.depth>0;}
 async readTransaction(fn){assert.equal(this.depth,0,'No recursive operationalSnapshot');this.depth++;this.transactionMode='READ';try{return await fn(this);}finally{this.depth--;this.transactionMode=null;}}
 async getMetadata(){return{instanceId:this.instanceId,runtimeEpoch:this.runtimeEpoch,releaseId:this.releaseId,repositoryRevision:this.repositoryRevision,eventSequence:this.sequence};}
 async readView(){return{...await this.getMetadata(),profile:this.snapshot.instance,snapshot:structuredClone(this.snapshot),recipes:structuredClone(this.recipes),eventsByKind:Object.groupBy([...this.events].reverse(),e=>e.eventKind),sourceRevisionIds:[],dataFingerprint:sha256(canonicalJson(this.snapshot)),recipeFingerprint:sha256(canonicalJson(this.recipes))};}
 async listPublishedDocumentMetadata(){return [];}
 async getPublishedDocument(){return null;}
 async listEvents(kind){return this.events.filter(e=>e.eventKind===kind).reverse();}
 async getAux(namespace,key){this.auxReads++;return this.aux.get('aux:'+namespace+'/'+key)||null;}
 async listAux(namespace,{prefix='',includeDeleted=false}={}){this.auxReads++;return[...this.aux.values()].filter(r=>r.namespace==='aux:'+namespace&&r.key.startsWith(prefix)&&(includeDeleted||!r.deleted));}
 async putAux({namespace,key,bytes,expectedRevisionId=null,deleted=false}){const old=await this.getAux(namespace,key);assert.equal(old?.revisionId||null,expectedRevisionId);const row={namespace:'aux:'+namespace,key,bytes:Buffer.from(bytes),revisionId:'head:'+ ++this.repositoryRevision,deleted};this.aux.set(row.namespace+'/'+key,row);return row;}
 async getProjectionFingerprint(namespaces){assert.equal(this.depth,1,'Fingerprint must be inside read transaction');this.fingerprintReads++;return sqliteFingerprint.call({db:{prepare:sql=>({all:(...params)=>databaseRows(this,sql,params)})}},namespaces);}
 async getMedia(family,version){return this.media.find(m=>m.mediaId===family&&m.versionId===version)||null;}
 async listMedia(){return this.media;}
 async registerMedia(input){const row={availability:'PRESENT',aliases:[],...input};this.media.push(row);this.repositoryRevision++;return row;}
 async appendEvent({kind,payload}){const event={...payload,eventId:'event:'+ ++this.sequence,eventKind:kind,eventSequence:this.sequence,recordedAt:new Date().toISOString()};this.events.push(event);this.repositoryRevision++;return{event,replayed:false};}
}
// Compile the actual complete module and its actual one-layer dependencies.
// The test-only appended closure replaces transport selection, not production logic.
const previous=new Map();
for(const ext of ['.ts','.tsx']){previous.set(ext,require.extensions[ext]);require.extensions[ext]=(module,filename)=>{assert.ok(filename.startsWith(path.join(root,'app')+path.sep));let source=fs.readFileSync(filename,'utf8');if(filename===path.join(root,'app/api/v8/_store.ts'))source+=`\nexport function __bindMemoryRepository(repo){ instanceRepository=async()=>repo; instanceRepositoryMode=()=>true; hostedReadOnlyMode=()=>false; dataCache=null; dataCacheFingerprint=null; publishedViews.clear(); operationsCache.clear(); }\nexport function __bindFrozenFixture(data,recipes,hosted){ instanceRepository=async()=>{throw Error('No repository on fixture/hosted path')}; instanceRepositoryMode=()=>false; hostedReadOnlyMode=()=>hosted; dataCacheFingerprint='fixture';recipeCacheFingerprint='recipes'; reviewData=async()=>data;recipeCatalog=async()=>recipes;listAllEvents=async()=>[];}\nexport const __candidateBindsCurrentGraph=candidateBindsCurrentGraph;\n`;module._compile(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,filename);};}
const api=require(path.join(root,'app/api/v8/_store.ts'));
const {exactReviewContextForScope}=require(path.join(root,'app/api/v8/_action-queue.ts'));
for(const [ext,loader] of previous){if(loader)require.extensions[ext]=loader;else delete require.extensions[ext];}
function fixture(){
 const bundle=blankSnapshot(blankProfile({title:'内存投影验证'})),repo=new MemoryRepository(bundle.snapshot,bundle.recipes),model=bundle.snapshot.productionModel;
 const scene='scene:test',shot='shot:A',board={familyId:'family:board',versionId:'family:board@V001',sha256:'a'.repeat(64)},timeline={schemaVersion:'1.0',sceneId:scene,shotPlanRevisionId:'plan:one',fps:24,width:1920,height:1080,shots:[{shotId:shot,durationFrames:24,panels:[{id:'panel:A',media:board,startFrame:0,endFrame:24,motion:'STILL'}],beats:[]}],audio:[],cards:[]};
 const content={sceneId:scene,shots:[{shotId:shot,sceneId:scene,order:1}]},hash=animaticHash(content),work={id:'work:animatic',scopeType:'SCENE',scopeId:scene,sceneId:scene,scopeRole:'CURRENT',activeInCurrentProduction:true,deliverableKey:'ANIMATIC',gateId:'ANIMATIC_LOCK',outputAssetRef:'family:animatic',reviewContextRef:'context:animatic',inputBindings:[]};
 Object.assign(model,{shotProductionPlans:[{id:'production:one',sceneId:scene,scopeRole:'CURRENT',content:{shots:[]},workItemIds:['work:animatic','work:board']}],shotPlanSetRevisions:[{id:'plan:one',episodeUid:'episode:one',scopeType:'SCENE',scopeId:scene,scopeRole:'CURRENT',sourceOperationId:'op:one',sourceSyncState:'SUCCEEDED',content,contentHash:hash,episodeNarrativeReleaseId:'release:episode'}],episodeNarrativeReleases:[{id:'release:episode',episodeUid:'episode:one',scopeRole:'CURRENT',sourceSyncState:'SOURCE_CURRENT',reviewInput:{scenes:[{id:scene,contentHash:'scenehash'}]}}],sceneScriptRevisions:[{sceneId:scene,scopeRole:'CURRENT',episodeNarrativeReleaseId:'release:episode',contentHash:'scenehash'}],scopeLocks:[{scopeType:'SCENE',scopeId:scene,lockPurpose:'SHOT_PLAN_SET',lockState:'LOCKED',denominatorState:'KNOWN',shotPlanSetRevisionId:'plan:one',shotPlanSetRevisionHash:hash,shotIds:[shot]}],shots:[{id:shot,sceneId:scene,scopeRole:'CURRENT',shotPlanSetRevisionId:'plan:one',shotPlanSetRevisionHash:hash}],assetFamilies:[{id:board.familyId,label:'粗分镜',kind:'IMAGE',currentVersionId:board.versionId,canFlowDownstream:true},{id:'family:animatic',ownerRef:work.id,label:'预演',kind:'VIDEO',expectedOutputRefs:['expected:animatic'],currentExpectedOutputId:'expected:animatic'}],assetVersions:[{id:board.versionId,familyId:board.familyId,sha256:board.sha256,path:'media/board.png',canFlowDownstream:true}],workItems:[work,{id:'work:board',sceneId:scene,shotId:shot,scopeRole:'CURRENT',deliverableKey:'STORYBOARD',outputAssetRef:board.familyId,inputBindings:[]}],expectedOutputs:[{id:'expected:animatic',familyId:'family:animatic',targetPath:'media/_review_pending/animatic/V001.mp4',expectationState:'PLANNED',scopeRole:'CURRENT'}],reviewContexts:[{id:'context:animatic',scopeType:'SCENE',scopeId:scene,contextHash:'c'.repeat(64)}]});
 model.episodeNarrativeReleases[0].episodeScriptReleaseSnapshot={id:'script-snapshot:one',contentHash:'d'.repeat(64)};
 return{...bundle,repo,model,timeline,board,work};
}
async function complete(f){
 const {repo,model,timeline,board}=f;await repo.registerMedia({mediaId:board.familyId,versionId:board.versionId,relativePath:'media/board.png',sha256:board.sha256,byteSize:4,metadata:{authorityDomain:'FORMAL'}});
 const saved=await animatic.saveAnimaticTimeline(repo,{sceneId:timeline.sceneId,expectedReleaseId:repo.releaseId,expectedRevisionId:null,requestId:randomUUID(),content:timeline},{model});
 const queued=await animatic.enqueueAnimaticRender(repo,{sceneId:timeline.sceneId,expectedReleaseId:repo.releaseId,expectedRevisionId:saved.revisionId,timelineRevisionId:saved.timelineRevisionId,requestId:randomUUID()},{model});
 const claim=await animatic.claimAnimaticRender(repo,queued.jobId,'worker:memory');
 const result={relativePath:claim.job.expectedOutput.targetPath,sha256:'b'.repeat(64),byteSize:123,frameCount:24,fps:24,width:1920,height:1080};
 await animatic.finishAnimaticRender(repo,{jobId:queued.jobId,jobRevisionId:claim.jobRevisionId,workerId:'worker:memory',result},{model});return queued.jobId;
}
test('completed AUX render without a new release is a current asset version with exact scene review context',async()=>{
 const f=fixture(),release=f.repo.releaseId;await complete(f);const candidate=f.repo.events[0];assert.equal(api.__candidateBindsCurrentGraph(f.snapshot,candidate),false,'Raw published snapshot reproduces old missing candidate');api.__bindMemoryRepository(f.repo);const result=await api.operationalSnapshot();assert.equal(f.repo.releaseId,release);assert.equal(result.stateProjection.assetVersionsById[candidate.versionId].sha256,candidate.sha256);assert.equal(result.stateProjection.assetVersionsById[candidate.versionId].canFlowDownstream,false,'Registration is not adoption');const data=await api.reviewData(),context=exactReviewContextForScope(f.work.reviewContextRef,data.productionModel.reviewContexts,'SCENE',f.timeline.sceneId);assert.equal(context.contextHash,'c'.repeat(64));assert.equal(exactReviewContextForScope(f.work.reviewContextRef,data.productionModel.reviewContexts,'SCENE','other'),null);assert.equal(api.__candidateBindsCurrentGraph(data,candidate),true);assert.ok(f.repo.fingerprintReads>0);
});
test('AUX-only and deleted-head changes invalidate cache while assistant heartbeat does not',async()=>{
 const f=fixture(),jobId=await complete(f);api.__bindMemoryRepository(f.repo);const first=await api.operationalSnapshot(),sequence=f.repo.sequence,release=f.repo.releaseId,reads=f.repo.auxReads;await f.repo.putAux({namespace:'assistant-public',key:'heartbeat',bytes:'{}'});assert.strictEqual(await api.operationalSnapshot(),first);assert.equal(f.repo.auxReads,reads+1,'No AUX projection bodies reread for heartbeat');
 const row=await f.repo.getAux('animatic-render-jobs',jobId),job=JSON.parse(row.bytes);const changed=await f.repo.putAux({namespace:'animatic-render-jobs',key:jobId,bytes:canonicalJson({...job,status:'RESULT_UNKNOWN'}),expectedRevisionId:row.revisionId});const second=await api.operationalSnapshot();assert.notStrictEqual(second,first);assert.notEqual(second.operationRevision,first.operationRevision);assert.equal(second.stateProjection.assetVersionsById[f.repo.events[0].versionId],undefined);await f.repo.putAux({namespace:'animatic-render-jobs',key:jobId,bytes:changed.bytes,expectedRevisionId:changed.revisionId,deleted:true});const third=await api.operationalSnapshot();assert.notEqual(third.operationRevision,second.operationRevision);assert.equal(f.repo.sequence,sequence);assert.equal(f.repo.releaseId,release);
});
test('registered-media changes independently invalidate the projection and reject a mismatched receipt',async()=>{
 const f=fixture();await complete(f);api.__bindMemoryRepository(f.repo);const first=await api.operationalSnapshot(),output=f.repo.media.at(-1);output.metadata={...output.metadata,registrationEventId:'wrong'};f.repo.repositoryRevision++;const second=await api.operationalSnapshot();assert.notEqual(first.operationRevision,second.operationRevision);assert.equal(second.stateProjection.assetVersionsById[output.versionId],undefined);
});
test('SQLite and PostgreSQL fingerprint contracts use the same bounded parameterized namespaces and metadata rows',async()=>{
 const f=fixture();await complete(f);const namespaces=['animatic-render-jobs','animatic-heads','animatic-render-jobs'],sqlite=()=>sqliteFingerprint.call({db:{prepare:sql=>({all:(...params)=>databaseRows(f.repo,sql,params)})}},namespaces),pg=()=>pgFingerprint.call({all:async(sql,params=[])=>databaseRows(f.repo,sql,params)},namespaces);assert.equal(await sqlite(),await pg());assert.equal(await sqlite(),await pgFingerprint.call({all:async(sql,params=[])=>databaseRows(f.repo,sql,params)},[...new Set(namespaces)].reverse()));const before=await sqlite();f.repo.media[0].aliases.push('media/alias.png');assert.notEqual(await sqlite(),before);assert.equal(await sqlite(),await pg());assert.throws(()=>sqliteFingerprint.call({},['']));assert.throws(()=>sqliteFingerprint.call({},Array(65).fill('x')));assert.throws(()=>sqliteFingerprint.call({},['nul\0']));assert.ok(f.repo.queries.some(q=>q.sql.includes('ANY($1::text[])')));assert.ok(f.repo.queries.some(q=>q.sql.includes('IN (?,?)')));assert.ok(f.repo.queries.every(q=>!q.sql.includes('assistant-public')));
});
test('new empty instance and ordinary/hosted frozen fixtures need no production AUX or repository',async()=>{
 const bundle=blankSnapshot(blankProfile()),repo=new MemoryRepository(bundle.snapshot,bundle.recipes);api.__bindMemoryRepository(repo);const a=await api.operationalSnapshot();assert.equal(a.counts.candidates,0);assert.equal(repo.fingerprintReads,0);assert.equal(repo.auxReads,0);for(const hosted of [false,true]){api.__bindFrozenFixture(bundle.snapshot,bundle.recipes,hosted);const result=await api.operationalSnapshot();assert.equal(result.counts.candidates,0);assert.deepEqual(result.stateProjection.assetVersionsById,{});}
});
