import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir, mkdtemp, rm} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createInstanceRepository} from '../host/instance-runtime/index.mjs';
import {blankProfile, blankSnapshot} from '../host/instance-runtime/blank.mjs';
import {readOrchestration, writeOrchestration, WORKER_KINDS} from '../host/instance-runtime/orchestration-service.mjs';
import {includedNamespace} from '../host/instance-runtime/git-business-archive.mjs';
import {sharedStoryPostgres} from './fixtures/shared-story-postgres.mjs';

test('PostgreSQL serializes twelve independent pool leases, idempotent reports and persistent history', {skip: process.env.REVIEW_TEST_POSTGRES !== '1', timeout: 120000}, async t => {
  const parent = path.resolve('tests/.test-tmp'); await mkdir(parent, {recursive: true});
  const root = await mkdtemp(path.join(parent, 'orchestration-postgres-'));
  const keys = ['REVIEW_POSTGRES_HOST', 'REVIEW_POSTGRES_PORT', 'REVIEW_POSTGRES_PASSWORD_FILE', 'REVIEW_POSTGRES_PASSWORD', 'REVIEW_POSTGRES_USER'];
  const original = Object.fromEntries(keys.map(key => [key, process.env[key]]));
  let pg, repo;
  t.after(async () => {await repo?.close(); await pg?.cleanup(); await rm(root, {recursive: true, force: true}); for (const key of keys) if (original[key] === undefined) delete process.env[key]; else process.env[key] = original[key];});
  pg = await sharedStoryPostgres(root); const profile = blankProfile({title: 'Isolated orchestration protocol test'});
  repo = await createInstanceRepository({root, instanceId: profile.instanceId, backend: 'postgres', database: pg.database, profile});
  await repo.writeTransaction(tx => tx.publishRelease({...blankSnapshot(profile), expectedReleaseId: null, sourceRevisionIds: []}));
  const epoch = (await repo.getMetadata()).runtimeEpoch;
  const write = (command, args = {}, actor, requestId = randomUUID()) => repo.writeTransaction(tx => writeOrchestration(tx, {schemaVersion: '1.0', runtimeEpoch: epoch, requestId, command, actor, args}));
  const token = () => randomUUID() + randomUUID();
  const attached = await write('attach', {entryId: 'main-pg', capabilityToken: token()}), main = {kind: 'MAIN', ...attached.main};
  await write('activate', {projectRoot: root, authorization: {source: 'Isolated test only', scope: 'fixture only', automaticCompletion: true}}, main);
  const opened = await write('scheduler-open', {schedulerId: 'scheduler-pg', capabilityToken: token()}, main), scheduler = {kind: 'SCHEDULER', ...opened.scheduler};
  const submit = kind => write('submit', {kind, title: 'Fixture', goal: 'Protocol validation', scope: 'fixture only', acceptance: [{id: 'exact', text: 'Exact observed fixture bytes'}], inputs: []}, main);
  const claim = (kind, taskId) => write('claim', {kind, taskId, workerId: randomUUID(), capabilityToken: token()}, scheduler);
  const artifact = {ref: 'fixture:revision-one', sha256: 'a'.repeat(64)};
  for (const kind of ['CREATIVE', 'DEVELOP']) for (let index = 0; index < 3; index++) {
    const submitted = await submit(kind), acquired = await claim(kind, submitted.task.id);
    const actor = {kind: 'WORKER', id: acquired.run.workerId, token: acquired.run.token};
    const args = {runId: acquired.run.id, result: {status: 'SUBMITTED', summary: 'Fixture produced', artifacts: [artifact]}}, requestId = randomUUID();
    const first = await write('report', args, actor, requestId); assert.deepEqual(await write('report', args, actor, requestId), first);
  }
  await Promise.all(['CREATIVE', 'DEVELOP'].flatMap(kind => Array.from({length: 6}, () => submit(kind))));
  const attempts = await Promise.all(WORKER_KINDS.flatMap(kind => Array.from({length: 6}, () => claim(kind))));
  assert.equal(attempts.filter(Boolean).length, 12);
  const status = await repo.readTransaction(readOrchestration);
  for (const kind of WORKER_KINDS) assert.equal(status.counts[kind].running, 3);
  assert.equal(new Set(status.runs.map(run => run.taskId)).size, 12);
  assert.doesNotMatch(JSON.stringify(status), /tokenHash|capabilityToken|"token"/);
  assert.equal(includedNamespace('aux:assistant-orchestration'), false, 'private orchestration records never enter business Git exports');
  const before = await repo.getMetadata();
  await assert.rejects(write('scale', {concurrency: {CREATIVE: -1}}, main), {code: 'ORCHESTRATION_INVALID'});
  assert.deepEqual(await repo.getMetadata(), before, 'invalid mutation rolls back the whole PostgreSQL transaction');
  const events = await repo.readTransaction(tx => readOrchestration(tx, {query: 'events', limit: 500}));
  assert.ok(events.events.length > 30); assert.equal(events.events.at(-1).sequence, status.lastEventSeq);
});
