import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{createRequire}from'node:module';import{execFileSync}from'node:child_process';
const root=process.cwd(),require=createRequire(path.join(root,'package.json')),ts=require('typescript'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const pgSource=read('host/instance-runtime/postgres.mjs'),fileSource=read('host/instance-runtime/archive-file.mjs'),transferSource=read('scripts/instance-transfer.mjs');
const {validateArchive,createArchiveStreamValidator,encodeArchiveRow}=await import(pathToFileURL(path.join(root,'host/instance-runtime/postgres.mjs')));
const {hashArchiveRows,ARCHIVE_FILE_FORMAT}=await import(pathToFileURL(path.join(root,'host/instance-runtime/archive-file.mjs')));
const {MAX_DECLARED_ARCHIVE_BYTES}=await import(pathToFileURL(path.join(root,'host/instance-runtime/archive-stream-validation.mjs')));
const {DEFAULT_ARCHIVE_MAX_ROW_BYTES}=await import(pathToFileURL(path.join(root,'host/instance-runtime/archive-file-reader.mjs')));
const {canonicalJson,sha256}=await import(pathToFileURL(path.join(root,'host/instance-runtime/bytes.mjs')));
const {canonicalSha256}=await import(pathToFileURL(path.join(root,'host/instance-runtime/archive-integrity.mjs')));
const {BUSINESS_TABLES}=await import(pathToFileURL(path.join(root,'host/instance-runtime/postgres-schema.mjs')));
const {SCHEMA_VERSION,APPLICATION_ID}=await import(pathToFileURL(path.join(root,'host/instance-runtime/schema.mjs')));
const {retirementManifestFromArchive,retirementManifestFromFrozenRows}=await import(pathToFileURL(path.join(root,'host/instance-runtime/media-retirement-transfer.mjs')));
const {RETIREMENT_NAMESPACES:NS,manifestHash,targetSetHash}=await import(pathToFileURL(path.join(root,'host/instance-runtime/media-retirement.mjs')));
const ast=(file,source)=>ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
const nodeText=(file,source,name)=>{const a=ast(file,source),node=a.statements.find(n=>(ts.isFunctionDeclaration(n)||ts.isClassDeclaration(n))&&n.name?.text===name);assert(node,name);return node.getText(a).replace(/^export /,'');};
const initializer=(source,name)=>{const a=ast('source.mjs',source);for(const s of a.statements)if(ts.isVariableStatement(s))for(const d of s.declarationList.declarations)if(d.name.getText(a)===name)return d.initializer.getText(a);throw Error(name);};
const ensure=(ok,code,message)=>{if(!ok)throw Object.assign(Error(message),{code});},number=value=>{const n=Number(value);ensure(Number.isSafeInteger(n),'INTEGER_RANGE','Invalid number');return n;};
const archiveRowOrder=Function('return '+initializer(pgSource,'archiveRowOrder'))(),retirementNamespaces=new Set(Object.values(NS).map(n=>'aux:'+n));
const PgUnit=Function('ensure','number','encodeArchiveRow','BUSINESS_TABLES','archiveRowOrder','SCHEMA_VERSION','APPLICATION_ID','createArchiveStreamValidator','hashArchiveRows','retirementNamespaces','canonicalSha256','canonicalJson','ARCHIVE_FILE_FORMAT','MAX_DECLARED_ARCHIVE_BYTES','DEFAULT_ARCHIVE_MAX_ROW_BYTES',nodeText('postgres.mjs',pgSource,'PgUnit')+';return PgUnit;')(ensure,number,encodeArchiveRow,BUSINESS_TABLES,archiveRowOrder,SCHEMA_VERSION,APPLICATION_ID,createArchiveStreamValidator,hashArchiveRows,retirementNamespaces,canonicalSha256,canonicalJson,ARCHIVE_FILE_FORMAT,MAX_DECLARED_ARCHIVE_BYTES,DEFAULT_ARCHIVE_MAX_ROW_BYTES);
const header=()=>({schemaVersion:SCHEMA_VERSION,applicationId:APPLICATION_ID,instanceId:'fixture',sequence:[{name:'domain_events',seq:1}],mediaIncluded:false});
const recordBytes=Buffer.from('{"profile":"source"}'),snapshotBytes=Buffer.from('{"snapshotId":"snapshot"}'),eventBytes=Buffer.from('{"eventId":"event","eventKind":"TEST","idempotencyKeyHash":"key"}');
function rawFixture(){const tables=Object.fromEntries(BUSINESS_TABLES.map(t=>[t,[]]));tables.repository_meta=[{singleton:1,instance_id:'fixture',runtime_epoch:'epoch',repository_revision:3,current_release_id:'release',created_at:'date'}];tables.record_revisions=[{namespace:'settings',record_key:'profile',revision_id:'r1',revision_number:1,previous_revision_id:null,content_bytes:recordBytes,content_sha256:sha256(recordBytes)}];tables.record_heads=[{namespace:'settings',record_key:'profile',revision_id:'r1'}];tables.releases=[{release_id:'release',snapshot_id:'snapshot',snapshot_bytes:snapshotBytes,snapshot_sha256:sha256(snapshotBytes),recipes_bytes:snapshotBytes,recipes_sha256:sha256(snapshotBytes),profile_revision_id:'r1',source_revision_ids_json:'["r1"]'}];tables.domain_events=[{storage_sequence:1,event_id:'event',event_kind:'TEST',event_bytes:eventBytes,event_sha256:sha256(eventBytes),idempotency_key_hash:'key',original_sequence:null}];tables.media_versions=[{media_id:'m1',version_id:'v1',byte_size:0,relative_path:null,availability:'MISSING_HISTORY',sha256:'a'.repeat(64),metadata_json:'{}',created_at:'date'}];tables.media_aliases=[{alias:'中文\n"\\🙂',media_id:'m1',version_id:'v1'}];return tables;}
const encodeTables=tables=>Object.fromEntries(Object.entries(tables).map(([name,rows])=>[name,rows.map(encodeArchiveRow)]));
function archive(tables){const body={...header(),tables:encodeTables(tables)};return{...body,exportSha256:canonicalSha256(body)};}
function validateStream(value,{reverseTables=false,reverseRows=false}={}){const names=Object.keys(value.tables),validator=createArchiveStreamValidator(value,names,'fixture');for(const table of reverseTables?names.reverse():names.sort()){for(const row of reverseRows?[...value.tables[table]].reverse():value.tables[table])validator.accept(table,row);validator.finishTable(table);}validator.finish();}
const mutations={
 'record SHA':t=>{t.record_revisions[0].content_sha256='0'.repeat(64);},'revision gap':t=>{t.record_revisions[0].revision_number=2;},'previous ref':t=>{t.record_revisions[0].previous_revision_id='missing';},
 'missing head':t=>{t.record_heads=[];},'duplicate head':t=>{t.record_heads.push({...t.record_heads[0]});},'wrong head':t=>{t.record_heads[0].revision_id='missing';},'extra head':t=>{t.record_heads.push({namespace:'missing',record_key:'missing',revision_id:'missing'});},
 'event SHA':t=>{t.domain_events[0].event_sha256='0'.repeat(64);},'event ID':t=>{t.domain_events[0].event_id='other';},'event kind':t=>{t.domain_events[0].event_kind='other';},'event idempotency':t=>{t.domain_events[0].idempotency_key_hash='other';},
 'snapshot SHA':t=>{t.releases[0].snapshot_sha256='0'.repeat(64);},'recipe SHA':t=>{t.releases[0].recipes_sha256='0'.repeat(64);},'snapshot pair':t=>{const b=Buffer.from('{"snapshotId":"other"}');t.releases[0].recipes_bytes=b;t.releases[0].recipes_sha256=sha256(b);},'profile ref':t=>{t.releases[0].profile_revision_id='missing';},'source ref':t=>{t.releases[0].source_revision_ids_json='["missing"]';},
 'missing meta':t=>{t.repository_meta=[];},'duplicate meta':t=>{t.repository_meta.push({...t.repository_meta[0]});},'wrong meta':t=>{t.repository_meta[0].instance_id='other';},
};
test('stream validator equals original validateArchive rejection semantics, including canonical heads-first ordering',()=>{
 const good=archive(rawFixture());validateArchive(good,'fixture');validateStream(good);validateStream(good,{reverseTables:true,reverseRows:true});
 const multi=rawFixture();multi.record_revisions.push({...multi.record_revisions[0],revision_id:'r2',revision_number:2,previous_revision_id:'r1'});multi.record_heads[0].revision_id='r2';const m=archive(multi);validateArchive(m,'fixture');validateStream(m,{reverseRows:true});
 for(const [name,mutate]of Object.entries(mutations)){const raw=rawFixture();mutate(raw);const value=archive(raw);assert.throws(()=>validateArchive(value,'fixture'),undefined,name);assert.throws(()=>validateStream(value),undefined,name);}
 for(const mutate of[v=>{v.schemaVersion=-1;},v=>{v.applicationId=-1;},v=>{v.instanceId='other';},v=>{delete v.tables.releases;},v=>{v.tables.extra=[];},v=>{v.tables.record_revisions[0].content_bytes.bytes+='!';}]){const v=archive(rawFixture());mutate(v);const{exportSha256,...body}=v;v.exportSha256=canonicalSha256(body);assert.throws(()=>validateArchive(v,'fixture'));assert.throws(()=>validateStream(v));}
 const incomplete=createArchiveStreamValidator(header(),BUSINESS_TABLES,'fixture');assert.throws(()=>incomplete.finish(),/incomplete/);incomplete.finishTable('releases');assert.throws(()=>incomplete.finishTable('releases'),/repeated/);assert.throws(()=>incomplete.accept('releases',{}),/closed/);
});
function cloneRow(row){return Object.fromEntries(Object.entries(row).map(([k,v])=>[k,Buffer.isBuffer(v)?Buffer.from(v):v]));}
function fakeUnit(tables,{readActive=()=>true,failureSql=null,doubleFetch=false}={}){let cursor=null,index=0;const log=[];const client={async query(sql){assert(readActive(),'Iterator escaped read transaction');log.push(sql);if(sql===failureSql)throw Error('query failure '+sql);if(sql.startsWith('SELECT * FROM repository_meta'))return{rows:tables.repository_meta.map(cloneRow)};if(/^SELECT \* FROM [a-z_]+ ORDER BY/.test(sql))return{rows:tables[sql.match(/FROM ([a-z_]+)/)[1]].map(cloneRow)};if(sql.startsWith('SELECT COALESCE(max(storage_sequence)'))return{rows:[{n:1}]};if(sql.startsWith('DECLARE review_archive_rows')){assert.equal(cursor,null);cursor=sql.match(/FROM ([a-z_]+)/)[1];index=0;return{rows:[]};}if(sql==='FETCH FORWARD 1 FROM review_archive_rows'){const rows=tables[cursor],values=[];for(let n=0;n<(doubleFetch?2:1)&&index<rows.length;n++)values.push(cloneRow(rows[index++]));return{rows:values};}if(sql==='CLOSE review_archive_rows'){cursor=null;return{rows:[]};}throw Error('unexpected SQL '+sql);}};return{unit:new PgUnit(client,{instanceId:'fixture'},false),log};}
function memoryFile({collect=true,writeFailure=false,closeFailure=false,partial=false}={}){let bytes=0,closed=false;const hash=createHash('sha256'),chunks=[];return{async write(content,offset,length){if(writeFailure)throw Error('write failure');const n=partial?Math.min(13,length):length,piece=content.subarray(offset,offset+n);hash.update(piece);bytes+=n;if(collect)chunks.push(Buffer.from(piece));return{bytesWritten:n};},async sync(){},async close(){closed=true;if(closeFailure)throw Error('file close failure');},proof(){return{bytes,sha256:hash.digest('hex'),closed,...(collect?{content:Buffer.concat(chunks)}:{})};}};}
function fileFunctions(open){const bindings={open,canonicalJson,createHash,ARCHIVE_FILE_FORMAT};const code=['hashArchiveRows','writeArchiveRowsFile','writeArchiveFile'].map(name=>nodeText('archive-file.mjs',fileSource,name)).join('\n');return Function(...Object.keys(bindings),code+';return{writeArchiveRowsFile,writeArchiveFile};')(...Object.values(bindings));}
test('actual PG cursor and writer preserve original export/file hashes in two read-only passes',async()=>{
 const tables=rawFixture();tables.media_versions[0].byte_size='9007199254740991';const {unit,log}=fakeUnit(tables),plan=await unit.scanValidatedArchive(),original=await unit.exportState();assert.equal(plan.exportSha256,original.exportSha256);assert.deepEqual(original.tables,encodeTables(tables));assert.equal(plan.frozenRetirement.tables.record_revisions.length,0);assert.equal(plan.frozenRetirement.tables.record_heads.length,0);
 const output=memoryFile({partial:true}),f=fileFunctions(async()=>output);const result=await f.writeArchiveRowsFile('/synthetic',{...plan,iterate:t=>unit.iterateArchiveRows(t)}),observed=output.proof();const reference=memoryFile();await fileFunctions(async()=>reference).writeArchiveFile('/synthetic',original);assert.deepEqual(observed.content,reference.proof().content);assert.equal(result.sha256,observed.sha256);assert.equal(result.bytes,observed.bytes);assert.equal(log.filter(s=>s.startsWith('DECLARE')).length,16);assert(log.every(s=>!/^INSERT|^UPDATE|^DELETE/.test(s)));
 unit.writable=true;await assert.rejects(unit.scanValidatedArchive(),/read-only/);
 const wrongMeta=fakeUnit(rawFixture());const saved=wrongMeta.unit.meta.bind(wrongMeta.unit);wrongMeta.unit.meta=async()=>({...await saved(),current_release_id:'changed'});await assert.rejects(wrongMeta.unit.scanValidatedArchive(),/metadata changed/);
});
test('two-pass drift, iterator cancellation, query/CLOSE and physical write failures never complete an archive',async()=>{
 const tables=rawFixture(),{unit}=fakeUnit(tables),plan=await unit.scanValidatedArchive();tables.media_aliases.push({alias:'changed',media_id:'m1',version_id:'v1'});const file=memoryFile();await assert.rejects(fileFunctions(async()=>file).writeArchiveRowsFile('/synthetic',{...plan,iterate:t=>unit.iterateArchiveRows(t)}),/changed between/);assert(!file.proof().content.toString().includes('"end":true'));
 const stopped=fakeUnit(rawFixture());for await(const row of stopped.unit.iterateArchiveRows('record_revisions')){assert(row);break;}assert.equal(stopped.log.at(-1),'CLOSE review_archive_rows');
 for(const failureSql of['FETCH FORWARD 1 FROM review_archive_rows','CLOSE review_archive_rows']){const r=fakeUnit(rawFixture(),{failureSql});await assert.rejects(r.unit.scanValidatedArchive(),/query failure/);assert.equal(r.log.at(-1),'CLOSE review_archive_rows');}
 const doubled=rawFixture();doubled.repository_meta.push({...doubled.repository_meta[0]});await assert.rejects(fakeUnit(doubled,{doubleFetch:true}).unit.scanValidatedArchive(),/exceeded one row/);
 for(const options of[{writeFailure:true},{closeFailure:true}]){const u=fakeUnit(rawFixture()).unit,p=await u.scanValidatedArchive(),bad=memoryFile(options);await assert.rejects(fileFunctions(async()=>bad).writeArchiveRowsFile('/synthetic',{...p,iterate:t=>u.iterateArchiveRows(t)}),/failure/);assert(bad.proof().closed);}
 const injection=fakeUnit(rawFixture());await assert.rejects(async()=>{for await(const _ of injection.unit.iterateArchiveRows('releases;DELETE')){};},/Unknown archive table/);assert.equal(injection.log.length,0);
});
const retirementTest=read('tests/media-retirement-transfer.test.mjs'),prelude=retirementTest.slice(retirementTest.indexOf('const canonical ='),retirementTest.indexOf("test('ACTIVE"));
const {fixture:retirementFixture,seal}=Function('createHash','manifestHash','targetSetHash','NS','retirementManifestFromArchive',prelude.replaceAll("'unit-instance'","'fixture'")+';return{fixture,seal};')(createHash,manifestHash,targetSetHash,NS,retirementManifestFromArchive);
const subset=a=>({instanceId:a.instanceId,tables:{repository_meta:a.tables.repository_meta,record_revisions:a.tables.record_revisions.filter(r=>retirementNamespaces.has(r.namespace)),record_heads:a.tables.record_heads.filter(r=>retirementNamespaces.has(r.namespace)),media_versions:a.tables.media_versions,media_aliases:a.tables.media_aliases}});
test('frozen retirement rows retain original nine success/failure cases, without a fake archive hash or live AUX',async()=>{
 const result=async input=>{try{return{value:await input()};}catch(e){return{code:e.code,message:e.message};}};
 for(const phase of['ACTIVE','QUARANTINED','PURGED','QUARANTINE_INTENT','PURGE_INTENT','RESULT_UNKNOWN']){const a=retirementFixture(phase,true);assert.deepEqual(await result(()=>retirementManifestFromFrozenRows(subset(a))),await result(()=>retirementManifestFromArchive(a)));}
 for(const mutate of[a=>{a.tables.record_heads.pop();},a=>{a.tables.record_revisions.at(-1).deleted=1;},a=>{a.tables.media_aliases.push({...a.tables.media_aliases[0],alias:'extra'});}]){const a=retirementFixture('PURGED');mutate(a);seal(a);await assert.rejects(retirementManifestFromArchive(a));await assert.rejects(retirementManifestFromFrozenRows(subset(a)));}
});
test('actual backup function holds one snapshot for both passes and keeps the media lease through copy/manifest; pending opens nothing',async()=>{
 for(const pending of[false,true]){
  const live=rawFixture(),evidence=retirementFixture(pending?'PURGE_INTENT':'QUARANTINED');for(const row of evidence.tables.record_revisions)live.record_revisions.push({...row,content_bytes:Buffer.from(row.content_bytes.bytes,'base64')});live.record_heads.push(...evidence.tables.record_heads);live.media_versions=evidence.tables.media_versions;live.media_aliases=evidence.tables.media_aliases;let readActive=false,lease=false,transactions=0,targets=0,opens=0,copies=0,manifest=null;
  const repo={async withMediaReadLease(fn){lease=true;try{return await fn();}finally{lease=false;}},async readTransaction(fn){assert(lease);transactions++;readActive=true;const snapshot=Object.fromEntries(Object.entries(live).map(([table,rows])=>[table,rows.map(cloneRow)])),{unit}=fakeUnit(snapshot,{readActive:()=>readActive});try{return await fn(unit);}finally{readActive=false;}},async close(){},async listAux(){assert.fail('live AUX');},async listMedia(){assert.fail('live media');},async exportState(){assert.fail('whole archive');}};
  const f=fileFunctions(async()=>{assert(readActive&&lease);opens++;return memoryFile({collect:false});});
  const bindings={resolveInstance:()=>({backend:'postgres',instanceId:'fixture',root:'/synthetic'}),process:{env:{REVIEW_DATABASE_BACKEND:'postgres'}},openInstanceRepository:async()=>repo,retirementManifestFromFrozenRows,writeArchiveRowsFile:f.writeArchiveRowsFile,newTarget:async()=>{assert(readActive&&lease);targets++;live.media_aliases.push({alias:'concurrent-live-alias',media_id:'other',version_id:'other'});return'/synthetic/output';},mkdir:async()=>{},copyVerified:async()=>{assert(lease&&!readActive);copies++;},path,writeFile:async(_p,bytes)=>{assert(lease&&!readActive);manifest=JSON.parse(bytes);},sha256,canonicalJson};
  const backup=Function(...Object.keys(bindings),nodeText('transfer.mjs',transferSource,'backupPostgresInstance')+';return backupPostgresInstance;')(...Object.values(bindings));
  if(pending){await assert.rejects(backup('/synthetic','/synthetic/output'),{code:'RETIREMENT_RESULT_UNKNOWN'});assert.equal(targets,0);assert.equal(opens,0);assert.equal(copies,0);assert.equal(manifest,null);}else{const r=await backup('/synthetic','/synthetic/output');assert.equal(r.status,'BACKUP_VERIFIED');assert.equal(transactions,1);assert.equal(targets,1);assert.equal(opens,1);assert.equal(copies,1);assert.equal(manifest.mediaRetirement.retired[0].state,'QUARANTINED');assert.equal(manifest.database.format,ARCHIVE_FILE_FORMAT);}assert(!lease&&!readActive);
 }
});

test('backup capacity counts exact UTF-8 NDJSON header, every row and end with inclusive boundaries',async()=>{
 assert.equal(MAX_DECLARED_ARCHIVE_BYTES,16*1024**3);assert.equal(DEFAULT_ARCHIVE_MAX_ROW_BYTES,128*1024**2);
 const unit=fakeUnit(rawFixture()).unit,scan=await unit.scanValidatedArchive(),file=memoryFile();await fileFunctions(async()=>file).writeArchiveFile('/synthetic',await unit.exportState());const bytes=file.proof().content,lines=bytes.toString('utf8').trimEnd().split('\n');
 assert.equal(scan.archiveBytes,bytes.length);const maximumRow=Math.max(...lines.slice(1,-1).map(line=>Buffer.byteLength(line))),limits={maxBytes:bytes.length,maxRowBytes:maximumRow,maxRows:scan.rows};
 assert.equal((await fakeUnit(rawFixture()).unit.scanValidatedArchive(limits)).archiveBytes,bytes.length);
 for(const input of[{maxBytes:bytes.length-1},{maxRowBytes:maximumRow-1},{maxRows:scan.rows-1},{maxRowBytes:Buffer.byteLength(lines[0])-1}])await assert.rejects(fakeUnit(rawFixture()).unit.scanValidatedArchive(input),{code:'ARCHIVE_LIMIT'});
 for(const input of[{maxBytes:MAX_DECLARED_ARCHIVE_BYTES+1},{maxRowBytes:DEFAULT_ARCHIVE_MAX_ROW_BYTES+1},{maxRows:1000001},{maxRows:0},{maxBytes:NaN}]){const f=fakeUnit(rawFixture());await assert.rejects(f.unit.scanValidatedArchive(input),{code:'ARCHIVE_LIMIT'});assert.equal(f.log.length,0);}
});
test('actual backup rejects capacity before target creation and refuses inconsistent writer bytes before manifest',async()=>{
 const normal=await fakeUnit(rawFixture()).unit.scanValidatedArchive();
 const initial=memoryFile();await fileFunctions(async()=>initial).writeArchiveFile('/synthetic',archive(rawFixture()));const lines=initial.proof().content.toString('utf8').trimEnd().split('\n'),maximumRow=Math.max(...lines.slice(1,-1).map(line=>Buffer.byteLength(line)));
 const cases=[{maxBytes:Buffer.byteLength(lines[0])},{maxBytes:normal.archiveBytes-1},{maxRowBytes:maximumRow-1},{maxRows:normal.rows-1},'writer-size-mismatch',{maxBytes:normal.archiveBytes,maxRowBytes:maximumRow,maxRows:normal.rows}];
 for(const limits of cases){
  let active=false,lease=false,targets=0,opens=0,copies=0,manifest=null;const {unit,log}=fakeUnit(rawFixture(),{readActive:()=>active}),original=unit.scanValidatedArchive.bind(unit);unit.scanValidatedArchive=()=>original(typeof limits==='object'?limits:{});
  const repo={async withMediaReadLease(fn){lease=true;try{return await fn();}finally{lease=false;}},async readTransaction(fn){assert(lease);active=true;try{return await fn(unit);}finally{active=false;}},async close(){}};
  const writer=fileFunctions(async()=>{assert(active&&lease);opens++;return memoryFile({collect:false});}).writeArchiveRowsFile;
  const bindings={resolveInstance:()=>({backend:'postgres',instanceId:'fixture',root:'/synthetic'}),process:{env:{REVIEW_DATABASE_BACKEND:'postgres'}},openInstanceRepository:async()=>repo,retirementManifestFromFrozenRows,writeArchiveRowsFile:async(...args)=>{const result=await writer(...args);return limits==='writer-size-mismatch'?{...result,bytes:result.bytes+1}:result;},newTarget:async()=>{assert(active&&lease);targets++;return'/synthetic/output';},mkdir:async()=>{},copyVerified:async()=>{copies++;},path,writeFile:async(_p,bytes)=>{assert(lease&&!active);manifest=JSON.parse(bytes);},sha256,canonicalJson};
  const backup=Function(...Object.keys(bindings),nodeText('transfer.mjs',transferSource,'backupPostgresInstance')+';return backupPostgresInstance;')(...Object.values(bindings));
  if(limits===cases.at(-1)){assert.equal((await backup('/synthetic','/synthetic/output')).status,'BACKUP_VERIFIED');assert.equal(targets,1);assert.equal(opens,1);assert.equal(manifest.database.bytes,normal.archiveBytes);}
  else if(limits==='writer-size-mismatch'){await assert.rejects(backup('/synthetic','/synthetic/output'),/physical size changed/);assert.equal(targets,1);assert.equal(opens,1);assert.equal(copies,0);assert.equal(manifest,null);}
  else{await assert.rejects(backup('/synthetic','/synthetic/output'),{code:'ARCHIVE_LIMIT'});assert.equal(targets,0);assert.equal(opens,0);assert.equal(copies,0);assert.equal(manifest,null);}
  if(log.some(sql=>sql.startsWith('DECLARE')))assert.equal(log.at(-1),'CLOSE review_archive_rows');assert(!active&&!lease);
 }
});
test('new RESTORE instructions use streaming commands without a heap override',()=>{
 const source=read('scripts/instance-git-export.mjs'),text=Function('return '+initializer(source,'RESTORE_TEXT'))();assert(!text.includes('--max-old-space-size'));assert(text.includes('有界逐行通路'));assert(text.includes('node scripts/instance-git-export.mjs verify'));assert(text.includes('node scripts/instance-git-export.mjs restore'));
});

async function largeStreamTestMain(){
 const fs=await import('node:fs'),{createHash}=await import('node:crypto'),v=JSON.parse(fs.readFileSync(0,'utf8'));
 const ensure=(ok,code,message)=>{if(!ok)throw Error(code+': '+message);},number=value=>{const n=Number(value);ensure(Number.isSafeInteger(n),'INTEGER_RANGE','Invalid number');return n;},sha256=b=>createHash('sha256').update(b).digest('hex'),parse=b=>JSON.parse(Buffer.from(b).toString('utf8'));
 const canonicalJson=Function(v.canonicalJson+';return canonicalJson;')(),canonicalSha256=Function('createHash',v.canonicalSha256+';return canonicalSha256;')(createHash);
 const {BUSINESS_TABLES,SCHEMA_VERSION,APPLICATION_ID,ARCHIVE_FILE_FORMAT,archiveRowOrder,namespaceValues,MAX_DECLARED_ARCHIVE_BYTES,DEFAULT_ARCHIVE_MAX_ROW_BYTES}=v,retirementNamespaces=new Set(namespaceValues);
 const make=(code,bindings,result)=>Function(...Object.keys(bindings),code+';return '+result+';')(...Object.values(bindings));
 const encodeArchiveRow=make(v.encodeArchiveRow,{number},'encodeArchiveRow');
 const createArchiveStreamValidator=make(v.validator,{ensure,canonicalJson,sha256,parse,SCHEMA_VERSION,APPLICATION_ID,BUSINESS_TABLES},'createArchiveStreamValidator');
 const hashArchiveRows=make(v.hashRows,{canonicalJson,createHash},'hashArchiveRows');
 const PgUnit=make(v.pgUnit,{ensure,number,encodeArchiveRow,BUSINESS_TABLES,archiveRowOrder,SCHEMA_VERSION,APPLICATION_ID,createArchiveStreamValidator,hashArchiveRows,retirementNamespaces,canonicalJson,ARCHIVE_FILE_FORMAT,MAX_DECLARED_ARCHIVE_BYTES,DEFAULT_ARCHIVE_MAX_ROW_BYTES},'PgUnit');
 const rawFixture=make(v.rawFixture,{BUSINESS_TABLES,recordBytes:Buffer.from('{"profile":"source"}'),snapshotBytes:Buffer.from('{"snapshotId":"snapshot"}'),eventBytes:Buffer.from('{"eventId":"event","eventKind":"TEST","idempotencyKeyHash":"key"}'),sha256},'rawFixture');
 const tables=rawFixture(),count=70,payloadBytes=24*1024*1024;tables.repository_meta[0].current_release_id='release_00000';tables.releases=new Array(count);let peakRss=process.memoryUsage().rss;
 for(let i=0;i<count;i++)Object.defineProperty(tables.releases,i,{enumerable:true,get(){const body=Buffer.from(JSON.stringify({snapshotId:'snapshot',padding:String.fromCharCode(65+i%26).repeat(payloadBytes)}));peakRss=Math.max(peakRss,process.memoryUsage().rss);return{release_id:'release_'+String(i).padStart(5,'0'),snapshot_id:'snapshot',snapshot_bytes:body,snapshot_sha256:sha256(body),recipes_bytes:Buffer.from('{"snapshotId":"snapshot"}'),recipes_sha256:sha256(Buffer.from('{"snapshotId":"snapshot"}')),profile_revision_id:'r1',source_revision_ids_json:'["r1"]'};}});
 let cursor=null,index=0,fetches=0;const client={async query(sql){if(sql.startsWith('SELECT * FROM repository_meta'))return{rows:tables.repository_meta};if(sql.startsWith('SELECT COALESCE(max(storage_sequence)'))return{rows:[{n:1}]};if(sql.startsWith('DECLARE')){ensure(cursor===null,'CURSOR','cursor leak');cursor=sql.match(/FROM ([a-z_]+)/)[1];index=0;return{rows:[]};}if(sql==='FETCH FORWARD 1 FROM review_archive_rows'){fetches++;const row=tables[cursor][index++];peakRss=Math.max(peakRss,process.memoryUsage().rss);return{rows:row?[row]:[]};}if(sql==='CLOSE review_archive_rows'){cursor=null;return{rows:[]};}throw Error('unexpected SQL');}};
 const unit=new PgUnit(client,{instanceId:'fixture'},false),plan=await unit.scanValidatedArchive();
 ensure(plan.frozenRetirement.tables.record_revisions.length===0,'RETIREMENT','unrelated settings body retained');ensure(!('releases'in plan.frozenRetirement.tables),'RETIREMENT','release bodies retained');
 const expectedTables={};for(const table of BUSINESS_TABLES){expectedTables[table]=new Array(tables[table].length);for(let i=0;i<tables[table].length;i++)Object.defineProperty(expectedTables[table],i,{enumerable:true,get:()=>encodeArchiveRow(tables[table][i])});}
 const body={...plan.header,tables:expectedTables},exportSha256=canonicalSha256(body);ensure(plan.exportSha256===exportSha256,'HASH','Original export SHA differs');
 function output(){const hash=createHash('sha256');let bytes=0;return{async write(b,o,n){hash.update(b.subarray(o,o+n));bytes+=n;peakRss=Math.max(peakRss,process.memoryUsage().rss);return{bytesWritten:n};},async close(){},async sync(){},getBytes:()=>bytes};}
 const binding={canonicalJson,createHash,ARCHIVE_FILE_FORMAT,hashArchiveRows},current=output(),write=make(v.writeRows,{...binding,open:async()=>current},'writeArchiveRowsFile'),proof=await write('/no-real-file',{...plan,iterate:t=>unit.iterateArchiveRows(t)});
 const legacy=output(),oldWrite=make(v.oldWrite,{...binding,open:async()=>legacy},'writeArchiveFile'),reference=await oldWrite('/no-real-file',{...body,exportSha256});
 ensure(proof.sha256===reference.sha256&&proof.bytes===reference.bytes,'FILE','Original NDJSON bytes/hash differ');ensure(proof.bytes>2166029427,'SCALE','Below real failure scale');ensure(peakRss<1200*1024*1024,'MEMORY','Unbounded RSS');
 console.log(JSON.stringify({status:'PASS',archiveBytes:proof.bytes,exportSha256,ndjsonSha256:proof.sha256,releaseRows:count,rows:plan.rows,cursorFetches:fetches,peakRssObservedBytes:peakRss,jsHeapMiB:384,wholeArchiveMaterializations:0,realFiles:0,databaseConnections:0,modelCalls:0}));
}
test('over 2 GB complete scan/validator/two-pass writer matches original export and NDJSON under 384 MiB heap',{timeout:120000},()=>{
 const source={canonicalJson:nodeText('bytes.mjs',read('host/instance-runtime/bytes.mjs'),'canonicalJson'),canonicalSha256:nodeText('integrity.mjs',read('host/instance-runtime/archive-integrity.mjs'),'canonicalSha256'),encodeArchiveRow:nodeText('postgres.mjs',pgSource,'encodeArchiveRow'),validator:nodeText('postgres.mjs',pgSource,'createArchiveStreamValidator'),hashRows:nodeText('archive.mjs',fileSource,'hashArchiveRows'),pgUnit:nodeText('postgres.mjs',pgSource,'PgUnit'),rawFixture:rawFixture.toString(),writeRows:nodeText('archive.mjs',fileSource,'writeArchiveRowsFile'),oldWrite:nodeText('archive.mjs',fileSource,'writeArchiveFile'),BUSINESS_TABLES,SCHEMA_VERSION,APPLICATION_ID,ARCHIVE_FILE_FORMAT,archiveRowOrder,namespaceValues:[...retirementNamespaces],MAX_DECLARED_ARCHIVE_BYTES,DEFAULT_ARCHIVE_MAX_ROW_BYTES};
 const out=execFileSync(process.execPath,['--max-old-space-size=384','-e','('+largeStreamTestMain.toString()+')().catch(e=>{console.error(e);process.exitCode=1;})'],{input:JSON.stringify(source),encoding:'utf8',timeout:115000,maxBuffer:32000,env:{PATH:process.env.PATH}});const result=JSON.parse(out);assert.equal(result.status,'PASS');assert(result.archiveBytes>2166029427);console.log(JSON.stringify(result));
});
