import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';

// Actual current source functions; no live instance, copied product code or mocked selector.
const file=new URL('../app/production-workbench.tsx',import.meta.url),source=readFileSync(file,'utf8');
const ast=ts.createSourceFile(file.pathname,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const one=name=>{const nodes=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.equal(nodes.length,1,name);return nodes[0];};
const names=['historicalFocusForProductionContext','productionPackagesInNavigationScope','fullProductionPackagesForGate','fullProductionPackagesForStep','fullProductionCurrentShotIds','formalCurrentShotSpecIds','fullProductionCurrentP07ShotIds','gateForStep','productionGates'];
const declarations=names.map(name=>one(name).getText(ast));
const profile={exports:{}};
new Function('module','exports',ts.transpileModule(readFileSync(new URL('../app/instance-profile.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(profile,profile.exports);
const compiled={exports:{}};
new Function('module','exports','projectIdFor',ts.transpileModule(declarations.join('\n'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(compiled,compiled.exports,profile.exports.projectIdFor);
const {historicalFocusForProductionContext:focus,fullProductionCurrentShotIds:current,productionPackagesInNavigationScope:packages,formalCurrentShotSpecIds:formal,fullProductionCurrentP07ShotIds:p07}=compiled.exports;
function fixture(){
 const history={id:'S14-SH01',sceneId:'S14',episodeId:'E02',title:'历史标题',scopeRole:'HISTORICAL',activityRole:'HISTORICAL_EVIDENCE',activeInCurrentProduction:false,workPackageRefs:['old-package']};
 const modern={id:'shot-current',sceneId:'permanent-scene',episodeUid:'permanent-episode',scopeRole:'CURRENT',activeInCurrentProduction:true,shotPlanSetRevisionId:'current-plan'};
 const gate={id:'SHOT_LOCK',phaseId:'SHOT_FINISH',scopeType:'SHOT',legacyStepIds:[]};
 const model={instance:{projectId:'project-permanent'},shots:[history,modern],counts:{currentP07ShotPlans:0},workItems:[],reviewContexts:[],productionGates:[gate],workPackages:[{id:'current-package',gateId:'SHOT_LOCK',phaseId:'SHOT_FINISH',scopeType:'SHOT',scopeId:modern.id,stepId:'CUSTOM',activeInCurrentProduction:true,applicabilityState:'REQUIRED',shotIds:[modern.id]},{id:'old-package',gateId:'SHOT_LOCK',phaseId:'SHOT_FINISH',scopeType:'SHOT',scopeId:history.id,stepId:'CUSTOM',activeInCurrentProduction:false,applicabilityState:'NOT_REQUIRED',shotIds:[history.id]}]};
 return {model,history,modern,gate,context:{shotId:history.id,workPackageId:'HISTORICAL_ONLY:'+history.id}};
}
test('precise immutable historical marker returns only the same existing historical record',()=>{const {model,history,context}=fixture(),before=JSON.stringify(model);assert.equal(focus(model,context),history);assert.equal(JSON.stringify(model),before);});
test('no marker, another marker, missing identity and a display/title alias all fail closed',()=>{const {model,context}=fixture();for(const c of [{...context,workPackageId:''},{...context,workPackageId:'old-package'},{...context,workPackageId:'HISTORICAL_ONLY:S14-SH02'},{...context,shotId:''},{shotId:'UNKNOWN',workPackageId:'HISTORICAL_ONLY:UNKNOWN'},{shotId:'历史标题',workPackageId:'HISTORICAL_ONLY:历史标题'},{shotId:'s14-sh01',workPackageId:'HISTORICAL_ONLY:s14-sh01'}])assert.equal(focus(model,c),null);});
test('duplicate permanent history IDs never choose the first matching record',()=>{const {model,history,context}=fixture();model.shots.push({...history,sceneId:'different-scene'});assert.equal(focus(model,context),null);});
test('proposal, unknown or contradictory historical flags are not treated as retired evidence',()=>{for(const change of [{scopeRole:'CURRENT'},{scopeRole:'PROPOSAL'},{scopeRole:'UNKNOWN'},{scopeRole:undefined},{activityRole:'CURRENT_PRODUCTION'},{activityRole:undefined},{activeInCurrentProduction:true},{activeInCurrentProduction:undefined}]){const {model,history,context}=fixture();Object.assign(history,change);assert.equal(focus(model,context),null);}});
test('current formal and current storyboard identity cannot be relabeled as history',()=>{const {model,modern,context}=fixture();assert.equal(focus(model,{shotId:modern.id,workPackageId:'HISTORICAL_ONLY:'+modern.id}),null);model.counts.currentP07ShotPlans=1;model.workItems.push({id:'conflicting-p07',workflowStepId:'W02',pipelineStageCode:'P07',shotId:context.shotId,reviewContextRef:'rc'});model.reviewContexts.push({id:'rc',scopeType:'SHOT',scopeId:context.shotId,binding:{bindingStatus:'CURRENT'}});assert.equal(focus(model,context),null);});
test('revealing evidence leaves current shot IDs, packages and all production counts unchanged',()=>{const {model,context,gate}=fixture();const state=()=>({current:[...current(model)],formal:[...formal(model)],p07:[...p07(model)],packages:packages(model,gate,{navigationScopeType:'SCENE',sceneId:'permanent-scene'}).map(p=>p.id),counts:model.counts});const before=structuredClone(state());assert.equal(focus(model,context)?.id,'S14-SH01');assert.deepEqual(state(),before);assert.deepEqual(before.current,['shot-current']);assert.deepEqual(before.packages,['current-package']);});
test('workbench wires the helper only to the read-only historical card, never active scopes or anchors',()=>{const ready=one('FullProductionWorkbenchReady');const vars=new Map();function visit(node){if(ts.isVariableDeclaration(node)&&ts.isIdentifier(node.name))vars.set(node.name.text,node.initializer?.getText(ast));ts.forEachChild(node,visit);}visit(ready);assert.equal(vars.get('legacyFocus'),'historicalFocusForProductionContext(model, context)');assert.match(vars.get('sceneShots'),/currentShotIds\.has\(record\.id\)/);assert.match(vars.get('contextShot'),/^sceneShots\.find/);for(const key of ['packages','activePackage','anchorShot','target'])assert.doesNotMatch(vars.get(key),/legacyFocus|historicalFocusForProductionContext/);const cards=[];function find(node){if(ts.isJsxSelfClosingElement(node)&&node.tagName.getText(ast)==='FullProductionHistoricalFocusEvidence')cards.push(node);ts.forEachChild(node,find);}find(ready);assert.equal(cards.length,1);assert.match(cards[0].getText(ast),/shot=\{legacyFocus\}/);});
test('actual evidence component contains no links, buttons, handlers or formal review/execution child components',()=>{const card=one('FullProductionHistoricalFocusEvidence'),tags=[],attrs=[];function visit(node){if(ts.isJsxOpeningElement(node)||ts.isJsxSelfClosingElement(node)){tags.push(node.tagName.getText(ast));for(const a of node.attributes.properties){assert(ts.isJsxAttribute(a),'No spread props into evidence card');attrs.push(a.name.getText(ast));}}ts.forEachChild(node,visit);}visit(card);assert(tags.every(tag=>['aside','header','small','h3','p','dl','div','dt','dd'].includes(tag)));assert(attrs.every(name=>!/^on[A-Z]/.test(name)&&!['href','action','formAction','dangerouslySetInnerHTML'].includes(name)));assert.match(card.getText(ast),/data-historical-shot-id=\{shot\.id\}/);assert.match(card.getText(ast),/仅作证据，不可生成、审阅或计入完成率/);});
