import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {chromium} from '@playwright/test';
import {requiredPhase} from '../tools/process-resources.mjs';
assert.ok(await requiredPhase(process.cwd()));
const base=process.env.REVIEW_UI_BASE||'http://127.0.0.1:3916';
const output=process.env.REVIEW_UI_ARTIFACT_DIR||process.env.REVIEW_TASK_DIR;
mkdirSync(output,{recursive:true});
const path='/api/v1/workspaces/domain-workspaces?owner=SETTINGS';
const read=()=>fetch(base+path).then(r=>{assert.equal(r.status,200);return r.json()});
const data=await read(),subjects=data.graph.entities.filter(e=>e.type!=='LOCATION');
const versions=data.materialGraph.versions,families=data.materialGraph.families;
const reps=data.graph.representations;
const current=rep=>rep.assetFamilyIds.map(id=>families.find(f=>f.id===id)).map(f=>versions.find(v=>v.id===f?.currentVersionRef)).find(Boolean);
const rep=reps.find(r=>current(r)?.preview&&current(r)?.mediaKind==='IMAGE'&&data.graph.relations.some(e=>e.from.id===r.entityId||e.to.id===r.entityId)&&subjects.some(e=>e.id===r.entityId));
assert.ok(rep,'actual entity with relationship and image material required');
const entity=subjects.find(e=>e.id===rep.entityId);
const expected=subjects.map(e=>e.id).sort(),errors=[],writes=[];
const browser=await chromium.launch({channel:'chrome'});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/'))writes.push(r.url());});
 await page.goto(base+'/?view=settings',{waitUntil:'networkidle'});
 const board=page.getByRole('region',{name:'主体与关联关系',exact:true}),all=()=>board.locator('[data-canvas-node-id]').evaluateAll(ns=>ns.map(n=>n.dataset.canvasNodeId).sort());
 assert.deepEqual(await all(),expected);
 for(const name of ['登记主体','登记关系','编辑此项'])assert.equal(await page.getByRole('button',{name,exact:true}).count(),0);
 assert.equal(await board.locator('[data-canvas-edge]').count(),0);
 assert.ok((await board.locator('[data-canvas-node-id]').first().evaluate(n=>n.offsetWidth))<200);
 await page.screenshot({path:output+'/after-desktop.png'});
 const search=page.getByRole('textbox',{name:'搜索设定与关系'});await search.fill(entity.name);await search.fill('');assert.deepEqual(await all(),expected);
 const node=board.locator('[data-canvas-node-id="'+entity.id+'"]');await node.evaluate(n=>n.click());
 const adjacent=data.graph.relations.filter(e=>!e.historicalOnly&&e.from.kind==='ENTITY'&&e.to.kind==='ENTITY'&&(e.from.id===entity.id||e.to.id===entity.id)&&expected.includes(e.from.id)&&expected.includes(e.to.id));
 assert.equal(await board.locator('[data-canvas-edge]').count(),adjacent.length);
 const bounds=await board.locator('[data-canvas-node-id]').evaluateAll(ns=>({top:Math.min(...ns.map(n=>Number(n.dataset.canvasNodeY))),bottom:Math.max(...ns.map(n=>Number(n.dataset.canvasNodeY)+n.offsetHeight))}));
 const labelYs=await board.locator('[data-canvas-edge]').evaluateAll(ns=>ns.map(n=>parseFloat(n.style.top)));
 assert.ok(labelYs.every(y=>y<bounds.bottom+440&&y>bounds.top-440),'labels remain near graph');
 await page.getByRole('checkbox',{name:'只看选中主体及相邻主体'}).check();
 assert.deepEqual(await all(),[...new Set([entity.id,...adjacent.flatMap(e=>[e.from.id,e.to.id])])].sort());
 const viewport=page.getByRole('group',{name:'主体与关联关系画板',exact:true});await viewport.focus();const x=await viewport.getAttribute('data-canvas-x');await viewport.press('ArrowRight');assert.notEqual(await viewport.getAttribute('data-canvas-x'),x);const scale=await viewport.getAttribute('data-canvas-scale');await page.getByRole('button',{name:'放大画板',exact:true}).click();assert.notEqual(await viewport.getAttribute('data-canvas-scale'),scale);await viewport.press('Home');
 await page.screenshot({path:output+'/after-neighborhood.png'});
 await page.getByRole('button',{name:'打开 '+entity.name+' 档案',exact:true}).click();
 const dialog=page.getByRole('dialog'),local=dialog.getByRole('region',{name:'主体与素材局部关系',exact:true});await local.waitFor();
 assert.equal(await dialog.getByRole('button',{name:'编辑此项',exact:true}).count(),0);
 for(const name of ['状态与制作条件','关联素材表现','关联素材需求'])assert.equal(await dialog.getByRole('heading',{name,exact:true}).count(),0);
 const trace=dialog.locator('details').filter({has:page.getByText('追溯信息 · 来源、身份与适用修订',{exact:true})});assert.equal(await trace.getAttribute('open'),null);await trace.locator('summary').click();assert.ok((await trace.innerText()).includes(entity.id));assert.ok((await trace.innerText()).includes(data.ownership['entities:'+entity.id].revisionId));await trace.locator('summary').click();
 const material=local.locator('[data-canvas-node-id="rep:'+rep.id+'"]');await material.evaluate(n=>n.click());const detail=dialog.getByRole('region',{name:'素材要求与版本',exact:true});await detail.waitFor();assert.ok((await detail.innerText()).includes('当前采用：'));assert.equal(new URL(page.url()).searchParams.get('settingsEntity'),entity.id);
 const img=material.locator('img');assert.equal(await img.count(),1);await img.evaluate(img=>new Promise((resolve,reject)=>{if(img.complete)return img.naturalWidth?resolve():reject(Error('image missing'));img.onload=resolve;img.onerror=reject;}));
 assert.equal(await dialog.getByRole('textbox',{name:'实体修改意见',exact:true}).count(),1);
 await page.screenshot({path:output+'/after-detail.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:output+'/after-narrow.png'});
 assert.ok(await dialog.evaluate(d=>d.getBoundingClientRect().width<=window.innerWidth));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 const localViewport=local.getByRole('group',{name:'关联主体与素材画板',exact:true});await localViewport.focus();const oldX=await localViewport.getAttribute('data-canvas-x');await localViewport.press('ArrowLeft');assert.notEqual(await localViewport.getAttribute('data-canvas-x'),oldX);
 await dialog.getByRole('button',{name:'关闭对象详情',exact:true}).click();await page.getByRole('checkbox',{name:'只看选中主体及相邻主体'}).uncheck();assert.deepEqual(await all(),expected);
 await page.getByRole('tab',{name:'空间设定',exact:true}).click();assert.equal(await page.getByRole('button',{name:/登记地点/}).count(),0);
 // Controlled read projection validates honest missing-media fallback without mutating the fixture.
 const missing=structuredClone(data);const v=missing.materialGraph.versions.find(v=>v.id===current(rep).id);v.outputState='MISSING';v.preview=null;
 await page.route('**/api/v1/workspaces/domain-workspaces?owner=SETTINGS',r=>r.fulfill({json:missing}));
 await page.goto(base+'/?view=settings&settingsEntity='+encodeURIComponent(entity.id),{waitUntil:'networkidle'});
 const missingNode=page.getByRole('dialog').locator('[data-canvas-node-id="rep:'+rep.id+'"]');assert.ok((await missingNode.innerText()).includes('媒体缺失'));assert.equal(await missingNode.locator('img').count(),0);
 assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);const after=await read();assert.equal(after.revisionId,data.revisionId);assert.deepEqual(after.graph,data.graph);
 console.log(JSON.stringify({status:'PASS',subjects:subjects.length,entity:entity.id,adjacent:adjacent.length,checks:['full set','compact nodes','entry removal','search','neighbor filter','bounded labels','keyboard and zoom','real thumbnail','inline requirements','collapsed trace','comment preserved','narrow','missing media','zero business POST','unchanged graph']}));
}finally{await browser.close();}
