import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';

const site=fileURLToPath(new URL('../',import.meta.url));
const basis=[{bindingType:'MATERIAL_REQUIREMENT_SET',bindingId:'requirements:letter',bindingHash:'a'.repeat(64)},{bindingType:'SCENE_COVERAGE_REVISION',bindingId:'coverage:letter',bindingHash:'b'.repeat(64)}];
const oldShot={shotId:'scene:letter-SH01',sceneId:'scene:letter',order:1,title:'迟疑后打开信',coverageBeatRefs:['scene:letter-B01'],visualIntent:'人和信同框',actionIntent:'打开信',soundIntent:'纸声',dialogueContext:'无对白',narrativeBeat:'得到消息',audienceTakeaway:'来信改变决定',materialRequirementRefs:['MATREQ-LETTER'],inputBindings:basis};
const plan={canAuthor:true,basisBindings:basis,template:{planId:'SHOT-PLAN:letter',revisionHash:'c'.repeat(64),content:{sceneId:'scene:letter',identityChangeReason:'NO_IDENTITY_CHANGE',shots:[oldShot]}}};
async function fixture(page:Page,{conflict=false,unknown=false,readOnly=false,delayRead=false,delayPost=false,invalidReceipt=false}={}){
 const writes:Record<string,unknown>[]=[],errors:string[]=[],unexpected:string[]=[];let resume=()=>{};const pending=new Promise<void>(resolve=>{resume=resolve;});
 page.on('pageerror',error=>errors.push(error.message));
 const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{ShotDesignEditor,ShotDesignSummary}from'./app/shot-design-editor';const plan=${JSON.stringify(plan)};const frozen=JSON.stringify(plan);function App(){return <main style={{maxWidth:1000,margin:'auto',padding:20}}><ShotDesignSummary/><ShotDesignEditor plan={plan} coverage={{beats:[{beatId:'scene:letter-B01',narrativeBeat:'获得消息',materialRequirementRefs:['MATREQ-LETTER']}]}} sceneId="scene:letter" snapshotId="snapshot:letter" readOnly={${readOnly}} onSaved={()=>{document.getElementById('result').textContent=JSON.stringify({sourceUnchanged:frozen===JSON.stringify(plan),saved:true})}}/><output id="result"/></main>}createRoot(document.getElementById('root')).render(<App/>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:site,sourcefile:'shot-editor-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-shot-editor',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles;
 const js=files.find(file=>file.path.endsWith('.js'))!.text,css=files.filter(file=>file.path.endsWith('.css')).map(file=>file.text).join('\n');
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname==='/api/v8/operations/snapshot'&&request.method()==='GET'){if(delayRead)await pending;return route.fulfill({json:{snapshotId:'snapshot:letter',mutationEtag:'"editor-cas"'}});}if(url.pathname==='/api/v8/creative-revisions'&&request.method()==='POST'){expect(request.headers()['if-match']).toBe('"editor-cas"');writes.push(request.postDataJSON());if(delayPost)await pending;if(invalidReceipt)return route.fulfill({json:{creativeRevisionId:''}});if(unknown)return route.abort('failed');return route.fulfill({status:conflict?409:201,json:conflict?{error:'baseRevisionHash is stale'}:{creativeRevisionId:'candidate:design'}});}unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,json:{error:'UNEXPECTED'}});});
 await page.route('**/__shot-design-editor',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="root"></div><script>${js.replaceAll('</script','<\/script')}</script></body></html>`}));
 await page.goto('/__shot-design-editor');return {writes,errors,unexpected,resume};
}
test('old plan reads as missing structured data, explicit edit registers V3 without rewriting its source',async({page})=>{
 const f=await fixture(page);await expect(page.getByText('此版本尚未登记结构化镜头规格，设计估时和关键帧策略待确认。')).toBeVisible();
 await page.getByRole('button',{name:'编辑新镜头设计候选'}).click();await page.getByRole('combobox',{name:'景别',exact:true}).selectOption('MEDIUM');await page.getByRole('spinbutton',{name:'设计估时（秒，留空为待确认）',exact:true}).fill('5.2');await page.getByRole('combobox',{name:'关键帧策略',exact:true}).selectOption('START_ONLY');await page.getByRole('textbox',{name:'关键帧策略依据',exact:true}).fill('固定机位只需单首帧');
 await page.getByRole('button',{name:'登记镜头设计候选'}).click();await expect(page.locator('#result')).toContainText('"sourceUnchanged":true');expect(f.writes).toHaveLength(1);
 const request=f.writes[0] as {planningContractVersion:string;content:{shots:Array<Record<string,unknown>>}};expect(request.planningContractVersion).toBe('3.0');expect(request.content.shots[0]).toMatchObject({shotId:oldShot.shotId,inputBindings:basis,design:{estimatedDurationSeconds:5.2,keyframeStrategy:{mode:'START_ONLY',intermediateFrameCount:0},continuity:{previousShotId:null,nextShotId:null}}});expect(request.content.shots[0]).not.toHaveProperty('durationStatus');expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);
});
test('CAS conflict keeps edited fields without retrying',async({page})=>{
 const f=await fixture(page,{conflict:true});await page.getByRole('button',{name:'编辑新镜头设计候选'}).click();await page.getByRole('textbox',{name:'镜头标题',exact:true}).fill('保留这次修改');await page.getByRole('button',{name:'登记镜头设计候选'}).click();await expect(page.getByRole('region',{name:'结构化镜头设计编辑'}).getByRole('status')).toContainText('baseRevisionHash is stale');await expect(page.getByRole('textbox',{name:'镜头标题',exact:true})).toHaveValue('保留这次修改');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('unknown write outcome disables retries until the current candidate is checked',async({page})=>{
 const f=await fixture(page,{unknown:true});await page.getByRole('button',{name:'编辑新镜头设计候选'}).click();await page.getByRole('textbox',{name:'镜头标题',exact:true}).fill('等待结果核查');await page.getByRole('button',{name:'登记镜头设计候选'}).click();await expect(page.getByRole('region',{name:'结构化镜头设计编辑'}).getByRole('status')).toContainText('请先核查当前候选');await expect(page.getByRole('button',{name:'登记镜头设计候选'})).toBeDisabled();await expect(page.getByRole('textbox',{name:'镜头标题',exact:true})).toHaveValue('等待结果核查');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('read-only structured design cannot open a candidate editor',async({page})=>{
 const f=await fixture(page,{readOnly:true});await expect(page.getByText('此版本尚未登记结构化镜头规格，设计估时和关键帧策略待确认。')).toBeVisible();await expect(page.getByRole('button',{name:'编辑新镜头设计候选'})).toHaveCount(0);expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);
});

for(const stage of ['read','post'])test(`saving blocks all authoring controls while ${stage} is pending`,async({page})=>{
 const f=await fixture(page,{delayRead:stage==='read',delayPost:stage==='post'});await page.getByRole('button',{name:'编辑新镜头设计候选'}).click();await page.getByRole('textbox',{name:'镜头标题',exact:true}).fill('准确提交的内容');await page.getByRole('button',{name:'登记镜头设计候选'}).click();await expect(page.getByRole('textbox',{name:'镜头标题',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'增加镜头',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'移除本镜',exact:true})).toBeDisabled();await expect(page.getByRole('textbox',{name:'镜头增删或身份变更理由',exact:true})).toBeDisabled();f.resume();await expect(page.locator('#result')).toContainText('"saved":true');expect((f.writes[0].content as {shots:Array<{title:string}>}).shots[0].title).toBe('准确提交的内容');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('empty success receipt preserves pending authoring and cannot be retried',async({page})=>{const f=await fixture(page,{invalidReceipt:true});await page.getByRole('button',{name:'编辑新镜头设计候选'}).click();await page.getByRole('button',{name:'登记镜头设计候选'}).click();await expect(page.getByRole('region',{name:'结构化镜头设计编辑'}).getByRole('status')).toContainText('候选登记回执不完整');await expect(page.getByRole('button',{name:'登记镜头设计候选'})).toBeDisabled();expect(f.writes).toHaveLength(1);await expect(page.locator('#result')).toBeEmpty();});
