import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
async function fixture(page:Page,{conflict=false,unknown=false,readOnly=false,invalidResponse=''}={}){
 const writes:Array<Record<string,unknown>>=[],errors:string[]=[],unexpected:string[]=[];let draft:{revisionId:string;content:unknown}|null=null;
 const inputs=[{order:1,path:'media/adopted/master.png',assetFamilyRef:'MASTER',assetVersionRef:'MASTER@V1',sha256:'a'.repeat(64)}],output={expectedOutputId:'EXPECTED',familyId:'OUTPUT',path:'media/_review_pending/output/V001.png'};
 const entry=`import React from'react';import{createRoot}from'react-dom/client';import{ShotProductionRecipeEditor}from'./app/shot-production-recipe-editor';createRoot(document.getElementById('root')).render(<ShotProductionRecipeEditor workItemId="SP-WI-letter" readOnly={${readOnly}}/>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'recipe-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-recipe',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname==='/api/v8/operations/snapshot'&&request.method()==='GET')return route.fulfill({json:{mutationEtag:'"recipe-etag"'}});if(url.pathname==='/api/instance/shot-production/recipes'){if(request.method()==='GET')return route.fulfill({json:{releaseId:'RELEASE',draftHeadRevisionId:draft?.revisionId||null,draft,current:null,defaults:{model:'',prompt:'',negativePrompt:'',parameters:{width:1920,height:1080}},inputs,output,readOnly:false,blockers:[]}});const body=request.postDataJSON();writes.push(body);expect(request.headers()['if-match']).toBe('"recipe-etag"');expect(body.requestId).toBe(request.headers()['idempotency-key']);if(unknown)return route.abort('failed');if(invalidResponse==='5xx')return route.fulfill({status:503,json:{error:'提交后连接中断'}});if(invalidResponse==='html')return route.fulfill({status:200,contentType:'text/html',body:'<p>gateway</p>'});if(invalidResponse==='missing')return route.fulfill({json:{message:'ok'}});if(conflict)return route.fulfill({status:409,json:{error:'发布依据已变化'}});if(body.action==='save'){draft={revisionId:'DRAFT-1',content:body.content};return route.fulfill({json:{revisionId:'DRAFT-1'}});}if(body.action==='preview')return route.fulfill({json:{previewHash:'PREVIEW-EXACT',definition:{model:draft?.content,upload:{items:inputs},output}}});if(body.action==='publish')return route.fulfill({json:{jobId:'JOB-1',status:'QUEUED'}});}unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,json:{error:'unexpected'}});});
 await page.route('**/__production-recipe',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>${css}</style></head><body><div id="root"></div><script>${js}</script></body></html>`}));await page.goto('/__production-recipe');return{writes,errors,unexpected};
}
async function author(page:Page){await page.getByRole('button',{name:'编写本工作项调用包'}).click();await page.getByRole('textbox',{name:'模型ID',exact:true}).fill('image-model');await page.getByRole('textbox',{name:'完整主提示词',exact:true}).fill('使用母版人物，在桌边迟疑并拿起信封。');await page.getByRole('textbox',{name:'完整负面提示词',exact:true}).fill('避免身份、服装与桌面道具漂移。');}
test('call-package author only writes four content fields and publishes the reviewed exact preview without model authorization',async({page})=>{
 const f=await fixture(page);await author(page);await expect(page.getByText('media/adopted/master.png',{exact:true})).toBeVisible();await page.getByRole('button',{name:'保存调用包草稿'}).click();await expect(page.getByRole('button',{name:'预览完整调用包'})).toBeEnabled();
 expect(f.writes[0]).toMatchObject({action:'save',workItemId:'SP-WI-letter',expectedReleaseId:'RELEASE',expectedDraftRevisionId:null,content:{model:'image-model',prompt:'使用母版人物，在桌边迟疑并拿起信封。',negativePrompt:'避免身份、服装与桌面道具漂移。',parameters:{width:1920,height:1080}}});expect(Object.keys(f.writes[0].content as object).sort()).toEqual(['model','negativePrompt','parameters','prompt']);
 await page.getByRole('button',{name:'预览完整调用包'}).click();await expect(page.getByRole('heading',{name:'待登记调用包'})).toBeVisible();await page.getByRole('button',{name:'确认登记调用包'}).click();await expect(page.getByText(/调用包登记任务已排队/)).toBeVisible();expect(f.writes[2]).toMatchObject({action:'publish',draftRevisionId:'DRAFT-1',previewHash:'PREVIEW-EXACT'});expect(f.writes.map(w=>w.action)).toEqual(['save','preview','publish']);expect(f.unexpected).toEqual([]);expect(f.errors).toEqual([]);
});
test('known CAS conflict preserves author text and does not retry',async({page})=>{
 const f=await fixture(page,{conflict:true});await author(page);await page.getByRole('button',{name:'保存调用包草稿'}).click();await expect(page.getByRole('status')).toContainText('发布依据已变化');await expect(page.getByRole('textbox',{name:'完整主提示词',exact:true})).toHaveValue('使用母版人物，在桌边迟疑并拿起信封。');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('unknown write result requires a read and keeps author text during that check',async({page})=>{
 const f=await fixture(page,{unknown:true});await author(page);await page.getByRole('button',{name:'保存调用包草稿'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('button',{name:'保存调用包草稿'})).toBeDisabled();await page.getByRole('button',{name:'重读调用包与任务'}).click();await expect(page.getByRole('status')).toContainText('本次编辑仍保留');await expect(page.getByRole('textbox',{name:'完整主提示词',exact:true})).toHaveValue('使用母版人物，在桌边迟疑并拿起信封。');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);
});
test('read-only output has no recipe authoring action',async({page})=>{const f=await fixture(page,{readOnly:true});await expect(page.getByRole('button')).toHaveCount(0);expect(f.writes).toEqual([]);expect(f.unexpected).toEqual([]);});
for(const invalidResponse of ['5xx','html','missing'])test(`recipe ${invalidResponse} receipt remains unknown until reread without losing text`,async({page})=>{
 const f=await fixture(page,{invalidResponse});await author(page);await page.getByRole('button',{name:'保存调用包草稿'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('button',{name:'保存调用包草稿'})).toBeDisabled();await expect(page.getByRole('textbox',{name:'完整主提示词',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重读调用包与任务'}).click();await expect(page.getByRole('status')).toContainText('本次编辑仍保留');await expect(page.getByRole('textbox',{name:'完整主提示词',exact:true})).toHaveValue('使用母版人物，在桌边迟疑并拿起信封。');await expect(page.getByRole('button',{name:'保存调用包草稿'})).toBeEnabled();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);
});
