import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('../',import.meta.url)),image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lS8AAAAASUVORK5CYII=','base64'),sha=createHash('sha256').update(image).digest('hex');
function template(){return {snapshotId:'S1',required:true,requiresJointReview:true,evidence:{schemaVersion:'1.0',kind:'KEYFRAME',productionPlanId:'PLAN',productionRevisionId:'REV',shotId:'SHOT',timingHash:'a'.repeat(64),visualHash:'b'.repeat(64),overlayHash:'c'.repeat(64),boundaryHash:'d'.repeat(64),strategyHash:'e'.repeat(64),members:[{workItemId:'WORK',slot:'main',familyId:'FAMILY',versionId:'IMAGE-V1',sha256:sha}],observedImageIds:[],jointFindings:{}},requiredObservedImageIds:['IMAGE-V1'],requiredObservedVideoIds:[],observationMedia:[{versionId:'IMAGE-V1',familyId:'FAMILY',sha256:sha,kind:'IMAGE'}]};}
async function fixture(page:Page,{stale=false,missing=false}={}){
 const errors:string[]=[],writes:string[]=[];let reads=0;page.on('pageerror',e=>errors.push(e.message));
 const entry=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{useShotProductionEvidence,ShotProductionEvidencePanel}from'./app/shot-production-review-evidence';function App(){const[value,setValue]=useState(),[revision,setRevision]=useState(0);const state=useShotProductionEvidence({required:true,workItemId:'WORK',versionId:'IMAGE-V1',snapshotId:'S1',revisionKey:String(revision),value,onChange:setValue});return <main><button onClick={()=>setRevision(n=>n+1)}>重新读取当前闭包</button><output data-testid="ready">{String(state.ready)}</output><pre data-testid="payload">{JSON.stringify(value)}</pre>{state.error&&<p role="alert">{state.error}</p>}{state.template&&<ShotProductionEvidencePanel template={state.template} evidence={value} onChange={setValue} disabled={false}/>}</main>}createRoot(document.getElementById('root')).render(<App/>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'evidence-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-evidence',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(request.method()!=='GET'){writes.push(request.url());return route.fulfill({status:418,body:'forbidden'});}if(url.pathname==='/api/v8/ui/shot-production-review-evidence'){expect(url.searchParams.get('versionId')).toBe('IMAGE-V1');const body=template();if(stale)body.snapshotId='OLD';if(++reads>1)body.evidence.timingHash='f'.repeat(64);return route.fulfill({json:body});}if(url.pathname.startsWith('/api/v8/media/'))return route.fulfill(missing?{status:404,body:'missing'}:{contentType:'image/png',body:image});return route.fulfill({status:418,body:'unknown'});});
 await page.route('**/__production-evidence',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>${css}</style></head><body><div id="root"></div><script>${js}</script></body></html>`}));await page.goto('/__production-evidence');return{errors,writes};
}
test('joint review requires explicit image observation, PASS and notes, and rebinding clears only the evidence closure',async({page})=>{
 const f=await fixture(page),checkbox=page.getByRole('checkbox',{name:'我已观察这张精确版本原图'});await expect(checkbox).toBeEnabled();await expect(checkbox).not.toBeChecked();await expect(page.getByTestId('ready')).toHaveText('false');await checkbox.check();
 for(const name of ['首尾及中间状态连续性','构图、身份与美术一致性']){const group=page.getByRole('group',{name});await group.getByRole('combobox').selectOption('PASS');await group.getByRole('textbox').fill('已核对同一人物、服装及桌面状态。');}
 await expect(page.getByTestId('ready')).toHaveText('true');await expect(page.getByTestId('payload')).toContainText('"observedImageIds":["IMAGE-V1"]');
 await page.getByRole('button',{name:'重新读取当前闭包'}).click();await expect(page.getByTestId('payload')).toContainText('"timingHash":"'+'f'.repeat(64)+'"');await expect(checkbox).not.toBeChecked();await expect(page.getByTestId('ready')).toHaveText('false');expect(f.errors).toEqual([]);expect(f.writes).toEqual([]);
});
test('missing original cannot be confirmed as observed',async({page})=>{
 const f=await fixture(page,{missing:true});await expect(page.getByRole('alert')).toContainText('原件无法加载');await expect(page.getByRole('checkbox')).toBeDisabled();await expect(page.getByTestId('ready')).toHaveText('false');expect(f.errors).toEqual([]);expect(f.writes).toEqual([]);
});
test('stale template does not expose a ready or prefabricated review',async({page})=>{
 const f=await fixture(page,{stale:true});await expect(page.getByRole('alert')).toContainText('当前验收依据已变化');await expect(page.getByTestId('ready')).toHaveText('false');await expect(page.getByRole('checkbox')).toHaveCount(0);expect(f.errors).toEqual([]);expect(f.writes).toEqual([]);
});
