import {productionHash,resolveShotProductionScope,defaultShotProductionPlan,validateShotProductionPlan,compileShotProductionPlan,shotProductionReadiness} from '../host/instance-runtime/shot-production-model.mjs';

const sceneId='SCENE-letter',episodeUid='EPUID-letter';
export function fixture(){
 const content={sceneId,identityChangeReason:'初次镜头设计',shots:[1,2].map(i=>({shotId:`${sceneId}-SH0${i}`,sceneId,order:i,title:`镜头${i}`,narrativeBeat:'拿信后产生迟疑',audienceTakeaway:'来信改变决定',materialRequirementRefs:[`MATREQ-${i}`,'VOICE-REQ']}))};
 const plan={id:'DESIGN-r1',episodeUid,episodeNarrativeReleaseId:'RELEASE-r1',scopeId:sceneId,scopeRole:'CURRENT',sourceOperationId:'SYNC-1',sourceSyncState:'SUCCEEDED',content,contentHash:productionHash(content)};
 const model={shotPlanSetRevisions:[plan],episodeNarrativeReleases:[{id:'RELEASE-r1',episodeUid,scopeRole:'CURRENT',sourceSyncState:'SOURCE_CURRENT',reviewInput:{scenes:[{id:sceneId,contentHash:productionHash('script')} ]}}],sceneScriptRevisions:[{id:'SCRIPT-r1',sceneId,scopeRole:'CURRENT',episodeNarrativeReleaseId:'RELEASE-r1',contentHash:productionHash('script')}],scopeLocks:[{id:'LOCK-design',scopeType:'SCENE',scopeId:sceneId,lockPurpose:'SHOT_PLAN_SET',lockState:'LOCKED',denominatorState:'KNOWN',shotPlanSetRevisionId:plan.id,shotPlanSetRevisionHash:plan.contentHash,shotIds:content.shots.map(s=>s.shotId)}],shots:content.shots.map(s=>({...s,id:s.shotId,scopeRole:'CURRENT',activeInCurrentProduction:true,shotPlanSetRevisionId:plan.id,shotPlanSetRevisionHash:plan.contentHash})),materialRequirements:[1,2].map(i=>({id:`MATREQ-${i}`,requirementClass:'REQUIRED',assetFamilyRefs:[`BASE-${i}`]}))};
 const scope=resolveShotProductionScope(model,sceneId),settings=defaultShotProductionPlan(scope,{schemaVersion:'1.0'});
 settings.shots.forEach((s,i)=>Object.assign(s,{keyframeStrategy:{mode:i===0?'START_ONLY':'MULTI_KEYFRAME',reason:'动作状态明确',intermediateFrameCount:i===0?0:1},dialogueLines:[{id:`LINE-${i+1}`,text:'这是给我的？',speakerEntityId:'ENTITY-girl',purpose:'FINAL',performance:'迟疑后低声问'}],inputs:[{requirementId:`MATREQ-${i+1}`,familyId:`BASE-${i+1}`,versionId:`BASE-${i+1}@V1`,sha256:productionHash(`base-${i+1}`),purpose:'REFERENCE'}],space:{loc:'ROOM',state:'NIGHT',zone:'TABLE',camera:'CAMERA-A',freeze:'FREEZE-r1'},handles:{headFrames:8,tailFrames:12},videoBranch:'POST_LIP'}));
 const mapHash=productionHash('spatial');model.sourceHashes={productionMapSha256:mapHash};model.spatialEvidence={sourceRef:'story/spatial.json',sourceSha256:mapHash,locations:[{id:'ROOM'}],locationPackages:[{id:'ROOM',zones:[{id:'TABLE'}],cameras:[{id:'CAMERA-A',zoneId:'TABLE'}]}]};model.domainGraph={entities:[{id:'ENTITY-room',type:'LOCATION'}],states:[{id:'NIGHT',entityId:'ENTITY-room',authority:'L'}],representations:[]};for(const r of model.materialRequirements){r.stateRef='NIGHT';r.entityRef='ENTITY-room';}for(const s of settings.shots)s.space.freeze=mapHash;
 model.materialRequirements.push({id:'VOICE-REQ',requirementClass:'REQUIRED',assetFamilyRefs:['VOICE-A'],requirementHash:productionHash('voice-requirement'),representationRef:'VOICE-REP'});
 model.domainGraph.entities.push({id:'ENTITY-girl',type:'CHARACTER',authority:'A'});model.domainGraph.representations.push({id:'VOICE-REP',entityId:'ENTITY-girl',type:'VOICE_IDENTITY',authority:'L',assetFamilyIds:['VOICE-A'],requirementIds:['VOICE-REQ']});model.assetFamilies=[{id:'VOICE-A',kind:'AUDIO'}];
 for(const shot of settings.shots)shot.inputs.push({requirementId:'VOICE-REQ',familyId:'VOICE-A',versionId:'VOICE-A@V1',sha256:productionHash('voice-a'),purpose:'VOICE_MASTER'});
 return {model,scope,content:validateShotProductionPlan(settings,scope)};
}
export function readyFixture(){
 const f=fixture(),{model,scope,content}=f,compiled=compileShotProductionPlan(scope,content,{id:'PRODUCTION-1',revisionId:'SOURCE-1',sourceRef:'story/production-1.json'});
 const baseFamilies=model.assetFamilies;Object.assign(model,compiled);model.assetFamilies=[...baseFamilies,...compiled.assetFamilies];model.shotProductionPlans=[{id:'PRODUCTION-1',sceneId,scopeRole:'CURRENT',sourceRevisionId:'SOURCE-1',content,contentHash:productionHash(content),workItemIds:compiled.workItems.map(w=>w.id)}];
 const state={assetFamiliesById:{},assetVersionsById:{},executionGatesByWorkItem:{},episodeNarrativeReleasesByUid:{[episodeUid]:{id:'RELEASE-r1',canFlowDownstream:true}},scopeLocksById:{'LOCK-design':model.scopeLocks[0]}};
 const register=(family,versionId,sha256)=>{state.assetFamiliesById[family.id]={...family,currentVersionId:versionId,canFlowDownstream:true};state.assetVersionsById[versionId]={id:versionId,familyId:family.id,path:`media/${versionId}`,sha256,canFlowDownstream:true};};
 for(const s of content.shots)for(const b of s.inputs)register({id:b.familyId},b.versionId,b.sha256);
 for(const w of compiled.workItems){register(compiled.assetFamilies.find(f=>f.id===w.outputAssetRef),`${w.outputAssetRef}@V1`,productionHash(w.id));if(w.deliverableKey==='SHOT_VIDEO'){w.executionDefinitionRef='CALL-'+w.id;state.executionGatesByWorkItem[w.id]=[];}}
 const shotSlices=content.shots.map(s=>({shotId:s.shotId,...Object.fromEntries(['timingHash','visualHash','overlayHash','boundaryHash'].map(key=>[key,productionHash(key+s.shotId)]))}));
 model.animaticLocks=[{sceneId,scopeRole:'CURRENT',shotPlanRevisionId:scope.plan.id,shotSlices}];
 model.shotInputLocks=[{sceneId,scopeRole:'CURRENT',productionPlanId:'PRODUCTION-1',perShotHashes:content.shots.map(s=>({shotId:s.shotId,inputHash:productionHash({shotId:s.shotId,inputs:s.inputs,space:s.space})}))}];
 model.shotKeyframeSets=content.shots.map(s=>({id:'FRAMES-'+s.shotId,productionPlanId:'PRODUCTION-1',scopeRole:'CURRENT',...shotSlices.find(row=>row.shotId===s.shotId),strategyHash:productionHash(s.keyframeStrategy),members:compiled.workItems.filter(w=>w.shotId===s.shotId&&w.gateId==='KEYFRAMES').map(w=>({workItemId:w.id,slot:w.outputSlot,familyId:w.outputAssetRef,versionId:state.assetFamiliesById[w.outputAssetRef].currentVersionId,sha256:state.assetVersionsById[state.assetFamiliesById[w.outputAssetRef].currentVersionId].sha256}))}));
 return {...f,compiled,state,read:()=>shotProductionReadiness(model,state,sceneId)};
}


export {sceneId,episodeUid};
