const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
// Real image controls, pointer handlers and startDraft; geometry/target handoff
// is checked here, while physical drag and visual positioning need Chrome.
class Element{
 constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.attrs={};this.classList={add(){},remove(){},toggle(){}};this.hidden=false;this.className=''}
 append(...nodes){for(const n of nodes){if(n.parent)n.parent.children=n.parent.children.filter(old=>old!==n);n.parent=this;this.children.push(n)}}setAttribute(k,v){this.attrs[k]=v}addEventListener(){}
 all(){return this.children.flatMap(n=>[n,...n.all()])}contains(n){return n===this||this.all().includes(n)}
 matches(s){return s==='figure'?this.tag==='figure':s==='.structure-visual-stage'?this.className===s.slice(1):this.tag===s}
 closest(s){for(let n=this;n;n=n.parent)if(n.matches(s))return n;return null}querySelector(s){return this.all().find(n=>n.matches(s))||null}
 getBoundingClientRect(){return{left:0,top:0,width:100,height:100}}setPointerCapture(){}
}
function fixture(mode='none'){
 const nodes=new Map(),events={},messages=[],storage=new Map();for(const id of ['source-view','structure-reader','production-reader','comment-panel','comments-toggle','screenplay-comments','toast'])nodes.set('#'+id,new Element('div'));
 Object.defineProperty(nodes.get('#toast'),'textContent',{set:v=>messages.push(v)});
 const ctx={console,URL,setTimeout:()=>0,clearTimeout(){},window:{addEventListener(){}},document:{addEventListener:(name,fn)=>{(events[name]??=[]).push(fn)},querySelector:s=>nodes.get(s)||null,querySelectorAll:()=>[],createElement:t=>new Element(t),createElementNS:(_ns,t)=>new Element(t)},getSelection:()=>({removeAllRanges(){}}),localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v))}};
 vm.createContext(ctx);const dir=process.env.SOURCE_REGION_STATIC||path.join(__dirname,'../review_desk/static');for(const file of ['app.js','structure.js'])vm.runInContext(fs.readFileSync(path.join(dir,file),'utf8'),ctx);
 vm.runInContext('globalThis.state=state;globalThis.target=commentTarget;globalThis.key=draftKey;hideSelectionAction=()=>{};globalThis.reviewSurface=n=>n;renderDocument=()=>{};renderComments=()=>{};renderStructureReader=()=>{};globalThis.paintProductionReview=()=>{};paintStructureRegions=()=>{};',ctx);
 const source={id:'source-old',target_revision_id:'source-exact',assets:[{file:'source.png'}]};Object.assign(ctx.state,{workspace:'story.sources',current:source,structure:mode==='none'?null:{revisions:[{id:'structure-rev',payload:{sections:[{visuals:[{id:mode==='same-id'?'source.png':'other-id',file:'structure.png'}]}]}}]},structureRevision:mode==='none'?null:'structure-rev'});
 const figure=ctx.renderStructureVisual({id:'source.png',file:'source.png',title:'Technical source'});nodes.get('#source-view').append(figure);const stage=figure.querySelector('.structure-visual-stage');
 const emit=(name,x,y,id=1)=>{for(const fn of events[name]||[])fn({target:stage,clientX:x,clientY:y,pointerId:id,shiftKey:true,preventDefault(){}})};
 const down=()=>{nodes.get(ctx.state.workspace==='story.sources'?'#source-view':ctx.state.workspace==='story.outline'?'#structure-reader':'#production-reader').append(figure);figure.all().find(n=>n.tag==='button'&&n.textContent==='圈选评论').onclick();emit('pointerdown',10,10);emit('pointermove',30,30)};
 return {ctx,nodes,messages,source,figure,stage,emit,down};
}
for(const mode of ['none','different-id','same-id'])test(`source drag uses its exact old original with ${mode} structure`,()=>{
 const f=fixture(mode);f.down();f.emit('pointerup',40,40);assert.equal(f.ctx.state.anchor.asset_file,'source.png');assert.equal(f.ctx.state.anchor.visual_id,'source.png');assert.deepEqual(JSON.parse(JSON.stringify(f.ctx.target())),{source_id:'source-old',target_revision_id:'source-exact'});
 assert.deepEqual(JSON.parse(JSON.stringify(f.ctx.state.anchor.points)),[{x:.1,y:.1},{x:.4,y:.1},{x:.4,y:.4},{x:.1,y:.4}]);assert.equal(f.ctx.state.drawMode,null);assert.equal(f.nodes.get('#comment-panel').hidden,false);
});
for(const change of ['workspace','source','revision','detached','new-draft'])test(`late source pointerup after ${change} does not replace another draft or notify its context`,()=>{
 const f=fixture('same-id');f.down();const newer={type:'global'};f.ctx.state.anchor=newer;
 if(change==='workspace')f.ctx.state.workspace='story.outline';if(change==='source')f.ctx.state.current={...f.source,id:'source-new'};if(change==='revision')f.ctx.state.current={...f.source,target_revision_id:'source-new-rev'};if(change==='detached')f.nodes.get('#source-view').children=[];if(change==='new-draft'){f.ctx.renderDocument=()=>{f.nodes.get('#source-view').children=[]};f.ctx.startDraft(newer)}
 const messages=f.messages.length;f.emit('pointerup',40,40);assert.equal(f.ctx.state.anchor,newer);assert.equal(f.ctx.state.drawMode,null);assert.equal(f.messages.length,messages);
});
test('missing or mismatched source original cannot borrow a structure image with the same id',()=>{for(const mismatch of ['missing','file']){const f=fixture('same-id');f.down();if(mismatch==='missing')f.source.assets=[];else f.figure.dataset.reviewFile='structure.png';f.emit('pointerup',40,40);assert.equal(f.ctx.state.anchor,null);assert.equal(f.ctx.state.drawMode,null);assert.match(f.messages.at(-1),/原图已不可用/)}});
test('unrelated pointer and too-small gesture keep the original geometry rules',()=>{const f=fixture();f.down();f.emit('pointerup',40,40,2);assert.equal(f.ctx.state.anchor,null);assert.equal(f.ctx.state.drawMode,'source.png');f.emit('pointerup',40,40);assert.equal(f.ctx.state.anchor.asset_file,'source.png');const tiny=fixture();tiny.figure.all().find(n=>n.textContent==='圈选评论').onclick();tiny.emit('pointerdown',10,10);tiny.emit('pointerup',10.1,10.1);assert.equal(tiny.ctx.state.anchor,null);assert.match(tiny.messages.at(-1),/圈选区域太小/)});
for(const workspace of ['story.outline','materials.workspace'])test(`${workspace} retains its original visual resolver`,()=>{const f=fixture('same-id');f.ctx.state.workspace=workspace;if(workspace==='materials.workspace'){f.ctx.state.productionSelected={object_id:'asset',id:'asset-rev'};f.ctx.productionVisuals=()=>[{id:'source.png',file:'production.png'}]}f.down();f.emit('pointerup',40,40);assert.equal(f.ctx.state.anchor.asset_file,workspace==='story.outline'?'structure.png':'production.png')});

for(const workspace of ['story.outline','materials.workspace'])for(const change of ['workspace','revision','reader','replaced-reader'])test(`${workspace} late pointerup after ${change} cannot become a new source or revision draft`,()=>{const f=fixture('same-id');f.ctx.state.workspace=workspace;if(workspace==='materials.workspace'){f.ctx.state.productionSelected={object_id:'asset',id:'asset-rev'};f.ctx.productionVisuals=()=>[{id:'source.png',file:'production.png'}]}f.down();const newer={type:'global'};f.ctx.state.anchor=newer;const oldMessages=f.messages.length;if(change==='workspace')f.ctx.state.workspace='story.sources';if(change==='revision'){if(workspace==='story.outline')f.ctx.state.structureRevision='another';else f.ctx.state.productionSelected={object_id:'asset',id:'another'}}if(change==='reader')f.nodes.get(workspace==='story.outline'?'#structure-reader':'#production-reader').children=[];if(change==='replaced-reader')f.nodes.set(workspace==='story.outline'?'#structure-reader':'#production-reader',new Element('article'));f.emit('pointerup',40,40);assert.equal(f.ctx.state.anchor,newer);assert.equal(f.ctx.state.drawMode,null);assert.equal(f.messages.length,oldMessages)});
