import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,rm,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createServer} from 'vite';
import {createInstanceRepository} from '../host/instance-runtime/index.mjs';
import {blankProfile,blankSnapshot} from '../host/instance-runtime/blank.mjs';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {initializeConfiguration} from '../host/instance-runtime/configuration-service.mjs';
import {applyProductionSpatialProjection,preserveProductionSpatialProjection} from '../host/instance-runtime/spatial-production.mjs';
import {SPATIAL_SHOT_VIEW_NS,getSpatialShotViewWorkspace,saveSpatialShotViewDraft,previewSpatialShotView,enqueueSpatialShotView,applySpatialShotViewJob,runSpatialShotViewIteration} from '../host/instance-runtime/spatial-shot-view-service.mjs';
const hash=value=>sha256(canonicalJson(value)),sceneId='scene:spatial-one';
async function fixture(t){
 const softwareRoot=fileURLToPath(new URL('..',import.meta.url));await mkdir(path.join(softwareRoot,'tests/.test-tmp'),{recursive:true});const root=await mkdtemp(path.join(softwareRoot,'tests/.test-tmp/spatial-author-')),profile=blankProfile({title:'Spatial author isolated fixture'}),dbPath=path.join(root,'data/review.sqlite'),repo=await createInstanceRepository({dbPath,instanceId:profile.instanceId,profile});
 t.after(async()=>{await repo.close();await rm(root,{recursive:true,force:true});});await repo.writeTransaction(tx=>tx.publishRelease({...blankSnapshot(profile),expectedReleaseId:null,sourceRevisionIds:[]}));await repo.writeTransaction(tx=>initializeConfiguration(tx));
 const spec={version:'1.0',locations:[{id:'ROOM-A',name:'房间A'},{id:'ROOM-B',name:'房间B'}],minimal_location_packages:Object.fromEntries(['A','B'].map(x=>['ROOM-'+x,{name:'房间'+x,fact_boundary:'原房间',lock_boundary:'原门窗保留',zones:[{id:'ZONE-'+x}],cameras:[{id:'CAM-'+x,zoneId:'ZONE-'+x,from:'原机位',looks:'北'}]}]))};
 let map;await repo.writeTransaction(async tx=>{const view=await tx.readView();map=await tx.putDocument({documentId:'spatial:map',aliases:['data/production_map_spec.json'],expectedRevisionId:null,bytes:canonicalJson(spec),metadata:{sourceRole:'MACHINE_MODEL_SOURCE'}});const snapshot=structuredClone(view.snapshot);snapshot.sourceHashes={...snapshot.sourceHashes,productionMapSha256:map.sha256};snapshot.productionModel.sceneScriptRevisions=[{id:'script:spatial-one',sceneId,scopeRole:'CURRENT',episodeNarrativeReleaseId:'episode:spatial-release',contentHash:hash('scene script')}];snapshot.productionModel.episodeNarrativeReleases=[{id:'episode:spatial-release',episodeUid:'episode:spatial-one',scopeRole:'CURRENT',sourceSyncState:'SOURCE_CURRENT',episodeScriptReleaseSnapshot:{id:'episode:spatial-snapshot',contentHash:hash('scene script')},reviewInput:{scenes:[{id:sceneId,contentHash:hash('scene script')}]}}];await tx.publishRelease({snapshot,recipes:view.recipes,expectedReleaseId:view.releaseId,sourceRevisionIds:[...view.sourceRevisionIds,map.revisionId]});});
 const workspace=()=>repo.readTransaction(tx=>getSpatialShotViewWorkspace(tx,{sceneId}));
 const content=async(note='原门窗保持，新增床与碗架的本场视角。')=>{const w=await workspace();return {sceneId,viewId:w.viewId,locationId:'ROOM-A',zoneId:'ZONE-A',camera:{origin:'NORTHEAST_INTERIOR',looks:'SOUTHWEST',height:'EYE_LEVEL',purpose:'门内视角'},dressing:[{id:'new-bed',kind:'BED',anchor:{kind:'CAMERA',id:'CAM-A'},relation:'WEST_OF',orientation:'EAST_WEST',appearance:'原木床'}],note};};
 const stage=async(note)=>{const w=await workspace(),value=await content(note),saved=await repo.writeTransaction(tx=>saveSpatialShotViewDraft(tx,{sceneId,viewId:w.viewId,expectedReleaseId:w.releaseId,expectedBasisHash:w.basisHash,expectedDraftRevisionId:w.draftHeadRevisionId,content:value})),preview=await repo.readTransaction(tx=>previewSpatialShotView(tx,{sceneId,viewId:w.viewId,draftRevisionId:saved.revisionId}));return {w,content:value,saved,preview};};
 const queue=(s,key)=>repo.writeTransaction(tx=>enqueueSpatialShotView(tx,{sceneId,viewId:s.w.viewId,draftRevisionId:s.saved.revisionId,previewHash:s.preview.previewHash,requestId:key}));
 return {repo,root,softwareRoot,dbPath,profile,map,workspace,content,stage,queue};
}

test('local spatial author publishes immutable scene-bound views through one worker and preserves global map, old sources and unrelated state',async t=>{
 const f=await fixture(t),before=await f.repo.readView(),initial=await f.workspace();assert.equal(initial.defaults.locationId,'');assert.equal(initial.defaults.zoneId,'');assert.deepEqual(initial.blockers,[]);assert.equal(initial.availableLocations.length,2);assert(initial.options.cameraOrigins.includes('NORTHEAST_INTERIOR'));
 const staged=await f.stage(),job=await f.queue(staged,'first');assert.deepEqual(await f.queue(staged,'first'),job);assert.equal((await f.repo.readView()).releaseId,before.releaseId);
 const result=await runSpatialShotViewIteration({repository:f.repo});assert.equal(result.status,'SUCCEEDED');assert.equal(result.modelCalls,0);assert.equal(result.formalAdoptionPerformed,false);const after=await f.repo.readView(),first=after.snapshot.productionModel.spatialShotViews[0],source=await f.repo.readDocumentRevision(result.sourceRevisionId);assert.equal(source.metadata.sourceRole,'SPATIAL_SHOT_VIEW');assert.equal(source.sha256,hash(first.content));assert.equal(first.content.sceneBinding.sceneId,sceneId);assert.equal(first.content.base.sourceSha256,f.map.sha256);assert.notEqual(first.content.camera.id,'CAM-A');assert.equal(first.content.preserveBaseGeometry,true);
 assert.deepEqual(await f.repo.readDocumentRevision(f.map.revisionId),f.map);assert.deepEqual(await f.repo.readDocument('data/production_map_spec.json'),f.map);assert.deepEqual(after.snapshot.productionModel.domainGraph,before.snapshot.productionModel.domainGraph);assert.deepEqual(after.recipes.executionDefinitions,before.recipes.executionDefinitions);assert.equal(after.snapshot.snapshotId,after.recipes.snapshotId);assert.deepEqual(await f.repo.listMedia(),[]);assert.deepEqual(after.eventsByKind,before.eventsByKind);
 const w=await f.workspace();assert.equal(w.currentView.id,first.id);assert.equal(w.draft,null);assert.equal(w.staleDraft.content.note,staged.content.note);assert.equal(w.defaults.note,staged.content.note);await assert.rejects(f.stage(),/已发布版本相同/);
 const second=await f.stage('本场第二视角说明，保持原门窗。');await f.queue(second,'second');assert.equal((await runSpatialShotViewIteration({repository:f.repo})).status,'SUCCEEDED');const newest=await f.repo.readView(),rows=newest.snapshot.productionModel.spatialShotViews;assert.deepEqual(rows.map(r=>r.scopeRole),['EVIDENCE_ONLY','CURRENT']);assert.notEqual(rows[0].id,rows[1].id);assert.deepEqual(await f.repo.readDocumentRevision(first.sourceRevisionId),source);assert.deepEqual(await f.repo.readDocumentRevision(f.map.revisionId),f.map);
 const model=await f.repo.readTransaction(tx=>applyProductionSpatialProjection(tx,newest.snapshot.productionModel,{view:newest}));assert.equal(Object.keys(model.spatialShotViewProofs).length,2);const stripped=structuredClone(newest.snapshot);stripped.productionModel.spatialShotViews=[];const restored=await preserveProductionSpatialProjection({snapshot:stripped,baseSnapshot:newest.snapshot,documents:await Promise.all(newest.sourceRevisionIds.map(id=>f.repo.readDocumentRevision(id)))});assert.deepEqual(restored.productionModel.spatialShotViews,rows);
 assert.deepEqual(await runSpatialShotViewIteration({repository:f.repo}),{processed:false});
});

test('spatial author requires precise basis/draft CAS, forbids source/old geometry injection and leaves all formal state unchanged on rejection',async t=>{
 const f=await fixture(t),w=await f.workspace(),value=await f.content(),before=await f.repo.exportState(),save=(patch)=>f.repo.writeTransaction(tx=>saveSpatialShotViewDraft(tx,{sceneId,viewId:w.viewId,expectedReleaseId:w.releaseId,expectedBasisHash:w.basisHash,expectedDraftRevisionId:null,content:value,...patch}));
 for(const patch of [{expectedBasisHash:'0'.repeat(64)},{expectedReleaseId:'old'},{content:{...value,base:{sourceRevisionId:'forged'}}},{content:{...value,camera:{...value.camera,id:'CAM-A'}}},{content:{...value,dressing:[{...value.dressing[0],kind:'DOOR'}]}},{content:{...value,zoneId:'ZONE-B'}},{content:{...value,sceneId:'scene:other'}}]){await assert.rejects(save(patch));assert.deepEqual(await f.repo.exportState(),before);}
 const s=await f.stage();await assert.rejects(save({}),/冲突|revision|current|HEAD/i);await assert.rejects(f.repo.readTransaction(tx=>previewSpatialShotView(tx,{sceneId,viewId:w.viewId,draftRevisionId:'old'})),/草稿/);const queued=await f.queue(s,'one');await assert.rejects(f.queue(s,'two'),/待处理/);assert.deepEqual(await f.queue(s,'one'),queued);
});

test('spatial publication rollback is atomic and an unknown or stale queued result is never dispatched again',async t=>{
 const f=await fixture(t),s=await f.stage(),job=await f.queue(s,'first'),before=await f.repo.exportState();await assert.rejects(f.repo.writeTransaction(tx=>{tx.publishRelease=async()=>{throw Error('injected spatial publication failure');};return applySpatialShotViewJob(tx,{jobId:job.jobId});}),/injected/);assert.deepEqual(await f.repo.exportState(),before);
 await f.repo.writeTransaction(async tx=>{const record=await tx.getAux(SPATIAL_SHOT_VIEW_NS.jobs,job.jobId);await tx.putAux({namespace:SPATIAL_SHOT_VIEW_NS.jobs,key:job.jobId,expectedRevisionId:record.revisionId,bytes:canonicalJson({...JSON.parse(record.bytes),status:'RESULT_UNKNOWN'})});});const unknown=await f.repo.exportState();assert.deepEqual(await runSpatialShotViewIteration({repository:f.repo}),{processed:false});await assert.rejects(f.queue(s,'retry'),/未知/);await assert.rejects(f.repo.writeTransaction(tx=>applySpatialShotViewJob(tx,{jobId:job.jobId})),/不能自动重试/);assert.deepEqual(await f.repo.exportState(),unknown);
 await assert.rejects(runSpatialShotViewIteration({repository:{readOnly:true}}),/只读/);
});

test('current scene or map publication changes invalidate pending spatial work without creating a frozen view',async t=>{
 const f=await fixture(t),s=await f.stage();await f.queue(s,'first');await f.repo.writeTransaction(async tx=>{const view=await tx.readView(),snapshot=structuredClone(view.snapshot);snapshot.productionModel.sceneScriptRevisions[0].contentHash=hash('new scene');snapshot.productionModel.episodeNarrativeReleases[0].reviewInput.scenes[0].contentHash=hash('new scene');await tx.publishRelease({snapshot,recipes:view.recipes,expectedReleaseId:view.releaseId,sourceRevisionIds:view.sourceRevisionIds});});const before=await f.repo.readView();assert.equal((await runSpatialShotViewIteration({repository:f.repo})).status,'FAILED');assert.equal((await f.repo.readView()).releaseId,before.releaseId);assert.equal((await f.repo.readView()).snapshot.productionModel.spatialShotViews?.length||0,0);assert.deepEqual(await runSpatialShotViewIteration({repository:f.repo}),{processed:false});
});

test('real spatial API uses Origin, exact mutation/basis CAS, idempotent AUX queue and read-only guards without provider or media operations',async t=>{
 const f=await fixture(t),keys=['REVIEW_INSTANCE_DB','REVIEW_INSTANCE_ID','REVIEW_INSTANCE_ROOT','REVIEW_INSTANCE_READ_ONLY','REVIEW_REMOTE_READ_ONLY','REVIEW_SITE_ROOT','REVIEW_EXPORT_DIR','REVIEW_ALLOWED_ORIGINS'],env=Object.fromEntries(keys.map(k=>[k,process.env[k]]));Object.assign(process.env,{REVIEW_INSTANCE_DB:f.dbPath,REVIEW_INSTANCE_ID:f.profile.instanceId,REVIEW_INSTANCE_ROOT:'',REVIEW_INSTANCE_READ_ONLY:'',REVIEW_REMOTE_READ_ONLY:'',REVIEW_SITE_ROOT:f.softwareRoot,REVIEW_EXPORT_DIR:'',REVIEW_ALLOWED_ORIGINS:'http://localhost'});
 const server=await createServer({root:f.softwareRoot,configFile:false,logLevel:'error',cacheDir:path.join(f.root,'vite-cache'),server:{middlewareMode:true},appType:'custom'});let store;const originalFetch=globalThis.fetch;let externalCalls=0;globalThis.fetch=async()=>{externalCalls++;throw Error('Provider call forbidden');};
 try{store=await server.ssrLoadModule('/app/api/v8/_store.ts');const route=await server.ssrLoadModule('/app/api/instance/spatial-shot-view/route.ts'),response=await route.GET(new Request('http://localhost/api/instance/spatial-shot-view?sceneId='+sceneId));assert.equal(response.status,200,await response.clone().text());const w=await response.json(),value=await f.content(),save={action:'save',sceneId,viewId:w.viewId,expectedReleaseId:w.releaseId,expectedBasisHash:w.basisHash,expectedDraftRevisionId:w.draftHeadRevisionId,content:value};
 const post=async(body,key,headers={})=>{const res=await route.POST(new Request('http://localhost/api/instance/spatial-shot-view',{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://localhost','If-Match':(await store.operationalSnapshot()).mutationEtag,'Idempotency-Key':'spatial-api:'+key,...headers},body:JSON.stringify(body)}));return {status:res.status,body:await res.json()};};
 const before=await f.repo.exportState();assert.equal((await post(save,'origin',{Origin:'https://wrong.example'})).status,403);assert.equal((await post(save,'etag',{'If-Match':'"wrong"'})).status,412);assert.equal((await post({...save,content:{...value,sourceSha256:f.map.sha256}},'bad-field')).status,422);assert.deepEqual(await f.repo.exportState(),before);
 const saved=await post(save,'save');assert.equal(saved.status,200,JSON.stringify(saved.body));const preview=await post({action:'preview',sceneId,viewId:w.viewId,draftRevisionId:saved.body.revisionId},'preview');assert.equal(preview.status,200,JSON.stringify(preview.body));assert.equal(preview.body.view.sceneBinding.sceneId,sceneId);assert.equal(preview.body.view.base.locationId,'ROOM-A');assert.equal(preview.body.view.base.zoneId,'ZONE-A');assert.equal(preview.body.modelCalls,0);
 const input={action:'publish',sceneId,viewId:w.viewId,draftRevisionId:saved.body.revisionId,previewHash:preview.body.previewHash},queued=await post(input,'publish');assert.equal(queued.status,200);assert.deepEqual(await post(input,'publish'),queued);assert.equal((await f.repo.readView()).releaseId,w.releaseId);
 for(const key of ['REVIEW_INSTANCE_READ_ONLY','REVIEW_REMOTE_READ_ONLY']){process.env[key]='1';const res=await route.POST(new Request('http://localhost/api/instance/spatial-shot-view',{method:'POST',body:JSON.stringify(save)}));assert.equal(res.status,405);process.env[key]='';}assert.equal(externalCalls,0);assert.deepEqual(await f.repo.listMedia(),[]);
 }finally{globalThis.fetch=originalFetch;process.env.REVIEW_REMOTE_READ_ONLY='';process.env.REVIEW_INSTANCE_READ_ONLY='';await (await store?.instanceRepository())?.close();await server.close();for(const key of keys){if(env[key]===undefined)delete process.env[key];else process.env[key]=env[key];}}
});

test('shared host worker owns the spatial dispatcher',async()=>{const source=await readFile(new URL('../scripts/instance-shot-production-worker.mjs',import.meta.url),'utf8');assert(source.includes('await runSpatialShotViewIteration({repository})'));});

test('worker reads the committed SUCCEEDED receipt after a lost transaction response instead of reporting failure or retrying',async t=>{
 const f=await fixture(t),s=await f.stage(),job=await f.queue(s,'lost-response');let lose=true;
 const repository={readTransaction:callback=>f.repo.readTransaction(callback),writeTransaction:async callback=>{const result=await f.repo.writeTransaction(callback);if(lose){lose=false;throw Error('simulated lost commit response');}return result;}};
 const result=await runSpatialShotViewIteration({repository});assert.equal(result.status,'SUCCEEDED');assert.ok(result.releaseId);assert.equal(result.jobId,job.jobId);assert.equal((await f.repo.readView()).snapshot.productionModel.spatialShotViews.length,1);assert.deepEqual(await runSpatialShotViewIteration({repository}),{processed:false});
});
