import {test,expect,type Page} from '@playwright/test';
import {buildSync} from 'esbuild';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
async function fixture(page:Page,{hosted=false,readOnly=false,stale=false,unknown=false,invalidReread=false,invalidPreview=false,conflict=false,firstReadFailure=false,malformedReread=""}={}){
 const writes:Array<Record<string,unknown>>=[],errors:string[]=[],unexpected:string[]=[];let draft:{revisionId:string;content:unknown}|null=null,reads=0;
 const defaults={viewId:'VIEW-1',sceneId:'SCENE-1',locationId:'LOC-10',zoneId:'MS-Z02',camera:{origin:'NORTHEAST_INTERIOR',looks:'SOUTHWEST',height:'EYE_LEVEL',purpose:'南墙床铺的反打机位'},dressing:[],note:'依据当前夜戏正文，保持已发布房间门窗方向。'};
 const staleContent={...defaults,camera:{...defaults.camera,purpose:'上次保留的完整反打设计'},dressing:[{id:'DRESSING-OLD',kind:'BED',anchor:{kind:'CAMERA',id:'MISSING-CAMERA'},relation:'SOUTH_OF',orientation:'EAST_WEST',appearance:'窄木床和旧灰被'}]};
 const entry=`import React from'react';import{createRoot}from'react-dom/client';import{RuntimeModeProvider}from'./app/runtime-mode';import{SpatialShotViewEditor}from'./app/spatial-shot-view-editor';createRoot(document.getElementById('root')).render(<RuntimeModeProvider hostedReadOnly={${hosted}}><SpatialShotViewEditor sceneId="SCENE-1"/></RuntimeModeProvider>);`;
 const files=buildSync({stdin:{contents:entry,resolveDir:root,sourcefile:'spatial-view-harness.tsx',loader:'tsx'},bundle:true,platform:'browser',format:'iife',jsx:'automatic',write:false,outdir:'virtual-spatial-view',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'}).outputFiles,js=files.find(f=>f.path.endsWith('.js'))!.text,css=files.filter(f=>f.path.endsWith('.css')).map(f=>f.text).join('\n');page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());
  if(url.pathname==='/api/v8/operations/snapshot'&&request.method()==='GET')return route.fulfill({json:{mutationEtag:'"spatial-etag"'}});
  if(url.pathname==='/api/instance/spatial-shot-view'){
   if(request.method()==='GET'){reads++;if(firstReadFailure&&reads===1)return route.fulfill({status:503,json:{error:'首次读取失败'}});expect(url.searchParams.get('sceneId')).toBe('SCENE-1');return route.fulfill({json:invalidReread&&reads>1?{sceneId:'SCENE-1'}:{sceneId:'SCENE-1',viewId:'VIEW-1',releaseId:'RELEASE',basisHash:'b'.repeat(64),readOnly,draftHeadRevisionId:draft?.revisionId||(stale?'DRAFT-OLD':null),draft,staleDraft:stale&&!draft?{revisionId:'DRAFT-OLD',content:staleContent,reason:'原锚点已变化'}:null,defaults,currentView:null,availableLocations:[{id:'LOC-10',name:'马三家',zones:[{id:'MS-Z02',name:'居室'}],cameras:[{id:'MS-CAM-04',zoneIds:['MS-Z02']},{id:'MS-CAM-05',zoneIds:['MS-Z03']}]}],options:{cameraOrigins:['NORTHEAST_INTERIOR','SOUTH_INTERIOR'],cameraDirections:['SOUTHWEST','NORTH'],cameraHeights:['EYE_LEVEL','LOW','HIGH'],dressingKinds:['BED','BOWL_RACK'],relations:['NORTH_OF','SOUTH_OF','AT'],orientations:['EAST_WEST','NORTH_SOUTH','NONE']},blockers:[],jobs:[],...(reads>1&&malformedReread==='draft'?{draft:false}:{}),...(reads>1&&malformedReread==='defaults'?{defaults:false}:{}),...(reads>1&&malformedReread==='head'?{draftHeadRevisionId:'UNKNOWN-HEAD'}:{})}});}
   const body=request.postDataJSON();writes.push(body);expect(request.headers()['if-match']).toBe('"spatial-etag"');expect(request.headers()['idempotency-key']).toMatch(/^spatial-shot-view:/);
   if(unknown)return route.fulfill({status:503,json:{error:'连接中断'}});if(conflict)return route.fulfill({status:409,json:{error:'空间依据已变化'}});
   if(body.action==='save'){draft={revisionId:'DRAFT-1',content:body.content};return route.fulfill({json:{revisionId:'DRAFT-1',formalAdoptionPerformed:false}});}
   if(body.action==='preview'){const c=draft!.content as typeof defaults;return route.fulfill({json:{previewHash:'c'.repeat(64),view:{id:'SPATIAL-VIEW-FROZEN',viewId:'VIEW-1',sceneBinding:{sceneId:invalidPreview?'OTHER-SCENE':'SCENE-1'},base:{locationId:c.locationId,zoneId:c.zoneId},camera:{id:'LOCAL-CAM-1',...c.camera},dressing:c.dressing,note:c.note},modelCalls:0,formalAdoptionPerformed:false}});}
   if(body.action==='publish')return route.fulfill({json:{jobId:'SPATIAL-JOB-1',status:'QUEUED'}});
  }unexpected.push(request.method()+' '+url.pathname);return route.fulfill({status:418,json:{error:'unexpected'}});
 });
 await page.route('**/__spatial-view',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>${css}</style></head><body><div id="root"></div><script>${js}</script></body></html>`}));await page.goto('/__spatial-view');return{writes,errors,unexpected};
}
async function author(page:Page){await page.getByRole('button',{name:'设计本场局部机位与摆位'}).click();await page.getByRole('textbox',{name:'机位用途',exact:true}).fill('女主视线后的南墙床铺反打');await page.getByRole('button',{name:'添加家具摆位'}).click();await page.getByRole('textbox',{name:'家具外观',exact:true}).fill('独立窄木床，旧灰棉被。');await page.getByRole('combobox',{name:'摆位锚点',exact:true}).selectOption('CAMERA:MS-CAM-04');await page.getByRole('combobox',{name:'相对位置',exact:true}).selectOption('SOUTH_OF');}
test('authors a scene-scoped camera and furniture view with precise CAS then queues reviewed preview',async({page})=>{const f=await fixture(page);await author(page);await expect(page.getByRole('combobox',{name:'摆位锚点',exact:true}).locator('option')).toHaveCount(2);await page.getByRole('button',{name:'保存空间草稿'}).click();await expect(page.getByRole('status')).toContainText('空间草稿已保存');expect(f.writes[0]).toMatchObject({action:'save',sceneId:'SCENE-1',viewId:'VIEW-1',expectedReleaseId:'RELEASE',expectedBasisHash:'b'.repeat(64),expectedDraftRevisionId:null,content:{sceneId:'SCENE-1',viewId:'VIEW-1',locationId:'LOC-10',zoneId:'MS-Z02',camera:{origin:'NORTHEAST_INTERIOR',looks:'SOUTHWEST'},dressing:[{kind:'BED',anchor:{kind:'CAMERA',id:'MS-CAM-04'},relation:'SOUTH_OF',appearance:'独立窄木床，旧灰棉被。'}]}});expect(Object.keys(f.writes[0].content as object).sort()).toEqual(['camera','dressing','locationId','note','sceneId','viewId','zoneId']);await page.getByRole('button',{name:'预览机位与摆位'}).click();await expect(page.getByRole('region',{name:'局部空间预览'})).toBeVisible();await page.getByRole('button',{name:'确认发布局部空间版本'}).click();await expect(page.getByRole('status')).toContainText('任务已排队');expect(f.writes.map(w=>w.action)).toEqual(['save','preview','publish']);expect(f.writes[2]).toMatchObject({draftRevisionId:'DRAFT-1',previewHash:'c'.repeat(64),viewId:'VIEW-1'});expect(f.errors).toEqual([]);expect(f.unexpected).toEqual([]);});
test('stale full draft and missing anchor stay visible until explicitly replaced',async({page})=>{const f=await fixture(page,{stale:true});await page.getByRole('button',{name:'设计本场局部机位与摆位'}).click();await expect(page.getByRole('status')).toContainText('完整草稿');await expect(page.getByRole('textbox',{name:'机位用途',exact:true})).toHaveValue('上次保留的完整反打设计');await expect(page.getByRole('combobox',{name:'摆位锚点',exact:true})).toHaveValue('CAMERA:MISSING-CAMERA');await page.getByRole('combobox',{name:'摆位锚点',exact:true}).selectOption('CAMERA:MS-CAM-04');await page.getByRole('button',{name:'保存空间草稿'}).click();await expect(page.getByRole('status')).toContainText('空间草稿已保存');expect(f.writes[0]).toMatchObject({expectedDraftRevisionId:'DRAFT-OLD',content:{camera:{purpose:'上次保留的完整反打设计'},dressing:[{id:'DRESSING-OLD',appearance:'窄木床和旧灰被',anchor:{id:'MS-CAM-04'}}]}});expect(f.errors).toEqual([]);});
for(const invalidReread of [false,true])test(`unknown submission freezes edits until ${invalidReread?'invalid reread keeps frozen':'valid reread confirms current state'}`,async({page})=>{const f=await fixture(page,{unknown:true,invalidReread});await author(page);await page.getByRole('button',{name:'保存空间草稿'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('textbox',{name:'机位用途',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重读空间资料与任务'}).click();await expect(page.getByRole('status')).toContainText(invalidReread?'空间资料回执不完整':'本次编辑仍保留');await expect(page.getByRole('textbox',{name:'机位用途',exact:true})).toHaveValue('女主视线后的南墙床铺反打');if(invalidReread)await expect(page.getByRole('button',{name:'保存空间草稿'})).toBeDisabled();else await expect(page.getByRole('button',{name:'保存空间草稿'})).toBeEnabled();expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
test('different scene preview cannot be published',async({page})=>{const f=await fixture(page,{invalidPreview:true});await author(page);await page.getByRole('button',{name:'保存空间草稿'}).click();await page.getByRole('button',{name:'预览机位与摆位'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await expect(page.getByRole('button',{name:'确认发布局部空间版本'})).toHaveCount(0);expect(f.writes.map(w=>w.action)).toEqual(['save','preview']);});
test('CAS conflict preserves complete unsaved design without retry',async({page})=>{const f=await fixture(page,{conflict:true});await author(page);await page.getByRole('button',{name:'保存空间草稿'}).click();await expect(page.getByRole('status')).toContainText('空间依据已变化');await expect(page.getByRole('textbox',{name:'家具外观',exact:true})).toHaveValue('独立窄木床，旧灰棉被。');expect(f.writes).toHaveLength(1);});
test('read-only instance disables authoring and hosted mirror omits it',async({page})=>{let f=await fixture(page,{readOnly:true});await page.getByRole('button',{name:'设计本场局部机位与摆位'}).click();await expect(page.getByRole('textbox',{name:'机位用途',exact:true})).toBeDisabled();expect(f.writes).toEqual([]);await page.unrouteAll({behavior:'wait'});f=await fixture(page,{hosted:true});await expect(page.getByRole('button',{name:'设计本场局部机位与摆位'})).toHaveCount(0);expect(f.unexpected).toEqual([]);});

test('a successful reread after initial GET failure restores an editable default form',async({page})=>{const f=await fixture(page,{firstReadFailure:true});await page.getByRole('button',{name:'设计本场局部机位与摆位'}).click();await expect(page.getByRole('status')).toContainText('首次读取失败');await expect(page.getByRole('textbox',{name:'机位用途',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'重读空间资料与任务'}).click();await expect(page.getByRole('textbox',{name:'机位用途',exact:true})).toHaveValue('南墙床铺的反打机位');await page.getByRole('textbox',{name:'机位用途',exact:true}).fill('重新读取后继续设计');await expect(page.getByRole('button',{name:'保存空间草稿'})).toBeEnabled();expect(f.writes).toEqual([]);expect(f.errors).toEqual([]);});
for(const malformedReread of ['draft','defaults','head'])test(`malformed ${malformedReread} closure cannot release an unknown submission`,async({page})=>{const f=await fixture(page,{unknown:true,malformedReread});await author(page);await page.getByRole('button',{name:'保存空间草稿'}).click();await expect(page.getByRole('status')).toContainText('提交结果尚未确认');await page.getByRole('button',{name:'重读空间资料与任务'}).click();await expect(page.getByRole('status')).toContainText('空间草稿版本依据不完整');await expect(page.getByRole('button',{name:'保存空间草稿'})).toBeDisabled();await expect(page.getByRole('textbox',{name:'家具外观',exact:true})).toHaveValue('独立窄木床，旧灰棉被。');expect(f.writes).toHaveLength(1);expect(f.errors).toEqual([]);});
