import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, writeFile, symlink } from 'node:fs/promises';
import path from 'node:path';
import { sharedStoryPostgres } from './fixtures/shared-story-postgres.mjs';
import { createInstanceRepository, sha256 } from '../host/instance-runtime/index.mjs';
import { blankProfile, blankSnapshot } from '../host/instance-runtime/blank.mjs';
import { instanceTrialSnapshot } from '../app/api/trial/_instance.mjs';
import * as trial from '../host/instance-runtime/trial.mjs';

test('PostgreSQL trial generation preserves formal authority and atomically binds one private candidate', { skip: process.env.REVIEW_TEST_POSTGRES !== '1', timeout: 120000 }, async () => {
  const parent = path.resolve('tests/.test-tmp'); await mkdir(parent, { recursive: true });
  const root = await mkdtemp(path.join(parent, 'trial-generation-')), pg = await sharedStoryPostgres(root), profile = blankProfile({ title: '试制隔离回归' });
  let repo;
  try {
    repo = await createInstanceRepository({ root, instanceId: profile.instanceId, backend: 'postgres', database: pg.database, profile });
    let document;
    const published = await repo.writeTransaction(async (tx) => {
      document = await tx.putDocument({ documentId: 'source', bytes: '完整素材依据', expectedRevisionId: null });
      return tx.publishRelease({ ...blankSnapshot(profile), expectedReleaseId: null, sourceRevisionIds: [document.revisionId] });
    });
    const baseline = await repo.readRelease(), scopeId = 'trial:test-generation', scopeBody = { expectedReleaseId: published.releaseId, expectedIndexRevisionId: null, scope: { id: scopeId, title: '图像试制', projectTitle: '隔离测试', countsTowardFormalProject: false }, limits: { IMAGE: 3, AUDIO: 0, VIDEO: 0 }, authorization: { id: 'test:batch', userInstruction: '隔离测试，每项一个候选', maxOutputsPerRecipe: 1 } };
    const created = await trial.instanceTrialPrepareScope(repo, scopeBody, { idempotencyKey: 'create-test-scope' });
    assert.equal((await trial.instanceTrialPrepareScope(repo, scopeBody, { idempotencyKey: 'create-test-scope' })).replayed, true);
    const options = async (key) => ({ root, scopeId, ifMatch: (await trial.instanceTrialInspect(repo, { scopeId })).mutationEtag, idempotencyKey: key });
    const recipe = (id) => ({ id: `recipe:${id}`, subjectId: `subject:${id}`, label: '测试图片', mediaKind: 'IMAGE', model: 'GPT-IMG-2', mainPrompt: '完整测试图像', fullPrompt: '完整测试图像\n无水印', negativePrompt: '无水印', inputBindings: [], sourceBindings: [{ documentId: 'source', revisionId: document.revisionId, sha256: document.sha256 }], output: { relativePath: `media/_review_pending/${id}/test.png`, versionId: `subject:${id}@TRIAL-V001` }, authorization: { id: `test:${id}`, userInstruction: '只生成一个测试候选', maxOutputs: 1 }, runtimeBlockers: [] });
    const sourceRecipe = recipe('first'), beforeDryRun = await repo.getMetadata();
    assert.equal((await trial.instanceTrialDryRun(repo, { recipe: sourceRecipe }, { root, scopeId })).status, 'PREFLIGHT_PASSED');
    assert.equal((await repo.getMetadata()).repositoryRevision, beforeDryRun.repositoryRevision);
    await assert.rejects(trial.instanceTrialPrepareRecipe(repo, { recipe: { ...sourceRecipe, sourceBindings: [{ ...sourceRecipe.sourceBindings[0], sha256: sha256('wrong') }] } }, await options('source-mismatch')), { code: 'SOURCE_BINDING' });
    await trial.instanceTrialPrepareRecipe(repo, { recipe: sourceRecipe }, await options('prepare-first'));
    const reserveOptions = await options('reserve-first'), reserveBody = { recipeId: sourceRecipe.id, workerId: 'test-worker', runtimeEpoch: (await repo.readView()).runtimeEpoch };
    const reserved = await trial.instanceTrialReserve(repo, reserveBody, reserveOptions);
    const replay = await trial.instanceTrialReserve(repo, reserveBody, { ...reserveOptions, ifMatch: 'stale' }); assert.equal(replay.replayed, true); assert.equal(replay.execution.requestId, reserved.execution.requestId);
    await assert.rejects(trial.instanceTrialReserve(repo, reserveBody, await options('reserve-duplicate')), { code: 'ONE_CANDIDATE' });
    const binding = Object.fromEntries(['requestId', 'leaseToken', 'fencingToken', 'inputHash', 'promptHash', 'runtimeEpoch'].map((key) => [key, reserved.execution[key]]));
    await assert.rejects(trial.instanceTrialStart(repo, { ...binding, fencingToken: 999 }, await options('bad-fencing-token')), { code: 'LEASE_CONFLICT' });
    const staleOptions = await options('cas-start-first');
    const started = await trial.instanceTrialStart(repo, binding, staleOptions);
    await assert.rejects(trial.instanceTrialStart(repo, binding, { ...staleOptions, idempotencyKey: 'stale-second-start' }), { code: 'CAS_CONFLICT' });
    await assert.rejects(trial.instanceTrialStart(repo, binding, await options('duplicate-start')), { code: 'EXECUTION_STATE' });
    const imageBytes = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aIasAAAAASUVORK5CYII=', 'base64');
    await mkdir(path.dirname(path.join(root, sourceRecipe.output.relativePath)), { recursive: true });
    await writeFile(path.join(root, sourceRecipe.output.relativePath), imageBytes, { flag: 'wx' });
    const resultBody = { ...binding, outcome: 'SUCCEEDED', file: sourceRecipe.output.relativePath, sha256: sha256(imageBytes), receipt: { dispatchId: started.execution.dispatchId, modelVersion: 'FIXTURE_NOT_A_MODEL_CALL' }, qa: { visualStatus: 'UNKNOWN' } };
    await assert.rejects(trial.instanceTrialResult(repo, { ...resultBody, sha256: sha256('wrong') }, await options('wrong-result-sha')), { code: 'MEDIA_SHA' });
    const resultOptions = await options('result-first'), revision = (await repo.getMetadata()).repositoryRevision;
    const failing = { backend: 'postgres', writeTransaction: (callback) => repo.writeTransaction((tx) => callback(new Proxy(tx, { get(target, property) {
      if (property === 'putAux') return (input) => { if (input.key.startsWith('idempotency/')) throw new Error('receipt-storage-failed'); return target.putAux(input); };
      const value = Reflect.get(target, property); return typeof value === 'function' ? value.bind(target) : value;
    } }))) };
    await assert.rejects(trial.instanceTrialResult(failing, resultBody, resultOptions), /receipt-storage-failed/);
    assert.equal((await repo.getMetadata()).repositoryRevision, revision); assert.equal(await repo.getMedia(sourceRecipe.subjectId, sourceRecipe.output.versionId), null);
    const result = await trial.instanceTrialResult(repo, resultBody, resultOptions);
    assert.equal(result.asset.lifecycle, 'REVIEW_PENDING'); assert.equal(result.asset.rightsStatus, 'UNKNOWN');
    const registered = await repo.getMedia(result.asset.mediaId, result.asset.versionId); assert.equal(registered.relativePath, resultBody.file); assert.equal(registered.metadata.visibility, 'PRIVATE');
    assert.equal((await trial.instanceTrialResult(repo, resultBody, { ...resultOptions, ifMatch: 'stale' })).asset.id, result.asset.id);
    const evidence = JSON.stringify({ summary: '仅合成测试数据，未调用模型' }); await writeFile(path.join(root, 'evidence.json'), evidence);
    await trial.instanceTrialAnnotateQa(repo, { versionId: result.asset.versionId, sha256: result.asset.sha256, evidencePath: 'evidence.json', evidenceSha256: sha256(evidence), observations: { summary: '测试失败观察不会代作正式审阅', technicalStatus: 'NEEDS_CORRECTION', visualPass: false } }, await options('annotate-first'));
    const snapshot = await instanceTrialSnapshot(repo, { scopeId });
    assert.equal(snapshot.assets[0].qualityBlocked, true); assert.equal(snapshot.assets[0].lifecycle, 'REVIEW_PENDING'); assert.equal(snapshot.executions[0].leaseToken, undefined);
    assert.equal(snapshot.budgets.find((item) => item.kind === 'IMAGE').spent, 1);
    const second = recipe('unknown'); await trial.instanceTrialPrepareRecipe(repo, { recipe: second }, await options('prepare-unknown'));
    const reservedUnknown = await trial.instanceTrialReserve(repo, { recipeId: second.id, workerId: 'worker-unknown', runtimeEpoch: (await repo.readView()).runtimeEpoch }, await options('reserve-unknown'));
    const unknownBinding = Object.fromEntries(['requestId', 'leaseToken', 'fencingToken', 'inputHash', 'promptHash', 'runtimeEpoch'].map((key) => [key, reservedUnknown.execution[key]]));
    const dispatched = await trial.instanceTrialStart(repo, unknownBinding, await options('start-unknown'));
    await assert.rejects(trial.instanceTrialResult(repo, { ...unknownBinding, outcome: 'FAILED', receipt: { dispatchId: dispatched.execution.dispatchId } }, await options('reject-vague-failure')), { code: 'UNKNOWN_NOT_FAILURE' });
    await trial.instanceTrialResult(repo, { ...unknownBinding, outcome: 'RESULT_UNKNOWN', receipt: { dispatchId: dispatched.execution.dispatchId, requestId: 'provider-request-known' } }, await options('result-unknown'));
    assert.equal((await trial.instanceTrialInspect(repo, { scopeId })).budgets[0].spent, 2);
    await assert.rejects(trial.instanceTrialReserve(repo, { recipeId: second.id, workerId: 'worker-unknown', runtimeEpoch: (await repo.readView()).runtimeEpoch }, await options('retry-unknown')), { code: 'ONE_CANDIDATE' });
    const collision = recipe('collision'); collision.output.relativePath = sourceRecipe.output.relativePath;
    await assert.rejects(trial.instanceTrialDryRun(repo, { recipe: collision }, { root, scopeId }), { code: 'OUTPUT_EXISTS' });
    await symlink(path.join(root, 'media'), path.join(root, 'escape'));
    const symlinkRecipe = recipe('symlink'); symlinkRecipe.inputBindings = [{ path: 'escape/_review_pending/first/test.png', sha256: sha256(imageBytes) }];
    await assert.rejects(trial.instanceTrialDryRun(repo, { recipe: symlinkRecipe }, { root, scopeId }), { code: 'PATH_ESCAPE' });
    // The real repository epoch rotation used by restore must not revive old
    // authorization, a claimed lease or an idempotent dispatch receipt.
    const third = recipe('claimed-before-restore');
    await trial.instanceTrialPrepareRecipe(repo, { recipe: third }, await options('prepare-before-restore'));
    const beforeRestore = await trial.instanceTrialReserve(repo, { recipeId: third.id, workerId: 'worker-fixture', runtimeEpoch: (await repo.readView()).runtimeEpoch }, await options('reserve-before-restore'));
    const oldBinding = Object.fromEntries(['requestId', 'leaseToken', 'fencingToken', 'inputHash', 'promptHash', 'runtimeEpoch'].map(key => [key, beforeRestore.execution[key]]));
    const fourth = recipe('unused-before-restore');
    await trial.instanceTrialPrepareRecipe(repo, { recipe: fourth }, await options('prepare-unused-before-restore'));
    await repo.writeTransaction(tx => tx.resetRuntimeEpoch());
    const restoredEpoch = (await trial.instanceTrialInspect(repo, { scopeId })).runtimeEpoch;
    assert.notEqual(restoredEpoch, oldBinding.runtimeEpoch);
    await assert.rejects(trial.instanceTrialReserve(repo, { recipeId: fourth.id, workerId: 'worker-fixture', runtimeEpoch: restoredEpoch }, await options('reserve-restored-unused')), { code: 'RUNTIME_EPOCH_CONFLICT' });
    await assert.rejects(trial.instanceTrialStart(repo, { ...oldBinding, runtimeEpoch: restoredEpoch }, await options('start-restored-claimed')), { code: 'RUNTIME_EPOCH_CONFLICT' });
    await assert.rejects(trial.instanceTrialStart(repo, { ...unknownBinding, runtimeEpoch: restoredEpoch }, await options('start-unknown')), { code: 'RUNTIME_EPOCH_CONFLICT' });
    const reconciled = await trial.instanceTrialResult(repo, { ...unknownBinding, runtimeEpoch: restoredEpoch, originRuntimeEpoch: unknownBinding.runtimeEpoch, reconciled: true, outcome: 'FAILED', receipt: { dispatchId: dispatched.execution.dispatchId, requestId: 'provider-request-known', definitiveFailure: true } }, await options('reconcile-after-restore'));
    assert.equal(reconciled.execution.runtimeEpoch, unknownBinding.runtimeEpoch); assert.equal(reconciled.asset, null);
    assert.equal((await trial.instanceTrialInspect(repo, { scopeId })).budgets[0].spent, 2);
    const finalRelease = await repo.readRelease();
    assert.equal(finalRelease.releaseId, baseline.releaseId); assert.deepEqual(finalRelease.snapshotBytes, baseline.snapshotBytes); assert.deepEqual(finalRelease.recipesBytes, baseline.recipesBytes);
    assert.deepEqual(await repo.listEvents(), []); assert.ok((await repo.listEvents(null, { authorityDomain: 'LOCAL_TRIAL' })).length > 8);
    assert.equal(created.config.scope.countsTowardFormalProject, false);
  } finally { await repo?.close(); await pg.cleanup(); await rm(root, { recursive: true, force: true }); }
});
