import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {apiFixture,pngs} from './fixtures/material-native-revision-api.mjs';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {validateArchive,createArchiveStreamValidator} from '../host/instance-runtime/postgres.mjs';
import {importRepositoryState,restoreInstanceRepository} from '../host/instance-runtime/index.mjs';
import {writeArchiveFile} from '../host/instance-runtime/archive-file.mjs';
import {openArchiveRowsWithBinding,validateArchiveRows} from '../host/instance-runtime/archive-stream-validation.mjs';
import {captureHistoricalEventContexts} from '../host/instance-historical-event-context.mjs';
import {validateModernEventsInChild} from '../host/instance-modern-event-bridge.mjs';
const options={skip:process.env.REVIEW_TEST_POSTGRES!=='1',timeout:180000};
async function setup(t,{oldRun=null,fulfilled=false,notCalled=true,advance=true}={}){
 const f=await apiFixture(t),p=await f.provision(await f.workspace(),'Neutral disposable cancellation protocol, no model call.'),authorize=async()=>{
  const r=await f.post(f.requests,'v8/execution-requests',{action:'AUTHORIZE',workItemId:p.result.workItemId,familyId:p.result.familyId,executionDefinitionId:p.recipe.id,callPackageHash:p.recipe.definitionHash,executor:'CODEX',authorized:true,maxOutputs:1,inputBindings:[]});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.executionRequestId;
 };
 const old=await authorize(),claim=await f.post(f.requests,'v8/execution-requests',{action:'CLAIM',executionRequestId:old,claimedBy:'isolated-cancel-executor',note:!advance&&notCalled?`Execution request ${old} NOT_CALLED: no Run, no candidate, zero provider calls.`:''});assert.equal(claim.status,201,JSON.stringify(claim.body));
 if(oldRun){const r=await f.post(f.runs,'v8/runs',{executionRequestId:old,executionDefinitionId:p.recipe.id,callPackageHash:p.recipe.definitionHash,state:'SUBMITTED',note:'Actual isolated protocol run, no provider.'});assert.equal(r.status,201);if(oldRun==='RESULT_UNKNOWN'){const u=await f.post(f.runs,'v8/runs',{executionRequestId:old,executionDefinitionId:p.recipe.id,callPackageHash:p.recipe.definitionHash,runId:r.body.runId,state:'RESULT_UNKNOWN',note:'Synthetic explicit unknown; no cancellation allowed.'});assert.equal(u.status,201);}}
 const original=await f.repo.readView();if(advance)await f.repo.writeTransaction(async tx=>{const v=await tx.readView(),snapshot=structuredClone(v.snapshot),recipes=structuredClone(v.recipes);snapshot.snapshotId='snapshot_'+sha256(canonicalJson({previous:snapshot.snapshotId,isolated:'unrelated-release'})).slice(0,32);recipes.snapshotId=snapshot.snapshotId;await tx.publishRelease({snapshot,recipes,expectedReleaseId:v.releaseId,sourceRevisionIds:v.sourceRevisionIds});});
 let successor=null;
 if(advance&&!oldRun&&notCalled){successor=await authorize();const c=await f.post(f.requests,'v8/execution-requests',{action:'CLAIM',executionRequestId:successor,claimedBy:'isolated-cancel-executor',note:`Continuation of ${old} after snapshot change. Prior allocation NOT_CALLED: no Run, no candidate, zero provider calls; evidence worker-results/neutral.json. First actual provider attempt only; no retry.`});assert.equal(c.status,201);
  if(fulfilled){const binding={executionRequestId:successor,executionDefinitionId:p.recipe.id,callPackageHash:p.recipe.definitionHash},r=await f.post(f.runs,'v8/runs',{...binding,state:'SUBMITTED',note:'Fixed PNG protocol fixture, zero provider calls.'});assert.equal(r.status,201);await f.register(p,{...binding,runId:r.body.runId},pngs[0]);}
 }
 const inspect=async()=>{const r=await f.requests.GET(new Request('http://localhost/api/v8/execution-requests?executionRequestId='+old+'&cancellation=1'));return {status:r.status,body:await r.json()};};
 const body=async()=>{const x=await inspect();assert.equal(x.status,200,JSON.stringify(x.body));const c=x.body.cancellation;return {action:'CANCEL',executionRequestId:old,cancellation:{schemaVersion:c.schemaVersion,purpose:c.purpose,requestSnapshotId:c.requestSnapshotId,expectedHead:c.expectedHead,historyHash:c.historyHash,notCalledAttestation:{confirmed:true,basis:'Isolated executor confirms only the exact old allocation NOT_CALLED; linked immutable claim is original evidence.',evidenceRefs:c.notCalledEvidence}},note:'Cancel only the original unstarted request; preserve its fulfilled successor.'};};
 return {...f,p,old,successor,original,inspect,body};
}
test('real PG cancel uses current CAS but appends original request snapshot and preserves fulfilled successor/history',options,async t=>{
 const f=await setup(t,{fulfilled:true}),before=await f.repo.readView(),media=await f.repo.listMedia(),body=await f.body();
 const legacyCurrent=await f.post(f.requests,'v8/execution-requests',{action:'CANCEL',executionRequestId:f.old,note:'Old route remains strict'});assert.equal(legacyCurrent.status,409);
 const legacyOld=await f.post(f.requests,'v8/execution-requests',{action:'CANCEL',executionRequestId:f.old,snapshotId:f.original.snapshot.snapshotId,note:'Old route remains strict'});assert.equal(legacyOld.status,412);
 const result=await f.post(f.requests,'v8/execution-requests',body,{key:'cancel:exact-replay'});assert.equal(result.status,201,JSON.stringify(result.body));const e=result.body.event;assert.equal(e.schemaVersion,'1.1');assert.equal(e.action,'CANCEL_UNSTARTED');assert.equal(e.snapshotId,f.original.snapshot.snapshotId);assert.equal(e.cancellationReceipt.mutation.snapshotId,before.snapshot.snapshotId);
 const oldRead=await f.requests.GET(new Request('http://localhost/api/v8/execution-requests?executionRequestId='+f.old));const oldProjection=(await oldRead.json()).requests[0];assert.equal(oldProjection.requestState,'CANCELLED');assert.equal(oldProjection.action,'CANCEL_UNSTARTED');
 const replay=await f.post(f.requests,'v8/execution-requests',body,{key:'cancel:exact-replay'});assert.equal(replay.status,200);assert.equal(replay.body.eventId,e.eventId);const wrongReplay=await f.post(f.requests,'v8/execution-requests',{...body,note:'Different'},{key:'cancel:exact-replay'});assert.equal(wrongReplay.status,409);
 const after=await f.repo.readView();assert.equal(after.releaseId,before.releaseId);assert.deepEqual(after.snapshot,before.snapshot);assert.deepEqual(after.recipes,before.recipes);assert.deepEqual(after.eventsByKind.run,before.eventsByKind.run);assert.deepEqual(after.eventsByKind['asset-version'],before.eventsByKind['asset-version']);assert.deepEqual(await f.repo.listMedia(),media);for(const old of before.eventsByKind['execution-request'])assert.deepEqual(after.eventsByKind['execution-request'].find(r=>r.eventId===old.eventId),old);
 const successor=await f.requests.GET(new Request('http://localhost/api/v8/execution-requests?executionRequestId='+f.successor));assert.equal((await successor.json()).requests[0].status,'FULFILLED');
 const archive=await f.repo.exportState();validateArchive(archive,f.profile.instanceId);
 const filename=path.join(f.root,'cancel-archive.jsonl'),file=await writeArchiveFile(filename,archive),reader=await openArchiveRowsWithBinding(filename,file);try{assert.equal((await validateArchiveRows(reader,{instanceId:f.profile.instanceId,createValidator:createArchiveStreamValidator})).exportSha256,archive.exportSha256);}finally{await reader.close();}
 const imported=importRepositoryState({dbPath:path.join(f.root,'cancel-import.sqlite'),instanceId:f.profile.instanceId,archive});try{assert.deepEqual((await imported.exportState()).tables.domain_events,archive.tables.domain_events);const backup=await imported.backupTo(path.join(f.root,'cancel-backup.sqlite')),restored=await restoreInstanceRepository({dbPath:path.join(f.root,'cancel-restore.sqlite'),backupPath:backup.path,expectedSha256:backup.sha256,instanceId:f.profile.instanceId});try{assert.deepEqual((await restored.exportState()).tables.domain_events,archive.tables.domain_events);}finally{await restored.close();}}finally{await imported.close();}
 await f.repo.readTransaction(async tx=>{const events=await tx.listEvents(),meta=await tx.getMetadata(),historicalContexts=await captureHistoricalEventContexts(tx,{events,instanceId:meta.instanceId}),proof=await validateModernEventsInChild({events,baseRelease:await tx.readRelease(),eventDirectory:'events',historicalContexts});assert(proof.proof.partition.some(r=>r.eventId===e.eventId&&r.recordValidator==='RUNTIME_MODERN'));});
 for(const mutate of [event=>{delete event.cancellationReceipt;event.schemaVersion='1.0';},event=>delete event.cancellationReceipt,event=>event.cancellationReceipt.schemaVersion='UNKNOWN',event=>event.cancellationReceipt.priorHead.sha256='0'.repeat(64),event=>event.cancellationReceipt.notCalledAttestation.evidenceRefs[0].sha256='0'.repeat(64),event=>event.cancellationReceipt.mutation.snapshotId='snapshot:invented']){
  const altered=structuredClone(archive),row=altered.tables.domain_events.find(r=>r.event_id===e.eventId),event=JSON.parse(Buffer.from(row.event_bytes.bytes,'base64'));mutate(event);const bytes=Buffer.from(canonicalJson(event));row.event_bytes={encoding:'base64',bytes:bytes.toString('base64')};row.event_sha256=sha256(bytes);delete altered.exportSha256;altered.exportSha256=sha256(canonicalJson(altered));assert.throws(()=>validateArchive(altered,f.profile.instanceId));
 }
 const protectedBefore=await f.repo.exportState(),fulfilled=await f.post(f.requests,'v8/execution-requests',{...body,executionRequestId:f.successor});assert.equal(fulfilled.status,409);assert.deepEqual(await f.repo.exportState(),protectedBefore);
 assert.equal(f.externalCalls(),0);
});
test('real PG requires observed NOT_CALLED evidence and exact prior head/CAS, not mere ledger absence',options,async t=>{
 const f=await setup(t),body=await f.body(),before=await f.repo.exportState();
 for(const patch of [{cancellation:{...body.cancellation,notCalledAttestation:{...body.cancellation.notCalledAttestation,evidenceRefs:[]}}},{cancellation:{...body.cancellation,expectedHead:{...body.cancellation.expectedHead,sha256:'0'.repeat(64)}}},{cancellation:{...body.cancellation,schemaVersion:'UNKNOWN'}},{action:'CLAIM'}]){const r=await f.post(f.requests,'v8/execution-requests',{...body,...patch});assert([409,422].includes(r.status),JSON.stringify(r.body));assert.deepEqual(await f.repo.exportState(),before);}
 const stale=await f.post(f.requests,'v8/execution-requests',body,{headers:{'If-Match':'"stale-cas"'}});assert.equal(stale.status,412);assert.deepEqual(await f.repo.exportState(),before);assert.equal(f.externalCalls(),0);
});
for(const state of ['SUBMITTED','RESULT_UNKNOWN'])test('real PG old '+state+' excludes versioned unstarted cancellation',options,async t=>{const f=await setup(t,{oldRun:state}),before=await f.repo.exportState(),r=await f.inspect();assert.equal(r.status,409,JSON.stringify(r.body));assert.deepEqual(await f.repo.exportState(),before);assert.equal(f.externalCalls(),0);});
test('real PG no attested immutable evidence remains pending although it has zero Run/candidate',options,async t=>{const f=await setup(t,{notCalled:false}),x=await f.inspect();assert.equal(x.status,200);assert.equal(x.body.cancellation.eligible,false);const before=await f.repo.exportState(),r=await f.post(f.requests,'v8/execution-requests',await f.body());assert.equal(r.status,409);assert.deepEqual(await f.repo.exportState(),before);});
test('real PG changed runtime epoch rejects the new path without rewriting old authorization',options,async t=>{const f=await setup(t),body=await f.body();await f.repo.pool.query('UPDATE repository_meta SET runtime_epoch=$1 WHERE singleton=1',['restore_v1_11111111-1111-4111-8111-111111111111']);const before=await f.repo.exportState(),r=await f.post(f.requests,'v8/execution-requests',body);assert.equal(r.status,409);assert.deepEqual(await f.repo.exportState(),before);});
test('actual PG concurrent start and cancellation share one CAS; a recorded Run cannot be hidden by refreshing CAS',options,async t=>{
 const f=await setup(t,{advance:false}),body=await f.body(),etag=(await f.store.operationalSnapshot()).mutationEtag,before=await f.repo.readView(),runBody={executionRequestId:f.old,executionDefinitionId:f.p.recipe.id,callPackageHash:f.p.recipe.definitionHash,state:'SUBMITTED',note:'Concurrent isolated protocol start; no provider.'};
 const [cancel,run]=await Promise.all([f.post(f.requests,'v8/execution-requests',body,{headers:{'If-Match':etag}}),f.post(f.runs,'v8/runs',runBody,{headers:{'If-Match':etag}})]);assert.equal([cancel,run].filter(r=>r.status===201).length,1,JSON.stringify({cancel,run}));assert([cancel,run].some(r=>[409,412].includes(r.status)));
 const after=await f.repo.readView();assert.equal(Object.values(after.eventsByKind).flat().length,Object.values(before.eventsByKind).flat().length+1);
 const refresh=await f.post(f.requests,'v8/execution-requests',body);assert.equal(refresh.status,409);assert.deepEqual((await f.repo.readView()).eventsByKind,after.eventsByKind);assert.equal(f.externalCalls(),0);
});

test('actual PG same-clock publication ambiguity rejects cancellation before append',options,async t=>{
 const f=await setup(t),body=await f.body(),NativeDate=Date,fixedTime=Date.now();
 // Publish two immutable, real disposable releases under an explicitly tied clock.
 globalThis.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:[fixedTime]));}static now(){return fixedTime;}};
 try{for(let i=0;i<2;i++)await f.repo.writeTransaction(async tx=>{const v=await tx.readView(),snapshot=structuredClone(v.snapshot),recipes=structuredClone(v.recipes);snapshot.snapshotId='snapshot_'+sha256(canonicalJson({old:snapshot.snapshotId,tied:i})).slice(0,32);recipes.snapshotId=snapshot.snapshotId;await tx.publishRelease({snapshot,recipes,expectedReleaseId:v.releaseId,sourceRevisionIds:v.sourceRevisionIds});});}finally{globalThis.Date=NativeDate;}
 const before=await f.repo.exportState(),response=await f.post(f.requests,'v8/execution-requests',body);assert.equal(response.status,409,JSON.stringify(response.body));assert.match(JSON.stringify(response.body),/唯一最新/);assert.deepEqual(await f.repo.exportState(),before);assert.equal(f.externalCalls(),0);
});
