import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {UNSTARTED_CANCELLATION_SCHEMA,unstartedRequestHistory,cancellationHeadProof,cancellationPublication,readUnstartedCancellationBasis,buildUnstartedCancellation,validateUnstartedCancellationEvents} from '../host/instance-runtime/execution-cancellation.mjs';
const hash=v=>sha256(canonicalJson(v));
export function cancellationFixture(){
 const runtime={instanceId:'instance:cancel-fixture',runtimeEpoch:'epoch:original'},base={eventKind:'execution-request',schemaVersion:'1.0',snapshotId:'snapshot:old',authorizationRuntime:runtime,executionRequestId:'xreq_old',workItemId:'work:neutral',familyId:'family:neutral',executionDefinitionId:'call:neutral',executionDefinitionHash:'a'.repeat(64),callPackageHash:'a'.repeat(64),inputBindings:[],inputBindingsHash:hash([]),executor:'CODEX',authorized:true,maxOutputs:1};
 const events=[{...base,eventId:'event:authorize',eventSequence:1,recordedAt:'2026-01-01T00:00:01Z',action:'AUTHORIZE',requestState:'AUTHORIZED',status:'AUTHORIZED'},{...base,eventId:'event:claim',eventSequence:2,recordedAt:'2026-01-01T00:00:02Z',action:'CLAIM',requestState:'CLAIMED',status:'CLAIMED'},{...base,eventId:'event:successor-claim',eventSequence:3,recordedAt:'2026-01-01T00:00:03Z',executionRequestId:'xreq_successor',action:'CLAIM',requestState:'CLAIMED',status:'CLAIMED',note:'Execution request xreq_old NOT_CALLED: no Run, no candidate, zero provider calls.'}];
 events[2].eventSequence=4;events.push({...base,eventId:'event:successor-authorize',eventSequence:3,recordedAt:'2026-01-01T00:00:02.500Z',executionRequestId:'xreq_successor',action:'AUTHORIZE',requestState:'AUTHORIZED',status:'AUTHORIZED'});
 const release={releaseId:'release:current',snapshotId:'snapshot:current',snapshotSha256:'b'.repeat(64),recipesSha256:'c'.repeat(64),profileRevisionId:'profile:current',sourceRevisionIds:[],createdAt:'2026-01-01T00:00:04Z'},basis={...unstartedRequestHistory(events,'xreq_old',runtime),runtime,publication:cancellationPublication(release)};
 const input={schemaVersion:UNSTARTED_CANCELLATION_SCHEMA,purpose:'CANCEL_UNSTARTED_ALLOCATION',requestSnapshotId:basis.head.snapshotId,expectedHead:cancellationHeadProof(basis.head),historyHash:basis.historyHash,notCalledAttestation:{confirmed:true,basis:'Executor observes no provider invocation for this exact old request.',evidenceRefs:basis.notCalledEvidence}},options={snapshotId:release.snapshotId,expectedEtag:'"current-cas"',note:'Revoke only the old unstarted allocation.'};
 const event={...buildUnstartedCancellation(basis,input,options),schemaVersion:'1.1',eventKind:'execution-request',eventId:'event:cancel',eventSequence:5,recordedAt:'2026-01-01T00:00:05Z'};
 return {runtime,events,release,basis,input,options,event,validate:(rows=[...events,event],publication=release)=>validateUnstartedCancellationEvents({events:rows,instanceId:runtime.instanceId,releaseContext:()=>publication})};
}
test('new cancel preserves exact old snapshot/binding and separate current mutation; original bytes do not change',()=>{const f=cancellationFixture(),before=canonicalJson(f.events);assert.equal(f.validate().length,1);assert.equal(f.event.snapshotId,'snapshot:old');assert.equal(f.event.cancellationReceipt.mutation.snapshotId,'snapshot:current');assert.equal(canonicalJson(f.events),before);});
for(const [label,mutate]of [['epoch',f=>f.runtime.runtimeEpoch='another'],['instance',f=>f.runtime.instanceId='another'],['missing prior claim',f=>f.events.splice(1,1)],['wrong prior hash',f=>f.event.cancellationReceipt.priorHead.sha256='0'.repeat(64)],['unknown schema',f=>f.event.schemaVersion='9.0'],['stripped receipt',f=>delete f.event.cancellationReceipt],['wrong action',f=>f.event.action='CLAIM'],['rewritten request snapshot',f=>f.event.snapshotId='snapshot:current'],['missing attestation',f=>delete f.event.cancellationReceipt.notCalledAttestation],['no observed NOT_CALLED reference',f=>f.event.cancellationReceipt.notCalledAttestation.evidenceRefs=[]],['wrong evidence hash',f=>f.event.cancellationReceipt.notCalledAttestation.evidenceRefs[0].sha256='0'.repeat(64)],['evidence about another request',f=>f.events[2].note='xreq_other NOT_CALLED'],['wrong event kind',f=>f.event.eventKind='run'],['later old execution',f=>f.events.push({eventId:'event:future',eventKind:'run',eventSequence:5,executionRequestId:'xreq_old'})]])test(label+' fails closed',()=>{const f=cancellationFixture();mutate(f);assert.throws(()=>f.validate());});
for(const state of ['PLANNED','SUBMITTED','RUNNING','RESULT_UNKNOWN','SUCCEEDED','FAILED','CANCELLED'])test('any recorded '+state+' run excludes the zero-Run protocol',()=>{const f=cancellationFixture();f.events.push({eventId:'run:e',eventSequence:3,eventKind:'run',executionRequestId:'xreq_old',runState:state});assert.throws(()=>f.validate());});
test('candidate and ambiguous unowned execution cannot be inferred absent',()=>{for(const row of [{eventKind:'asset-version',executionRequestId:'xreq_old'},{eventKind:'run',workItemId:'work:neutral'}]){const f=cancellationFixture();f.events.push({...row,eventId:'e',eventSequence:3});assert.throws(()=>f.validate());}});
test('new fulfilled successor output is unrelated and remains unchanged',()=>{const f=cancellationFixture();f.events.push({eventId:'run:successor',eventSequence:3,eventKind:'run',executionRequestId:'xreq_successor',runState:'SUCCEEDED'},{eventId:'candidate:successor',eventSequence:3,eventKind:'asset-version',executionRequestId:'xreq_successor',familyId:'family:neutral'});assert.equal(f.validate().length,1);});
for(const field of ['releaseId','snapshotId','snapshotSha256','recipesSha256','profileRevisionId'])test('actual mutation publication '+field+' cannot be self-declared',()=>{const f=cancellationFixture();f.release[field]='other';assert.throws(()=>f.validate());});
test('future or same-clock publication is not proved prior',()=>{const f=cancellationFixture();for(const createdAt of [f.event.recordedAt,'2027-01-01T00:00:00Z'])assert.throws(()=>f.validate(undefined,{...f.release,createdAt}));});
test('NOT_CALLED record must mention the whole exact request ID, not a prefix of another allocation',()=>{for(const note of ['xreq_old_other NOT_CALLED','prefixxreq_old NOT_CALLED']){const f=cancellationFixture();f.events[2].note=note;assert.deepEqual(unstartedRequestHistory(f.events,'xreq_old',f.runtime).notCalledEvidence,[]);}});
test('orphan or rebound NOT_CALLED claim cannot substitute for a real recorded execution chain',()=>{for(const fault of ['missing','rebound']){const f=cancellationFixture();if(fault==='missing')f.events.pop();else f.events[3].callPackageHash='0'.repeat(64);assert.deepEqual(unstartedRequestHistory(f.events,'xreq_old',f.runtime).notCalledEvidence,[]);}});
test('same-clock current publication is rejected while preparing, before any cancellation append',async()=>{
 const f=cancellationFixture(),now=Date.now(),snapshotBytes=Buffer.from(canonicalJson({snapshotId:f.release.snapshotId})),recipesBytes=Buffer.from(canonicalJson({snapshotId:f.release.snapshotId})),release={...f.release,createdAt:new Date(now).toISOString(),snapshotBytes,recipesBytes,snapshotSha256:sha256(snapshotBytes),recipesSha256:sha256(recipesBytes)},oldNow=Date.now;
 const tx={getMetadata:async()=>f.runtime,listEvents:async()=>f.events,readRelease:async()=>release};Date.now=()=>now;try{await assert.rejects(readUnstartedCancellationBasis(tx,{executionRequestId:'xreq_old'}),/同毫秒/);}finally{Date.now=oldNow;}
});

test('NOT_CALLED evidence has an exact declaration grammar and excludes misleading prose',()=>{
 for(const note of ['xreq_old WAS_CALLED; xreq_new NOT_CALLED','xreq_old NOT_CALLED claim is false; provider invocation happened.','Execution request xreq_old NOT_CALLED: no Run, no candidate, zero provider calls. This claim is false.']){const f=cancellationFixture();f.events[2].note=note;assert.deepEqual(unstartedRequestHistory(f.events,'xreq_old',f.runtime).notCalledEvidence,[]);assert.throws(()=>f.validate());}
 const f=cancellationFixture();f.events[2].note='Continuation of xreq_old after snapshot change. Prior allocation NOT_CALLED: no Run, no candidate, zero provider calls; evidence worker-results/V11.json. First actual provider attempt only; no retry.';
 assert.equal(unstartedRequestHistory(f.events,'xreq_old',f.runtime).notCalledEvidence.length,1);
 f.events[2].note=f.events[2].note.replace('xreq_old after','xreq_old_other after');assert.deepEqual(unstartedRequestHistory(f.events,'xreq_old',f.runtime).notCalledEvidence,[]);
});
test('write preparation requires the same unique latest publication as archive history',async()=>{
 const f=cancellationFixture(),snapshotBytes=Buffer.from(canonicalJson({snapshotId:f.release.snapshotId})),recipesBytes=Buffer.from(canonicalJson({snapshotId:f.release.snapshotId})),release={...f.release,snapshotBytes,recipesBytes,snapshotSha256:sha256(snapshotBytes),recipesSha256:sha256(recipesBytes)};
 const tx={getMetadata:async()=>f.runtime,listEvents:async()=>f.events,readRelease:async()=>release,readPublishedReleaseTimeGroup:async()=>[release]};
 assert.equal((await readUnstartedCancellationBasis(tx,{executionRequestId:'xreq_old'})).publication.releaseId,release.releaseId);
 for(const group of [[],[release,{...release,releaseId:'release:same-clock'}],[{...release,releaseId:'release:other'}]]){tx.readPublishedReleaseTimeGroup=async()=>group;await assert.rejects(readUnstartedCancellationBasis(tx,{executionRequestId:'xreq_old'}),/唯一最新/);}
});

test('independent cancellation action prevents receipt plus schema downgrade into legacy CANCEL',()=>{
 const f=cancellationFixture();assert.equal(f.event.action,'CANCEL_UNSTARTED');delete f.event.cancellationReceipt;f.event.schemaVersion='1.0';assert.throws(()=>f.validate(),/schema1.1/);
});
