import {previewAuthoringAdoption,adoptAuthoringPlan} from '../../../../host/instance-runtime/domain-authoring-sync.mjs';
import {getAuthoring,saveAuthoringRoot,type AuthoringRootInput,type AuthoringRoot} from '../../../../host/instance-runtime/domain-authoring.mjs';
import {hostedReadOnlyMode,reviewData,currentCreativeSubjectBaseHash} from '../../v8/_store';
import {POST as registerCreativeRevision} from '../../v8/creative-revisions/route';
import {domainRepository,domainMutation,domainError,domainBody,requiredString,expectedRevision,jsonResponse,HttpError} from '../_domain';
export async function GET(){try{if(hostedReadOnlyMode()){const data=await reviewData(),model=data.productionModel as typeof data.productionModel&{genericAuthoring?:{roots:AuthoringRoot[]};initialization?:{state:string}};return jsonResponse({releaseId:'HOSTED_READ_ONLY',roots:model.genericAuthoring?.roots||[],initializationReady:model.initialization?.state==='READY',readOnly:true,denominatorState:'UNKNOWN'});}const repo=await domainRepository();return await repo.readTransaction(async tx=>jsonResponse(await getAuthoring(tx)));}catch(e){return domainError(e);}}
export async function POST(request:Request){try{const {idempotencyKey}=await domainMutation(request);const body=domainBody(await request.json(),['action','root','rootId','expectedReleaseId','expectedRevisionId','creativeRevisionId','reviewEventId','previewHash']);const repo=await domainRepository();
 if(body.action==='adoptionPreview'||body.action==='adopt'){const input={expectedReleaseId:requiredString(body,'expectedReleaseId'),rootId:requiredString(body,'rootId'),expectedRevisionId:requiredString(body,'expectedRevisionId'),creativeRevisionId:requiredString(body,'creativeRevisionId'),reviewEventId:requiredString(body,'reviewEventId')};return body.action==='adoptionPreview'?await repo.readTransaction(async tx=>jsonResponse(await previewAuthoringAdoption(tx,input))):await repo.writeTransaction(async tx=>jsonResponse(await adoptAuthoringPlan(tx,{...input,previewHash:requiredString(body,'previewHash'),requestId:idempotencyKey})));}
 if(body.action==='submit'){
  const state=await repo.readTransaction(tx=>getAuthoring(tx));if(state.releaseId!==requiredString(body,'expectedReleaseId'))throw new HttpError(409,'实例已变化');const root=state.roots.find(r=>r.id===requiredString(body,'rootId'));if(!root||root.revisionId!==expectedRevision(body,'expectedRevisionId')||root.kind!=='EPISODE_PLAN'||!root.planContent)throw new HttpError(422,'请先保存完整结构化分集卷宗');
  const scriptRoot=state.roots.find(r=>r.id===root.parentId&&r.revisionId===root.parentRevisionId),storyRoot=state.roots.find(r=>r.id===scriptRoot?.parentId&&r.revisionId===scriptRoot?.parentRevisionId);const data=await reviewData(),script=data.productionModel.scriptRevisions?.find(r=>r.id===scriptRoot?.revisionId),story=data.productionModel.storyRevisions?.find(r=>r.id===storyRoot?.revisionId);if(!script||!story)throw new HttpError(422,'分集候选需要已登记故事和剧本依据');
  const payload={snapshotId:data.snapshotId,subjectKind:'EPISODE_PLAN',subjectId:root.planContent.planId,baseRevisionHash:currentCreativeSubjectBaseHash(data,'EPISODE_PLAN',root.planContent.planId),content:root.planContent,authorityClass:'A',basisBindings:[{bindingType:'STORY_REVISION',bindingId:story.id,bindingHash:story.revisionHash},{bindingType:'SCRIPT_REVISION',bindingId:script.id,bindingHash:script.revisionHash}],evidenceRefs:[`authoring:${root.id}@${root.revisionId}#sha256=${root.sha256}`,...root.sourceBindings.map(b=>`${b.sourceId}@${b.revisionId}#sha256=${b.sha256}`)],note:'由作者完整首稿登记候选；等待分集审阅与受控采用。'};
  return registerCreativeRevision(new Request(new URL('/api/v8/creative-revisions',request.url),{method:'POST',headers:request.headers,body:JSON.stringify(payload)}));
 }
 if(body.action!=='save')throw new HttpError(422,'不支持的创作操作');return await repo.writeTransaction(async tx=>jsonResponse(await saveAuthoringRoot(tx,{expectedReleaseId:requiredString(body,'expectedReleaseId'),expectedRevisionId:expectedRevision(body,'expectedRevisionId'),root:body.root as AuthoringRootInput,requestId:idempotencyKey})));}catch(e){return domainError(e);}}
