'use client';
import {useEffect,useRef,useState} from 'react';
import type {AnimaticTimeline,AnimaticMedia} from '../host/instance-runtime/animatic-model.mjs';
import type {AnimaticState} from '../host/instance-runtime/animatic-service.mjs';
import {managementMutation,readManagementResponse} from './system-management-client';
import {useManagementDraftGuard} from './management-draft-guard';
import './animatic-workspace.css';

const endpoint='/api/instance/shot-production/animatics';
const binding=(m:AnimaticMedia):AnimaticMedia=>({familyId:m.familyId,versionId:m.versionId,sha256:m.sha256});
const uid=()=>`clip_${crypto.randomUUID()}`;
function TimelineAudio({url,start,sourceIn,duration,frame,playing,volume}:{url:string;start:number;sourceIn:number;duration:number;frame:number;playing:boolean;volume:number}){
 const ref=useRef<HTMLAudioElement>(null);
 useEffect(()=>{const audio=ref.current;if(!audio)return;audio.volume=volume;const active=frame>=start&&frame<start+duration;const target=(sourceIn+Math.max(0,frame-start))/24;if(active&&Math.abs(audio.currentTime-target)>0.15)audio.currentTime=target;if(playing&&active)void audio.play().catch(()=>{});else audio.pause();},[frame,playing,start,duration,sourceIn,volume]);
 return <audio ref={ref} src={url} preload="metadata"/>;
}
export function AnimaticWorkspace({sceneId,readOnly=false,onChanged}:{sceneId:string;readOnly?:boolean;onChanged?:()=>void}){
 const [state,setState]=useState<(AnimaticState&{readOnly?:boolean})|null>(null),[draft,setDraft]=useState<AnimaticTimeline|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[attempt,setAttempt]=useState(0);
 const dirtyRef=useRef(false);dirtyRef.current=dirty;useManagementDraftGuard(dirty,'镜头预演时间线');
 useEffect(()=>{const abort=new AbortController();void fetch(endpoint+'?sceneId='+encodeURIComponent(sceneId),{cache:'no-store',signal:abort.signal}).then(readManagementResponse<AnimaticState&{readOnly?:boolean}>).then(value=>{if(abort.signal.aborted)return;if(dirtyRef.current)return;setState(value);setDraft(value.content);setError('');}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[sceneId,attempt]);
 useEffect(()=>{if(!state?.jobs.some(j=>['QUEUED','RUNNING'].includes(j.status)))return;const timer=setInterval(()=>setAttempt(a=>a+1),5000);return()=>clearInterval(timer);},[state?.jobs]);
 const disabled=readOnly||state?.readOnly||busy||state?.stale,total=draft?.shots.reduce((n,s)=>n+s.durationFrames,0)||0;
 useEffect(()=>{if(!playing||!total)return;let handle=0;const started=performance.now(),initial=frame;const tick=(now:number)=>{const next=initial+Math.floor((now-started)*24/1000);if(next>=total){setFrame(total-1);setPlaying(false);return;}setFrame(next);handle=requestAnimationFrame(tick);};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[playing,total]); // The starting frame is captured once per playback.
 function edit(change:(value:AnimaticTimeline)=>void){if(!draft||disabled)return;const next=structuredClone(draft);change(next);setDraft(next);setDirty(true);setPlaying(false);}
 function initialize(){if(!state?.basis)return;setDraft({schemaVersion:'1.0',sceneId,shotPlanRevisionId:state.basis.shotPlanRevisionId,fps:24,width:1920,height:1080,shots:state.basis.shots.map(s=>({shotId:s.shotId,durationFrames:s.durationFrames,panels:[],beats:[]})),audio:[],cards:[]});setDirty(true);}
 async function mutate(action:'save'|'render'){if(!state||!draft)return;setBusy(true);setError('');try{await managementMutation(endpoint,{action,sceneId,expectedReleaseId:state.releaseId,expectedRevisionId:state.revisionId,...(action==='save'?{content:draft}:{timelineRevisionId:state.timelineRevisionId})});setDirty(false);dirtyRef.current=false;setAttempt(a=>a+1);onChanged?.();}catch(e){setError(e instanceof Error?e.message:'预演操作未完成');}finally{setBusy(false);}}
 let cursor=0;const scheduled=(draft?.shots||[]).map(s=>{const start=cursor;cursor+=s.durationFrames;return{...s,start,end:cursor};}),current=scheduled.find(s=>frame>=s.start&&frame<s.end)||scheduled[0],local=current?frame-current.start:0,panel=current?.panels.find(p=>local>=p.startFrame&&local<p.endFrame),mediaUrl=(versionId:string)=>state?.availableMedia.find(m=>m.versionId===versionId)?.mediaUrl||'',images=state?.availableMedia.filter(m=>/\.(png|jpe?g|webp)$/i.test(m.path||''))||[],sounds=state?.availableMedia.filter(m=>/\.(wav|mp3|m4a|flac)$/i.test(m.path||''))||[];
 const scale=panel?.motion==='PUSH_IN'?1+0.08*(local-panel.startFrame)/Math.max(1,panel.endFrame-panel.startFrame-1):panel?.motion==='PULL_OUT'?1.08-0.08*(local-panel.startFrame)/Math.max(1,panel.endFrame-panel.startFrame-1):1;
 return <section className="animatic-workspace" aria-label="场级预演时间线"><header><h3>场级预演与锁时</h3><p>以粗分镜和声音校准镜头顺序、时长与动作节拍。草稿播放和文件生成均不代表完成正式审阅。</p></header>
 {error&&<p role="alert" className="animatic-error">{error}</p>}{state?.blockers.map(b=><p key={b}>{b}</p>)}{state?.stale&&<p role="alert">镜头设计已变化；此时间线保留为历史，须从当前计划重新绑定。</p>}
 {!state&&!error?<p>正在读取本场时间线…</p>:!draft?<div><p>本场尚无预演时间线。只有已采用并同步的正式镜头计划才能建立时间线。</p>{state?.basis&&!readOnly&&!state.readOnly&&<button onClick={initialize}>从当前镜头计划建立预演草稿</button>}</div>:<>
 <div className="animatic-preview" aria-label="预演画面">{panel&&mediaUrl(panel.media.versionId)?<img src={mediaUrl(panel.media.versionId)} alt={`${current.shotId} 粗分镜`} style={{transform:`scale(${scale})`}}/>:<span>{current?.shotId} · 待选粗分镜</span>}{draft.cards.filter(c=>c.shotId===current?.shotId&&local>=c.startFrame&&local<c.endFrame).map(c=><span key={c.id} className="animatic-card" style={{left:c.style.x/19.2+'%',top:c.style.y/10.8+'%',fontSize:c.style.fontSize/19.2+'cqw',color:c.style.color}}>{c.textLines.join('\n')}<small>草稿字体预览；精确字体以渲染候选为准</small></span>)}</div>
 <div className="animatic-controls"><button onClick={()=>{if(frame>=total-1)setFrame(0);setPlaying(p=>!p);}} disabled={!total}>{playing?'暂停':'播放草稿'}</button><input aria-label="预演播放位置" type="range" min={0} max={Math.max(0,total-1)} value={Math.min(frame,Math.max(0,total-1))} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/><span>{frame} / {total} 帧 · {(total/24).toFixed(3)} 秒</span></div>
 {draft.audio.filter(a=>!a.muted&&mediaUrl(a.media.versionId)).map(a=><TimelineAudio key={a.id} url={mediaUrl(a.media.versionId)} start={(scheduled.find(s=>s.shotId===a.anchorShotId)?.start||0)+a.offsetFrames} sourceIn={a.sourceInFrames} duration={a.durationFrames} frame={frame} playing={playing} volume={a.volume}/>)}
 <div className="animatic-shot-strip">{scheduled.map(s=><button key={s.shotId} className={current?.shotId===s.shotId?'active':''} onClick={()=>{setPlaying(false);setFrame(s.start);}}><b>{s.shotId}</b><span>{s.durationFrames} 帧 · {(s.durationFrames/24).toFixed(3)} 秒</span></button>)}</div>
 <div className="animatic-editors">{draft.shots.map((s,index)=><fieldset key={s.shotId} disabled={disabled}><legend>{s.shotId}</legend><div className="animatic-row"><button disabled={index===0} onClick={()=>edit(v=>{[v.shots[index-1],v.shots[index]]=[v.shots[index],v.shots[index-1]];})}>前移</button><button disabled={index===draft.shots.length-1} onClick={()=>edit(v=>{[v.shots[index+1],v.shots[index]]=[v.shots[index],v.shots[index+1]];})}>后移</button><label>镜长（帧）<input type="number" min={1} max={14400} value={s.durationFrames} onChange={e=>edit(v=>{const value=Math.max(1,Number(e.target.value)),shot=v.shots[index];shot.durationFrames=value;if(shot.panels.length===1)shot.panels[0].endFrame=value;})}/></label><small>{(s.durationFrames/24).toFixed(3)} 秒；非整秒按帧明确保存</small></div>
 {s.panels.length===0?<label>选择已放行粗分镜<select value="" onChange={e=>{const media=images.find(m=>m.versionId===e.target.value);if(media)edit(v=>{v.shots[index].panels=[{id:uid(),media:binding(media),startFrame:0,endFrame:s.durationFrames,motion:'STILL'}];});}}><option value="">请选择精确版本</option>{images.map(m=><option key={m.versionId} value={m.versionId}>{m.label} · {m.versionId}</option>)}</select></label>:s.panels.map((p,i)=><div className="animatic-row" key={p.id}><select aria-label="粗分镜版本" value={p.media.versionId} onChange={e=>{const media=images.find(m=>m.versionId===e.target.value);if(media)edit(v=>{v.shots[index].panels[i].media=binding(media);});}}>{images.map(m=><option key={m.versionId} value={m.versionId}>{m.label}</option>)}</select><label>入帧<input type="number" min={0} value={p.startFrame} onChange={e=>edit(v=>{v.shots[index].panels[i].startFrame=Number(e.target.value);})}/></label><label>出帧<input type="number" min={1} value={p.endFrame} onChange={e=>edit(v=>{v.shots[index].panels[i].endFrame=Number(e.target.value);})}/></label><select aria-label="粗分镜运动" value={p.motion} onChange={e=>edit(v=>{v.shots[index].panels[i].motion=e.target.value as typeof p.motion;})}><option value="STILL">固定</option><option value="PUSH_IN">缓推</option><option value="PULL_OUT">缓拉</option></select></div>)}
 {s.panels.length===1&&s.durationFrames>1&&<button onClick={()=>edit(v=>{const p=v.shots[index].panels[0],end=p.endFrame,middle=Math.floor(end/2);p.endFrame=middle;v.shots[index].panels.push({...structuredClone(p),id:uid(),startFrame:middle,endFrame:end});})}>增加中间粗分镜</button>}
 {s.beats.map((b,i)=><div className="animatic-row" key={b.id}><label>动作帧<input type="number" min={0} max={s.durationFrames-1} value={b.frame} onChange={e=>edit(v=>{v.shots[index].beats[i].frame=Number(e.target.value);})}/></label><label>动作节拍<input value={b.label} onChange={e=>edit(v=>{v.shots[index].beats[i].label=e.target.value;})}/></label><button onClick={()=>edit(v=>{v.shots[index].beats.splice(i,1);})}>删除动作点</button></div>)}<button onClick={()=>edit(v=>{v.shots[index].beats.push({id:uid(),frame:0,label:'待填写动作节拍'});})}>添加动作点</button>
 </fieldset>)}</div>
 <fieldset disabled={disabled}><legend>对白与临时声音</legend><p>临时对白可参与锁时；正面对白视频仍须最终干声放行。音乐、音效仅作节奏参考。</p>{draft.audio.map((a,index)=><div className="animatic-audio-editor" key={a.id}><b>{state?.availableMedia.find(m=>m.versionId===a.media.versionId)?.label||a.media.versionId}</b><select aria-label="声音用途" value={a.role} onChange={e=>edit(v=>{v.audio[index].role=e.target.value as typeof a.role;})}><option value="DIALOGUE">对白</option><option value="MUSIC">临时音乐</option><option value="SFX">临时音效</option></select><label>锚定镜头<select value={a.anchorShotId} onChange={e=>edit(v=>{v.audio[index].anchorShotId=e.target.value;})}>{draft.shots.map(s=><option key={s.shotId}>{s.shotId}</option>)}</select></label>{([['offsetFrames','偏移帧'],['sourceInFrames','源入帧'],['durationFrames','持续帧']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={a[key]} onChange={e=>edit(v=>{v.audio[index][key]=Number(e.target.value);})}/></label>)}<label>台词身份（逗号分隔）<input value={a.lineIds.join(',')} onChange={e=>edit(v=>{v.audio[index].lineIds=e.target.value.split(',').map(x=>x.trim()).filter(Boolean);})}/></label><label>音量<input type="range" min={0} max={1} step={0.05} value={a.volume} onChange={e=>edit(v=>{v.audio[index].volume=Number(e.target.value);})}/></label><label><input type="checkbox" checked={a.temporary} onChange={e=>edit(v=>{v.audio[index].temporary=e.target.checked;})}/>临时声音</label><label><input type="checkbox" checked={a.muted} onChange={e=>edit(v=>{v.audio[index].muted=e.target.checked;})}/>静音</label><button onClick={()=>edit(v=>{v.audio.splice(index,1);})}>移除此音轨</button></div>)}<label>添加已放行声音<select value="" onChange={e=>{const media=sounds.find(m=>m.versionId===e.target.value);if(media)edit(v=>{v.audio.push({id:uid(),media:binding(media),anchorShotId:v.shots[0].shotId,offsetFrames:0,sourceInFrames:0,durationFrames:Math.min(total,24),role:'DIALOGUE',temporary:true,volume:1,muted:false,lineIds:[]});});}}><option value="">选择已登记声音版本</option>{sounds.map(m=><option key={m.versionId} value={m.versionId}>{m.label}</option>)}</select></label></fieldset>
 {(draft.cards.length>0||Boolean(state?.requiredCards?.length))&&<fieldset disabled={disabled}><legend>人物信息卡</legend><p>沿用本场已发布的两行文案。出入帧、字体和排版随时间线形成新修订。</p>{draft.cards.map((c,index)=><div className="animatic-row" key={c.id}><b>{c.textLines.join('／')}</b><label>镜头<select value={c.shotId} onChange={e=>edit(v=>{v.cards[index].shotId=e.target.value;})}>{draft.shots.map(s=><option key={s.shotId}>{s.shotId}</option>)}</select></label>{([['startFrame','入帧'],['endFrame','出帧']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={c[key]} onChange={e=>edit(v=>{v.cards[index][key]=Number(e.target.value);})}/></label>)}{([['x','安全区横向位置'],['y','安全区纵向位置'],['fontSize','字号']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={c.style[key]} onChange={e=>edit(v=>{v.cards[index].style[key]=Number(e.target.value);})}/></label>)}<label>颜色<input type="color" value={c.style.color} onChange={e=>edit(v=>{v.cards[index].style.color=e.target.value;})}/></label><button onClick={()=>edit(v=>{v.cards.splice(index,1);})}>移除此卡</button><small>精确字体由已登记版本绑定</small></div>)}{state?.requiredCards?.filter(card=>!draft.cards.some(c=>c.specRevisionId===card.specRevisionId)).map(card=><label key={card.requirementId}>为“{card.textLines.join('／')}”选择已放行字体<select value="" onChange={e=>{const font=state.availableMedia.find(m=>m.versionId===e.target.value);if(font)edit(v=>{v.cards.push({id:uid(),shotId:v.shots[0].shotId,startFrame:0,endFrame:Math.min(v.shots[0].durationFrames,48),textLines:card.textLines,fontMedia:binding(font),style:{fontSize:48,x:120,y:800,color:'#ffffff'},specRevisionId:card.specRevisionId,specHash:card.specHash});});}}><option value="">选择精确字体文件（TTF/OTF）</option>{state.availableMedia.filter(m=>/\.(ttf|otf)$/i.test(m.path)).map(m=><option key={m.versionId} value={m.versionId}>{m.label}</option>)}</select></label>)}</fieldset>}
 <div className="animatic-controls"><button disabled={disabled||!dirty} onClick={()=>void mutate('save')}>保存时间线新修订</button><button disabled={disabled||dirty||!state?.timelineRevisionId||Boolean(state.jobs.some(j=>['QUEUED','RUNNING','RESULT_UNKNOWN'].includes(j.status)))} onClick={()=>void mutate('render')}>生成审阅预演</button><span>{dirty?'有未保存修改':state?.lock?.timelineRevisionId===state?.timelineRevisionId?'本修订已有正式锁时':'待正式审阅锁时'}</span></div>
 {state&&state.impact.length>0&&<p>本次影响：{state.impact.map(i=>`${i.shotId}（${[i.timingChanged?'时间':'',i.visualChanged?'粗分镜':'',i.overlayChanged?'人物卡':'',i.boundaryChanged?'邻接':''].filter(Boolean).join('、')}）`).join('；')}</p>}
 </>}
 {state?.jobs.map(job=><section className="animatic-render-result" key={job.jobId}><p>{job.status==='SUCCEEDED'?'审阅预演已生成':job.status==='RUNNING'?'正在渲染':job.status==='QUEUED'?'等待预演工作器':job.status==='RESULT_UNKNOWN'?'结果待核查':'渲染未完成'}{job.timelineRevisionId!==state.timelineRevisionId?' · 历史修订':''}</p>{job.error&&<p role="alert">{job.error}</p>}{job.result?.mediaUrl&&<video controls preload="metadata" src={job.result.mediaUrl}/>}</section>)}
 </section>;
}
