'use client';
import {useEffect,useRef,useState} from 'react';
import type {AnimaticTimeline,AnimaticMedia} from '../host/instance-runtime/animatic-model.mjs';
import type {AnimaticState} from '../host/instance-runtime/animatic-service.mjs';
import {readManagementResponse} from './system-management-client';
import {useManagementDraftGuard} from './management-draft-guard';
import './animatic-workspace.css';

const endpoint='/api/instance/shot-production/animatics';
const binding=(m:AnimaticMedia):AnimaticMedia=>({familyId:m.familyId,versionId:m.versionId,sha256:m.sha256});
const uid=()=>`clip_${crypto.randomUUID()}`;
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const text=(value:unknown):value is string=>typeof value==='string';
const identity=(value:unknown):value is string=>text(value)&&Boolean(value.trim());
const nullableIdentity=(value:unknown)=>value===null||identity(value);
const finite=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const frames=(value:unknown)=>finite(value)&&Number.isSafeInteger(value)&&value>=0;
const list=(value:unknown,valid:(row:unknown)=>boolean)=>Array.isArray(value)&&value.every(valid);
const mediaBinding=(value:unknown)=>record(value)&&identity(value.familyId)&&identity(value.versionId)&&identity(value.sha256);
/** Validate the UI's read contract before replacing state or clearing UNKNOWN. */
function validateState(value:unknown,sceneId:string):AnimaticState&{readOnly?:boolean}{
 const panel=(p:unknown)=>record(p)&&identity(p.id)&&mediaBinding(p.media)&&frames(p.startFrame)&&frames(p.endFrame)&&['STILL','PUSH_IN','PULL_OUT'].includes(String(p.motion));
 const shot=(s:unknown)=>record(s)&&identity(s.shotId)&&frames(s.durationFrames)&&Number(s.durationFrames)>0&&list(s.panels,panel)&&list(s.beats,b=>record(b)&&identity(b.id)&&frames(b.frame)&&text(b.label));
 const audio=(a:unknown)=>record(a)&&identity(a.id)&&identity(a.anchorShotId)&&mediaBinding(a.media)&&finite(a.offsetFrames)&&frames(a.sourceInFrames)&&frames(a.durationFrames)&&['DIALOGUE','MUSIC','SFX'].includes(String(a.role))&&typeof a.temporary==='boolean'&&typeof a.muted==='boolean'&&finite(a.volume)&&list(a.lineIds,text);
 const card=(c:unknown)=>record(c)&&identity(c.id)&&identity(c.shotId)&&frames(c.startFrame)&&frames(c.endFrame)&&list(c.textLines,text)&&mediaBinding(c.fontMedia)&&identity(c.specRevisionId)&&identity(c.specHash)&&record(c.style)&&finite(c.style.fontSize)&&finite(c.style.x)&&finite(c.style.y)&&text(c.style.color);
 const timeline=(c:unknown)=>record(c)&&c.schemaVersion==='1.0'&&c.sceneId===sceneId&&identity(c.shotPlanRevisionId)&&c.fps===24&&c.width===1920&&c.height===1080&&Array.isArray(c.shots)&&c.shots.length>0&&list(c.shots,shot)&&list(c.audio,audio)&&list(c.cards,card);
 const job=(j:unknown)=>record(j)&&identity(j.jobId)&&identity(j.status)&&identity(j.timelineRevisionId)&&(j.jobRevisionId===undefined||identity(j.jobRevisionId))&&(j.error==null||text(j.error))&&(j.result==null||record(j.result)&&text(j.result.mediaUrl))&&(j.pendingReconciliation==null||record(j.pendingReconciliation)&&identity(j.pendingReconciliation.reconciliationId)&&identity(j.pendingReconciliation.status))&&(j.lastReconciliation==null||record(j.lastReconciliation)&&identity(j.lastReconciliation.status)&&(j.lastReconciliation.error==null||text(j.lastReconciliation.error)))&&(j.reconciliation==null||record(j.reconciliation)&&identity(j.reconciliation.outcome));
 if(!record(value)||value.sceneId!==sceneId||!identity(value.releaseId)||!nullableIdentity(value.revisionId)||!nullableIdentity(value.timelineRevisionId)||(value.runtimeEpoch!==undefined&&!identity(value.runtimeEpoch))||(value.readOnly!==undefined&&typeof value.readOnly!=='boolean')||typeof value.stale!=='boolean'||!list(value.blockers,text)||!list(value.impact,i=>record(i)&&identity(i.shotId)&&['timingChanged','visualChanged','overlayChanged','boundaryChanged'].every(key=>typeof i[key]==='boolean'))||!list(value.availableMedia,m=>record(m)&&mediaBinding(m)&&text(m.label)&&text(m.kind)&&text(m.path)&&text(m.mediaUrl))||!list(value.requiredCards,c=>record(c)&&identity(c.requirementId)&&identity(c.specRevisionId)&&identity(c.specHash)&&list(c.textLines,text))||!list(value.jobs,job)||(value.hashes!==null&&!(record(value.hashes)&&identity(value.hashes.timelineHash)&&frames(value.hashes.totalFrames)))||(value.lock!==null&&!(record(value.lock)&&identity(value.lock.timelineRevisionId)&&identity(value.lock.reviewEventId)))||(value.content===null?value.timelineRevisionId!==null:!identity(value.timelineRevisionId)||!timeline(value.content))||(value.basis!==null&&!(record(value.basis)&&value.basis.sceneId===sceneId&&identity(value.basis.shotPlanRevisionId)&&Array.isArray(value.basis.shots)&&value.basis.shots.length>0&&list(value.basis.shots,s=>record(s)&&identity(s.shotId)&&text(s.title)&&frames(s.durationFrames)&&Number(s.durationFrames)>0))))throw Error('时间线回执无效，请继续重读；草稿与待核状态已保留');
 return value as AnimaticState&{readOnly?:boolean};
}
function TimelineAudio({url,start,sourceIn,duration,frame,playing,volume}:{url:string;start:number;sourceIn:number;duration:number;frame:number;playing:boolean;volume:number}){
 const ref=useRef<HTMLAudioElement>(null);
 useEffect(()=>{const audio=ref.current;if(!audio)return;audio.volume=volume;const active=frame>=start&&frame<start+duration;const target=(sourceIn+Math.max(0,frame-start))/24;if(active&&Math.abs(audio.currentTime-target)>0.15)audio.currentTime=target;if(playing&&active)void audio.play().catch(()=>{});else audio.pause();},[frame,playing,start,duration,sourceIn,volume]);
 return <audio ref={ref} src={url} preload="metadata"/>;
}
type WorkspaceProps={sceneId:string;readOnly?:boolean;onChanged?:()=>void};
export function AnimaticWorkspace(props:WorkspaceProps){return <AnimaticWorkspaceInner key={props.sceneId} {...props}/>;}
function AnimaticWorkspaceInner({sceneId,readOnly=false,onChanged}:WorkspaceProps){
 const [state,setState]=useState<(AnimaticState&{readOnly?:boolean})|null>(null),[draft,setDraft]=useState<AnimaticTimeline|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[attempt,setAttempt]=useState(0),[uncertain,setUncertain]=useState(false);
 const dirtyRef=useRef(false);useManagementDraftGuard(dirty||uncertain,'镜头预演时间线');
 useEffect(()=>{const abort=new AbortController();void fetch(endpoint+'?sceneId='+encodeURIComponent(sceneId),{cache:'no-store',signal:abort.signal}).then(readManagementResponse<unknown>).then(result=>{if(abort.signal.aborted)return;const value=validateState(result,sceneId);setState(value);if(!dirtyRef.current)setDraft(value.content);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[sceneId,attempt]);
 useEffect(()=>{if(!state?.jobs.some(j=>['QUEUED','RUNNING'].includes(j.status)||j.pendingReconciliation?.status==='QUEUED'))return;const timer=setInterval(()=>setAttempt(a=>a+1),5000);return()=>clearInterval(timer);},[state?.jobs]);
 const blocked=readOnly||state?.readOnly||busy||uncertain,disabled=blocked||!state?.basis||draft?.shotPlanRevisionId!==state.basis.shotPlanRevisionId,total=draft?.shots.reduce((n,s)=>n+s.durationFrames,0)||0;
 useEffect(()=>{if(!playing||!total)return;let handle=0;const started=performance.now(),initial=frame;const tick=(now:number)=>{const next=initial+Math.floor((now-started)*24/1000);if(next>=total){setFrame(total-1);setPlaying(false);return;}setFrame(next);handle=requestAnimationFrame(tick);};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[playing,total]); // The starting frame is captured once per playback.
 function edit(change:(value:AnimaticTimeline)=>void){if(!draft||disabled)return;const next=structuredClone(draft);change(next);setDraft(next);setDirty(true);dirtyRef.current=true;setPlaying(false);}
 function initialize(){if(!state?.basis||blocked)return;setFrame(0);setPlaying(false);setDraft({schemaVersion:'1.0',sceneId,shotPlanRevisionId:state.basis.shotPlanRevisionId,fps:24,width:1920,height:1080,shots:state.basis.shots.map(s=>({shotId:s.shotId,durationFrames:s.durationFrames,panels:[],beats:[]})),audio:[],cards:[]});setDirty(true);dirtyRef.current=true;}
 async function reread(){const next=validateState(await readManagementResponse<unknown>(await fetch(endpoint+'?sceneId='+encodeURIComponent(sceneId),{cache:'no-store'})),sceneId);setState(next);if(!dirtyRef.current)setDraft(next.content);return next;}
 async function verifyCurrent(){setBusy(true);try{await reread();setUncertain(false);setError('');}catch(e){setError(e instanceof Error?e.message:'重读未完成');}finally{setBusy(false);}}
 async function mutate(action:'save'|'render'|'reconcile',job?:AnimaticState['jobs'][number]){
  if(!state||blocked||action!=='reconcile'&&!draft)return;setBusy(true);setError('');let submitted=false;
  try{
   const snapshot=await readManagementResponse<{mutationEtag:string}>(await fetch('/api/v8/operations/snapshot?summary=1',{cache:'no-store'}));if(!snapshot.mutationEtag?.trim())throw Error('缺少当前制作状态，请重读');
   const body=action==='reconcile'?{action,sceneId,jobId:job?.jobId,expectedJobRevisionId:job?.jobRevisionId,expectedRuntimeEpoch:state.runtimeEpoch,expectedReleaseId:state.releaseId}:{action,sceneId,expectedReleaseId:state.releaseId,expectedRevisionId:state.revisionId,...(action==='save'?{content:draft}:{timelineRevisionId:state.timelineRevisionId})};
   submitted=true;const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','If-Match':snapshot.mutationEtag,'Idempotency-Key':'animatic-ui:'+crypto.randomUUID()},body:JSON.stringify(body)});
   if(response.status>=400&&response.status<500)submitted=false;
   const result=await readManagementResponse<Record<string,unknown>>(response),nonempty=(key:string)=>typeof result[key]==='string'&&Boolean((result[key] as string).trim());
   if(action==='save'?!(nonempty('timelineRevisionId')&&nonempty('revisionId')):action==='render'?!(nonempty('jobId')&&result.status==='QUEUED'):!(nonempty('reconciliationId')&&result.status==='QUEUED'&&result.automaticRetry===false))throw Error('提交回执无法核验');
   if(action==='save'){setDirty(false);dirtyRef.current=false;}await reread();submitted=false;window.dispatchEvent(new Event('review:operations-updated'));onChanged?.();
  }catch(e){if(submitted)setUncertain(true);setError(submitted?'提交结果待核查；请先重读当前时间线与任务，确认后再操作。':e instanceof Error?e.message:'预演操作未完成');}finally{setBusy(false);}
 }
 const scheduled=(draft?.shots||[]).reduce<Array<AnimaticTimeline['shots'][number]&{start:number;end:number}>>((rows,s)=>{const start=rows.at(-1)?.end||0;return[...rows,{...s,start,end:start+s.durationFrames}];},[]),current=scheduled.find(s=>frame>=s.start&&frame<s.end)||scheduled[0],local=current?frame-current.start:0,panel=current?.panels.find(p=>local>=p.startFrame&&local<p.endFrame),mediaUrl=(versionId:string)=>state?.availableMedia.find(m=>m.versionId===versionId)?.mediaUrl||'',images=state?.availableMedia.filter(m=>/\.(png|jpe?g|webp)$/i.test(m.path||''))||[],sounds=state?.availableMedia.filter(m=>/\.(wav|mp3|m4a|flac)$/i.test(m.path||''))||[];
 const scale=panel?.motion==='PUSH_IN'?1+0.08*(local-panel.startFrame)/Math.max(1,panel.endFrame-panel.startFrame-1):panel?.motion==='PULL_OUT'?1.08-0.08*(local-panel.startFrame)/Math.max(1,panel.endFrame-panel.startFrame-1):1;
 return <section className="animatic-workspace" aria-label="场级预演时间线"><header><h3>场级预演与锁时</h3><p>以粗分镜和声音校准镜头顺序、时长与动作节拍。草稿播放和文件生成均不代表完成正式审阅。</p></header>
 {error&&<p role="alert" className="animatic-error">{error}</p>}{uncertain&&<button disabled={busy} onClick={()=>void verifyCurrent()}>重读当前时间线与任务（保留草稿）</button>}{state?.blockers.map(b=><p key={b}>{b}</p>)}{state?.stale&&<><p role="alert">镜头设计已变化；旧时间线及素材绑定保留为历史。新草稿按当前镜头计划建立，保存后形成新修订。</p>{state.basis&&!readOnly&&!state.readOnly&&draft?.shotPlanRevisionId!==state.basis.shotPlanRevisionId&&<button disabled={blocked} onClick={initialize}>按当前镜头计划新建预演草稿</button>}</>}
 {!state&&!error?<p>正在读取本场时间线…</p>:!draft?<div><p>本场尚无预演时间线。只有已采用并同步的正式镜头计划才能建立时间线。</p>{state?.basis&&!readOnly&&!state.readOnly&&<button disabled={blocked} onClick={initialize}>从当前镜头计划建立预演草稿</button>}</div>:<>
 <div className="animatic-preview" aria-label="预演画面">{panel&&mediaUrl(panel.media.versionId)?<img src={mediaUrl(panel.media.versionId)} alt={`${current.shotId} 粗分镜`} style={{transform:`scale(${scale})`}}/>:<span>{current?.shotId} · 待选粗分镜</span>}{draft.cards.filter(c=>c.shotId===current?.shotId&&local>=c.startFrame&&local<c.endFrame).map(c=><span key={c.id} className="animatic-card" style={{left:c.style.x/19.2+'%',top:c.style.y/10.8+'%',fontSize:c.style.fontSize/19.2+'cqw',color:c.style.color}}>{c.textLines.join('\n')}<small>草稿字体预览；精确字体以渲染候选为准</small></span>)}</div>
 <div className="animatic-controls"><button onClick={()=>{if(frame>=total-1)setFrame(0);setPlaying(p=>!p);}} disabled={!total}>{playing?'暂停':'播放草稿'}</button><input aria-label="预演播放位置" type="range" min={0} max={Math.max(0,total-1)} value={Math.min(frame,Math.max(0,total-1))} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/><span>{frame} / {total} 帧 · {(total/24).toFixed(3)} 秒</span></div>
 {draft.audio.filter(a=>!a.muted&&mediaUrl(a.media.versionId)).map(a=><TimelineAudio key={a.id} url={mediaUrl(a.media.versionId)} start={(scheduled.find(s=>s.shotId===a.anchorShotId)?.start||0)+a.offsetFrames} sourceIn={a.sourceInFrames} duration={a.durationFrames} frame={frame} playing={playing} volume={a.volume}/>)}
 <div className="animatic-shot-strip">{scheduled.map(s=><button key={s.shotId} className={current?.shotId===s.shotId?'active':''} onClick={()=>{setPlaying(false);setFrame(s.start);}}><b>{s.shotId}</b><span>{s.durationFrames} 帧 · {(s.durationFrames/24).toFixed(3)} 秒</span></button>)}</div>
 <div className="animatic-editors">{draft.shots.map((s,index)=><fieldset key={s.shotId} disabled={disabled}><legend>{s.shotId}</legend><div className="animatic-row"><button disabled={index===0} onClick={()=>edit(v=>{[v.shots[index-1],v.shots[index]]=[v.shots[index],v.shots[index-1]];})}>前移</button><button disabled={index===draft.shots.length-1} onClick={()=>edit(v=>{[v.shots[index+1],v.shots[index]]=[v.shots[index],v.shots[index+1]];})}>后移</button><label>镜长（帧）<input type="number" min={1} max={14400} value={s.durationFrames} onChange={e=>edit(v=>{const value=Math.max(1,Number(e.target.value)),shot=v.shots[index];shot.durationFrames=value;if(shot.panels.length===1)shot.panels[0].endFrame=value;})}/></label><small>{(s.durationFrames/24).toFixed(3)} 秒；非整秒按帧明确保存</small></div>
 {s.panels.length===0?<label>选择已放行粗分镜<select value="" onChange={e=>{const media=images.find(m=>m.versionId===e.target.value);if(media)edit(v=>{v.shots[index].panels=[{id:uid(),media:binding(media),startFrame:0,endFrame:s.durationFrames,motion:'STILL'}];});}}><option value="">请选择精确版本</option>{images.map(m=><option key={m.versionId} value={m.versionId}>{m.label} · {m.versionId}</option>)}</select></label>:s.panels.map((p,i)=><div className="animatic-row" key={p.id}><select aria-label="粗分镜版本" value={p.media.versionId} onChange={e=>{const media=images.find(m=>m.versionId===e.target.value);if(media)edit(v=>{v.shots[index].panels[i].media=binding(media);});}}>{images.map(m=><option key={m.versionId} value={m.versionId}>{m.label}</option>)}</select><label>入帧<input type="number" min={0} value={p.startFrame} onChange={e=>edit(v=>{v.shots[index].panels[i].startFrame=Number(e.target.value);})}/></label><label>出帧<input type="number" min={1} value={p.endFrame} onChange={e=>edit(v=>{v.shots[index].panels[i].endFrame=Number(e.target.value);})}/></label><select aria-label="粗分镜运动" value={p.motion} onChange={e=>edit(v=>{v.shots[index].panels[i].motion=e.target.value as typeof p.motion;})}><option value="STILL">固定</option><option value="PUSH_IN">缓推</option><option value="PULL_OUT">缓拉</option></select></div>)}
 {s.panels.length===1&&s.durationFrames>1&&<button onClick={()=>edit(v=>{const p=v.shots[index].panels[0],end=p.endFrame,middle=Math.floor(end/2);p.endFrame=middle;v.shots[index].panels.push({...structuredClone(p),id:uid(),startFrame:middle,endFrame:end});})}>增加中间粗分镜</button>}
 {s.beats.map((b,i)=><div className="animatic-row" key={b.id}><label>动作帧<input type="number" min={0} max={s.durationFrames-1} value={b.frame} onChange={e=>edit(v=>{v.shots[index].beats[i].frame=Number(e.target.value);})}/></label><label>动作节拍<input value={b.label} onChange={e=>edit(v=>{v.shots[index].beats[i].label=e.target.value;})}/></label><button onClick={()=>edit(v=>{v.shots[index].beats.splice(i,1);})}>删除动作点</button></div>)}<button onClick={()=>edit(v=>{v.shots[index].beats.push({id:uid(),frame:0,label:'待填写动作节拍'});})}>添加动作点</button>
 </fieldset>)}</div>
 <fieldset disabled={disabled}><legend>对白与临时声音</legend><p>临时对白可参与锁时；正面对白视频仍须最终干声放行。音乐、音效仅作节奏参考。</p>{draft.audio.map((a,index)=><div className="animatic-audio-editor" key={a.id}><b>{state?.availableMedia.find(m=>m.versionId===a.media.versionId)?.label||a.media.versionId}</b><select aria-label="声音用途" value={a.role} onChange={e=>edit(v=>{v.audio[index].role=e.target.value as typeof a.role;})}><option value="DIALOGUE">对白</option><option value="MUSIC">临时音乐</option><option value="SFX">临时音效</option></select><label>锚定镜头<select value={a.anchorShotId} onChange={e=>edit(v=>{v.audio[index].anchorShotId=e.target.value;})}>{draft.shots.map(s=><option key={s.shotId}>{s.shotId}</option>)}</select></label>{([['offsetFrames','偏移帧'],['sourceInFrames','源入帧'],['durationFrames','持续帧']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={a[key]} onChange={e=>edit(v=>{v.audio[index][key]=Number(e.target.value);})}/></label>)}<label>台词身份（逗号分隔）<input value={a.lineIds.join(',')} onChange={e=>edit(v=>{v.audio[index].lineIds=e.target.value.split(',').map(x=>x.trim()).filter(Boolean);})}/></label><label>音量<input type="range" min={0} max={1} step={0.05} value={a.volume} onChange={e=>edit(v=>{v.audio[index].volume=Number(e.target.value);})}/></label><label><input type="checkbox" checked={a.temporary} onChange={e=>edit(v=>{v.audio[index].temporary=e.target.checked;})}/>临时声音</label><label><input type="checkbox" checked={a.muted} onChange={e=>edit(v=>{v.audio[index].muted=e.target.checked;})}/>静音</label><button onClick={()=>edit(v=>{v.audio.splice(index,1);})}>移除此音轨</button></div>)}<label>添加已放行声音<select value="" onChange={e=>{const media=sounds.find(m=>m.versionId===e.target.value);if(media)edit(v=>{v.audio.push({id:uid(),media:binding(media),anchorShotId:v.shots[0].shotId,offsetFrames:0,sourceInFrames:0,durationFrames:Math.min(total,24),role:'DIALOGUE',temporary:true,volume:1,muted:false,lineIds:[]});});}}><option value="">选择已登记声音版本</option>{sounds.map(m=><option key={m.versionId} value={m.versionId}>{m.label}</option>)}</select></label></fieldset>
 {(draft.cards.length>0||Boolean(state?.requiredCards?.length))&&<fieldset disabled={disabled}><legend>人物信息卡</legend><p>沿用本场已发布的两行文案。出入帧、字体和排版随时间线形成新修订。</p>{draft.cards.map((c,index)=><div className="animatic-row" key={c.id}><b>{c.textLines.join('／')}</b><label>镜头<select value={c.shotId} onChange={e=>edit(v=>{v.cards[index].shotId=e.target.value;})}>{draft.shots.map(s=><option key={s.shotId}>{s.shotId}</option>)}</select></label>{([['startFrame','入帧'],['endFrame','出帧']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={c[key]} onChange={e=>edit(v=>{v.cards[index][key]=Number(e.target.value);})}/></label>)}{([['x','安全区横向位置'],['y','安全区纵向位置'],['fontSize','字号']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={c.style[key]} onChange={e=>edit(v=>{v.cards[index].style[key]=Number(e.target.value);})}/></label>)}<label>颜色<input type="color" value={c.style.color} onChange={e=>edit(v=>{v.cards[index].style.color=e.target.value;})}/></label><button onClick={()=>edit(v=>{v.cards.splice(index,1);})}>移除此卡</button><small>精确字体由已登记版本绑定</small></div>)}{state?.requiredCards?.filter(card=>!draft.cards.some(c=>c.specRevisionId===card.specRevisionId)).map(card=><label key={card.requirementId}>为“{card.textLines.join('／')}”选择已放行字体<select value="" onChange={e=>{const font=state.availableMedia.find(m=>m.versionId===e.target.value);if(font)edit(v=>{v.cards.push({id:uid(),shotId:v.shots[0].shotId,startFrame:0,endFrame:Math.min(v.shots[0].durationFrames,48),textLines:card.textLines,fontMedia:binding(font),style:{fontSize:48,x:120,y:800,color:'#ffffff'},specRevisionId:card.specRevisionId,specHash:card.specHash});});}}><option value="">选择精确字体文件（TTF/OTF）</option>{state.availableMedia.filter(m=>/\.(ttf|otf)$/i.test(m.path)).map(m=><option key={m.versionId} value={m.versionId}>{m.label}</option>)}</select></label>)}</fieldset>}
 <div className="animatic-controls"><button disabled={disabled||!dirty} onClick={()=>void mutate('save')}>保存时间线新修订</button><button disabled={disabled||state?.stale||dirty||!state?.timelineRevisionId||Boolean(state.jobs.some(j=>['QUEUED','RUNNING','RESULT_UNKNOWN'].includes(j.status)))} onClick={()=>void mutate('render')}>生成审阅预演</button><span>{dirty?'有未保存修改':state?.lock?.timelineRevisionId===state?.timelineRevisionId?'本修订已有正式锁时':'待正式审阅锁时'}</span></div>
 {state&&state.impact.length>0&&<p>本次影响：{state.impact.map(i=>`${i.shotId}（${[i.timingChanged?'时间':'',i.visualChanged?'粗分镜':'',i.overlayChanged?'人物卡':'',i.boundaryChanged?'邻接':''].filter(Boolean).join('、')}）`).join('；')}</p>}
 </>}
 {state?.jobs.map(job=><section className="animatic-render-result" key={job.jobId}><p>{job.status==='SUCCEEDED'?'审阅预演已生成':job.status==='RUNNING'?'正在渲染／执行状态待核':job.status==='QUEUED'?'等待预演工作器':job.status==='RESULT_UNKNOWN'?'结果待核查':job.status==='RECONCILED_UNREGISTERED'?'产物已核验并保留，未登记为正式候选':'渲染未完成'}{job.timelineRevisionId!==state.timelineRevisionId?' · 历史修订':''}</p>{job.error&&<p role="alert">{job.error}</p>}{job.pendingReconciliation?<p>等待受控工作器核查；不会自动重新渲染。</p>:['RUNNING','RESULT_UNKNOWN'].includes(job.status)&&!readOnly&&!state.readOnly&&<button disabled={blocked||!job.jobRevisionId||!state.runtimeEpoch} onClick={()=>void mutate('reconcile',job)}>核查任务结果</button>}{job.lastReconciliation?.status==='BLOCKED'&&<p role="alert">核查尚未排除冲突：{job.lastReconciliation.error}</p>}{job.lastReconciliation?.status==='SUPERSEDED'&&<p>核查依据已变化，请按当前任务重新核查。</p>}{job.reconciliation?.outcome==='NO_OUTPUT_CONFIRMED'&&<p>已在排他租约下确认没有产物或登记记录，可手动生成新版本。</p>}{job.status==='RECONCILED_UNREGISTERED'&&<p>旧文件不会覆盖；可手动生成新版本。文件校验不代表已看视频或完成审阅。</p>}{job.result?.mediaUrl&&<video controls preload="metadata" src={job.result.mediaUrl}/>}</section>)}
 </section>;
}
