'use client';
import type {DomainScope,Evidence} from '../host/instance-runtime/domain-model.mjs';
export type EvidenceSource={id:string;title:string;revisionId:string;sha256:string};
export function DomainEvidenceFields({value,sources,onChange,readonly}:{value:Evidence[];sources:EvidenceSource[];onChange:(value:Evidence[])=>void;readonly:boolean}){
 function edit(index:number,update:Partial<Evidence>){onChange(value.map((row,i)=>i===index?{...row,...update}:row));}
 return <details className="domain-evidence-fields"><summary>来源依据（{value.length}）</summary>{!value.length&&<p>尚未登记来源。来源事实与有限亲缘参考需要精确依据。</p>}{value.map((row,index)=><div key={index} className="domain-binding-row"><label>来源资料<select disabled={readonly} value={row.sourceId} onChange={e=>{const source=sources.find(s=>s.id===e.target.value);if(source)onChange(value.map((r,i)=>i===index?{sourceId:source.id,revisionId:source.revisionId,sha256:source.sha256}:r));}}>{!sources.some(s=>s.id===row.sourceId)&&<option value={row.sourceId}>{row.sourceId}</option>}{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>原文引用<textarea rows={2} disabled={readonly} value={row.quote||''} onChange={e=>edit(index,{quote:e.target.value})} placeholder="粘贴原文中可核验的连续文字"/></label><label>来源位置<input disabled={readonly} value={row.locator||''} onChange={e=>edit(index,{locator:e.target.value})} placeholder="例如：第3段、00:12:30"/></label><small>已绑定这份来源的精确版本。</small>{!readonly&&<button onClick={()=>onChange(value.filter((_,i)=>i!==index))}>移除此依据</button>}</div>)}{!readonly&&<button disabled={!sources.length} onClick={()=>{const s=sources[0];if(s)onChange([...value,{sourceId:s.id,revisionId:s.revisionId,sha256:s.sha256}]);}}>＋ 添加来源依据</button>}{!readonly&&!sources.length&&<p>先在系统管理登记故事资料，才能选择精确依据。</p>}</details>;
}
export function DomainScopeFields({value,projectId,onChange,readonly}:{value:DomainScope[];projectId:string;onChange:(value:DomainScope[])=>void;readonly:boolean}){
 function edit(index:number,update:Partial<DomainScope>){onChange(value.map((row,i)=>i===index?{...row,...update}:row));}
 return <details className="domain-scope-fields"><summary>适用范围（{value.length||'未限定'}）</summary>{!value.length&&<p>尚未限定到具体集、场或镜头。</p>}{value.map((row,index)=><div key={index} className="domain-binding-row"><label>范围类型<select disabled={readonly} value={row.scopeType} onChange={e=>edit(index,{scopeType:e.target.value as DomainScope['scopeType'],scopeId:e.target.value==='PROJECT'?projectId:'',revisionId:undefined})}>{[['PROJECT','全剧'],['EPISODE','分集'],['SCENE','场'],['SHOT','镜头']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{row.scopeType==='PROJECT'?<p>本故事全剧范围。</p>:<><label>对象永久身份<input disabled={readonly} value={row.scopeId} onChange={e=>edit(index,{scopeId:e.target.value})}/></label><label>对象修订<input disabled={readonly} value={row.revisionId||''} onChange={e=>edit(index,{revisionId:e.target.value})}/></label><small>从已登记对象复制永久身份和修订；仅有显示编号不足以绑定。</small></>}{!readonly&&<button onClick={()=>onChange(value.filter((_,i)=>i!==index))}>移除此范围</button>}</div>)}{!readonly&&<button onClick={()=>onChange([...value,{scopeType:'PROJECT',scopeId:projectId}])}>＋ 添加适用范围</button>}</details>;
}
