'use client';
import {useEffect,useState} from 'react';
import type {EpisodePlanContext} from './episode-plan-context';
import {useSceneNarrativeContext,SceneNarrativeRequirements,SceneNarrativeReview} from './scene-narrative-panel';
import {readManagementResponse} from './system-management-client';
import {StoryCommentsProvider,CommentText} from './story-comments';

export function GenericSceneReview({plan,selectedSceneId,onSelectScene,embedded=false}:{plan:EpisodePlanContext;selectedSceneId:string|null;onSelectScene:(id:string)=>void;embedded?:boolean}){
 const ids=plan.content.episodes.flatMap(episode=>episode.sceneIds),sceneId=selectedSceneId||ids[0];
 const inheritance=useSceneNarrativeContext(plan,sceneId||'');
 const [sourcesResult,setSourcesResult]=useState<{snapshotId:string;loaded:boolean;error:string}>({snapshotId:'',loaded:false,error:''}),[attempt,setAttempt]=useState(0);
 const genericSourcesLoaded=sourcesResult.snapshotId===plan.snapshotId&&sourcesResult.loaded;
 useEffect(()=>{const controller=new AbortController();void fetch('/api/instance/sources',{cache:'no-store',signal:controller.signal}).then(readManagementResponse<{sources:unknown[]}>).then(value=>{if(!Array.isArray(value.sources))throw new Error('来源目录格式不匹配');if(!controller.signal.aborted)setSourcesResult({snapshotId:plan.snapshotId,loaded:true,error:''});}).catch(error=>{if(!controller.signal.aborted)setSourcesResult({snapshotId:plan.snapshotId,loaded:false,error:error.message});});return()=>controller.abort();},[plan.snapshotId,attempt]);
 const context=inheritance.context,scene=context?.sceneDocument;
 if(selectedSceneId&&!ids.includes(selectedSceneId))return <section role="alert"><h2>此场不属于当前方案</h2><p>分集归属为 UNKNOWN，请从当前方案选择场次。</p></section>;
 function locate(ids:string[]){const element=document.getElementById(ids[0]||`generic-scene-${sceneId}`);element?.scrollIntoView({behavior:'smooth',block:'center'});element?.focus({preventScroll:true});}
 return <StoryCommentsProvider key={`${plan.revisionId}:${sceneId}`} plan={plan} sceneId={sceneId} onReveal={(target,blockId)=>{if(target.kind==='SCENE_SCRIPT'&&target.subjectId!==sceneId)onSelectScene(target.subjectId);else locate([blockId]);}}><section className={`narrative-reader generic-scene-review${embedded?' is-embedded':''}`} aria-label="通用故事逐场审阅">{!embedded&&<header><h2>逐场正文与正式审阅</h2><p>按当前分集方案读取本场完整正文、来源版本与审阅标准。来源目录已读取不表示原件已观察或事实已核验。</p></header>}<div className="narrative-reader-layout">{!embedded&&<nav aria-label="分集与场次">{plan.content.episodes.map(episode=><section key={episode.episodeUid}><h3>{episode.displayId} {episode.title}</h3>{episode.sceneIds.map(id=><button type="button" key={id} aria-current={id===sceneId?'page':undefined} onClick={()=>onSelectScene(id)}>{context?.sceneLabels[id]||id}</button>)}</section>)}</nav>}<article className="narrative-scene">{!genericSourcesLoaded&&<p role={sourcesResult.error?'alert':'status'}>{sourcesResult.error||'正在读取通用来源目录…'}{sourcesResult.error&&<button onClick={()=>setAttempt(value=>value+1)}>重新读取来源目录</button>}</p>}{inheritance.error&&<p role="alert">{inheritance.error}<button onClick={inheritance.retry}>重新读取本场</button></p>}{!context&&!inheritance.error&&<p role="status">正在读取本场正文与承接要求…</p>}{context&&<SceneNarrativeRequirements context={context} onOpenScene={onSelectScene} onLocate={locate}/>}<h3>本场完整正文</h3>{scene?<><h4>{scene.displayId} {scene.title}</h4><div className="narrative-script-body" id={`generic-scene-${scene.id}`} tabIndex={-1}>{scene.scriptBlocks.map(block=><p key={block.id} id={block.id} tabIndex={-1} className={block.type}>{block.speaker&&<b>【{block.speaker}】</b>}{block.performanceNote&&`（${block.performanceNote}）`}{<CommentText kind="SCENE_SCRIPT" subjectId={scene.id} blockId={block.id} text={block.text}/>}</p>)}</div><p>本场绑定 {scene.sourceBindings.length} 份精确来源版本。原音与其他媒体的观察状态继续保留在来源记录中。</p></>:context&&<p role="alert">本场精确正文未返回，正式审阅保持关闭。</p>}</article><aside className="narrative-review-sidebar">{genericSourcesLoaded&&context&&scene&&scene.contentHash===context.sceneContentHash?<SceneNarrativeReview context={context}/>:<section className="scene-inheritance-review"><h3>本场正式审阅</h3><p>当前来源目录、精确正文与承接上下文读取完成后开放。</p></section>}</aside></div></section></StoryCommentsProvider>;
}
