'use client';
import {useEffect,useState} from 'react';
import {readManagementResponse} from './system-management-client';
import {useManagementDraftGuard} from './management-draft-guard';
import './shot-production-workspace.css';
type Input={requirementId:string;familyId:string;versionId:string;sha256:string;purpose?:string};
type Shot={shotId:string;keyframeStrategy:{mode:string;reason:string;intermediateFrameCount:number};dialogueLines:Array<{id:string;text:string;speakerEntityId:string|null;purpose:string;performance:string}>;inputs:Input[];space:Record<string,string>;handles:{headFrames:number;tailFrames:number};videoBranch:string};
type Content={schemaVersion:string;sceneId:string;shotPlanRevisionId:string;shotPlanHash:string;shots:Shot[]};
type ManifestPreview={workItemId:string;expectedReleaseId:string;manifestHash:string;content:unknown};
type ProductionPreview={previewHash:string;workItemCount:number;outputCount:number;previousWorkItemIds:string[]};
type ProductionAction='save'|'preview'|'publish'|'manifest-preview'|'manifest-render';
type Job={jobId:string;status:string;error?:string};
type Workspace={sceneId:string;releaseId:string;readOnly:boolean;basis:{shots:Array<{id:string;title:string;materialRequirementRefs:string[]}>}|null;blockers:string[];defaultContent:Content|null;currentPlan:{content:Content}|null;draft:{revisionId:string;content:Content}|null;draftHeadRevisionId:string|null;availableInputs:Array<Input&{label:string;canFlowDownstream:boolean}>;availableSpace?:{sourceSha256:string|null;version:string|null;locations:Array<{id:string;label:string;zones:Array<{id:string;label:string}>;cameras:Array<{id:string;label:string}>}>;states:Array<{id:string;label:string}>};jobs:Array<{jobId:string;status:string;error?:string}>;readiness:{ready:boolean;readyCount:number;shotCount:number|null;shots:Array<{shotId:string;title:string;ready:boolean;blockers:string[]}>}};
const spaceLabels:Record<string,string>={loc:'地点',state:'场景状态',zone:'区域',camera:'机位',freeze:'空间冻结版本'};
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value&&typeof value==='object'&&!Array.isArray(value));
const nonempty=(value:unknown):value is string=>typeof value==='string'&&value.trim().length>0;
const hash=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
const sourceContent=(value:Workspace)=>value.draft?.content||value.currentPlan?.content||value.defaultContent;
async function readWorkspace(sceneId:string,signal?:AbortSignal):Promise<Workspace>{
 const response=await fetch('/api/instance/shot-production?sceneId='+encodeURIComponent(sceneId),{cache:'no-store',signal});if(!response.ok)await readManagementResponse(response);
 const value:unknown=await response.json();
 if(!record(value)||value.sceneId!==sceneId||typeof value.readOnly!=='boolean'||(!value.readOnly&&!nonempty(value.releaseId))||!Array.isArray(value.jobs)||!Array.isArray(value.blockers)||!Array.isArray(value.availableInputs)||!record(value.readiness)||!Array.isArray(value.readiness.shots)||!('draft' in value)||!('currentPlan' in value)||!('draftHeadRevisionId' in value))throw Error('当前制作计划、草稿或任务回执无效，请重新读取');
 if(value.draft&&(!record(value.draft)||!nonempty(value.draft.revisionId)||value.draft.revisionId!==value.draftHeadRevisionId||!record(value.draft.content)||value.draft.content.sceneId!==sceneId||!Array.isArray(value.draft.content.shots)))throw Error('当前制作草稿回执无效，请重新读取');
 return value as Workspace;
}
const reasons:Record<string,string>={PRODUCTION_PLAN_REQUIRED:'尚未建立制作计划',SPATIAL_INPUTS_UNKNOWN:'空间条件尚未确认',INPUT_LOCK_REQUIRED:'输入尚未锁定',KEYFRAME_STRATEGY_REQUIRED:'请选择关键帧策略',VIDEO_BRANCH_REQUIRED:'请选择声音与口型分支',STORYBOARD_NOT_RELEASED:'粗分镜尚未通过',DIALOGUE_NOT_RELEASED:'对白尚未通过',FINAL_DIALOGUE_REQUIRED:'所选分支需要正式对白',ANIMATIC_TIMING_LOCK_REQUIRED:'Animatic 尚未锁时',KEYFRAMES_NOT_RELEASED:'正式关键帧尚未通过',KEYFRAME_SET_REVIEW_REQUIRED:'关键帧集合尚未通过',VIDEO_CALL_PACKAGE_REQUIRED:'视频调用包尚未就绪'};
type WorkspaceProps={sceneId:string;episodeUid?:string;gateId:string;shotId?:string};
export function ShotProductionWorkspace(props:WorkspaceProps){return <ShotProductionWorkspaceBody key={[props.sceneId,props.gateId,props.shotId||''].join(':')} {...props}/>;}
function ShotProductionWorkspaceBody({sceneId,gateId,shotId}:WorkspaceProps){
 const [manifest,setManifest]=useState<ManifestPreview|null>(null);
 const [state,setState]=useState<Workspace|null>(null),[draft,setDraft]=useState<Content|null>(null),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState<ProductionAction|null>(null),[refresh,setRefresh]=useState(0),[preview,setPreview]=useState<ProductionPreview|null>(null);
 useManagementDraftGuard(dirty||Boolean(uncertain),'镜头制作设置');
 useEffect(()=>{const c=new AbortController();void readWorkspace(sceneId,c.signal).then(v=>{if(c.signal.aborted)return;setState(v);setDraft(sourceContent(v));setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[sceneId,refresh]);
 const reload=()=>{setState(null);setDraft(null);setDirty(false);setPreview(null);setManifest(null);setError('');setRefresh(v=>v+1);};
 const update=(id:string,patch:Partial<Shot>)=>{if(busy||uncertain||state?.readOnly)return;setDraft(d=>d?{...d,shots:d.shots.map(s=>s.shotId===id?{...s,...patch}:s)}:d);setDirty(true);setPreview(null);setManifest(null);};
 async function inspectUnconfirmed(){if(busy)return;setBusy(true);try{
  const value=await readWorkspace(sceneId);if(uncertain==='manifest-render'&&!Array.isArray((value as Workspace&{manifestJobs?:Job[]}).manifestJobs))throw Error('清单任务尚未读取，当前提交结果仍待核查');
  setState(value);setDirty(JSON.stringify(draft)!==JSON.stringify(sourceContent(value)));setUncertain(null);setPreview(null);setManifest(null);setError('已重读当前制作计划、草稿及任务，本次编辑仍保留。请核对是否已经登记。');
 }catch(e){setError(e instanceof Error?e.message:'当前结果仍无法核查');}finally{setBusy(false);}}
 async function submit(action:ProductionAction,body:Record<string,unknown>){
  if(!state||state.readOnly||busy||uncertain)return;setBusy(true);setError('');let submitted=false;
  try{
   const operations=await readManagementResponse<{mutationEtag:string}>(await fetch('/api/v8/operations/snapshot?summary=1',{cache:'no-store'}));if(!nonempty(operations.mutationEtag))throw Error('当前运行快照不可用');
   submitted=true;const response=await fetch('/api/instance/shot-production',{method:'POST',headers:{'Content-Type':'application/json','If-Match':operations.mutationEtag,'Idempotency-Key':'shot-production:'+crypto.randomUUID()},body:JSON.stringify(body)});
   if(response.status>=400&&response.status<500)submitted=false;if(!response.ok)await readManagementResponse(response);
   const result:unknown=await response.json();if(!record(result))throw Error('服务返回的操作回执无效');
   const valid=action==='save'?nonempty(result.revisionId)&&hash(result.contentHash)&&result.formalAdoptionPerformed===false:action==='preview'?hash(result.previewHash)&&result.sceneId===sceneId&&result.draftRevisionId===state.draft?.revisionId&&result.expectedReleaseId===state.releaseId&&Number.isSafeInteger(result.workItemCount)&&Number(result.workItemCount)>=0&&Number.isSafeInteger(result.outputCount)&&Number(result.outputCount)>=0&&Array.isArray(result.previousWorkItemIds)&&result.previousWorkItemIds.every(nonempty):action==='manifest-preview'?result.workItemId===body.workItemId&&result.expectedReleaseId===state.releaseId&&hash(result.manifestHash)&&record(result.content):nonempty(result.jobId)&&result.status==='QUEUED';
   if(!valid)throw Error('服务返回的操作回执缺少精确版本或任务依据');submitted=false;
   if(action==='preview')setPreview(result as ProductionPreview);else if(action==='manifest-preview')setManifest(result as ManifestPreview);else{reload();window.dispatchEvent(new Event('review:operations-updated'));}
  }catch(e){if(submitted)setUncertain(action);setError((e instanceof Error?e.message:'操作失败')+(submitted?'；提交结果尚未确认，请重读当前制作计划、草稿与任务后再操作。':''));}finally{setBusy(false);}
 }
 async function act(action:'save'|'preview'|'publish'){if(!state)return;await submit(action,action==='save'?{action,sceneId,content:draft,expectedReleaseId:state.releaseId,expectedDraftRevisionId:state.draftHeadRevisionId}:{action,sceneId,draftRevisionId:state.draft?.revisionId,previewHash:action==='publish'?preview?.previewHash:undefined});}
 async function manifestAction(workItemId:string,render=false){if(render&&!manifest)return;await submit(render?'manifest-render':'manifest-preview',render?{action:'manifest-render',sceneId,workItemId,expectedReleaseId:manifest!.expectedReleaseId,manifestHash:manifest!.manifestHash}:{action:'manifest-preview',sceneId,workItemId});}
 if(!state)return <section className="shot-production-workspace"><p role={error?'alert':'status'}>{error||'正在读取本场镜头制作…'}</p></section>;
 const editing=gateId==='SHOT_PLAN_INPUT_LOCK'&&!state.readOnly;
 return <section className="shot-production-workspace" aria-label="镜头制作设置">
  <header><h3>本场制作输入</h3><span>{state.readiness.readyCount} / {state.readiness.shotCount??'待定'} 镜头已具备视频生成素材</span><button disabled={busy||(dirty&&!uncertain)} onClick={()=>{if(uncertain)void inspectUnconfirmed();else reload();}}>{uncertain?'重读制作计划与任务':'刷新状态'}</button></header>
  {error&&<p role="alert">{error}</p>}{state.blockers.map(reason=><p key={reason}>{reason}</p>)}
  {!state.readOnly&&((state as Workspace&{manifestTargets?:Array<{workItemId:string;shotId:string|null;gateId:string;label:string}>}).manifestTargets||[]).filter(t=>t.gateId===gateId&&(!shotId||t.shotId===shotId||!t.shotId)).map(t=><button key={t.workItemId} disabled={busy||dirty||Boolean(uncertain)} onClick={()=>void manifestAction(t.workItemId)}>准备{t.label}清单</button>)}
  {manifest&&!state.readOnly&&<section aria-label="制作清单预览"><p>核对清单后生成可审阅的正式文件；生成完成后仍需逐项审阅。</p><pre>{JSON.stringify(manifest.content,null,2)}</pre><button disabled={busy||Boolean(uncertain)} onClick={()=>void manifestAction(manifest.workItemId,true)}>生成清单文件</button><button disabled={busy||Boolean(uncertain)} onClick={()=>setManifest(null)}>关闭预览</button></section>}
  {draft?.shots.filter(s=>!shotId||s.shotId===shotId).map(shot=>{const spec=state.basis?.shots.find(s=>s.id===shot.shotId),ready=state.readiness.shots.find(s=>s.shotId===shot.shotId);return <details key={shot.shotId} open={Boolean(shotId)}><summary>{spec?.title||shot.shotId} · {ready?.ready?'素材就绪':'准备中'}</summary>
   <ul>{ready?.blockers.map(reason=><li key={reason}>{reasons[reason]||reason}</li>)}</ul>
   {editing&&<fieldset className="shot-production-fields" disabled={busy||Boolean(uncertain)}>
    <label>关键帧策略<select value={shot.keyframeStrategy.mode} onChange={e=>update(shot.shotId,{keyframeStrategy:{...shot.keyframeStrategy,mode:e.target.value,intermediateFrameCount:e.target.value==='MULTI_KEYFRAME'?Math.max(1,shot.keyframeStrategy.intermediateFrameCount):0}})}><option value="UNDECIDED">待确定</option><option value="START_ONLY">单首帧</option><option value="START_END">首尾帧</option><option value="MULTI_KEYFRAME">首尾及中间关键帧</option></select></label>
    <label>策略依据<textarea value={shot.keyframeStrategy.reason} onChange={e=>update(shot.shotId,{keyframeStrategy:{...shot.keyframeStrategy,reason:e.target.value}})}/></label>
    {shot.keyframeStrategy.mode==='MULTI_KEYFRAME'&&<label>中间帧数量<input type="number" min={1} max={24} value={shot.keyframeStrategy.intermediateFrameCount} onChange={e=>update(shot.shotId,{keyframeStrategy:{...shot.keyframeStrategy,intermediateFrameCount:Number(e.target.value)}})}/></label>}
    <label>声音与口型分支<select value={shot.videoBranch} onChange={e=>update(shot.shotId,{videoBranch:e.target.value})}><option value="UNKNOWN">待确定</option><option value="SILENT">无对白</option><option value="AUDIO_DRIVEN">声音驱动表演</option><option value="POST_LIP">后期口型</option></select></label>
    {Object.entries(spaceLabels).map(([key,label])=>{const location=state.availableSpace?.locations.find(l=>l.id===shot.space.loc),options=key==='loc'?state.availableSpace?.locations:key==='state'?state.availableSpace?.states:key==='zone'?location?.zones:key==='camera'?location?.cameras:state.availableSpace?.sourceSha256?[{id:state.availableSpace.sourceSha256,label:'当前已发布空间基线'+(state.availableSpace.version?' · '+state.availableSpace.version:'')}]:[];return <label key={key}>{label}<select value={shot.space[key]} onChange={e=>update(shot.shotId,{space:{...shot.space,[key]:e.target.value,...(key==='loc'?{zone:'UNKNOWN',camera:'UNKNOWN'}:{})}})}><option value="UNKNOWN">待确认</option>{options?.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>;})}
    {(['headFrames','tailFrames'] as const).map((key,i)=><label key={key}>{i?'片尾':'片头'}剪辑余量（帧）<input type="number" min={0} max={240} value={shot.handles[key]} onChange={e=>update(shot.shotId,{handles:{...shot.handles,[key]:Number(e.target.value)}})}/></label>)}
    <fieldset><legend>本镜素材输入</legend>{spec?.materialRequirementRefs.map(requirementId=>{const options=state.availableInputs.filter(i=>i.requirementId===requirementId&&i.canFlowDownstream);return <label key={requirementId}>{options[0]?.label||requirementId}<select value={shot.inputs.find(i=>i.requirementId===requirementId)?.versionId||''} onChange={e=>{const selected=options.find(i=>i.versionId===e.target.value);update(shot.shotId,{inputs:[...shot.inputs.filter(i=>i.requirementId!==requirementId),...(selected?[{requirementId:selected.requirementId,familyId:selected.familyId,versionId:selected.versionId,sha256:selected.sha256,purpose:'REFERENCE'}]:[])]});}}><option value="">尚未绑定</option>{options.map(i=><option key={i.versionId} value={i.versionId}>{i.label} · {i.versionId}</option>)}</select></label>;})}</fieldset>
    <fieldset><legend>对白与表演</legend>{shot.dialogueLines.map((line,i)=><div key={line.id}><label>台词<textarea value={line.text} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,text:e.target.value}:l)})}/></label><label>角色身份<input value={line.speakerEntityId||''} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,speakerEntityId:e.target.value||null}:l)})}/></label><label>表演<textarea value={line.performance} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,performance:e.target.value}:l)})}/></label><label>用途<select value={line.purpose} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,purpose:e.target.value}:l)})}><option value="TEMPORARY">临时对白</option><option value="FINAL">正式对白</option></select></label><button onClick={()=>update(shot.shotId,{dialogueLines:shot.dialogueLines.filter((_,j)=>i!==j)})}>移除对白</button></div>)}<button disabled={shot.videoBranch==='SILENT'} onClick={()=>update(shot.shotId,{dialogueLines:[...shot.dialogueLines,{id:'LINE-'+crypto.randomUUID(),text:'',speakerEntityId:null,purpose:'TEMPORARY',performance:''}]})}>添加对白</button></fieldset>
   </fieldset>}
  </details>;})}
  {editing&&draft&&<footer><button disabled={busy||Boolean(uncertain)||!dirty} onClick={()=>void act('save')}>保存制作设置</button><button disabled={busy||Boolean(uncertain)||dirty||!state.draft} onClick={()=>void act('preview')}>预览制作需求</button>{preview&&<div><p>将建立 {preview.workItemCount} 个制作项、{preview.outputCount} 个预期产物；实际素材仍需制作与审阅。{preview.previousWorkItemIds.length>0?` 原计划 ${preview.previousWorkItemIds.length} 个制作项转入历史。`:''}</p><button disabled={busy||Boolean(uncertain)||dirty} onClick={()=>void act('publish')}>确认并建立制作需求</button></div>}</footer>}
  {state.jobs.map(job=><p key={job.jobId}>制作任务：{({QUEUED:'等待工作器处理',SUCCEEDED:'制作需求已建立',FAILED:'处理失败，需重新核对',RESULT_UNKNOWN:'结果待核'} as Record<string,string>)[job.status]||job.status}{job.error?' · '+job.error:''}</p>)}
  {((state as Workspace&{manifestJobs?:Job[]}).manifestJobs||[]).map(job=><p key={job.jobId}>清单任务 {job.jobId} · {({QUEUED:'等待工作器处理',RUNNING:'正在生成文件',SUCCEEDED:'清单文件已生成，仍需正式审阅',FAILED:'处理失败，需重新核对',RESULT_UNKNOWN:'结果待核'} as Record<string,string>)[job.status]||job.status}{job.error?' · '+job.error:''}</p>)}
 </section>;
}
