'use client';
import {useEffect,useState} from 'react';
import {managementMutation,readManagementResponse} from './system-management-client';
import {useManagementDraftGuard} from './management-draft-guard';
import './shot-production-workspace.css';
type Input={requirementId:string;familyId:string;versionId:string;sha256:string;purpose?:string};
type Shot={shotId:string;keyframeStrategy:{mode:string;reason:string;intermediateFrameCount:number};dialogueLines:Array<{id:string;text:string;speakerEntityId:string|null;purpose:string;performance:string}>;inputs:Input[];space:Record<string,string>;handles:{headFrames:number;tailFrames:number};videoBranch:string};
type Content={schemaVersion:string;sceneId:string;shotPlanRevisionId:string;shotPlanHash:string;shots:Shot[]};
type ManifestPreview={workItemId:string;expectedReleaseId:string;manifestHash:string;content:unknown};
type Workspace={sceneId:string;releaseId:string;readOnly:boolean;basis:{shots:Array<{id:string;title:string;materialRequirementRefs:string[]}>}|null;blockers:string[];defaultContent:Content|null;currentPlan:{content:Content}|null;draft:{revisionId:string;content:Content}|null;draftHeadRevisionId:string|null;availableInputs:Array<Input&{label:string;canFlowDownstream:boolean}>;availableSpace?:{sourceSha256:string|null;version:string|null;locations:Array<{id:string;label:string;zones:Array<{id:string;label:string}>;cameras:Array<{id:string;label:string}>}>;states:Array<{id:string;label:string}>};jobs:Array<{jobId:string;status:string;error?:string}>;readiness:{ready:boolean;readyCount:number;shotCount:number|null;shots:Array<{shotId:string;title:string;ready:boolean;blockers:string[]}>}};
const spaceLabels:Record<string,string>={loc:'地点',state:'场景状态',zone:'区域',camera:'机位',freeze:'空间冻结版本'};
const reasons:Record<string,string>={PRODUCTION_PLAN_REQUIRED:'尚未建立制作计划',SPATIAL_INPUTS_UNKNOWN:'空间条件尚未确认',INPUT_LOCK_REQUIRED:'输入尚未锁定',KEYFRAME_STRATEGY_REQUIRED:'请选择关键帧策略',VIDEO_BRANCH_REQUIRED:'请选择声音与口型分支',STORYBOARD_NOT_RELEASED:'粗分镜尚未通过',DIALOGUE_NOT_RELEASED:'对白尚未通过',FINAL_DIALOGUE_REQUIRED:'所选分支需要正式对白',ANIMATIC_TIMING_LOCK_REQUIRED:'Animatic 尚未锁时',KEYFRAMES_NOT_RELEASED:'正式关键帧尚未通过',KEYFRAME_SET_REVIEW_REQUIRED:'关键帧集合尚未通过',VIDEO_CALL_PACKAGE_REQUIRED:'视频调用包尚未就绪'};
export function ShotProductionWorkspace({sceneId,gateId,shotId}:{sceneId:string;episodeUid?:string;gateId:string;shotId?:string}){
 const [manifest,setManifest]=useState<ManifestPreview|null>(null);
 const [state,setState]=useState<Workspace|null>(null),[draft,setDraft]=useState<Content|null>(null),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[preview,setPreview]=useState<{previewHash:string;workItemCount:number;outputCount:number;previousWorkItemIds:string[]}|null>(null);
 useManagementDraftGuard(dirty,'镜头制作设置');
 useEffect(()=>{const c=new AbortController();setState(null);setDraft(null);setDirty(false);setPreview(null);void fetch('/api/instance/shot-production?sceneId='+encodeURIComponent(sceneId),{cache:'no-store',signal:c.signal}).then(readManagementResponse<Workspace>).then(v=>{if(c.signal.aborted)return;setState(v);setDraft(v.draft?.content||v.currentPlan?.content||v.defaultContent);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[sceneId,refresh]);
 const update=(id:string,patch:Partial<Shot>)=>{setDraft(d=>d?{...d,shots:d.shots.map(s=>s.shotId===id?{...s,...patch}:s)}:d);setDirty(true);setPreview(null);};
 async function act(action:'save'|'preview'|'publish'){if(!state)return;setBusy(true);setError('');try{
  const body=action==='save'?{action,sceneId,content:draft,expectedReleaseId:state.releaseId,expectedDraftRevisionId:state.draftHeadRevisionId}:{action,sceneId,draftRevisionId:state.draft?.revisionId,previewHash:action==='publish'?preview?.previewHash:undefined};
  const result=await managementMutation('/api/instance/shot-production',body);if(action==='preview')setPreview(result as typeof preview);else{setDirty(false);setRefresh(v=>v+1);window.dispatchEvent(new Event('review:operations-updated'));}
 }catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 async function manifestAction(workItemId:string,render=false){setBusy(true);setError('');try{if(render&&manifest){await managementMutation('/api/instance/shot-production',{action:'manifest-render',sceneId,workItemId,expectedReleaseId:manifest.expectedReleaseId,manifestHash:manifest.manifestHash});setManifest(null);setRefresh(v=>v+1);}else setManifest(await managementMutation<ManifestPreview>('/api/instance/shot-production',{action:'manifest-preview',sceneId,workItemId}));}catch(e){setError(e instanceof Error?e.message:'清单生成失败');}finally{setBusy(false);}}
 if(!state)return <section className="shot-production-workspace"><p role={error?'alert':'status'}>{error||'正在读取本场镜头制作…'}</p></section>;
 const editing=gateId==='SHOT_PLAN_INPUT_LOCK'&&!state.readOnly;
 return <section className="shot-production-workspace" aria-label="镜头制作设置">
  <header><h3>本场制作输入</h3><span>{state.readiness.readyCount} / {state.readiness.shotCount??'待定'} 镜头已具备视频生成素材</span><button disabled={dirty||busy} onClick={()=>setRefresh(v=>v+1)}>刷新状态</button></header>
  {error&&<p role="alert">{error}</p>}{state.blockers.map(reason=><p key={reason}>{reason}</p>)}
  {!state.readOnly&&((state as Workspace&{manifestTargets?:Array<{workItemId:string;shotId:string|null;gateId:string;label:string}>}).manifestTargets||[]).filter(t=>t.gateId===gateId&&(!shotId||t.shotId===shotId||!t.shotId)).map(t=><button key={t.workItemId} disabled={busy||dirty} onClick={()=>void manifestAction(t.workItemId)}>准备{t.label}清单</button>)}
  {manifest&&<section aria-label="制作清单预览"><p>核对清单后生成可审阅的正式文件；生成完成后仍需逐项审阅。</p><pre>{JSON.stringify(manifest.content,null,2)}</pre><button disabled={busy} onClick={()=>void manifestAction(manifest.workItemId,true)}>生成清单文件</button><button onClick={()=>setManifest(null)}>关闭预览</button></section>}
  {draft?.shots.filter(s=>!shotId||s.shotId===shotId).map(shot=>{const spec=state.basis?.shots.find(s=>s.id===shot.shotId),ready=state.readiness.shots.find(s=>s.shotId===shot.shotId);return <details key={shot.shotId} open={Boolean(shotId)}><summary>{spec?.title||shot.shotId} · {ready?.ready?'素材就绪':'准备中'}</summary>
   <ul>{ready?.blockers.map(reason=><li key={reason}>{reasons[reason]||reason}</li>)}</ul>
   {editing&&<div className="shot-production-fields">
    <label>关键帧策略<select value={shot.keyframeStrategy.mode} onChange={e=>update(shot.shotId,{keyframeStrategy:{...shot.keyframeStrategy,mode:e.target.value,intermediateFrameCount:e.target.value==='MULTI_KEYFRAME'?Math.max(1,shot.keyframeStrategy.intermediateFrameCount):0}})}><option value="UNDECIDED">待确定</option><option value="START_ONLY">单首帧</option><option value="START_END">首尾帧</option><option value="MULTI_KEYFRAME">首尾及中间关键帧</option></select></label>
    <label>策略依据<textarea value={shot.keyframeStrategy.reason} onChange={e=>update(shot.shotId,{keyframeStrategy:{...shot.keyframeStrategy,reason:e.target.value}})}/></label>
    {shot.keyframeStrategy.mode==='MULTI_KEYFRAME'&&<label>中间帧数量<input type="number" min={1} max={24} value={shot.keyframeStrategy.intermediateFrameCount} onChange={e=>update(shot.shotId,{keyframeStrategy:{...shot.keyframeStrategy,intermediateFrameCount:Number(e.target.value)}})}/></label>}
    <label>声音与口型分支<select value={shot.videoBranch} onChange={e=>update(shot.shotId,{videoBranch:e.target.value})}><option value="UNKNOWN">待确定</option><option value="SILENT">无对白</option><option value="AUDIO_DRIVEN">声音驱动表演</option><option value="POST_LIP">后期口型</option></select></label>
    {Object.entries(spaceLabels).map(([key,label])=>{const location=state.availableSpace?.locations.find(l=>l.id===shot.space.loc),options=key==='loc'?state.availableSpace?.locations:key==='state'?state.availableSpace?.states:key==='zone'?location?.zones:key==='camera'?location?.cameras:state.availableSpace?.sourceSha256?[{id:state.availableSpace.sourceSha256,label:'当前已发布空间基线'+(state.availableSpace.version?' · '+state.availableSpace.version:'')}]:[];return <label key={key}>{label}<select value={shot.space[key]} onChange={e=>update(shot.shotId,{space:{...shot.space,[key]:e.target.value,...(key==='loc'?{zone:'UNKNOWN',camera:'UNKNOWN'}:{})}})}><option value="UNKNOWN">待确认</option>{options?.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>;})}
    {(['headFrames','tailFrames'] as const).map((key,i)=><label key={key}>{i?'片尾':'片头'}剪辑余量（帧）<input type="number" min={0} max={240} value={shot.handles[key]} onChange={e=>update(shot.shotId,{handles:{...shot.handles,[key]:Number(e.target.value)}})}/></label>)}
    <fieldset><legend>本镜素材输入</legend>{spec?.materialRequirementRefs.map(requirementId=>{const options=state.availableInputs.filter(i=>i.requirementId===requirementId&&i.canFlowDownstream);return <label key={requirementId}>{options[0]?.label||requirementId}<select value={shot.inputs.find(i=>i.requirementId===requirementId)?.versionId||''} onChange={e=>{const selected=options.find(i=>i.versionId===e.target.value);update(shot.shotId,{inputs:[...shot.inputs.filter(i=>i.requirementId!==requirementId),...(selected?[{requirementId:selected.requirementId,familyId:selected.familyId,versionId:selected.versionId,sha256:selected.sha256,purpose:'REFERENCE'}]:[])]});}}><option value="">尚未绑定</option>{options.map(i=><option key={i.versionId} value={i.versionId}>{i.label} · {i.versionId}</option>)}</select></label>;})}</fieldset>
    <fieldset><legend>对白与表演</legend>{shot.dialogueLines.map((line,i)=><div key={line.id}><label>台词<textarea value={line.text} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,text:e.target.value}:l)})}/></label><label>角色身份<input value={line.speakerEntityId||''} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,speakerEntityId:e.target.value||null}:l)})}/></label><label>表演<textarea value={line.performance} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,performance:e.target.value}:l)})}/></label><label>用途<select value={line.purpose} onChange={e=>update(shot.shotId,{dialogueLines:shot.dialogueLines.map((l,j)=>j===i?{...l,purpose:e.target.value}:l)})}><option value="TEMPORARY">临时对白</option><option value="FINAL">正式对白</option></select></label><button onClick={()=>update(shot.shotId,{dialogueLines:shot.dialogueLines.filter((_,j)=>i!==j)})}>移除对白</button></div>)}<button disabled={shot.videoBranch==='SILENT'} onClick={()=>update(shot.shotId,{dialogueLines:[...shot.dialogueLines,{id:'LINE-'+crypto.randomUUID(),text:'',speakerEntityId:null,purpose:'TEMPORARY',performance:''}]})}>添加对白</button></fieldset>
   </div>}
  </details>;})}
  {editing&&draft&&<footer><button disabled={busy||!dirty} onClick={()=>void act('save')}>保存制作设置</button><button disabled={busy||dirty||!state.draft} onClick={()=>void act('preview')}>预览制作需求</button>{preview&&<div><p>将建立 {preview.workItemCount} 个制作项、{preview.outputCount} 个预期产物；实际素材仍需制作与审阅。{preview.previousWorkItemIds.length>0?` 原计划 ${preview.previousWorkItemIds.length} 个制作项转入历史。`:''}</p><button disabled={busy} onClick={()=>void act('publish')}>确认并建立制作需求</button></div>}</footer>}
  {state.jobs.map(job=><p key={job.jobId}>制作任务：{({QUEUED:'等待工作器处理',SUCCEEDED:'制作需求已建立',FAILED:'处理失败，需重新核对',RESULT_UNKNOWN:'结果待核'} as Record<string,string>)[job.status]||job.status}{job.error?' · '+job.error:''}</p>)}
 </section>;
}
