'use client';


import {runtimePath} from './runtime-path';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import type {DomainGraph,DomainEntity} from '../host/instance-runtime/domain-model.mjs';
import type {WorkspaceState,DomainOwner,DomainCollection,DomainRow,DomainChange} from '../host/instance-runtime/domain-workspaces.mjs';
import {DomainGraphEditor} from './story-relations-editor';
import {managementMutation,readManagementResponse} from './system-management-client';
import {useManagementDraftGuard} from './management-draft-guard';
import {useRuntimeMode} from './runtime-mode';
import {visibleText} from './review-semantics';
import {useAssistantFocus} from './assistant/context-provider';
import {useInstanceProfile} from './instance-context';
import {StoryEntityRegistration} from './story-entity-registration';
import {StoryLocationDetails} from './story-location-details';
import {SettingsImagePreview} from './settings-image-preview';
import './story-settings.css';
import {StorySettingsCanvas} from './story-settings-canvas';
import {LocationVisualGallery} from './location-visual-gallery';
import {SettingsDetailDialog} from './settings-detail-dialog';
import {CanvasSymbol,canvasTone} from './free-canvas';
import {entityCanvasIcon} from './entity-canvas-appearance';

type PendingWorkspace={base:WorkspaceState;changes:DomainChange[]};
type WorkspacePreview={previewHash:string;checks:string[];impact:{added:number;changed:number;removed:number;affectedFamilies?:{familyId:string;representationIds:string[]}[];invalidations?:{familyId:string;versionIds:string[]}[]};notice?:string};
// Per-instance ephemeral drafts survive same-document router remounts. Never a published source.
const pendingWorkspaces=new Map<string,PendingWorkspace>();
const collections:DomainCollection[]=['entities','states','representations','relations','requirements'];
const views=[['subjects','主体档案'],['space','空间设定']] as const;
type View='subjects'|'space'|'relations'|'continuity';
const materialViews=[['states','状态与发展'],['representations','素材表现'],['requirements','需求准备'],['relations','参考与依赖']] as const;
const authority={F:'来源事实',A:'改编提案',L:'制作锁定',U:'待核依据'};
const keyOf=(collection:DomainCollection,id:string)=>`${collection}:${id}`;
const nameOf=(row:DomainRow)=>'name'in row?row.name:'label'in row?row.label:row.title;
const scopeOf=(row:DomainRow)=>'scope'in row?row.scope:[];
function scopeLabel(row:DomainRow){const scope=scopeOf(row);return !scope.length?'项目设定 · 场次适用性未确认':scope.every(s=>s.scopeType==='PROJECT')?'项目范围':`限定 ${scope.length} 项范围 · 核对原修订`;}
function materialUrl(id:string){return `?view=materials&material=${encodeURIComponent(id)}`;}
function settingsUrl(id?:string,collection:DomainCollection='entities'){const key=collection==='states'?'settingsState':collection==='relations'?'settingsRelation':'settingsEntity';return `?view=settings${id?'&'+key+'='+encodeURIComponent(id):''}`;}

export function StorySettingsWorkspace({owner='SETTINGS',compact=false,active=true,focus,entityId}:{owner?:DomainOwner;compact?:boolean;active?:boolean;focus?:{collection:DomainCollection;id:string};entityId?:string}) {
  const {hostedReadOnly}=useRuntimeMode();const instance=useInstanceProfile();
  const [state,setState]=useState<WorkspaceState|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[attempt,setAttempt]=useState(0);
  const [view,setView]=useState<View>('subjects'),[materialView,setMaterialView]=useState<'states'|'representations'|'requirements'|'relations'>('representations');
  const [query,setQuery]=useState(''),[category,setCategory]=useState('ALL'),[issuesOnly,setIssuesOnly]=useState(false);
  const [selection,setSelection]=useState<{collection:DomainCollection;id:string}|null>(null),[editing,setEditing]=useState(false);
  const draftKey=instance.instanceId+':'+owner;
  const [local,setLocalState]=useState<PendingWorkspace|null>(()=>pendingWorkspaces.get(draftKey)||null),[draftVisible,setDraftVisible]=useState(false);
  function setLocal(value:PendingWorkspace|null){if(value)pendingWorkspaces.set(draftKey,value);else pendingWorkspaces.delete(draftKey);setLocalState(value);}
  const [busy,setBusy]=useState(false),[preview,setPreview]=useState<WorkspacePreview|null>(null);
  const [claimReason,setClaimReason]=useState('');
  const [newEntity,setNewEntity]=useState<DomainEntity|null>(null);
  const detailRef=useRef<HTMLElement>(null),origin=useRef<HTMLElement|null>(null);
  useManagementDraftGuard(Boolean(local),'故事设定与素材草稿');
  useEffect(()=>{const controller=new AbortController();void fetch(`/api/instance/domain-workspaces?owner=${owner}`,{cache:'no-store',signal:controller.signal}).then(readManagementResponse<WorkspaceState>).then(setState).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[owner,attempt]);
  useEffect(()=>{const sync=()=>{if(owner==='MATERIAL'){const url=new URL(location.href),id=url.searchParams.get('materialDefinitionId')||url.searchParams.get('materialRepresentation'),collection=url.searchParams.get('materialDefinitionKind')||'representations',tab=url.searchParams.get('materialDefinitionTab');setMaterialView(materialViews.some(([v])=>v===tab)?tab as typeof materialView:'representations');setSelection(id&&collections.includes(collection as DomainCollection)?{collection:collection as DomainCollection,id}:null);return;}const url=new URL(location.href),section=url.searchParams.get('settingsSection');setView(views.some(([id])=>id===section)?section as View:'subjects');const entity=url.searchParams.get('settingsEntity'),relation=url.searchParams.get('settingsRelation'),stateId=url.searchParams.get('settingsState');if(entity)setSelection({collection:'entities',id:entity});else if(stateId)setSelection({collection:'states',id:stateId});else if(relation)setSelection({collection:'relations',id:relation});else setSelection(null);setIssuesOnly(url.searchParams.get('settingsIssues')==='1');};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[owner]);
  const graph=useMemo(()=>{if(!state)return null;const next=structuredClone(state.graph);for(const change of local?.changes||(draftVisible?state.draft?.changes:[])||[]){const list=next[change.collection] as DomainRow[],index=list.findIndex(r=>r.id===change.id);if(change.value===null){if(index>=0)list.splice(index,1);}else if(index>=0)list[index]=change.value;else list.push(change.value);}return next;},[state,local,draftVisible]);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Synchronize the selected parent inspector, without mutating any draft.
  useEffect(()=>{if(focus){setSelection(focus.id?focus:null);if(materialViews.some(([id])=>id===focus.collection))setMaterialView(focus.collection as typeof materialView);}},[focus]);
  const readonly=hostedReadOnly||state?.readOnly;
  useAssistantFocus(active&&state?{projectId:instance.projectId,snapshotId:state.snapshotId,view:owner==='SETTINGS'?'settings':'material-definitions',subjectType:'PROJECT',subjectId:instance.projectId,title:owner==='SETTINGS'?'故事设定':'素材定义与依赖',versionId:state.revisionId||undefined,filters:{sectionId:owner==='SETTINGS'?view:materialView,...(selection&&state.graph[selection.collection].some(r=>r.id===selection.id)?{settingId:selection.id,settingCollection:selection.collection}:{})}}:null,25);
  function navigate(next:View){if(local&&!window.confirm('有未保存修改，仍要切换查阅视角吗？'))return;setView(next);setCategory('ALL');setSelection(null);setEditing(false);const url=new URL(location.href);url.searchParams.set('settingsSection',next);url.searchParams.delete('settingsEntity');url.searchParams.delete('settingsRelation');url.searchParams.delete('settingsState');history.pushState({},'',url);}
  function select(collection:DomainCollection,id:string,target?:HTMLElement){if(!selection)origin.current=target||(document.activeElement instanceof HTMLElement?document.activeElement:null);setSelection({collection,id});setEditing(false);setClaimReason('');if(owner==='SETTINGS'){const url=new URL(location.href);url.searchParams.delete('settingsEntity');url.searchParams.delete('settingsRelation');url.searchParams.delete('settingsState');if(collection==='entities')url.searchParams.set('settingsEntity',id);if(collection==='relations')url.searchParams.set('settingsRelation',id);if(collection==='states')url.searchParams.set('settingsState',id);history.pushState({},'',url);}else{const url=new URL(location.href);url.searchParams.set('materialDefinitionId',id);url.searchParams.set('materialDefinitionKind',collection);url.searchParams.delete('materialRepresentation');history.pushState({},'',url);}requestAnimationFrame(()=>{detailRef.current?.focus({preventScroll:true});});}
  function close(){if(owner==='MATERIAL'){const url=new URL(location.href);['materialDefinitionId','materialDefinitionKind','materialRepresentation'].forEach(k=>url.searchParams.delete(k));history.pushState({},'',url);}setSelection(null);setEditing(false);if(owner==='SETTINGS'){const url=new URL(location.href);url.searchParams.delete('settingsEntity');url.searchParams.delete('settingsRelation');url.searchParams.delete('settingsState');history.pushState({},'',url);}origin.current?.focus();}
  function beginEditing(){if(state?.draft&&!draftVisible&&!local){setDraftVisible(true);setMessage('已恢复本模块保存的草稿，继续编辑不会覆盖未确认修改。');}setEditing(!editing);}
  function editGraph(next:DomainGraph){if(!state||!graph)return;const base=local?.base||state,changes=[...(local?.changes||(draftVisible?state.draft?.changes:[])||[])];for(const collection of collections){const ids=new Set([...graph[collection].map(r=>r.id),...next[collection].map(r=>r.id)]);for(const id of ids){const before=graph[collection].find(r=>r.id===id),after=next[collection].find(r=>r.id===id);if(JSON.stringify(before)===JSON.stringify(after))continue;const change:DomainChange={collection,id,beforeHash:base.ownership[keyOf(collection,id)]?.recordHash||null,value:after||null};const index=changes.findIndex(c=>c.collection===collection&&c.id===id);if(index>=0)changes[index]=change;else changes.push(change);}}setLocal({base,changes});setPreview(null);}
  async function run(action:'save'|'preview'|'publish'|'claim'|'transfer'|'rebase',extra:Record<string,unknown>={}){if(!state||readonly)return;setBusy(true);setError('');try{const body=action==='save'?{action,owner,expectedReleaseId:local?.base.releaseId,expectedDraftRevisionId:local?.base.draftHeadRevisionId,changes:local?.changes}:action==='preview'?{action,owner,draftRevisionId:state.draft?.revisionId}:action==='publish'?{action,owner,draftRevisionId:state.draft?.revisionId,previewHash:preview?.previewHash}:{action,owner,expectedReleaseId:state.releaseId,...extra};const result=await managementMutation<{previewHash:string;checks:string[];impact:{added:number;changed:number;removed:number};notice?:string}>('/api/instance/domain-workspaces',body);if(action==='preview')setPreview(result);else{setLocal(null);setPreview(null);setEditing(false);setDraftVisible(action==='save'||action==='transfer'||action==='rebase');setAttempt(v=>v+1);setMessage(result.notice||(action==='publish'?'本模块修改已确认；剧本采用和素材放行没有改变。':action==='claim'?'维护归属已明确，内容未改变。':'草稿已保存，尚未生效。'));if(action==='publish'||action==='claim'){window.dispatchEvent(new Event('review:relations-updated'));window.dispatchEvent(new Event('review:operations-updated'));}}}catch(e){setError(e instanceof Error?e.message:'操作未完成，修改仍保留');}finally{setBusy(false);}}
  async function saveNewEntity(entity:DomainEntity){
    if(!state||readonly||busy)throw new Error('当前不可保存，请稍后重试。');
    const base=local?.base||state;
    const changes=[...(local?.changes||state.draft?.changes||[]),{collection:'entities' as const,id:entity.id,beforeHash:null,value:entity}];
    setBusy(true);
    try{
      await managementMutation('/api/instance/domain-workspaces',{action:'save',owner,expectedReleaseId:local?.base.releaseId||state.draft?.baseReleaseId||state.releaseId,expectedDraftRevisionId:base.draftHeadRevisionId,changes});
      setLocal(null);setPreview(null);setDraftVisible(true);setNewEntity(null);setSelection(null);setEditing(false);
      setMessage('设定草稿已保存；预览影响并确认本模块更新后生效。');
      setAttempt(value=>value+1);
    }finally{setBusy(false);}
  }
  function add(collection:DomainCollection){if(!graph||!state)return;if(collection==='entities'&&owner==='SETTINGS'){
    const type=view==='space'?'LOCATION':state.configuration.entityTypes.find(item=>item.id!=='LOCATION'&&item.id!=='UNRESOLVED')?.id||'CHARACTER';
    setNewEntity({id:'entities_'+crypto.randomUUID(),type,name:'',aliases:[],description:'',authority:'A',evidence:[]});
    return;
  }if(state.draft&&!draftVisible&&!local){setDraftVisible(true);setMessage('已恢复保存的草稿，请在草稿视图继续登记。');return;}const next=structuredClone(graph),id=`${collection}_${crypto.randomUUID()}`,entity=graph.entities.find(e=>e.id===entityId)||graph.entities.find(e=>e.type!=='UNRESOLVED');let row:DomainRow;
    if(collection==='entities')row={id,type:owner==='SETTINGS'&&view==='space'?'LOCATION':'CHARACTER',name:owner==='SETTINGS'&&view==='space'?'新地点':'新主体',aliases:[],description:'',authority:'A',evidence:[]};
    else if(collection==='states'){if(!entity)return;row={id,entityId:entity.id,label:'新状态',dimensions:{},scope:[],authority:'A',evidence:[]};}
    else if(collection==='representations'){if(!entity)return;row={id,entityId:entity.id,stateId:null,type:'IDENTITY',label:'新素材表现',dimensions:{},assetFamilyIds:[],requirementIds:[],authority:'A',evidence:[]};}
    else if(collection==='requirements'){const representation=graph.representations.find(r=>!entityId||r.entityId===entityId);if(!representation)return;row={id,title:'新素材需求',representationId:representation.id,mediaType:'IMAGE',category:'',scope:[],evidence:[],acceptanceCriteria:[],reuseScope:'PROJECT'};}
    else{const nodes=owner==='SETTINGS'?graph.entities.map(e=>({kind:'ENTITY' as const,id:e.id})):graph.representations.map(r=>({kind:'REPRESENTATION' as const,id:r.id}));if(nodes.length<2)return;row={id,type:owner==='SETTINGS'?'SOCIAL':'VISUAL_REFERENCE',from:nodes[0],to:nodes[1],label:'新关系',purpose:owner==='SETTINGS'?'':'style',inherit:[],exclude:[],scope:[],authority:'A',evidence:[],status:'PROPOSED',...(owner==='MATERIAL'?{referencePolicyId:'CLEAN_MASTER'}:{})};}
    (next[collection] as DomainRow[]).push(row);editGraph(next);setSelection({collection,id});setEditing(true);
  }
  if(!state||!graph)return <section className="settings-workspace"><h1>{owner==='SETTINGS'?'故事设定':'素材定义与依赖'}</h1><p role={error?'alert':'status'}>{error||'正在读取设定与关联…'}</p>{error&&<button onClick={()=>{setError('');setAttempt(v=>v+1);}}>重新读取</button>}</section>;
  const current=selection?graph[selection.collection].find(r=>r.id===selection.id):null;
  const meta=selection?state.ownership[keyOf(selection.collection,selection.id)]:null;
  const selectedEntity=current&&selection?.collection==='entities'?current as DomainEntity:current&&'entityId'in current?graph.entities.find(e=>e.id===current.entityId):null;
  const isLocationDetail=owner==='SETTINGS'&&selection?.collection==='entities'&&selectedEntity?.type==='LOCATION';
  const relatedReps=graph.representations.filter(r=>selection?.collection==='entities'?r.entityId===selectedEntity?.id:selection?.collection==='states'?r.stateId===current?.id:r.id===current?.id);
  const linkedRequirements=state.requirements.filter(q=>q.entityRef===selectedEntity?.id&&selection?.collection==='entities'&&!!selectedEntity||relatedReps.some(r=>r.requirementIds.includes(q.id)||r.id===q.representationRef)||graph.requirements.some(d=>d.id===q.id&&relatedReps.some(r=>r.id===d.representationId)));
  const matches=(row:DomainRow,collection:DomainCollection)=>{const m=state.ownership[keyOf(collection,row.id)],owned=m?.owner===owner||!m||m.owner==='UNCERTAIN';return owned&&(!entityId||('entityId'in row?row.entityId===entityId:collection==='requirements'?graph.representations.some(r=>r.entityId===entityId&&'representationId'in row&&r.id===row.representationId):collection==='relations'?graph.representations.some(r=>r.entityId===entityId&&'from'in row&&(row.from.id===r.id||row.to.id===r.id)):true))&&(!query||JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))&&(!issuesOnly||m?.owner==='UNCERTAIN'||'authority'in row&&row.authority==='U'||'unresolved'in row&&!!row.unresolved?.length);};
  const card=(row:DomainRow,collection:DomainCollection)=><button type="button" className={`settings-object-card ${selection?.id===row.id?'selected':''}`} key={row.id} onClick={e=>select(collection,row.id,e.currentTarget)}><span className="settings-card-kind">{collection==='entities'?state.configuration.entityTypes.find(t=>t.id===(row as DomainEntity).type)?.label:collection==='states'?'状态':collection==='relations'?'关系':collection==='representations'?'素材表现':'素材需求'}{'authority'in row&&<em className={`authority-${row.authority}`}>{authority[row.authority]}</em>}</span><strong>{visibleText(nameOf(row))}</strong><p>{visibleText('description'in row?row.description:'purpose'in row?row.purpose:'entityId'in row?graph.entities.find(e=>e.id===row.entityId)?.name||'所属主体待核':'evidence'in row?row.evidence[0]?.quote||'查看依据与用途':'')}</p><span className="settings-card-meta">{state.ownership[keyOf(collection,row.id)]?.owner==='UNCERTAIN'?'维护归属待核':scopeLabel(row)}</span></button>;
  const materialCollection=materialView as DomainCollection;
  const addCollection=owner==='MATERIAL'?materialCollection:view==='relations'?'relations':view==='continuity'?'states':'entities';
  const addReason=addCollection==='relations'&&(owner==='SETTINGS'?graph.entities.length:graph.representations.length)<2?'先登记至少两个可关联的对象':addCollection==='requirements'&&!graph.representations.some(r=>!entityId||r.entityId===entityId)?'先为此实体登记素材表现':(addCollection==='states'||addCollection==='representations')&&!graph.entities.length?'先在故事设定登记主体':'';
  const browseCollection=owner==='MATERIAL'?materialCollection:view==='relations'?'relations':view==='continuity'?'states':'entities';
  const resultCount=(graph[browseCollection] as DomainRow[]).filter(r=>matches(r,browseCollection)&&(owner!=='SETTINGS'||view!=='space'||'type'in r&&r.type==='LOCATION')&&(owner!=='SETTINGS'||view!=='subjects'||category==='ALL'||'type'in r&&r.type===category)).length;
  const draftControls=!readonly&&(local||state.draft)&&<section className="settings-draft-bar" aria-label="本模块草稿"><span>{owner==='SETTINGS'?'故事设定':'素材'}草稿 · {local?.changes.length||state.draft?.changes.length||0} 项修改</span>{state.draft&&!local&&state.draft.baseReleaseId!==state.releaseId&&<button disabled={busy} onClick={()=>void run('rebase',{draftRevisionId:state.draft?.revisionId})}>在当前版本重新核对草稿</button>}{state.draft&&!local&&<button onClick={()=>{setDraftVisible(!draftVisible);setEditing(false);}}>{draftVisible?'返回已发布内容':'查看已保存草稿'}</button>}<button disabled={!local||busy} onClick={()=>void run('save')}>保存草稿</button><button disabled={!!local||busy||!state.draft} onClick={()=>void run('preview')}>预览影响</button><button disabled={!!local||busy||!preview} onClick={()=>void run('publish')}>确认本模块更新</button>{local&&<button onClick={()=>{if(window.confirm('放弃当前未保存修改？已保存草稿仍保留。')){setLocal(null);setEditing(false);}}}>放弃未保存修改</button>}</section>;
  const previewContent=preview&&<section className="settings-preview"><h2>本次确认的影响</h2><p>新增 {preview.impact.added} · 修改 {preview.impact.changed} · 移除 {preview.impact.removed}</p><p>关联上下文改变的素材族 {(preview.impact.affectedFamilies||[]).length} 项；涉及已有产物的失效记录 {(preview.impact.invalidations||[]).length} 项。未列出的素材不会因本次更新被批量作废。</p>{!!preview.impact.affectedFamilies?.length&&<details open><summary>受影响的精确素材与版本</summary><ul>{preview.impact.affectedFamilies.map(f=><li key={f.familyId}><a href={runtimePath(materialUrl(f.familyId))}>{f.familyId}</a> · 表现 {f.representationIds.join('、')||'已移除关联'}<p>已有版本：{preview.impact.invalidations?.filter(i=>i.familyId===f.familyId).flatMap(i=>i.versionIds).join('、')||'没有已登记产物失效'}</p></li>)}</ul></details>}<ul>{preview.checks.map(c=><li key={c}>{c}</li>)}</ul></section>;
  return <section className={`settings-workspace ${compact?'is-compact':''} ${focus?.id?'is-embedded':''}`} aria-label={owner==='SETTINGS'?'故事设定工作区':'素材定义与依赖'}>
    <header className="settings-heading"><div><p>{owner==='SETTINGS'?'STORY BIBLE':'MATERIAL DEFINITIONS'}</p><h1>{owner==='SETTINGS'?'故事设定':'素材定义与依赖'}</h1><span>{owner==='SETTINGS'?'可由项目 Codex 依据已登记的来源资料、最新故事与剧本抽取主体档案和空间设定，核对后保存并确认。':'表现、需求和制作参考；主体设定共用同一份身份'}</span></div><span className="settings-version">{readonly?'只读镜像':local?'未保存修改':draftVisible?'草稿预览 · 尚未生效':'已发布设定'}</span></header>
    <nav className="settings-tabs" role="tablist" onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const tabs=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')),index=tabs.indexOf(event.target as HTMLButtonElement);if(index<0)return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next]?.focus();tabs[next]?.click();}} aria-label={owner==='SETTINGS'?'故事设定视角':'素材定义视角'}>{owner==='SETTINGS'?views.map(([id,label])=><button type="button" role="tab" key={id} aria-selected={view===id} tabIndex={view===id?0:-1} onClick={()=>navigate(id)}>{label}</button>):materialViews.map(([id,label])=><button type="button" role="tab" key={id} aria-selected={materialView===id} tabIndex={materialView===id?0:-1} onClick={()=>{setMaterialView(id);setSelection(null);setEditing(false);const url=new URL(location.href);url.searchParams.set('materialDefinitionTab',id);['materialDefinitionId','materialDefinitionKind','materialRepresentation'].forEach(k=>url.searchParams.delete(k));history.pushState({},'',url);}}>{label}</button>)}</nav>
    <div className="settings-toolbar"><input aria-label="搜索设定与关系" placeholder="搜索名称、要点或关联" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={issuesOnly} onChange={e=>setIssuesOnly(e.target.checked)}/>仅看待核</label>{!readonly&&<button disabled={busy||!!addReason} title={addReason||undefined} onClick={()=>add(addCollection)}>＋ 登记{owner==='MATERIAL'?materialViews.find(([id])=>id===materialView)?.[1]:view==='relations'?'关系':view==='continuity'?'状态':view==='space'?'地点':'主体'}</button>}{owner==='SETTINGS'&&view==='subjects'&&!readonly&&<button type="button" className="settings-register-relation" disabled={busy||graph.entities.length<2} onClick={()=>add('relations')}>登记关系</button>}</div>
    {!readonly&&addReason&&<p className="settings-scope-note">{addReason}。</p>}
    <p className="settings-scope-note">助手只读取已发布对象；未保存编辑与未确认草稿未自动带入。依据和适用版本随对象保存。项目设定不代表已覆盖当前全部场次；旧场号与当前候选没有自动对应关系。</p>
    {newEntity&&<StoryEntityRegistration key={newEntity.id} initial={newEntity} configuration={state.configuration} busy={busy} onSave={saveNewEntity} onClose={()=>setNewEntity(null)}/>}
    {error&&<p role="alert" className="management-feedback is-error">{error}<button disabled={!!local} onClick={()=>{setError('');setAttempt(v=>v+1);}}>重新读取</button></p>}{message&&<p role="status">{message}</p>}
    {(owner!=='SETTINGS'||!selection)&&draftControls}
    {(owner!=='SETTINGS'||!selection)&&previewContent}
    <div className={`settings-layout ${owner==='SETTINGS'?'is-canvas-view':'has-detail'} ${selection?'is-selected':''}`} role="tabpanel" aria-label={owner==='SETTINGS'?views.find(([id])=>id===view)?.[1]:materialViews.find(([id])=>id===materialView)?.[1]}>
      <div className="settings-browse">
        {owner==='SETTINGS'&&<>{view!=='space'&&<nav className="entity-category-tabs settings-subject-filters" aria-label="实体分类">{[['ALL','全部'],...state.configuration.entityTypes.filter(t=>t.id!=='LOCATION').map(t=>[t.id,t.label])].map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(current=>current===id?'ALL':id)} style={{'--entity-tone':canvasTone(id)} as CSSProperties}>{<CanvasSymbol kind={id==='ALL'?'story':entityCanvasIcon(id)}/>}<span>{label}</span></button>)}</nav>}<StorySettingsCanvas businessFacts={state.businessFacts} view={view==='space'?'space':'subjects'} graph={graph} configuration={state.configuration} spatial={state.spatial} selectedId={selectedEntity?.id||selection?.id} entities={graph.entities.filter(e=>matches(e,'entities')&&(view==='space'?e.type==='LOCATION':e.type!=='LOCATION')&&(view==='space'||category==='ALL'||e.type===category))} viewportKey={instance.instanceId+':settings:'+view} onSelect={id=>select('entities',id)} onSelectRelation={id=>select('relations',id)}/></>}
        {owner==='MATERIAL'&&materialView==='relations'&&<div className="settings-card-grid">{graph.relations.filter(r=>matches(r,'relations')).map(r=>card(r,'relations'))}</div>}
        {owner==='MATERIAL'&&materialView!=='relations'&&<><div className="settings-card-grid">{(graph[materialCollection] as DomainRow[]).filter(r=>matches(r,materialCollection)).map(r=>card(r,materialCollection))}</div>{materialView==='requirements'&&<><p>当前素材目录共 {state.requirements.length} 项需求；下方包括既有受控源需求，不能通过新增需求覆盖。</p><div className="settings-card-grid">{state.requirements.filter(r=>(!entityId||r.entityRef===entityId||graph.representations.some(rep=>rep.entityId===entityId&&(rep.id===r.representationRef||rep.requirementIds.includes(r.id)||graph.requirements.some(q=>q.id===r.id&&q.representationId===rep.id))))&&(!query||r.title.includes(query))).map(r=><a className="settings-object-card" key={r.id} href={runtimePath(materialUrl(r.id))}><small>{visibleText(r.category||'素材')}</small><strong>{visibleText(r.title)}</strong><span>进入统一素材详情 →</span></a>)}</div></>}</>}
        {resultCount===0&&<p className="settings-empty">{query||issuesOnly||category!=='ALL'?'当前筛选没有匹配内容。可以修改关键词或取消筛选。':'此视角尚未登记内容。可以先从来源资料整理已知主体，再逐项补充；不需要先创建素材或完成全剧。'}</p>}
      </div>
      {owner!=='SETTINGS'&&!selection&&<aside className="settings-detail settings-detail-placeholder"><h2>选择一个实体</h2><p>从左侧分类与关系画板选择对象，在这里查看和维护完整资料。</p></aside>}
      {selection&&<SettingsDetailDialog enabled={owner==='SETTINGS'} onRequestClose={close}><aside className="settings-detail" ref={detailRef} tabIndex={-1} aria-label="对象设定详情"><header><div><small>{meta?.owner==='MATERIAL'?'素材定义':meta?.owner==='UNCERTAIN'?'归属待核':'故事设定'}</small><h2>{current?visibleText(nameOf(current)):'对象不在此版本中'}</h2></div><div className="settings-detail-header-actions">{current&&!readonly&&(meta?.owner===owner||!meta)&&<button type="button" disabled={busy} onClick={beginEditing}>{editing?'返回查阅':'编辑此项'}</button>}<button type="button" aria-label="关闭对象详情" onClick={close}>×</button></div></header>{owner==='SETTINGS'&&<>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{(!isLocationDetail||editing)&&<>{draftControls}{previewContent}</>}</>}{current&&<>
        {meta&&meta.owner!==owner&&meta.owner!=='UNCERTAIN'&&<p>此处只读引用。<a href={runtimePath(meta.owner==='SETTINGS'?settingsUrl(current.id,selection.collection) : '?view=materials&materialPanel=definitions&materialDefinitionKind='+selection.collection+'&materialDefinitionId='+encodeURIComponent(current.id))}>前往所属模块维护 →</a></p>}
        {editing&&selection.collection==='entities'&&<p>主体设定会被相关素材引用。正片人物卡文案请到素材表现编辑，避免把卡文案当作人物共用设定。</p>}{editing?<DomainGraphEditor key={selection.id} graph={graph} configuration={state.configuration} readonly={busy||!!readonly} focus={{section:selection.collection,id:selection.id}} onChange={editGraph}/>:isLocationDetail&&selectedEntity?<StoryLocationDetails entity={selectedEntity} configuration={state.configuration} spatial={state.spatial} visuals={state.locationVisuals?.[selectedEntity.id]||[]}/>:<>
          {'description'in current&&<p className="settings-full-text">{visibleText(current.description||'说明尚未补充')}</p>}{'purpose'in current&&<p>{visibleText(current.purpose)}</p>}{'dimensions'in current&&<dl className="settings-facts">{Object.entries(current.dimensions).map(([k,v])=><div key={k}><dt>{state.configuration.stateDimensions.find(d=>d.id===k)?.label||k}</dt><dd>{visibleText(v)}</dd></div>)}</dl>}
          {'authority'in current&&<p>{authority[current.authority]} · {scopeLabel(current)}</p>}
          {selection.collection==='relations'&&'from'in current&&<><h3>关系定义</h3><p>{current.from.id} {state.configuration.relationTypes.find(t=>t.id===current.type)?.directed?'→':'—'} {current.to.id}</p><p>允许继承：{current.inherit.join('、')||'未登记'}</p><p>明确排除：{current.exclude.join('、')||'未登记'}</p>{current.referencePolicyId&&<p>参考规则：{state.configuration.referencePolicies.find(p=>p.id===current.referencePolicyId)?.label||current.referencePolicyId} · 声明不证明实际使用</p>}</>}{selectedEntity&&<><h3>状态与制作条件</h3><div className="settings-mini-cards">{graph.states.filter(s=>s.entityId===selectedEntity.id).map(s=><button key={s.id} onClick={()=>{if(owner==='SETTINGS')location.href='?view=materials&entity='+encodeURIComponent(s.entityId)+'&materialState='+encodeURIComponent(s.id);else select('states',s.id);}}>{visibleText(s.label)}<small>{state.ownership[keyOf('states',s.id)]?.owner==='MATERIAL'?'素材条件 · 原制作依据':'主体状态'}</small></button>)}</div><h3>关联关系</h3><div className="settings-mini-cards">{graph.relations.filter(r=>r.from.id===selectedEntity.id||r.to.id===selectedEntity.id).map(r=><button key={r.id} onClick={()=>select('relations',r.id)}>{visibleText(r.label)}<small>{authority[r.authority]}</small></button>)}</div></>}
          {selectedEntity?.type==='LOCATION'&&<><LocationVisualGallery items={state.locationVisuals?.[selectedEntity.id]||[]} configuration={state.configuration}/><h3>空间基线</h3><div className="settings-space-maps">{state.spatial?.mapCards?.filter(map=>map.locationIds?.includes(selectedEntity.id)&&map.imageUrl).map(map=><figure key={map.id}>{map.imageUrl&&<SettingsImagePreview src={map.imageUrl} label={map.label}/>}<figcaption><strong>{map.label}</strong><p>{map.note}</p></figcaption></figure>)}</div>{state.spatial?.locations?.filter(l=>l.id===selectedEntity.id).map(l=><div key={l.id}><p>{visibleText(l.fact||'剧情空间事实待核')}</p><p>{visibleText(l.lock||'制作锁定待核')}</p><p>入口：{visibleText(l.entrance||'未登记')}</p></div>)}</>}
          {relatedReps.length>0&&<><h3>关联素材表现</h3><div className="settings-mini-cards">{relatedReps.map(r=><a key={r.id} href={runtimePath(`?view=materials&materialPanel=definitions&materialRepresentation=${encodeURIComponent(r.id)}`)}>{visibleText(r.label)}</a>)}</div></>}
          <h3>关联素材需求 · {linkedRequirements.length}</h3><div className="settings-mini-cards">{linkedRequirements.map(r=><a key={r.id} href={runtimePath(materialUrl(r.id))}>{visibleText(r.title)} →</a>)}</div>{!linkedRequirements.length&&<p>尚无已登记的关联需求；不代表需要生成新素材。</p>}
          <details className="settings-evidence" open><summary>来源依据 · {current.evidence.length}</summary>{current.evidence.map((e,i)=><article key={i}><blockquote>{visibleText(e.quote||'未登记精确引文')}</blockquote><small>{visibleText(e.locator||e.sourceId)}</small><code>{e.revisionId} · {e.sha256}</code></article>)}{!current.evidence.length&&<p>来源依据尚未登记。</p>}</details><details><summary>身份与适用修订</summary><code>{current.id}</code>{scopeOf(current).map((s,i)=><p key={i}>{s.scopeId} · {s.revisionId||'项目范围'}</p>)}<p>{meta?.reason}</p></details>
        </>}
        {!readonly&&meta?.owner==='UNCERTAIN'&&<section><h3>确认维护归属</h3><p>只改变维护入口，不确认故事事实或素材放行。</p><label>归属依据<textarea value={claimReason} onChange={e=>setClaimReason(e.target.value)} /></label><button disabled={!claimReason.trim()||busy||!!local} onClick={()=>void run('claim',{...selection,recordHash:meta.recordHash,reason:claimReason})}>归入{owner==='SETTINGS'?'故事设定':'素材管理'}</button></section>}
      </>}</aside></SettingsDetailDialog>}
    </div>
    {!readonly&&state.legacyDrafts.length>0&&<details className="settings-legacy"><summary>建议与旧草稿转交 · {state.legacyDrafts.length}</summary><p>原稿保留。仅转交本模块可确认的新增与修改，不自动发布，也不按旧稿删除当前对象。</p>{state.legacyDrafts.map(d=><div key={d.revisionId}><span>{d.kind==='EXTRACTION'?'AI 抽取建议稿':d.kind==='INITIALIZATION'?'旧初始化草稿':'旧整图关系草稿'}</span><button disabled={busy||!!local||!!state.draft} onClick={()=>void run('transfer',{kind:d.kind,legacyRevisionId:d.revisionId,expectedDraftRevisionId:state.draftHeadRevisionId})}>转交到本模块草稿</button></div>)}</details>}
  </section>;
}
