'use client';
import {useState} from 'react';
import type {DomainConfiguration} from '../presentation/domain-model.mjs';
import {defaultDomainConfiguration} from '../presentation/domain-defaults.mjs';
const split=(value:string)=>value.split(/[\n,，]/).map(v=>v.trim()).filter(Boolean);
type Section='entityTypes'|'stateDimensions'|'representationTypes'|'relationTypes'|'referencePolicies';
export function DomainConfigurationEditor({value,mode,onChange,readonly}:{value?:DomainConfiguration;mode:'structure'|'references';onChange:(value:DomainConfiguration)=>void;readonly:boolean}){
 const domain=value||defaultDomainConfiguration();
 const [section,setSection]=useState<Section>(mode==='references'?'referencePolicies':'entityTypes'),[selected,setSelected]=useState('');
 const groups:Array<[Section,string]>=mode==='references'?[['referencePolicies','生成参考规则']]:[['entityTypes','实体类型'],['stateDimensions','状态维度'],['representationTypes','素材表现'],['relationTypes','关系类型']];
 const actual=groups.some(([id])=>id===section)?section:groups[0][0],rows=domain[actual],index=Math.max(0,rows.findIndex(r=>r.id===selected)),row=rows[index];
 function edit(fn:(d:DomainConfiguration)=>void){const next=structuredClone(domain);fn(next);onChange(next);}
 const field=(label:string,v:string,change:(v:string)=>void)=><label className="configuration-field">{label}<input disabled={readonly} value={v} onChange={e=>change(e.target.value)}/></label>;
 function add(){const id=actual+'_'+crypto.randomUUID();edit(d=>{if(actual==='entityTypes'||actual==='stateDimensions')d[actual].push({id,label:'新'+groups.find(([key])=>key===actual)?.[1]});else if(actual==='representationTypes')d.representationTypes.push({id,label:'新素材表现',mediaType:'IMAGE',dimensions:[]});else if(actual==='relationTypes')d.relationTypes.push({id,label:'新关系',class:'STORY',directed:true,acyclic:false});else d.referencePolicies.push({id,label:'新参考规则',purposes:[],requireApprovedVersion:true,maxDerivedGenerations:2,allowIdentityTransfer:false});});setSelected(id);}
 return <div className="configuration-domain-workspace"><nav aria-label="配置结构目录">{groups.map(([key,label])=><section key={key}><button aria-pressed={actual===key} onClick={()=>{setSection(key);setSelected('');}}><b>{label}</b></button>{actual===key&&domain[key].map(item=><button className="configuration-node" key={item.id} aria-pressed={row?.id===item.id} onClick={()=>setSelected(item.id)}>{item.label}</button>)}</section>)}{!readonly&&<button onClick={add}>＋ 添加{groups.find(([key])=>key===actual)?.[1]}</button>}</nav><section className="configuration-domain-detail">{!row?<p>此结构尚无配置。</p>:<><h3>{row.label}</h3>{field('名称',row.label,v=>edit(d=>{d[actual][index].label=v;}))}
 {actual==='entityTypes'&&<p>此类型组织故事设定中的主体；主体可以拥有多个状态和不同媒介的素材表现。</p>}
 {actual==='stateDimensions'&&<><p>同一实体通过此维度描述不同状态。使用此维度的素材表现：</p><div className="entity-category-tabs">{domain.representationTypes.filter(t=>t.dimensions.includes(row.id)).map(t=><button key={t.id} onClick={()=>{setSection('representationTypes');setSelected(t.id);}}>{t.label}</button>)}</div></>}
 {actual==='representationTypes'&&<><label className="configuration-field">媒介<select disabled={readonly} value={domain.representationTypes[index].mediaType} onChange={e=>edit(d=>{d.representationTypes[index].mediaType=e.target.value;})}>{[['IMAGE','图像'],['AUDIO','声音'],['VIDEO','视频'],['TEXT','文本']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><h4>适用状态维度</h4><div className="configuration-options">{domain.stateDimensions.map(dimension=><label key={dimension.id}><input type="checkbox" disabled={readonly} checked={domain.representationTypes[index].dimensions.includes(dimension.id)} onChange={e=>edit(d=>{d.representationTypes[index].dimensions=e.target.checked?[...d.representationTypes[index].dimensions,dimension.id]:d.representationTypes[index].dimensions.filter(id=>id!==dimension.id);})}/>{dimension.label}</label>)}</div><p>版本属于一个具体素材条件下的生成结果；不同表现保持独立版本链。</p></>}
 {actual==='relationTypes'&&<><label className="configuration-field">关系用途<select disabled={readonly} value={domain.relationTypes[index].class} onChange={e=>edit(d=>{d.relationTypes[index].class=e.target.value as 'STORY';if(e.target.value==='REFERENCE'){d.relationTypes[index].directed=true;d.relationTypes[index].acyclic=true;}})}>{[['STORY','故事关系'],['CONTINUITY','状态连续性'],['REFERENCE','制作参考'],['COMPOSITION','组成关系']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="configuration-options"><label><input type="checkbox" disabled={readonly||domain.relationTypes[index].class==='REFERENCE'} checked={domain.relationTypes[index].directed} onChange={e=>edit(d=>{d.relationTypes[index].directed=e.target.checked;})}/>区分方向</label><label><input type="checkbox" disabled={readonly||domain.relationTypes[index].class==='REFERENCE'} checked={domain.relationTypes[index].acyclic} onChange={e=>edit(d=>{d.relationTypes[index].acyclic=e.target.checked;})}/>禁止循环依赖</label></div></>}
 {actual==='referencePolicies'&&<>{field('允许继承的用途',domain.referencePolicies[index].purposes.join('，'),v=>edit(d=>{d.referencePolicies[index].purposes=split(v);} ))}<label className="configuration-field">最多连续派生代数<input type="number" min={0} max={2} disabled={readonly} value={domain.referencePolicies[index].maxDerivedGenerations} onChange={e=>edit(d=>{d.referencePolicies[index].maxDerivedGenerations=Number(e.target.value);})}/></label><p>实际参考必须是已获批的精确版本。跨实体完整身份复制禁止；每次调用仍须锁定用途和明确排除项。</p></>}
 </>}</section></div>;
}
