'use client';
import {readWorkspaceJson,readWorkspaceBatch,workspaceCacheScope} from './workspace-read-cache';
import {useInstanceProfile} from './instance-context';
import type {MaterialCatalogRead} from './paged-production-data';

import {runtimePath} from './runtime-path';
import {currentMaterialDirectoryRow,atomicMaterialDirectoryRow} from './material-requirement-presentation';
import { materialExtraReviewPoints } from './material-review-display';
import {useCallback,useEffect,useMemo,useState,type CSSProperties,type ReactNode} from 'react';
import type {DomainGraph} from '../presentation/domain-model.mjs';
import type {WorkspaceState} from '../presentation/domain-workspaces.mjs';
import {useOriginalMediaUrl,type MaterialRequirement,type ProductionModel,type V7AssetVersion} from './production-workbench';
import {RelationshipCanvas,type CanvasNode,type CanvasEdge} from './relationship-canvas';
import {StorySettingsWorkspace} from './story-settings-workspace';
import {readManagementResponse} from './system-management-client';
import {publicRef,visibleText} from './review-semantics';
import {AssetReview,loadTrialWorkspace,type TrialSnapshot,type TrialAsset} from './trial-asset-review';
import {useRuntimeMode} from './runtime-mode';
import {classifiedMaterial,materialMediaTypeOptions,materialCreatorStageOptions,type MaterialCreatorStageProjection,type MaterialMediaType,type MaterialCreatorStage} from './material-taxonomy';
import {allMaterialCatalogFilters,filterMaterialCatalogRows,isAllCatalogValue,materialCatalogEntityGroups,materialCatalogFacetCounts,materialCatalogUsage,uniqueMaterialCatalogRows,type MaterialCatalogFacet,type MaterialCatalogFilters,type MaterialCatalogPreparation,type MaterialCatalogRow} from './material-catalog-facets';
import {CanvasSymbol,canvasTone} from './free-canvas';
import {entityCanvasIcon} from './entity-canvas-appearance';
import {MaterialReviewDrawer} from './material-review-drawer';
import {saveMaterialBrowseLocation} from './material-browse-state';
import {materialPanelIntent,materialPanelLocation,exactMaterialPanelMatch,type MaterialPanelIntent,type MaterialPanelKind} from './material-catalog-panel';
import {exactMaterialRepresentation,materialAttributes,materialReferenceEdges,materialReferenceLevels,materialRepresentativeImage} from './material-canvas-projection';
import {MaterialAppearanceIcon,MaterialProgressBadge,materialMediaAppearance,materialStageAppearance} from './material-appearance';
import './material-entity-review.css';

export function MaterialReviewPoints({requirement,historical=false}:{requirement:MaterialRequirement;version?:V7AssetVersion|null;historical?:boolean}){
 const points=materialExtraReviewPoints(requirement);
 if(!historical&&!points.length)return null;
 return <section className="entity-review-points" aria-label="审阅要点">{historical?<p>历史版本按实际生产资料和原冻结标准核对；当前要求不补作历史生成依据。</p>:<><h3>补充审阅要点</h3><ul>{points.map((p,i)=><li key={i}>{visibleText(p)}</li>)}</ul></>}</section>;
}

type TrialBinding={trialThemeId:string;entityId:string;stateId:string;title:string;mediaType:string;displayState:string;reason:string;versions:Array<{scopeId?:string;mediaId:string;versionId:string;sha256:string;lifecycle:string}>};
type Directory={revisionId?:string;releaseId?:string;graph:DomainGraph;bindings:Array<{requirementId:string;entityId:string;stateId:string;representationId?:string;reviewFocus?:{points:Array<{label:string}>}}>;trials:TrialBinding[];staleIds:string[]};
export type MaterialCatalogControlPatch={search?:string;mediaType?:'全部'|MaterialMediaType;creatorStage?:'全部'|MaterialCreatorStage;episodeScope?:string;sceneScope?:string};
type Props={initialRead?:MaterialCatalogRead;model?:ProductionModel;requirements:MaterialRequirement[];selectedRequirement:MaterialRequirement|null|undefined;mode?:'classification'|'episodes';onSelect:(r:MaterialRequirement)=>void;stageFor:(r:MaterialRequirement)=>MaterialCreatorStageProjection;inspector:ReactNode;inspectorReady?:boolean;episodeScope:string;sceneScope:string;mediaFilter:string;stageFilter:string;search:string;catalogLoading?:boolean;onFiltersChange?:(patch:MaterialCatalogControlPatch)=>void};
type Entry=MaterialCatalogRow&{representationId?:string;title:string;requirement?:MaterialRequirement;trial?:TrialBinding;stage?:MaterialCreatorStageProjection};
type ChipOption={value:string;label:string;count:number;description?:string;appearance?:'media'|'category'|'stage'};
const mediaLabels:Record<string,string>={IMAGE:'图像',AUDIO:'声音',VIDEO:'视频',TEXT:'文本',UNKNOWN:'媒介待核'};
const entityLabels:Record<string,string>={CHARACTER:'人物',PERSON:'人物',LOCATION:'地点',PROP:'道具',GROUP:'群体与组合',UNRESOLVED:'归属待核',PRODUCTION_THEME:'制作主题'};
const normalize=(value:string)=>isAllCatalogValue(value)?'ALL':value;


function EntityThumbnail({version,trial,mediaType}:{version?:V7AssetVersion;trial?:TrialAsset;mediaType:string}){
 const {url}=useOriginalMediaUrl(version);const src=version?(url||version.preview):trial?.mediaUrl;const [failed,setFailed]=useState('');
 return <span className="material-entity-thumbnail" data-thumbnail-version={version?.id||trial?.versionId||undefined} data-thumbnail-sha={version?.sha256||trial?.sha256||undefined}>{src&&failed!==src?<img src={runtimePath(src)} alt="" loading="lazy" decoding="async" onError={()=>setFailed(src)}/>:<MaterialAppearanceIcon kind="media" value={mediaType}/>}</span>;
}

function EntityProgressSummary({rows,trialCount}:{rows:MaterialCatalogRow[];trialCount:number}){
 const required=uniqueMaterialCatalogRows(rows).filter(row=>row.required&&row.currentSelectable!==false&&row.countsAsAtomic!==false);
 return <span className="material-entity-progress-copy"><span className="material-entity-progress-summary" data-entity-progress-summary>{materialCreatorStageOptions.map(({id,label})=>{
  const count=required.filter(row=>(materialCreatorStageOptions.some(stage=>stage.id===row.creatorStage)?row.creatorStage:'INITIAL')===id).length;
  return <span key={id} role="img" className={'material-entity-stage-count'+(count===0?' is-zero':'')} data-entity-stage-count={id} data-count={count} aria-label={label+' '+count+'项需求'} title={label+'：'+count+' 项需求'} style={{color:materialStageAppearance(id).tone}}><MaterialAppearanceIcon kind="stage" value={id}/><b aria-hidden="true">{count}</b></span>;
 })}<span className="material-entity-total" data-entity-total-count={required.length} title="当前筛选下的正式素材需求总数">总{required.length}</span></span>{trialCount>0&&<small className="material-entity-trial-count">另 {trialCount} 项独立试制</small>}</span>;
}

function CatalogChips({label,value,options,onChange,limit=10,defaultExpanded=false}:{label:string;value:string;options:ChipOption[];onChange:(value:string)=>void;limit?:number;defaultExpanded?:boolean}){
 const [expanded,setExpanded]=useState(defaultExpanded),[query,setQuery]=useState('');
 const matching=options.filter(option=>option.value==='ALL'||option.value===value||!query|| (option.label+' '+(option.description||'')).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const selected=matching.find(option=>option.value===value),compact=matching.slice(0,limit);if(selected&&!compact.includes(selected))compact.push(selected);
 return <fieldset className="material-facet" data-material-facet={label}><legend>{label}</legend><div className="material-facet-main"><div className="material-facet-chips">{(expanded||query?matching:compact).map(option=><button type="button" key={option.value} className={'material-filter-chip '+(option.value===value?'is-active ':'')+(option.count===0?'is-zero':'')} aria-pressed={option.value===value} aria-label={label+'：'+option.label+'，'+option.count+'项需求'} style={option.appearance==='stage'&&option.value!=='ALL'?{'--material-progress-tone':materialStageAppearance(option.value).tone} as CSSProperties:undefined} data-material-progress={option.appearance==='stage'&&option.value!=='ALL'?option.value:undefined} title={option.description||option.label} onClick={()=>onChange(option.value===value?'ALL':option.value)}>{option.appearance&&option.value!=='ALL'&&<MaterialAppearanceIcon kind={option.appearance} value={option.value}/>}<span>{option.label}</span><b aria-hidden="true">{option.count}</b></button>)}</div>{options.length>limit&&<div className="material-facet-more"><button type="button" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'收起选项':'展开其余 '+Math.max(0,matching.length-compact.length)+' 项'}</button>{expanded&&<input aria-label={'查找'+label+'选项'} value={query} onChange={event=>setQuery(event.target.value)} placeholder={'查找'+label}/>}</div>}</div></fieldset>;
}

export function EntityMaterialCatalog({initialRead,model,requirements,selectedRequirement,onSelect,stageFor,inspector,inspectorReady=true,episodeScope,sceneScope,mediaFilter,stageFilter,search,catalogLoading=false,onFiltersChange}:Props){
 const {hostedReadOnly}=useRuntimeMode();
 const instance=useInstanceProfile(),cacheScope=workspaceCacheScope(instance);
 const [workspace,setWorkspace]=useState<WorkspaceState|null>(null),[directory,setDirectory]=useState<Directory|null>(null),[preparation,setPreparation]=useState<MaterialCatalogPreparation|null>(null);
 const [canvasHighlight,setCanvasHighlight]=useState<{entityId:string;nodeId?:string}>({entityId:''});
 const [reading,setReading]=useState(true);
 const [error,setError]=useState(''),[refresh,setRefresh]=useState(0),[selectedEntity,setSelectedEntity]=useState(''),[directoryQuery,setDirectoryQuery]=useState('');
 const [panel,setPanel]=useState<MaterialPanelIntent|null>(null),[panelError,setPanelError]=useState(''),[trialSnapshots,setTrialSnapshots]=useState<TrialSnapshot[]>([]),[trialVersion,setTrialVersion]=useState('');
 const [definitionOwner,setDefinitionOwner]=useState<'MATERIAL'|'SETTINGS'>('MATERIAL'),[edit,setEdit]=useState<{collection:'states'|'representations'|'requirements'|'relations';id:string}|null>(null);
 const [filters,setFilters]=useState<MaterialCatalogFilters>(()=>({...allMaterialCatalogFilters(),mediaType:normalize(mediaFilter),creatorStage:normalize(stageFilter),episodeUid:normalize(episodeScope),sceneId:normalize(sceneScope),search}));
 const [initialLocation]=useState(()=>typeof window==='undefined'?null:window.location.href);
 const [lastPanelLocation,setLastPanelLocation]=useState('');
 useEffect(()=>{if(refresh===0&&initialRead?.scope===cacheScope){const [w,d,p]=initialRead.values as [WorkspaceState,Directory,MaterialCatalogPreparation];setWorkspace(w);setDirectory(d);setPreparation(p);setTrialSnapshots(initialRead.trials as TrialSnapshot[]);setError('');setReading(false);return;}const c=new AbortController();setReading(true);setError('');const urls=['/api/v1/workspaces/domain-workspaces?owner=MATERIAL','/api/v1/workspaces/material-directory?detail=summary','/api/v1/workspaces/production-preparation'];void (hostedReadOnly?readWorkspaceBatch<unknown>(urls,cacheScope,c.signal).then(values=>({values,trials:[] as TrialSnapshot[]})):loadTrialWorkspace(c.signal,cacheScope,urls)).then(({values,trials})=>{if(c.signal.aborted)return;const [w,d,p]=values as [WorkspaceState,Directory,MaterialCatalogPreparation];setWorkspace(w);setDirectory(d);setPreparation(p);setTrialSnapshots(trials);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setReading(false);});return()=>c.abort();},[refresh,cacheScope,hostedReadOnly,initialRead]);
 useEffect(()=>{const f=()=>setRefresh(v=>v+1);for(const e of ['review:relations-updated','review:operations-updated','review:sources-updated','focus'])window.addEventListener(e,f);return()=>{for(const e of ['review:relations-updated','review:operations-updated','review:sources-updated','focus'])window.removeEventListener(e,f);};},[]);
 const readLocation=useCallback((href:string)=>{setLastPanelLocation(href);const u=new URL(href),intent=materialPanelIntent(u.searchParams);setPanelError(intent.error);setPanel(intent.kind==='closed'?null:intent);setSelectedEntity(intent.entityId);setTrialVersion(intent.trial?intent.versionId:'');setEdit(intent.definition||null);setFilters(current=>({...current,entityType:u.searchParams.get('materialEntityType')||'ALL',entityId:'ALL',stateId:'ALL'}));if(intent.kind==='closed'&&!intent.error&&!u.searchParams.has('materialPanel')&&(u.search||u.hash)){u.searchParams.set('materialPanel','closed');history.replaceState(history.state,'',u);saveMaterialBrowseLocation(u);}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydrate the original URL once, then react only to explicit navigation events.
 useEffect(()=>{readLocation(initialLocation||location.href);},[initialLocation,readLocation]);
 useEffect(()=>{const restore=(event:Event)=>{const incoming=materialPanelIntent(new URL(location.href).searchParams),previous=lastPanelLocation?new URL(lastPanelLocation):null;const sameDefinition=Boolean(new URL(location.href).searchParams.get('view')==='materials'&&previous?.searchParams.get('view')==='materials'&&edit&&incoming.definition?.collection===edit.collection&&incoming.definition.id===edit.id&&incoming.entityId===(previous?.searchParams.get('entity')||''));if(edit&&!sameDefinition&&!window.dispatchEvent(new Event('review:configuration-before-leave',{cancelable:true}))){event.stopImmediatePropagation();if(lastPanelLocation)history.pushState(history.state,'',lastPanelLocation);return;}readLocation(location.href);};window.addEventListener('popstate',restore,true);window.addEventListener('review:material-panel-location',restore);const reset=()=>readLocation(location.href);window.addEventListener('review:root-location',reset);return()=>{window.removeEventListener('popstate',restore,true);window.removeEventListener('review:material-panel-location',restore);window.removeEventListener('review:root-location',reset);};},[edit,lastPanelLocation,readLocation]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- The parent owns these public filter axes, not drawer open intent.
 useEffect(()=>{setFilters(current=>({...current,mediaType:normalize(mediaFilter),creatorStage:normalize(stageFilter),episodeUid:normalize(episodeScope),sceneId:normalize(sceneScope),search}));},[mediaFilter,stageFilter,episodeScope,sceneScope,search]);
 const readOnly=hostedReadOnly||workspace?.readOnly===true;
 const graph=useMemo(()=>directory?.graph||workspace?.graph||{schemaVersion:'1.0',entities:[],states:[],representations:[],relations:[],requirements:[]} as DomainGraph,[directory,workspace]);
 const entityById=useMemo(()=>new Map(graph.entities.map(entity=>[entity.id,entity])),[graph]),stateById=useMemo(()=>new Map(graph.states.map(state=>[state.id,state])),[graph]);
 const entityLabel=(id:string)=>visibleText(entityById.get(id)?.name||'归属待核');
 const entityTypeLabel=(type:string)=>workspace?.configuration.entityTypes.find(row=>row.id===type)?.label||entityLabels[type]||'制作主题';
 const stateLabel=(id:string)=>visibleText(stateById.get(id)?.label||'状态归属未登记');
 const allTrialAssets=useMemo(()=>trialSnapshots.flatMap(snapshot=>snapshot.assets),[trialSnapshots]);
 const trialBindings=useMemo(()=>{
  const result:TrialBinding[]=(directory?.trials||[]).map(trial=>({...trial,versions:[...trial.versions]}));
  for(const snapshot of trialSnapshots)for(const recipe of snapshot.recipes){
   const subjectId=recipe.originalSubjectId||recipe.subjectId;
   const assets=snapshot.assets.filter(asset=>asset.mediaId===subjectId||asset.mediaId===recipe.subjectId);
   let binding=result.find(trial=>recipe.sourceTrialThemeId===trial.trialThemeId||trial.versions.some(version=>version.mediaId===subjectId));
   if(!binding){
    const requirement=requirements.find(row=>row.id===recipe.sourceRequirementId&&row.requirementClass==='REQUIRED');
    const ownership=directory?.bindings.find(row=>row.requirementId===requirement?.id);
    if(!requirement||!ownership)continue;
    binding={trialThemeId:`TRIAL:${snapshot.scope.id}:${subjectId}`,entityId:ownership.entityId,stateId:ownership.stateId,title:recipe.label,mediaType:recipe.mediaKind||assets[0]?.mediaKind||String(requirement.mediaType||requirement.mediaKind),displayState:'待生成',reason:`${requirement.title}的独立候选；本次产出尚未绑定为正式采用输入。`,versions:[]};
    result.push(binding);
   }
   for(const asset of assets){const prior=binding.versions.findIndex(version=>version.versionId===asset.versionId&&version.sha256===asset.sha256&&(!version.scopeId||version.scopeId===snapshot.scope.id));const next={scopeId:snapshot.scope.id,mediaId:asset.mediaId,versionId:asset.versionId,sha256:asset.sha256,lifecycle:asset.lifecycle};if(prior>=0)binding.versions[prior]=next;else binding.versions.push(next);}
   const latest=binding.versions.at(-1);if(latest)binding.displayState=latest.lifecycle==='RELEASED'?'已通过':latest.lifecycle==='REVIEW_PENDING'?'待审阅':'已定义';
  }
  return result;
 },[directory,requirements,trialSnapshots]);
 const entries:Entry[]=useMemo(()=>uniqueMaterialCatalogRows([
  ...requirements.filter(requirement=>requirement.requirementClass==='REQUIRED').map(requirement=>{
   const binding=directory?.bindings.find(row=>row.requirementId===requirement.id),representation=exactMaterialRepresentation(graph,requirement.id,binding?.representationId);
   const entityId=binding?.entityId||representation?.entityId||'UNASSIGNED',stateId=binding?.stateId||representation?.stateId||'BASE',entity=entityById.get(entityId),state=stateById.get(stateId);
   const taxonomy=classifiedMaterial(requirement as unknown as Record<string,unknown>&{category:string;mediaKind:string;shotIds:string[]}),stage=stageFor(requirement);
   const versionIds=(model?.assetFamilies||[]).filter(family=>requirement.assetFamilyRefs.includes(family.id)).flatMap(family=>family.versionRefs||[]),usage=materialCatalogUsage(requirement,preparation);
   const usagePairs=usage.sceneIds.flatMap(sceneId=>(preparation?.candidate?.episodes||[]).filter(episode=>episode.sceneIds.includes(sceneId)).map(episode=>({episodeUid:episode.episodeUid,sceneId})));
   const usageLabels=[...(preparation?.candidate?.episodes||[]).filter(episode=>usage.episodeUids.includes(episode.episodeUid)).flatMap(episode=>[episode.displayId,episode.title]),...(preparation?.candidate?.scenes||[]).filter(scene=>usage.sceneIds.includes(scene.id)).flatMap(scene=>[scene.displayId,scene.title])];
   return {id:requirement.id,required:true,currentSelectable:currentMaterialDirectoryRow(requirement),countsAsAtomic:atomicMaterialDirectoryRow(requirement),title:requirement.title,representationId:representation?.id,entityId,entityType:entity?.type||'UNRESOLVED',stateId,mediaType:taxonomy.mediaType,creatorStage:stage.creatorStage,stage,requirement,...usage,usagePairs,searchText:[requirement.id,requirement.title,entity?.name,state?.label,...Object.values(state?.dimensions||{}),requirement.storyBasis?.sourceRef,...requirement.assetFamilyRefs,...versionIds,...usageLabels,requirement.cardSpec?JSON.stringify(requirement.cardSpec):''].filter(Boolean).join(' ')};
  }),
  ...trialBindings.map(trial=>({id:trial.trialThemeId,required:false,title:trial.title,entityId:trial.entityId,entityType:entityById.get(trial.entityId)?.type||'UNRESOLVED',stateId:trial.stateId,mediaType:trial.mediaType,creatorStage:({已定义:'INITIAL',待生成:'PRODUCTION_READY',待审阅:'PENDING_REVIEW',已通过:'APPROVED'} as Record<string,string>)[trial.displayState]||'INITIAL',sceneIds:[],episodeUids:[],searchText:[trial.title,entityById.get(trial.entityId)?.name,stateById.get(trial.stateId)?.label].join(' '),trial})),
 ]),[requirements,directory,graph,entityById,stateById,stageFor,preparation,model?.assetFamilies,trialBindings]);

 const filtered=filterMaterialCatalogRows(entries,filters);
 const entryFor=(intent:MaterialPanelIntent|null)=>{if(!intent||intent.kind!=='material')return undefined;if(intent.id)return exactMaterialPanelMatch(entries.filter(row=>Boolean(row.trial)===intent.trial),intent.id,row=>row.id,publicRef);const familyIds=[...new Set(entries.flatMap(row=>row.requirement?.assetFamilyRefs||[]))],familyId=exactMaterialPanelMatch(familyIds,intent.familyId,id=>id,publicRef);const matches=familyId?entries.filter(row=>row.requirement?.assetFamilyRefs.includes(familyId)):[];return matches.length===1?matches[0]:undefined;};
 const panelEntry=entryFor(panel),definition=panel?.definition;
 // Old state-definition links remain read-only source audits. Resolve their
 // exact record even when the current directory no longer exposes that layer.
 const stateDefinition=definition?.collection==='states'?(workspace?.graph.states.find(row=>row.id===definition.id)||stateById.get(definition.id)):undefined;
 const definitionRow=definition?.collection==='states'?stateDefinition:definition?workspace?.graph[definition.collection].find(row=>row.id===definition.id):undefined;
 const panelState=panel?.kind==='state'?(stateDefinition||stateById.get(panel.id)):undefined;
 const definitionEntityId=definitionRow&&'entityId'in definitionRow?definitionRow.entityId:definitionRow&&'representationId'in definitionRow?graph.representations.find(row=>row.id===definitionRow.representationId)?.entityId:'';
 const relationIntent=panel?.kind==='relation'?graph.relations.find(row=>row.id===panel.id):undefined;
 const relationEntityIds=relationIntent?[...new Set([relationIntent.from,relationIntent.to].map(endpoint=>endpoint.kind==='ENTITY'?(entityById.has(endpoint.id)?endpoint.id:undefined):endpoint.kind==='STATE'?stateById.get(endpoint.id)?.entityId:graph.representations.find(row=>row.id===endpoint.id)?.entityId).filter((id):id is string=>Boolean(id)))]:[];
 const structuralEntityId=panel?.kind==='relation'?(panel.id.startsWith('entity-state:')?stateById.get(panel.id.slice('entity-state:'.length))?.entityId:/^(state-material:|entity-material:)/.test(panel.id)?entries.find(row=>row.id===panel.id.slice(panel.id.indexOf(':')+1))?.entityId:''):'';
 const inferredEntityId=panel?.kind==='entity'?panel.id:definitionEntityId||panelState?.entityId||panelEntry?.entityId||structuralEntityId||(relationEntityIds.length===1?relationEntityIds[0]:'');
 const explicitEntityId=selectedEntity||inferredEntityId;
 const groups=materialCatalogEntityGroups(filtered);
 if(entityById.has(explicitEntityId)&&!groups.some(group=>group.entityId===explicitEntityId))groups.push({entityId:explicitEntityId,rows:[],requirementCount:0,trialCount:0});
 groups.sort((a,b)=>entityLabel(a.entityId).localeCompare(entityLabel(b.entityId),'zh-CN'));
 const activeEntityId=explicitEntityId?(entityById.has(explicitEntityId)||groups.some(group=>group.entityId===explicitEntityId)?explicitEntityId:''):groups[0]?.entityId||'';
 const activeEntity=entityById.get(activeEntityId),activeEntries=groups.find(group=>group.entityId===activeEntityId)?.rows||[];
 const visibleGroups=groups.filter(group=>!directoryQuery||entityLabel(group.entityId).toLocaleLowerCase().includes(directoryQuery.trim().toLocaleLowerCase()));
 const typeGroups=[...new Set(visibleGroups.map(group=>entityById.get(group.entityId)?.type||'UNRESOLVED'))].map(type=>({type,groups:visibleGroups.filter(group=>(entityById.get(group.entityId)?.type||'UNRESOLVED')===type)}));
 const candidate=preparation?.candidate,episodes=candidate?.episodes||[],candidateScenes=candidate?.scenes||[];
 const invalidEpisode=Boolean(preparation&&!isAllCatalogValue(filters.episodeUid)&&!episodes.some(episode=>episode.episodeUid===filters.episodeUid)),invalidScene=Boolean(preparation&&!isAllCatalogValue(filters.sceneId)&&!candidateScenes.some(scene=>scene.id===filters.sceneId));
 const selectedEpisode=episodes.find(episode=>episode.episodeUid===filters.episodeUid),selectedScene=candidateScenes.find(scene=>scene.id===filters.sceneId);
 const facetOptions:Partial<Record<MaterialCatalogFacet,ChipOption[]>>={
  mediaType:materialCatalogFacetCounts(entries,filters,'mediaType',[{value:'ALL',label:'全部媒介'},...materialMediaTypeOptions.map(row=>({value:row.id,label:row.label,appearance:'media' as const})),...(entries.some(row=>row.mediaType==='UNKNOWN')?[{value:'UNKNOWN',label:'媒介待核',appearance:'media' as const}]:[])]),
  entityType:materialCatalogFacetCounts(entries,filters,'entityType',[{value:'ALL',label:'全部类别'},...[...new Set(entries.map(row=>row.entityType))].map(value=>({value,label:entityTypeLabel(value),appearance:'category' as const}))]),
  episodeUid:materialCatalogFacetCounts(entries,filters,'episodeUid',[{value:'ALL',label:'全部集'},...episodes.map(episode=>({value:episode.episodeUid,label:episode.displayId,description:episode.title})),...(invalidEpisode?[{value:filters.episodeUid,label:'未匹配集（保留原值）',description:filters.episodeUid}]:[])]),
  sceneId:materialCatalogFacetCounts(entries,filters,'sceneId',[{value:'ALL',label:'全部场'},...candidateScenes.map(scene=>({value:scene.id,label:scene.displayId,description:scene.title})),...(invalidScene?[{value:filters.sceneId,label:'未匹配场（保留原值）',description:filters.sceneId}]:[])]),
  creatorStage:materialCatalogFacetCounts(entries,filters,'creatorStage',[{value:'ALL',label:'全部进度'},...materialCreatorStageOptions.map(row=>({value:row.id,label:row.label,appearance:'stage' as const}))]),
 };
 function maySwitch(){return !edit||window.dispatchEvent(new Event('review:configuration-before-leave',{cancelable:true}));}
 function writePanel(kind:MaterialPanelKind,id='',entityId=activeEntityId,trial=false){const u=new URL(location.href);u.search=materialPanelLocation(u.searchParams,kind,id,entityId,{trial}).toString();history.replaceState(history.state,'',u);saveMaterialBrowseLocation(u);setLastPanelLocation(u.href);}
 function closePanel(){if(!maySwitch())return false;setEdit(null);setPanel(null);setPanelError('');writePanel('closed');return true;}
 function openPanel(kind:Exclude<MaterialPanelKind,'closed'>,id:string,entityId=activeEntityId,trial=false){if(!maySwitch())return;setEdit(null);setPanelError('');setDefinitionOwner('MATERIAL');setSelectedEntity(entityId);setPanel({kind,id,entityId,trial,familyId:'',versionId:'',legacy:false,error:''});writePanel(kind,id,entityId,trial);}
 function choose(entry:Entry){if(!maySwitch())return;openPanel('material',entry.id,entry.entityId,Boolean(entry.trial));setTrialVersion('');if(entry.requirement)onSelect(entry.requirement);}
 function chooseTrialVersion(versionId:string){if(!trialAssets.some(row=>row.versionId===versionId)||!panel?.trial)return;setTrialVersion(versionId);const u=new URL(location.href);u.searchParams.set('materialTrialVersion',versionId);u.searchParams.delete('version');history.replaceState(history.state,'',u);setLastPanelLocation(u.href);}
 function chooseEntity(id:string){if(!maySwitch())return;setSelectedEntity(id);setEdit(null);setPanel(null);setPanelError('');writePanel('closed','',id);}
 function changeFilter(facet:MaterialCatalogFacet,value:string){if(!maySwitch())return;setFilters(current=>({...current,[facet]:value}));setEdit(null);const external=value==='ALL'?'全部':value;if(facet==='mediaType')onFiltersChange?.({mediaType:external as '全部'|MaterialMediaType});if(facet==='creatorStage')onFiltersChange?.({creatorStage:external as '全部'|MaterialCreatorStage});if(facet==='episodeUid')onFiltersChange?.({episodeScope:external});if(facet==='sceneId')onFiltersChange?.({sceneScope:external});if(facet==='entityType'){const u=new URL(location.href);if(value==='ALL')u.searchParams.delete('materialEntityType');else u.searchParams.set('materialEntityType',value);history.replaceState(history.state,'',u);saveMaterialBrowseLocation(u);}}
 function clearFilters(){if(!maySwitch())return;setFilters(allMaterialCatalogFilters());setDirectoryQuery('');onFiltersChange?.({search:'',mediaType:'全部',creatorStage:'全部',episodeScope:'全部',sceneScope:'全部'});const u=new URL(location.href);for(const key of ['materialEntityType','materialEntityFilter'])u.searchParams.delete(key);history.replaceState(history.state,'',u);saveMaterialBrowseLocation(u);}
 const referenceEdges=materialReferenceEdges(graph,activeEntries,workspace?.configuration.relationTypes.filter(type=>type.class==='REFERENCE').map(type=>type.id)||[]);
 const referenceLevels=materialReferenceLevels(activeEntries,referenceEdges),levelRows=new Map<number,number>();
 const positions=new Map(activeEntries.map(entry=>{const level=referenceLevels['material:'+entry.id]||0,index=levelRows.get(level)||0;levelRows.set(level,index+1);return [entry.id,{x:424+level*330,y:62+index*160}];}));
 const attributesFor=(entry:Entry)=>materialAttributes(graph,entry,directory?.releaseId===workspace?.releaseId?workspace?.graph:undefined);
 const attributeLabel=(name:string)=>workspace?.configuration.stateDimensions.find(dimension=>dimension.id===name)?.label||name;
 const canvasNodes:CanvasNode[]=activeEntityId?[{id:activeEntityId,label:entityLabel(activeEntityId),group:'实体',detail:activeEntity?entityTypeLabel(activeEntity.type):'实体归属尚未登记',icon:entityCanvasIcon(activeEntity?.type||'UNRESOLVED'),tone:canvasTone(activeEntity?.type||'UNRESOLVED')},...activeEntries.map(entry=>{const attributes=attributesFor(entry).attributes,stage=materialStageAppearance(entry.creatorStage);return {id:'material:'+entry.id,label:visibleText(entry.title),group:'素材',...positions.get(entry.id),height:124,detail:(entry.trial?'独立试制 · ':'')+(mediaLabels[entry.mediaType]||'媒介待核')+(attributes.length?' · '+attributes.slice(0,2).map(attribute=>attributeLabel(attribute.name)+'：'+attribute.value).join(' · '):''),icon:(materialMediaAppearance[entry.mediaType]||materialMediaAppearance.UNKNOWN).icon,tone:(materialMediaAppearance[entry.mediaType]||materialMediaAppearance.UNKNOWN).tone,badge:{value:entry.creatorStage,label:stage.label,icon:stage.icon,tone:stage.tone}};})]:[];
 const nodeIds=new Set(canvasNodes.map(node=>node.id));
 const canvasSelectedId=canvasHighlight.entityId===activeEntityId?(nodeIds.has(canvasHighlight.nodeId||'')?canvasHighlight.nodeId:undefined):panel?.kind==='material'&&panelEntry&&nodeIds.has('material:'+panelEntry.id)?'material:'+panelEntry.id:undefined;
 const edgeForEntry=(entry:Entry):CanvasEdge=>({id:'entity-material:'+entry.id,from:entry.entityId,to:'material:'+entry.id,label:'素材归属',directed:true,hideLabel:true});
 const structuralEdges:CanvasEdge[]=activeEntries.map(edgeForEntry);
 const canvasEdges:CanvasEdge[]=[...structuralEdges,...referenceEdges];
 const panelReference=panel?.kind==='relation'?referenceEdges.find(row=>row.id===panel.id):undefined;
 const panelRelation=panelReference?graph.relations.find(row=>row.id===panelReference.relationId):undefined;
 const linkedEntry=panel?.kind==='relation'&&/^(entity-material:|state-material:)/.test(panel.id)?entries.filter(row=>row.id===panel.id.slice(panel.id.indexOf(':')+1)&&row.entityId===activeEntityId):[];
 const legacyStateRelation=panel?.kind==='relation'&&panel.id.startsWith('entity-state:')?stateById.get(panel.id.slice('entity-state:'.length)):undefined;
 const structuralRelation=panel?.kind==='relation'?(structuralEdges.find(row=>row.id===panel.id)||(linkedEntry.length===1?{...edgeForEntry(linkedEntry[0]),id:panel.id}:undefined)||(legacyStateRelation?.entityId===activeEntityId?{id:panel.id,from:activeEntityId,to:legacyStateRelation.id,label:'历史状态来源（兼容链接）',directed:true}:undefined)):undefined;
 const relationshipState=legacyStateRelation;
 const relationshipEntry=linkedEntry.length===1?linkedEntry[0]:undefined;
 let targetError=panelError;
 if(panel&&directory&&workspace&&!definition){if(panel.kind==='entity'&&!entityById.has(panel.id))targetError='实体永久身份未在当前目录登记，未换绑到其他实体。';if(panel.kind==='state'&&(!panelState||panel.entityId&&panelState.entityId!==panel.entityId))targetError='状态永久身份未登记，或不属于链接指定的实体。已保留原身份，未换绑。';if(panel.kind==='material'&&(!panelEntry||panel.entityId&&panelEntry.entityId!==panel.entityId))targetError='素材永久身份或实体归属无法精确匹配，未打开默认素材。';if(panel.kind==='relation'&&(!panelRelation&&!structuralRelation||panelRelation&&(!panelReference||!nodeIds.has(panelReference.from)||!nodeIds.has(panelReference.to)||panelRelation.historicalOnly)))targetError='关系永久身份未登记，或不属于当前实体画布，未推断关联。';}
 if(definition&&directory&&workspace&&(!definitionRow||panel?.entityId&&definitionEntityId&&definitionEntityId!==panel.entityId))targetError='素材定义永久身份未登记，或不属于链接指定实体。已保留原值，未打开其他定义。';
 const panelEntity=panel?.kind==='entity'?entityById.get(panel.id):undefined;
 const relatedEntries=panel?.kind==='entity'?entries.filter(entry=>entry.entityId===panel.id):panel?.kind==='state'?entries.filter(entry=>entry.stateId===panel.id&&entry.entityId===panelState?.entityId):relationshipEntry?[relationshipEntry]:relationshipState?entries.filter(entry=>entry.stateId===relationshipState.id&&entry.entityId===relationshipState.entityId):panelReference?entries.filter(entry=>[panelReference.from,panelReference.to].includes('material:'+entry.id)):[];
 const trial=panelEntry?.trial,trialAssets=allTrialAssets.filter(asset=>trial?.versions.some(version=>(!version.scopeId||version.scopeId===asset.scopeId)&&version.mediaId===asset.mediaId&&version.versionId===asset.versionId&&version.sha256===asset.sha256)),asset=trialVersion?trialAssets.find(row=>row.versionId===trialVersion):trialAssets.at(-1);
 const trialSnapshot=asset?trialSnapshots.find(snapshot=>snapshot.scope.id===asset.scopeId):undefined;
 if(panel?.trial&&trialVersion&&trialSnapshots.length&&!asset)targetError='试制版本未在该主题的精确版本与 SHA 绑定中登记，未换用最新版本。';

 const panelTitle=targetError?'无法定位原对象':definitionRow?('label'in definitionRow?visibleText(definitionRow.label):'title'in definitionRow?visibleText(definitionRow.title):'素材定义'):panel?.kind==='entity'?entityLabel(panel.id):panel?.kind==='state'?stateLabel(panel.id):panel?.kind==='material'?visibleText(panelEntry?.title||'正在核对素材'):visibleText(panelRelation?.label||structuralRelation?.label||'正在核对关系');
 const renderRelated=()=> <section className="material-panel-related"><h3>精确关联的素材需求</h3>{relatedEntries.length?<div>{relatedEntries.map(entry=><button type="button" key={entry.id} data-related-material-id={entry.id} onClick={()=>choose(entry)}><strong>{visibleText(entry.title)}</strong><small>{entry.trial?'独立试制 · 不计正式需求':entry.stage?.creatorStageLabel} · {stateLabel(entry.stateId)}</small></button>)}</div>:<p>没有已登记的精确关联需求；不会根据名称推测或新建需求。</p>}</section>;

 const thumbnailFor=(entityId:string)=>{const entityEntries=entries.filter(entry=>entry.entityId===entityId),familyIds=[...new Set(entityEntries.flatMap(entry=>entry.requirement?.assetFamilyRefs||[]))],version=materialRepresentativeImage(model,familyIds);const trialCandidates=entityEntries.flatMap(entry=>entry.trial?allTrialAssets.filter(asset=>asset.mediaKind==='IMAGE'&&asset.lifecycle!=='DO_NOT_USE'&&entry.trial!.versions.some(binding=>(!binding.scopeId||binding.scopeId===asset.scopeId)&&binding.mediaId===asset.mediaId&&binding.versionId===asset.versionId&&binding.sha256===asset.sha256)):[]).sort((a,b)=>Number(b.lifecycle==='RELEASED')-Number(a.lifecycle==='RELEASED')||b.version-a.version);return {version,trial:version?undefined:trialCandidates[0],mediaType:version||trialCandidates.length?'IMAGE':entityEntries[0]?.mediaType||'UNKNOWN'};};
 const renderEvidence=(row:{authority?:string;evidence?:unknown[]})=><section className="material-panel-evidence"><h3>依据与维护边界</h3><p>依据级别：{row.authority||'UNKNOWN'}。定义及其关联不证明已生成、正式采用或实际观察。</p>{row.evidence?.length?<pre>{JSON.stringify(row.evidence,null,2)}</pre>:<p>未登记进一步来源证据。</p>}</section>;
 const activeFilterCount=Object.entries(filters).filter(([key,value])=>key==='search'?Boolean(value.trim()):!isAllCatalogValue(value)).length;
 const renderFacet=(facet:MaterialCatalogFacet,label:string,defaultExpanded=false)=><CatalogChips key={facet} label={label} value={filters[facet]} options={facetOptions[facet]||[]} defaultExpanded={defaultExpanded} onChange={value=>changeFilter(facet,value)}/>;
 const waiting=Boolean(catalogLoading||reading||error);
 const loading=<div className="material-catalog-loading" aria-busy={!error}><p role={error?'alert':'status'}>{error||'正在读取完整素材目录、设定与集场用途…'}</p>{error&&<button onClick={()=>setRefresh(value=>value+1)}>重新完整读取</button>}</div>;
 if(!workspace||!directory||!preparation)return loading;
 // Keep mounted editors and their leave guards while revalidating; no partial
 // directory is visible and a background read cannot discard a local draft.
 return <>{waiting&&loading}<div className="material-entity-review" data-material-view="classification" aria-busy={waiting} hidden={waiting} style={waiting?{display:'none'}:undefined}>
  {(invalidEpisode||invalidScene)&&<p role="alert" className="material-invalid-scope">集、场筛选的永久身份不属于当前候选。已保留原筛选值，不会自动清空或换绑；请核对来源后重新点选当前集场。</p>}
  {panelError&&<p role="alert" className="material-invalid-panel">{panelError}</p>}
  {directory&&workspace&&explicitEntityId&&!activeEntityId&&<p role="alert">所选实体身份未匹配当前目录，已保留原值；请核对来源或重新选择实体。</p>}
  <section className="material-catalog-filters" aria-label="素材筛选"><header><label className="material-catalog-search"><span>搜索素材</span><input value={filters.search} onChange={event=>{if(!maySwitch())return;const value=event.target.value;setFilters(current=>({...current,search:value}));onFiltersChange?.({search:value});}} placeholder="素材、实体、状态或版本"/></label><button type="button" onClick={clearFilters} disabled={!activeFilterCount}>清除筛选</button></header><p className="material-filter-count-note">{entries.some(row=>row.countsAsAtomic===false)?'数字只计当前原子需求；整套汇总可查看但不重复计数，原已拆分需求仅保留历史深链。独立试制不计入需求数。':'数字为保留其他筛选、点选该项后可匹配的需求数；同一需求只计一次。独立试制不计入需求数。'}</p>
   <div className="material-facet-section">{renderFacet('mediaType','媒介')}{renderFacet('entityType','实体类别')}</div>
   <div className="material-facet-section" aria-label="剧集用途筛选">{renderFacet('episodeUid','集',true)}{renderFacet('sceneId','场',true)}</div>
   <div className="material-facet-section">{renderFacet('creatorStage','推进到哪一步')}<p className="material-stage-note">已定义含依赖缺项、返修与异常待处理；待生成含排队、生成中及待登记。结果未知须核查，不能重复调用。</p></div>
  </section>
  {!!preparation?.materialLinks?.pending?.length&&<p className="workflow-warning" role="status">部分集场用途需重新核对（{preparation.materialLinks.pending.length} 项）。当前筛选仍包含精确依据未变的用途。</p>}
  {(preparation?.materialLinks?.projectionPolicy==='PER_OCCURRENCE_V2'||!preparation?.stale&&!preparation?.materialLinksStale)&&<details className="material-pending-usage"><summary>当前集场范围尚未归位的准备项</summary><p>这里只显示精确当前场正文对应、尚无需求身份的准备项，不计入素材需求与已采用输入。</p>{(preparation?.materialLinks?.scenes||[]).filter(link=>candidateScenes.some(scene=>scene.id===link.sceneId&&scene.contentHash===link.sceneContentHash)&&(isAllCatalogValue(filters.sceneId)||link.sceneId===filters.sceneId)&&(isAllCatalogValue(filters.episodeUid)||selectedEpisode?.sceneIds.includes(link.sceneId))).flatMap(link=>(link.unboundNeeds||[]).map((need,index)=><p key={link.sceneId+':'+index}>{candidateScenes.find(scene=>scene.id===link.sceneId)?.displayId} · {visibleText(typeof need==='string'?need:need.description)}</p>))}</details>}
  {preparation?.materialLinksStale&&<p role="alert">准备稿或实体目录已更新；原集场用途关联已停用，需重新核对后绑定。</p>}{error&&<p role="alert">{error}<button onClick={()=>setRefresh(value=>value+1)}>重新读取</button></p>}{Boolean(directory?.staleIds.length)&&<p role="alert">部分目录依据已变化，已回到原登记归属，请重新核对实体状态。</p>}
  <div className="material-entity-body">
   <nav className="material-entity-directory" aria-label="实体目录"><header><h3>{selectedScene?selectedScene.displayId+' · 实体':selectedEpisode?selectedEpisode.displayId+' · 实体':'实体目录'}</h3><span>{groups.length} 个实体</span></header><input aria-label="查找目录实体" value={directoryQuery} onChange={event=>setDirectoryQuery(event.target.value)} placeholder="在匹配实体中查找"/><div className="material-entity-directory-list">{!workspace?<p role="status">正在读取实体与状态…</p>:!visibleGroups.length?<p>没有匹配的实体。请调整筛选。</p>:typeGroups.map(({type,groups:rows})=><details key={type} className="material-entity-type-group" data-entity-type={type} open style={{'--entity-tone':canvasTone(type)} as CSSProperties}><summary><CanvasSymbol kind={entityCanvasIcon(type)}/><strong>{entityTypeLabel(type)}</strong><span>{rows.length}</span></summary><div>{rows.map(group=><button type="button" key={group.entityId} data-entity-id={group.entityId} className="material-entity-directory-card" aria-pressed={activeEntityId===group.entityId} onClick={()=>chooseEntity(group.entityId)}><EntityThumbnail {...thumbnailFor(group.entityId)}/><span className="material-entity-directory-copy"><strong>{entityLabel(group.entityId)}</strong><EntityProgressSummary rows={group.rows} trialCount={group.trialCount}/><small className="material-entity-media-summary">{materialMediaTypeOptions.map(m=>({label:m.label,count:group.rows.filter(r=>r.required&&r.countsAsAtomic!==false&&r.mediaType===m.id).length})).filter(m=>m.count>0).map(m=>m.label+" "+m.count).join(" · ")}</small></span></button>)}</div></details>)}</div></nav>
   <section tabIndex={-1} className="material-entity-workspace" aria-label="选中实体的素材工作区"><header className="material-canvas-heading"><div><small>{activeEntity?entityTypeLabel(activeEntity.type):'实体目录'}</small><h2>{activeEntityId?entityLabel(activeEntityId):'请选择实体'}</h2></div><p>单击节点高亮直接关联，双击或 Shift+Enter 查看详情；拖动、缩放仅整理个人阅读布局。</p></header>{activeEntityId?<RelationshipCanvas label="实体与素材关系" notice="实体连线表示素材归属；素材间连线是登记参考定义，不证明已经实际生成或衍生。" viewportKey={'material-entity:'+activeEntityId} height="min(78dvh, 940px)" layout="flow" defaultAllEdges edgeRouting="curved" preserveGraphOnSelect showReadableList={false} onClearSelection={()=>setCanvasHighlight({entityId:activeEntityId})} onSelectEdge={id=>openPanel('relation',id,activeEntityId)} nodes={canvasNodes} edges={canvasEdges} selectedId={canvasSelectedId} onSelect={id=>setCanvasHighlight({entityId:activeEntityId,nodeId:id})} onOpenNode={id=>{const entry=activeEntries.find(row=>'material:'+row.id===id);if(entry)choose(entry);else if(id===activeEntityId)openPanel('entity',id,id);}}/>:<p>没有可用实体，未知身份不会自动替换为其他对象。</p>}</section>
  </div>
  <MaterialReviewDrawer open={Boolean(panel)} kind={panel?.kind||'closed'} title={panelTitle} onClose={closePanel}>
   {targetError?<section role="alert" className="material-panel-error"><h3>已停止静默回退</h3><p>{targetError}</p><code>{panel?.id||panel?.familyId}</code></section>:!directory||!workspace?<p role="status">正在核对当前发布目录与永久身份…</p>:edit&&edit.collection!=='states'?<StorySettingsWorkspace owner={definitionOwner} compact entityId={activeEntityId} focus={edit}/>:<>
    {panelEntity&&<><dl className="material-panel-facts"><div><dt>永久身份</dt><dd>{panelEntity.id}</dd></div><div><dt>实体类别</dt><dd>{entityTypeLabel(panelEntity.type)}</dd></div><div><dt>说明</dt><dd>{visibleText(panelEntity.description||'UNKNOWN')}</dd></div>{panelEntity.aliases.filter(a=>a!==panelEntity.name&&a!==panelEntity.id).length>0&&<div><dt>别名</dt><dd>{panelEntity.aliases.filter(a=>a!==panelEntity.name&&a!==panelEntity.id).join('、')}</dd></div>}<div><dt>素材覆盖</dt><dd>{entries.filter(e=>e.entityId===panelEntity.id&&e.required&&e.currentSelectable!==false&&e.countsAsAtomic!==false).length} 项需求 · {graph.states.filter(s=>s.entityId===panelEntity.id).length} 个已登记状态</dd></div></dl><section className="entity-business-relations"><h3>已登记关系</h3>{graph.relations.filter(r=>!r.historicalOnly&&r.from.kind==='ENTITY'&&r.to.kind==='ENTITY'&&(r.from.id===panelEntity.id||r.to.id===panelEntity.id)&&entityById.has(r.from.id)&&entityById.has(r.to.id)).map(r=><p key={r.id}><b>{visibleText(r.label)}</b> · {entityLabel(r.from.id===panelEntity.id?r.to.id:r.from.id)}{r.status!=='CONFIRMED'?' · 待确认':''}</p>)}</section></>}
    {panelState&&<><p className="material-stage-note">历史状态／属性来源审计：保留永久身份与原始记录，不再作为当前素材图的独立层级。</p><dl className="material-panel-facts"><div><dt>永久状态身份</dt><dd>{panelState.id}</dd></div><div><dt>所属实体</dt><dd><button onClick={()=>openPanel('entity',panelState.entityId,panelState.entityId)}>{entityLabel(panelState.entityId)}</button></dd></div>{Object.entries(panelState.dimensions).map(([key,value])=><div key={key}><dt>{workspace.configuration.stateDimensions.find(dimension=>dimension.id===key)?.label||key}</dt><dd>{value}</dd></div>)}</dl>{renderRelated()}{renderEvidence(panelState)}</>}
    {panel?.kind==='relation'&&<><section className="material-panel-relation"><h3>{panelRelation?'登记参考定义':'目录归属投影'}</h3><p>{panelRelation?'保留原关系类型、方向、状态与依据。这是登记参考定义，不证明已经作为模型输入，也不证明实际生成衍生。':'由已登记实体归属或需求绑定直接投影，不是新建的业务关系，不生成正式状态或版本。'}</p><dl className="material-panel-facts"><div><dt>精确标识</dt><dd>{panel.id}</dd></div><div><dt>起点</dt><dd>{panelRelation?.from.id||structuralRelation?.from}</dd></div><div><dt>终点</dt><dd>{panelRelation?.to.id||structuralRelation?.to}</dd></div>{panelRelation&&<><div><dt>关系类型</dt><dd>{workspace.configuration.relationTypes.find(type=>type.id===panelRelation.type)?.label||panelRelation.type}</dd></div><div><dt>登记状态</dt><dd>{panelRelation.status}</dd></div><div><dt>用途</dt><dd>{visibleText(panelRelation.purpose||'未登记')}</dd></div></>}</dl></section>{renderRelated()}{panelRelation&&renderEvidence(panelRelation)}{panelRelation&&!readOnly&&workspace.graph.relations.some(relation=>relation.id===panelRelation.id)&&<button onClick={()=>setEdit({collection:'relations',id:panelRelation.id})}>维护这项关系定义</button>}</>}
    {panel?.kind==='material'&&panelEntry&&<section className="material-entity-selected-detail" aria-label="统一素材详情">{trial?<MaterialProgressBadge stage={panelEntry.creatorStage}/>:null}{trial?<article className="material-detail trial-integrated"><p className="material-stage-note">独立试制 · 原结论不重审、不提升为全剧正式采用</p>{asset?<><fieldset className="material-version-chips"><legend>查看版本</legend>{trialAssets.map(row=><button type="button" key={row.versionId} aria-pressed={row.versionId===asset.versionId} onClick={()=>chooseTrialVersion(row.versionId)}>版本 {row.version}</button>)}</fieldset><AssetReview readOnly={readOnly} key={asset.versionId} asset={asset} etag={trialSnapshot!.mutationEtag} currentVersion={asset===trialAssets.at(-1)} refresh={async()=>{setRefresh(value=>value+1);window.dispatchEvent(new Event('review:operations-updated'));}}/></>:<section className="material-output-zone"><h3>{trial.title}</h3><p>{hostedReadOnly?'试制原件只保存在本地，镜像不托管。':'正在读取已登记的试制版本…'}</p></section>}<section className="material-purpose-usage"><h3>为什么需要及用在哪里</h3><p>{trial.reason}</p><p>当前正式集场输入尚未绑定；原放行与返修意见完整保留。</p></section></article>:selectedRequirement?.id===panelEntry.id?inspector:<p role="status">正在精确读取这项素材，未以默认素材替代。</p>}{panelEntry.requirement&&!inspectorReady&&<small>实际版本与完整生产资料核对中。</small>}</section>}
   </>}
  </MaterialReviewDrawer>
 </div></>;
}
