'use client';
import {useEffect,useState} from 'react';
import {visibleText} from './review-semantics';
type Source={objectId:string;revisionId:string;sha256:string;expectedVersion:number;field?:string};
export type BusinessFocus={contextHash:string;historical:boolean;sections:Array<{label:string;text:string;source:Source}>;missing:string[];rules:Array<{title:string;text:string;source:Source}>;sources:Source[];reviewSpec?:{criteria:Array<{id:string;label:string;question?:string}>}|null};
export function useMaterialBusinessFocus(requirementId:string,versionId:string|undefined,refresh:string){
 const [state,setState]=useState<{key:string;value?:BusinessFocus;error?:string}>({key:''});const key=requirementId+':'+versionId+':'+refresh;
 useEffect(()=>{if(!versionId)return;const controller=new AbortController();void fetch('/api/v1/workspaces/material-review-focus?'+new URLSearchParams({requirementId,versionId}),{cache:'no-store',signal:controller.signal}).then(async r=>{const value=await r.json();if(!r.ok)throw Error(typeof value.error==='string'?value.error:'业务依据读取失败');if(!controller.signal.aborted)setState({key,value});}).catch(e=>{if(!controller.signal.aborted)setState({key,error:e.message});});return()=>controller.abort();},[key,requirementId,versionId]);
 return state.key===key?state:{key};
}
export function MaterialBusinessFocus({value,error}:{value?:BusinessFocus;error?:string}){return <section className="material-business-focus" aria-label="具体业务关注重点"><h4>此素材的关注重点</h4>{error?<p role="alert">{error}</p>:!value?<p role="status">正在核对实体、状态与精确用途…</p>:<><p>{value.historical?'以下仅使用此版本冻结的依据。':'结合下列已登记属性核对原件；内容是审阅依据，尚未构成观察结论。'}</p><dl>{value.sections.filter(p=>p.label!=='已登记来源摘录').map((p,i)=><div key={i}><dt>{p.label.replace(/ · (age|dialect|posture|direction|gender)$/,(_,key)=>' · '+({age:'年龄',dialect:'口音',posture:'姿态',direction:'方位',gender:'性别'} as Record<string,string>)[key])}</dt><dd>{visibleText(p.text)}</dd></div>)}</dl>{value.missing.map((text,i)=><p key={i} className="material-context-unknown">UNKNOWN · {text}</p>)}{value.historical&&value.reviewSpec&&<section><h4>原冻结审阅标准</h4>{value.reviewSpec.criteria.map(c=><p key={c.id}><b>{c.label}</b> {c.question}</p>)}</section>}<details><summary>业务依据与项目规则</summary>{value.sections.filter(p=>p.label==='已登记来源摘录').map((p,i)=><blockquote key={i}>{p.text}</blockquote>)}{value.sources.map(s=><p key={s.revisionId}><code>{s.objectId}</code><br/><code>{s.revisionId}</code> · <code>{s.sha256}</code></p>)}{value.rules.map(r=><details key={r.source.revisionId}><summary>{r.title} · 已采用规则</summary><pre>{r.text}</pre></details>)}</details></>}</section>;}
export function HistoricalMaterialFocus({requirementId,versionId}:{requirementId:string;versionId?:string}){const state=useMaterialBusinessFocus(requirementId,versionId,'historical');return <MaterialBusinessFocus {...state}/>;}
