'use client';
import {useEffect,useRef,useState} from 'react';
import {read,commands,cache,uploadMedia} from './client';
import {Assistant} from './assistant';
import {Content} from './content';
import {Editor} from './editor';
import {useSession,readingPositions,rememberPosition} from './session';
import {LinkPicker} from './link-picker';
import {stateLabels,kindLabels,type Detail,type Summary,type Draft} from './types';

const workspaces=[{id:'overview',label:'当前工作',mark:'01',note:'进展与待审'},{id:'story',label:'故事创作',mark:'02',note:'资料、结构与集场'},{id:'settings',label:'故事设定',mark:'03',note:'主体、空间与关系'},{id:'materials',label:'素材管理',mark:'04',note:'需求、版本与依据'},{id:'production',label:'全剧制作',mark:'05',note:'准备、镜头与成片'},{id:'project',label:'系统管理',mark:'06',note:'配置、数据与运行'}];
const tabs:Record<string,string[]>={story:['SOURCE','STORY','EPISODE','SCENE'],settings:['ENTITY','RELATION','SPACE','STATE','REPRESENTATION'],materials:['REQUIREMENT','MATERIAL','ASSET','PROMPT','CALL','EXPECTED_OUTPUT'],production:['PREPARATION','COVERAGE','SHOT_DESIGN','SHOT','INPUT_LOCK','ASSEMBLY','DELIVERABLE'],project:['GUIDANCE','NOTE','COMMENT']};
type View={kind:string;id:string;query:string;offset:number;owner:string;historical:boolean};
const fresh=(module:string):View=>({kind:tabs[module]?.[0]||'',id:'',query:'',offset:0,owner:'',historical:false});
const blankContent=(kind:string)=>kind==='SCENE'?{text:''}:kind==='COMMENT'||kind==='GUIDANCE'||kind==='PROMPT'?{text:''}:{description:''};
function OperationError({error}:{error:any}){return error?<div className="error" role="alert">{error.message||String(error)}{error.operationId&&<small>操作编号：{error.operationId}</small>}</div>:null;}

export default function Desk(){
 const [workspace,setWorkspace]=useState('overview'),[views,setViews]=useState<Record<string,View>>({}),[title,setTitle]=useState('故事审阅台'),[ready,setReady]=useState(false),[summary,setSummary]=useState<any>(null),[error,setError]=useState<any>(null),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[systemTab,setSystemTab]=useState('config');
 useEffect(()=>{
  const url=new URL(location.href);const view=url.searchParams.get('view');if(view&&workspaces.some(x=>x.id===view))setWorkspace(view);
  try{const saved=JSON.parse(sessionStorage.getItem('review-unsaved')||'{}');setDrafts(saved);}catch{}
  read('work').then(value=>{setTitle(value.project?.title||'故事审阅台');setSummary(value);setReady(true);}).catch(setError);
  const back=()=>{const u=new URL(location.href),w=u.searchParams.get('view')||'overview';setWorkspace(w);if(u.searchParams.get('id'))setViews(old=>({...old,[w]:{...(old[w]||fresh(w)),kind:u.searchParams.get('kind')||old[w]?.kind||fresh(w).kind,id:u.searchParams.get('id')||''}}));};back();window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);
 },[]);
 useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(Object.keys(drafts).length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[drafts]);
 function updateDraft(id:string,draft:Draft|null){setDrafts(old=>{const next={...old};if(draft)next[id]=draft;else delete next[id];try{sessionStorage.setItem('review-unsaved',JSON.stringify(next));}catch{setError(Error('浏览器草稿存储已满；当前草稿仍保留在页面，请先保存。'));}return next;});}
 function navigate(w:string){setWorkspace(w);const u=new URL(location.href);u.search='';if(w!=='overview')u.searchParams.set('view',w);history.pushState({},'',u);}
 function updateView(value:Partial<View>){setViews(old=>{const next={...(old[workspace]||fresh(workspace)),...value};const u=new URL(location.href);u.searchParams.set('view',workspace);u.searchParams.set('kind',next.kind);if(next.id)u.searchParams.set('id',next.id);else u.searchParams.delete('id');history.replaceState({},'',u);return {...old,[workspace]:next};});}
 async function open(id:string){try{const object:Detail=await read('objects/'+encodeURIComponent(id));const module=object.module==='collaboration'?'project':object.module;setViews(old=>({...old,[module]:{...(old[module]||fresh(module)),kind:object.kind,id,offset:0,historical:object.historical}}));setWorkspace(module);const u=new URL(location.href);u.search=new URLSearchParams({view:module,kind:object.kind,id}).toString();history.pushState({},'',u);}catch(e){setError(e);}}
 return <div className="desk"><aside className="sidebar"><a className="brand" href="/" onClick={e=>{e.preventDefault();navigate('overview');}}><span>阅</span><div><b>{title}</b><small>故事审阅台</small></div></a><nav className="workspace-nav" aria-label="工作区">{workspaces.map(w=><button key={w.id} aria-current={workspace===w.id?'page':undefined} onClick={()=>navigate(w.id)}><span>{w.mark}</span><div><strong>{w.label}</strong><small>{w.note}</small></div></button>)}</nav><div className="sidebar-foot"><span className="online-dot"/> 单故事工作空间{Object.keys(drafts).length>0&&<button onClick={()=>void open(Object.keys(drafts)[0])}>{Object.keys(drafts).length} 份未保存内容</button>}</div></aside>
 <main className="main"><header className="page-heading"><div><p>创作工作空间</p><h1>{workspaces.find(w=>w.id===workspace)?.label}</h1></div><span className="project-label">{title}</span></header><OperationError error={error}/>
 {!ready&&!error?<div className="loading" role="status">正在读取项目…</div>:workspace==='overview'?<Overview summary={summary} onOpen={open} onNavigate={navigate}/>:<>
 {workspace==='project'&&<div className="tabs">{[['config','系统与项目配置'],['records','项目指引与候选'],['runtime','数据与运行']].map(([id,label])=><button key={id} aria-pressed={systemTab===id} onClick={()=>setSystemTab(id)}>{label}</button>)}</div>}
 {workspace==='project'&&systemTab!=='records'?<SystemPanel tab={systemTab}/>:<Workbench module={workspace} value={views[workspace]||fresh(workspace)} onChange={updateView} onOpen={open} drafts={drafts} onDraft={updateDraft}/>}
 </>}
 </main></div>;
}
function Overview({summary,onOpen,onNavigate}:{summary:any;onOpen:(id:string)=>void;onNavigate:(module:string)=>void}){
 if(!summary)return null;
 return <section data-ready="overview" className="overview"><div className="intro"><p className="eyebrow">从当前版本继续</p><h2>故事、设定与制作，在这里衔接。</h2><p>保存草稿，交给审阅；确认采用时，系统同步更新相关对象。</p></div><div className="workspace-cards">{workspaces.slice(1,5).map(w=><button key={w.id} onClick={()=>onNavigate(w.id)}><small>{w.mark}</small><h3>{w.label}</h3><p>{w.note}</p><b>{summary.counts.filter((c:any)=>c.module===w.id).reduce((n:number,c:any)=>n+c.count,0)} <span>个对象</span></b></button>)}</div><section className="attention"><h2>等待判断</h2>{summary.attention.length?summary.attention.map((o:Summary)=><button key={o.id} onClick={()=>onOpen(o.id)}><span><small>{kindLabels[o.kind]}</small><b>{o.title}</b></span><span className={'pill state-'+o.state}>{stateLabels[o.state]}</span></button>):<p className="empty">当前没有待审或要求修改的对象。</p>}</section>{summary.operations.length>0&&<section><h2>后台操作</h2>{summary.operations.map((o:any)=><p key={o.id}>{o.kind} · {o.status} · {o.id}</p>)}</section>}</section>;
}
function Workbench({module,value,onChange,onOpen,drafts,onDraft}:{module:string;value:View;onChange:(value:Partial<View>)=>void;onOpen:(id:string)=>void;drafts:Record<string,Draft>;onDraft:(id:string,draft:Draft|null)=>void}){
 const [catalog,setCatalog]=useState<{items:Summary[];total:number;nextOffset:number|null}|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState<any>(null),[attempt,setAttempt]=useState(0),[creating,setCreating]=useState(false),[newTitle,setNewTitle]=useState(''),[busy,setBusy]=useState(false),[newLinks,setNewLinks]=useState<any[]>([]),[file,setFile]=useState<File|null>(null),[episodes,setEpisodes]=useState<Summary[]>([]);
 const listRef=useRef<HTMLDivElement>(null),detailRef=useRef<HTMLDivElement>(null);
 const catalogKey=new URLSearchParams({kind:value.kind,query:value.query,offset:String(value.offset),limit:'50',historical:String(value.historical),...(value.owner?{owner:value.owner}:{})}).toString();
 useEffect(()=>{let active=true;setCatalog(null);setError(null);read('objects?'+catalogKey).then(rows=>{if(active)setCatalog(rows);}).catch(e=>active&&setError(e));return()=>{active=false;};},[catalogKey,attempt]);
 useEffect(()=>{if(!catalog)return;if(!value.id&&catalog.items[0])onChange({id:catalog.items[0].id});},[catalog,value.id]);
 useEffect(()=>{let active=true;const id=value.id;setDetail(null);if(id)read<Detail>('objects/'+encodeURIComponent(id)).then(d=>{if(active){setDetail(d);requestAnimationFrame(()=>{if(detailRef.current)detailRef.current.scrollTop=readingPositions.get('detail:'+id)||0;});}}).catch(e=>active&&setError(e));return()=>{active=false;};},[value.id,attempt]);
 useEffect(()=>{if(['SCENE','PREPARATION','COVERAGE','SHOT_DESIGN','SHOT','INPUT_LOCK'].includes(value.kind))read('objects?kind=EPISODE&limit=200').then(r=>setEpisodes(r.items)).catch(()=>{});},[value.kind]);
 const refresh=()=>{cache.clear();setAttempt(x=>x+1);};
 async function create(){setBusy(true);try{const id=crypto.randomUUID();const media=value.kind==='ASSET'&&file?[await uploadMedia(file)]:[];if(value.kind==='ASSET'&&!media.length)throw Error('请先选择此素材版本的实际文件');await commands([{type:'save',id,kind:value.kind,title:newTitle,content:blankContent(value.kind),expectedVersion:0,links:newLinks,media}]);setNewLinks([]);setFile(null);setCreating(false);setNewTitle('');onChange({id,offset:0,query:''});refresh();}catch(e){setError(e);}finally{setBusy(false);}}
 return <section className="workbench" data-ready={catalog?'workspace':undefined}><div className="tabs" role="tablist" aria-label="内容分类">{(tabs[module]||[]).map(kind=><button role="tab" aria-selected={value.kind===kind} key={kind} onClick={()=>onChange({kind,id:'',offset:0,owner:''})}>{kindLabels[kind]}</button>)}</div>
 <div className="workspace-toolbar"><label className="search"><span>⌕</span><input aria-label="搜索对象" placeholder="搜索当前目录" value={value.query} onChange={e=>onChange({query:e.target.value,offset:0,id:''})}/></label>{episodes.length>0&&['SCENE','PREPARATION','COVERAGE','SHOT_DESIGN','SHOT','INPUT_LOCK'].includes(value.kind)&&<select aria-label="分集筛选" value={value.owner} onChange={e=>onChange({owner:e.target.value,id:'',offset:0})}><option value="">全部分集</option>{episodes.map(e=><option key={e.id} value={e.id}>{e.displayId} · {e.title}</option>)}</select>}<label className="check"><input type="checkbox" checked={value.historical} onChange={e=>onChange({historical:e.target.checked,offset:0,id:''})}/>包含历史依据</label><button onClick={()=>{setNewLinks([]);setFile(null);setCreating(true);}}>＋ 新建{kindLabels[value.kind]}</button></div>
 <OperationError error={error}/>{error&&<button onClick={refresh}>重新读取</button>}
 {creating&&<div className="new-form"><label>新建{kindLabels[value.kind]}<input aria-label="新对象标题" autoFocus value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label>{['ASSET','RELATION'].includes(value.kind)&&<><p>{newLinks.map(l=><span key={l.id}>{l.title} <button onClick={()=>setNewLinks(newLinks.filter(x=>x.id!==l.id))}>移除</button></span>)}</p><LinkPicker kind={value.kind==='ASSET'?'MATERIAL':'ENTITY'} label={value.kind==='ASSET'?'选择所属素材族':'选择关系端点（两个主体）'} onChoose={item=>{if(!newLinks.some(l=>l.id===item.id))setNewLinks(value.kind==='ASSET'?[{...item,role:'FAMILY'}]:[...newLinks.slice(-1),{...item,role:'ENTITY'}]);}}/></>}{value.kind==='ASSET'&&<label>实际媒体文件<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}<button disabled={busy||!newTitle.trim()} onClick={create}>创建草稿</button><button onClick={()=>setCreating(false)}>取消</button></div>}
 <div className="workspace-columns"><div className="catalog" ref={listRef}><div className="catalog-heading"><span>{kindLabels[value.kind]}</span><small>{catalog?.total??'…'} 个</small></div>{!catalog?<p className="loading" role="status">读取目录…</p>:catalog.items.length?catalog.items.map(o=><button key={o.id} className="catalog-row" aria-current={value.id===o.id?'location':undefined} onClick={()=>onChange({id:o.id})}><small>{o.displayId||kindLabels[o.kind]}{drafts[o.id]?' · 未保存':''}</small><b>{o.title}</b><span><i className={'state-dot state-'+o.state}/>{stateLabels[o.state]}{o.stale?' · 依据待核':''}</span></button>):<p className="empty">此目录还没有内容。</p>}<div className="pager"><button disabled={!value.offset} onClick={()=>onChange({offset:Math.max(0,value.offset-50)})}>上一页</button><button disabled={!catalog?.nextOffset} onClick={()=>onChange({offset:catalog!.nextOffset!})}>下一页</button></div></div>
 <div className="detail-scroll" ref={detailRef} onScroll={e=>{rememberPosition('detail:'+value.id,e.currentTarget.scrollTop);}}>{detail&&detail.id===value.id?<ObjectPanel key={detail.id} detail={detail} draft={drafts[detail.id]} onDraft={d=>onDraft(detail.id,d)} onRefresh={refresh} onOpen={onOpen}/>:<div className="empty">{value.id?'正在读取此版本…':'从左侧选择一个对象，或创建新草稿。'}</div>}</div></div></section>;
}
function ObjectPanel({detail,draft,onDraft,onRefresh,onOpen}:{detail:Detail;draft?:Draft;onDraft:(d:Draft|null)=>void;onRefresh:()=>void;onOpen:(id:string)=>void}){
 const [editing,setEditing]=useState(Boolean(draft)),[busy,setBusy]=useState(false),[error,setError]=useState<any>(null),[message,setMessage]=useState(''),[revision,setRevision]=useState(detail.revision.id),[historic,setHistoric]=useState<Detail|null>(null),[assistant,setAssistant]=useState(false),[prompt,setPrompt]=useState(''),[suggestion,setSuggestion]=useState<any>(null),[source,setSource]=useState<any>(null);
 useEffect(()=>{setRevision(detail.revision.id);setHistoric(null);},[detail.revision.id]);
 const shown=historic||detail;const currentDraft=draft||{title:detail.title,content:detail.revision.content,basedOnVersion:detail.version};
 async function perform(command:any){setBusy(true);setError(null);setMessage('');try{const receipt=await commands([command]);const saved=await read<Detail>('objects/'+encodeURIComponent(detail.id),{refresh:true});if(saved.version!==receipt.results[0].version)throw Error('保存后对象再次改变；请读取最新版本，原操作回执已保留');setMessage('已保存并核对回读');onDraft(null);setEditing(false);onRefresh();return receipt;}catch(e){setError(e);}finally{setBusy(false);}}
 async function chooseRevision(id:string){setRevision(id);if(id===detail.revision.id){setHistoric(null);return;}try{setHistoric(await read('objects/'+encodeURIComponent(detail.id)+'?revisionId='+encodeURIComponent(id)));}catch(e){setError(e);}}
 async function loadSource(offset=0){try{setSource(await read('source/'+encodeURIComponent(shown.revision.id)+'?offset='+offset));}catch(e){setError(e);}}

 return <article className="object-panel" data-ready="detail" data-object-id={shown.id} data-object-version={shown.version}><header className="object-heading"><div><p>{kindLabels[shown.kind]} {shown.displayId&&' / '+shown.displayId}</p><h2>{shown.title}</h2></div><span className={'pill state-'+shown.state}>{stateLabels[shown.state]}</span></header><div className="object-actions"><select aria-label="查看版本" value={revision} onChange={e=>void chooseRevision(e.target.value)}>{detail.versions.map(v=><option value={v.id} key={v.id}>修订 {v.number}{v.id===detail.adoptedRevisionId?' · 已采用':''}{v.id===detail.draftRevisionId?' · 当前稿':''}</option>)}</select>{!historic&&detail.kind!=='ASSET'&&<button onClick={()=>setEditing(!editing)} disabled={busy}>{editing?'返回阅读':'编辑内容'}</button>}<button onClick={()=>setAssistant(!assistant)} aria-pressed={assistant}>AI 辅助</button>{draft&&<span className="unsaved">有未保存修改</span>}</div>
 <OperationError error={error}/>{message&&<p role="status" className="success">{message}</p>}{shown.invalidations.length>0&&<p className="notice">本版本引用的依据已改变。请核对受影响内容后保存新修订。</p>}
 {editing&&!historic?<><Editor detail={detail} draft={currentDraft} onChange={onDraft}/><div className="save-bar"><button className="primary" disabled={busy||!draft} onClick={()=>perform({type:'save',id:detail.id,expectedVersion:currentDraft.basedOnVersion,title:currentDraft.title,content:currentDraft.content,...(currentDraft.links?{links:currentDraft.links}:{})})}>保存草稿</button><button disabled={busy} onClick={()=>{onDraft(null);setEditing(false);}}>放弃本次修改</button></div></>:<><Content detail={shown} onOpen={onOpen}/>{shown.kind==='SOURCE'&&shown.revision.content.originalRevisionId&&<section className="source-reader"><button onClick={()=>void loadSource()}>读取原始资料正文</button>{source&&<><pre>{source.text}</pre><div className="pager"><button disabled={!source.offset} onClick={()=>void loadSource(Math.max(0,source.offset-16000))}>上一段</button><span>{source.offset+1}–{source.offset+source.text.length} / {source.total}</span><button disabled={source.nextOffset===null} onClick={()=>void loadSource(source.nextOffset)}>下一段</button></div></>}</section>}</>}
 {!historic&&!editing&&<><div className="submit-bar">{['DRAFT','CHANGES_REQUESTED'].includes(detail.state)&&<button className="primary" disabled={busy||Boolean(draft)} onClick={()=>perform({type:'submit',id:detail.id,expectedVersion:detail.version,revisionId:detail.revision.id})}>提交审阅</button>}<span>{detail.adoptedRevisionId&&detail.adoptedRevisionId!==detail.revision.id?'已采用版本继续保留，当前稿尚未采用。':detail.state==='ADOPTED'?'此修订已采用。':'保存和提交均不会自动采用。'}</span></div><ReviewPanel detail={detail} busy={busy} onReview={command=>perform(command)}/></>}
 {assistant&&<Assistant detail={detail} onApplied={onRefresh} onOpen={onOpen}/>}
 {shown.reviews.length>0&&<details className="review-history"><summary>已有判断 · {shown.reviews.length}</summary>{shown.reviews.map(r=><section key={r.id}><b>{{ADOPT:'采用',REQUEST_CHANGES:'要求修改',DISABLE:'禁止使用'}[r.decision]||r.decision}</b><p>{r.note}</p>{r.findings?.map((f:any,i:number)=><p key={i}>{f.verdict} · {f.note}</p>)}<small>{r.author} · {new Date(r.created_at).toLocaleDateString('zh-CN')}</small></section>)}</details>}
 </article>;
}
function ReviewPanel({detail,busy,onReview}:{detail:Detail;busy:boolean;onReview:(command:any)=>void}){
 const [decision,setDecision]=useSession('decision:'+detail.revision.id,''),[note,setNote]=useSession('judgment-note:'+detail.revision.id,''),[findings,setFindings]=useSession<Record<string,{verdict:string;note:string}>>('findings:'+detail.revision.id,{}),[attestation,setAttestation]=useSession('attestation:'+detail.revision.id,false);
 const criteria=detail.revision.content.reviewSpec?.criteria||detail.revision.content.configurationBinding?.reviewSpec?.criteria||[];
 if(!['SUBMITTED','ADOPTED'].includes(detail.state))return null;
 return <section className="review-panel"><h3>审阅当前修订</h3><p>判断与采用在一次提交中完成，保留所审版本和依据。</p>{criteria.map((c:any)=><fieldset key={c.id}><legend>{c.label||c.id}</legend><p>{c.question}</p><div className="choices">{[['PASS','通过'],['FAIL','需修改'],...(c.allowNA?[['NA','不适用']]:[])].map(([v,label])=><button key={v} aria-pressed={findings[c.id]?.verdict===v} onClick={()=>setFindings(old=>({...old,[c.id]:{verdict:old[c.id]?.verdict===v?'':v,note:old[c.id]?.note||''}}))}>{label}</button>)}</div><input aria-label={(c.label||c.id)+'说明'} placeholder="判断依据或修改建议" value={findings[c.id]?.note||''} onChange={e=>setFindings(old=>({...old,[c.id]:{verdict:old[c.id]?.verdict||'',note:e.target.value}}))}/></fieldset>)}<div className="choices decision">{(detail.state==='ADOPTED'?[['DISABLE','禁止使用']]:[['ADOPT','采用此修订'],['REQUEST_CHANGES','要求修改'],['DISABLE','禁止使用']]).map(([v,label])=><button key={v} aria-pressed={decision===v} onClick={()=>setDecision(decision===v?'':v)}>{label}</button>)}</div><textarea aria-label="审阅说明" placeholder="记录判断依据与必要修改" rows={3} value={note} onChange={e=>setNote(e.target.value)}/>{detail.kind==='ASSET'&&<label className="check"><input type="checkbox" checked={attestation} onChange={e=>setAttestation(e.target.checked)}/>确认本版本可用于项目内部制作（保留原始权利事实）</label>}<button className="primary" disabled={busy||!decision} onClick={()=>onReview({type:'review',id:detail.id,expectedVersion:detail.version,revisionId:detail.revision.id,decision,explicit:true,note,findings:Object.entries(findings).map(([criterionId,f])=>({criterionId,...f})),internalAttestation:attestation})}>提交判断</button></section>;
}
function SystemPanel({tab}:{tab:string}){
 const [configuration,setConfiguration]=useState<any>(null),[health,setHealth]=useState<any>(null),[error,setError]=useState<any>(null),[title,setTitle]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{read('configurations').then(v=>{setConfiguration(v);setTitle(v.items.find((x:any)=>x.scope==='project')?.content.title||'');}).catch(setError);read('health',{refresh:true}).then(setHealth).catch(setError);},[]);
 async function save(){try{const c=configuration.items.find((x:any)=>x.scope==='project');await commands([{type:'configuration.save',scope:'project',expectedVersion:c.version,content:{...c.content,title}}]);setConfiguration(await read('configurations',{refresh:true}));setMessage('配置已保存');}catch(e){setError(e);}}
 return <section className="system-panel" data-ready={configuration?'workspace':undefined}><OperationError error={error}/>{message&&<p role="status">{message}</p>}{tab==='config'?<><h2>项目配置</h2><label>故事名称<input value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="primary" onClick={save} disabled={!configuration}>保存项目配置</button><h2>系统配置</h2><p>审阅标准、实体类型、制作阶段与技术标准随项目独立导入导出。</p>{configuration?.items.find((x:any)=>x.scope==='system')?.content.reviewStandards?.map((s:any)=><details key={s.id}><summary>{s.label||s.title||s.id}</summary>{s.criteria?.map((c:any)=><p key={c.id}><b>{c.label}</b> · {c.question}</p>)}</details>)}</>:<><h2>数据与运行</h2><dl><dt>软件版本</dt><dd className="mono">{health?.softwareCommit||'读取中'}</dd><dt>数据库版本</dt><dd>{health?.schemaVersion||'读取中'}</dd><dt>后台工作器</dt><dd>{health?.worker?new Date(health.worker.updatedAt).toLocaleString():'尚未连接'}</dd></dl><a className="button" href="/api/v1/export">导出业务数据</a><p>完整项目包还包含登记媒体。使用项目命令可导出、核验和导入到独立空白审阅台。</p><pre>npm run review -- export --output 项目包目录</pre></>}</section>;
}
