export const productionFieldLabels: Record<string, string> = {
  sceneRole: "本场作用",
  candidatePurpose: "候选本场任务",
  informationBoundary: "信息与视点边界",
  viewpoint: "观察视点",
  retainUntilLater: "暂不揭晓",
  order: "顺序",
  soundAndDialogueIntent: "声音与对白意图",
  sourceDialogue: "本场对白依据",
  scriptBlockId: "正文块",
  speaker: "说话人",
  performanceNote: "表演提示",
  entityStateRequirements: "实体状态与素材需要",
  description: "具体要求",
  canonicalEntityId: "实体绑定",
  bindingStatus: "绑定情况",
  stateId: "状态绑定",
  timeAndSpace: "时间与空间",
  transition: "场间转换",
  locationBinding: "地点绑定",
  stateBinding: "状态绑定",
  zoneBinding: "区域绑定",
  cameraBinding: "机位绑定",
  freezeBinding: "冻结点绑定",
  beats: "叙事与动作节拍",
  visualIntent: "画面意图",
  actionIntent: "动作意图",
  soundIntent: "声音意图",
  dialogueContext: "对白与表演",
  entityStateNeeds: "实体、状态与空间条件",
  materialGaps: "素材缺项",
  nextPreparationAction: "下一步准备",
  reviewFocus: "审阅重点",
  narrativeBeat: "叙事节拍",
  audienceTakeaway: "观众所得",
  purpose: "本场作用",
  audienceKnown: "观众已知",
  audienceWithheld: "暂不揭晓",
  slugline: "场景",
  storyTime: "故事时间",
  title: "场名",
  text: "内容",
  entityName: "主体",
  state: "状态",
  reason: "依据",
  name: "名称",
  requirement: "要求",
  note: "说明",
  material: "素材",
  type: "类型",
};
Object.assign(productionFieldLabels, {
  authoringCuts: "作者镜头准备",
  proposedShotId: "拟定镜头编号",
  derivedFromAuthoringCutId: "拆分来源镜头",
  actualInputBindings: "实际输入绑定",
  canGenerate: "是否可生成",
  dialogueSpeakers: "对白角色",
  materialRequirementRefs: "素材需求引用",
  requirementDefinitions: "需求定义依据",
  requirementDefinitionStatus: "需求依据状态",
  requirementHash: "需求哈希",
  requirementId: "需求身份",
  pendingDefinitionIds: "待补定义",
  requirementsNotice: "需求核对说明",
  scope: "适用范围",
  sourceScriptBlockIds: "正文依据块",
  sourcePartUse: "正文分段用途",
  coverageBeatRef: "场级节拍引用",
  cameraIntent: "机位意图",
  design: "镜头设计",
  shotSize: "景别",
  cameraAngle: "机位角度",
  cameraMovement: "摄影机运动",
  composition: "构图",
  performance: "表演",
  lighting: "光线",
  estimatedDurationSeconds: "预计时长（秒）",
  subjectIds: "主体身份",
  continuity: "前后连续性",
  startState: "起始状态",
  endState: "结束状态",
  previousShotId: "前一镜头",
  nextShotId: "后一镜头",
  transitionIn: "入镜衔接",
  transitionOut: "出镜衔接",
  keyframeStrategy: "关键帧策略",
  mode: "方式",
  intermediateFrameCount: "中间关键帧数量",
  keyframePlan: "关键帧准备",
  classification: "依据性质",
  start: "开始",
  end: "结束",
  frame: "画面",
  intermediates: "中间关键帧",
  slot: "帧位置",
  actualVersionId: "实际素材版本",
  timingStatus: "时长确认状态",
  localViewAuthorReferences: "局部视图作者依据",
  definitionStatus: "定义状态",
  proposedRequirementId: "拟定需求身份",
  definitionResolutionNotice: "定义衔接说明",
  originalUnboundDefinitionEvidence: "原未绑定定义依据",
  originalUnboundNeed: "原未绑定需求",
  authoringUses: "作者用途",
  confirmationNeeded: "待确认事项",
  entityId: "实体身份",
  proposalKind: "提案类别",
  resolvedDefinitionBindings: "已定位定义",
});
export const productionValueLabels: Record<string, string> = {
  UNKNOWN: "待核",
  UNBOUND_PROPOSAL: "尚未绑定的准备提案",
  A: "改编与制作提案",
  AUTHORING_DRAFT: "准备草稿",
  EXTREME_WIDE: "大远景",
  WIDE: "远景",
  FULL: "全景",
  MEDIUM: "中景",
  CLOSE_UP: "近景",
  EXTREME_CLOSE_UP: "特写",
  EYE_LEVEL: "平视",
  HIGH: "俯拍",
  LOW: "仰拍",
  OVER_SHOULDER: "过肩",
  POV: "主观视角",
  TOP_DOWN: "垂直俯拍",
  DUTCH: "倾斜机位",
  OTHER: "其他",
  STATIC: "固定",
  PUSH: "推",
  PULL: "拉",
  PAN: "水平摇镜",
  TILT: "垂直摇镜",
  TRACK: "移",
  FOLLOW: "跟拍",
  HANDHELD: "手持",
  CRANE: "升降",
  ORBIT: "环绕",
  MULTI_KEYFRAME: "首尾及中间关键帧",
  START_END: "首尾帧",
  START_ONLY: "首帧",
  UNDECIDED: "尚未确定",
  ESTIMATE_ONLY_NOT_ANIMATIC_LOCKED: "仅估时，尚未完成 Animatic 锁时",
  AUTHORING_DESIGN_ONLY_REQUIREMENT_REVALIDATION_PENDING:
    "作者设计，素材用途待重新核对",
  HISTORICAL_AUTHORING_EVIDENCE_NOT_NEW_INPUT_BINDING:
    "历史作者依据，尚未建立新输入绑定",
  PUBLISHED_DEFINITION_ONLY_ACTUAL_INPUT_UNBOUND:
    "已有发布定义，实际输入尚未绑定",
  DEFINITION_OR_CURRENT_INPUT_GAPS_NOT_CLAIM_OF_NO_FILES:
    "定义或当前输入仍有缺项，实际文件需另行核对",
  AUTHORING_CUT_DEFINITION_USE_ONLY_NOT_FORMAL_SHOT_OR_ACTUAL_MEDIA:
    "作者准备镜头的定义用途，尚未建立正式镜头及实际素材绑定",
  UNPUBLISHED_REQUIREMENT_DEFINITION: "需求定义尚未发布",
};
