'use client';
import {readWorkspaceDraft,useWorkspaceDraftRetention} from './draft-retention';
import {useEffect,useState} from 'react';
import {useRuntimeMode} from './runtime-mode';
import {useManagementDraftGuard} from './management-draft-guard';
import type {SpatialShotViewAuthorContent as AuthorContent} from '../presentation/spatial-production.mjs';
import './shot-production-recipe-editor.css';
type Content=Omit<AuthorContent,'camera'>&{camera:Omit<AuthorContent['camera'],'origin'|'looks'>&{origin:AuthorContent['camera']['origin']|'';looks:AuthorContent['camera']['looks']|''}};
type Location={id:string;name:string;zones:Array<{id:string;name:string}>;cameras:Array<{id:string;zoneId?:string;zoneIds?:string[]}>};
type Options={cameraOrigins:AuthorContent['camera']['origin'][];cameraDirections:AuthorContent['camera']['looks'][];cameraHeights:AuthorContent['camera']['height'][];dressingKinds:Content['dressing'][number]['kind'][];relations:Content['dressing'][number]['relation'][];orientations:Content['dressing'][number]['orientation'][]};
type View={id:string;viewId:string;sceneBinding:{sceneId:string};base:{locationId:string;zoneId:string};camera:Content['camera']&{id:string};dressing:Content['dressing'];note:string};
type Workspace={sceneId:string;viewId:string;releaseId:string;basisHash:string;draftHeadRevisionId:string|null;draft:{revisionId:string;content:Content}|null;staleDraft?:{revisionId:string;content:Content;reason:string}|null;defaults:Content|null;currentView:unknown;availableLocations:Location[];options:Options;blockers:string[];jobs:Array<{jobId:string;status:string;error?:string}>;readOnly:boolean};
type Preview={view:View;previewHash:string;modelCalls:0;formalAdoptionPerformed:false};
const labels:Record<string,string>={NORTH_INTERIOR:'室内北侧',NORTHEAST_INTERIOR:'室内东北角',EAST_INTERIOR:'室内东侧',SOUTHEAST_INTERIOR:'室内东南角',SOUTH_INTERIOR:'室内南侧',SOUTHWEST_INTERIOR:'室内西南角',WEST_INTERIOR:'室内西侧',NORTHWEST_INTERIOR:'室内西北角',CENTER_INTERIOR:'室内中央',NORTH:'朝北',NORTHEAST:'朝东北',EAST:'朝东',SOUTHEAST:'朝东南',SOUTH:'朝南',SOUTHWEST:'朝西南',WEST:'朝西',NORTHWEST:'朝西北',EYE_LEVEL:'平视',LOW:'低机位',HIGH:'高机位',BED:'床',BOWL_RACK:'碗架',TABLE:'桌',CHAIR:'椅',SHELF:'架子',BENCH:'长凳',CONTAINER:'容器',NORTH_OF:'锚点北侧',SOUTH_OF:'锚点南侧',EAST_OF:'锚点东侧',WEST_OF:'锚点西侧',AT:'锚点处',EAST_WEST:'东西向',NORTH_SOUTH:'南北向',NONE:'不限定朝向'};
const endpoint='/api/v1/workspaces/spatial-shot-view';
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const nonempty=(v:unknown):v is string=>typeof v==='string'&&Boolean(v.trim());
async function read<T>(r:Response):Promise<T>{const v=await r.json() as {error?:string|{message?:string};message?:string};if(!r.ok)throw Error(typeof v?.error==='string'?v.error:v?.error?.message||v?.message||'空间资料读取失败');return v as T;}
function validContent(v:Content,sceneId:string,viewId:string){return v&&v.sceneId===sceneId&&v.viewId===viewId&&typeof v.locationId==='string'&&typeof v.zoneId==='string'&&v.camera&&['origin','looks','height','purpose'].every(k=>typeof (v.camera as unknown as Record<string,unknown>)[k]==='string')&&Array.isArray(v.dressing)&&v.dressing.every(d=>d&&nonempty(d.id)&&typeof d.kind==='string'&&d.anchor&&['CAMERA','ZONE'].includes(d.anchor.kind)&&typeof d.anchor.id==='string'&&typeof d.relation==='string'&&typeof d.orientation==='string'&&typeof d.appearance==='string')&&typeof v.note==='string';}
function valid(v:Workspace,sceneId:string){
 if(!v||v.sceneId!==sceneId||!nonempty(v.viewId)||!nonempty(v.releaseId)||!hash(v.basisHash)||typeof v.readOnly!=='boolean'||!(v.draftHeadRevisionId===null||nonempty(v.draftHeadRevisionId))||!('draft'in v)||!('defaults'in v)||!('currentView'in v)||!Array.isArray(v.availableLocations)||!v.availableLocations.every(l=>nonempty(l.id)&&typeof l.name==='string'&&Array.isArray(l.zones)&&l.zones.every(z=>nonempty(z.id)&&typeof z.name==='string')&&Array.isArray(l.cameras)&&l.cameras.every(c=>nonempty(c.id)))||!v.options||!['cameraOrigins','cameraDirections','cameraHeights','dressingKinds','relations','orientations'].every(k=>Array.isArray(v.options[k as keyof Options])&&v.options[k as keyof Options].every(nonempty))||!Array.isArray(v.blockers)||!v.blockers.every(b=>typeof b==='string')||!Array.isArray(v.jobs)||!v.jobs.every(j=>nonempty(j.jobId)&&nonempty(j.status)))throw Error('空间资料回执不完整');
 if(!(v.defaults===null||validContent(v.defaults,sceneId,v.viewId))||!(v.draft===null||v.draft&&nonempty(v.draft.revisionId)&&v.draft.revisionId===v.draftHeadRevisionId&&validContent(v.draft.content,sceneId,v.viewId))||!(v.staleDraft===undefined||v.staleDraft===null||v.staleDraft&&v.draft===null&&v.staleDraft.revisionId===v.draftHeadRevisionId&&typeof v.staleDraft.reason==='string'&&validContent(v.staleDraft.content,sceneId,v.viewId))||v.draftHeadRevisionId!==null&&v.draft===null&&!v.staleDraft)throw Error('空间草稿版本依据不完整');return v;
}
export function SpatialShotViewEditor({sceneId,onDirtyChange}:{sceneId:string;onDirtyChange?:(dirty:boolean)=>void}){const {hostedReadOnly}=useRuntimeMode();return hostedReadOnly?null:<Editor key={sceneId} sceneId={sceneId} onDirtyChange={onDirtyChange}/>;}
function Editor({sceneId,onDirtyChange}:{sceneId:string;onDirtyChange?:(dirty:boolean)=>void}){
 const [open,setOpen]=useState(false),[state,setState]=useState<Workspace|null>(null),[draft,setDraft]=useState<Content|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState(''),[preview,setPreview]=useState<Preview|null>(null);
 const draftKey='spatial-view:'+sceneId,draftRetained=useWorkspaceDraftRetention(draftKey,Boolean(state),dirty,{state,draft});
 useManagementDraftGuard((dirty&&!draftRetained)||uncertain,'局部机位与摆位');
 useEffect(()=>{onDirtyChange?.(dirty||uncertain);return()=>onDirtyChange?.(false);},[dirty,uncertain,onDirtyChange]);
 useEffect(()=>{if(!open)return;const c=new AbortController();void fetch(endpoint+'?sceneId='+encodeURIComponent(sceneId),{cache:'no-store',signal:c.signal}).then(read<Workspace>).then(v=>valid(v,sceneId)).then(v=>{if(c.signal.aborted)return;const local=readWorkspaceDraft<{state:Workspace;draft:Content}>(draftKey);setState(local?.state||v);setDraft(local?.draft||v.draft?.content||v.staleDraft?.content||v.defaults);setDirty(Boolean(local)||Boolean(v.staleDraft));setMessage(v.staleDraft?'已恢复之前的完整草稿，请核对当前空间依据后重新保存。':'');}).catch(e=>{if(!c.signal.aborted)setMessage(e.message);});return()=>c.abort();},[open,sceneId]);
 function edit(patch:Partial<Content>){if(!draft||busy||uncertain||state?.readOnly)return;setDraft({...draft,...patch});setDirty(true);setPreview(null);}
 async function inspect(){if(busy)return;setBusy(true);try{const v=valid(await read<Workspace>(await fetch(endpoint+'?sceneId='+encodeURIComponent(sceneId)+(state?'&viewId='+encodeURIComponent(state.viewId):''),{cache:'no-store'})),sceneId);if(state&&v.viewId!==state.viewId)throw Error('局部视图身份发生变化');const restored=draft===null?(v.draft?.content||v.staleDraft?.content||v.defaults):draft;setState(v);setDraft(restored);setUncertain(false);setPreview(null);setDirty(Boolean(v.staleDraft)||JSON.stringify(restored)!==JSON.stringify(v.draft?.content||v.defaults));setMessage('已重读当前空间资料及任务，本次编辑仍保留。请核对已登记结果。');}catch(e){setMessage(e instanceof Error?e.message:'尚无法核查结果');}finally{setBusy(false);}}
 async function act(action:'save'|'preview'|'publish'){
  if(!state||!draft||state.readOnly||busy||uncertain)return;setBusy(true);setMessage('');let submitted=false;
  try{
   const body=action==='save'?{action,sceneId,viewId:state.viewId,expectedReleaseId:state.releaseId,expectedBasisHash:state.basisHash,expectedDraftRevisionId:state.draftHeadRevisionId,content:draft}:{action,sceneId,viewId:state.viewId,draftRevisionId:state.draft?.revisionId,...(action==='publish'?{previewHash:preview?.previewHash}:{})};
   submitted=true;const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'spatial-shot-view:'+crypto.randomUUID()},body:JSON.stringify(body)});if(!response.ok&&response.status<500)submitted=false;const value=await read<Record<string,unknown>>(response),view=value?.view as View|undefined;
   if(!value||(action==='save'?!nonempty(value.revisionId):action==='preview'?!hash(value.previewHash)||value.modelCalls!==0||value.formalAdoptionPerformed!==false||!view||!nonempty(view.id)||view.viewId!==state.viewId||view.sceneBinding?.sceneId!==sceneId||view.base?.locationId!==draft.locationId||view.base?.zoneId!==draft.zoneId:!nonempty(value.revisionId)||value.status!=='SUCCEEDED'))throw Error('空间操作回执缺少精确版本或任务依据');submitted=false;
   if(action==='save'){setState({...state,staleDraft:null,draftHeadRevisionId:String(value.revisionId),draft:{revisionId:String(value.revisionId),content:draft}});setDirty(false);setPreview(null);setMessage('空间草稿已保存，请预览机位与摆位。');}
   else if(action==='preview'){setPreview(value as Preview);setMessage('请核对本场机位与摆位，确认后发布可供镜头引用的空间版本。');}
   else{setPreview(null);const next=valid(await read<Workspace>(await fetch(endpoint+'?sceneId='+encodeURIComponent(sceneId)+'&viewId='+encodeURIComponent(state.viewId),{cache:'no-store'})),sceneId);setState(next);setDraft(next.defaults);setDirty(false);setMessage('局部空间版本已登记，可在本场镜头中引用。');window.dispatchEvent(new Event('review:operations-updated'));}
  }catch(e){if(submitted)setUncertain(true);setMessage((e instanceof Error?e.message:'操作失败')+(submitted?'；提交结果尚未确认，请重读空间资料与任务后再操作。':''));}finally{setBusy(false);}
 }
 const location=state?.availableLocations.find(l=>l.id===draft?.locationId),anchors=location&&draft?[...location.zones.filter(z=>z.id===draft.zoneId).map(z=>({kind:'ZONE' as const,id:z.id,label:'区域 · '+z.name})),...location.cameras.filter(c=>c.zoneId?c.zoneId===draft.zoneId:!c.zoneIds||c.zoneIds.includes(draft.zoneId)).map(c=>({kind:'CAMERA' as const,id:c.id,label:'机位 · '+c.id}))]:[];
 const selectOptions=(items:string[])=>items.map(v=><option key={v} value={v}>{labels[v]||v}</option>);
 const changeDressing=(id:string,patch:Partial<Content['dressing'][number]>)=>draft&&edit({dressing:draft.dressing.map(d=>d.id===id?{...d,...patch}:d)});
 return <section className="shot-production-recipe-editor" aria-label="局部机位与摆位">
  {!open?<button type="button" onClick={()=>setOpen(true)}>设计本场局部机位与摆位</button>:<><header><h4>本场局部机位与摆位</h4><button type="button" disabled={busy} onClick={()=>void inspect()}>重读空间资料与任务</button></header><p>在已发布的地点与区域内设计本场机位，按需要增加家具摆位。空间版本发布后，可在本场镜头的空间条件中引用。</p>
   {state?.blockers.map(b=><p key={b}>{b}</p>)}{state?.staleDraft&&<p>之前的草稿依据已变化：{state.staleDraft.reason}</p>}
   {state&&draft&&<><fieldset disabled={state.readOnly||busy||uncertain}>
    <label>空间地点<select disabled={Boolean(state.currentView)} value={draft.locationId} onChange={e=>edit({locationId:e.target.value,zoneId:state.availableLocations.find(l=>l.id===e.target.value)?.zones[0]?.id||'',dressing:[]})}><option value="">选择地点</option>{state.availableLocations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>
    <label>空间区域<select disabled={Boolean(state.currentView)} value={draft.zoneId} onChange={e=>edit({zoneId:e.target.value,dressing:[]})}><option value="">选择区域</option>{location?.zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label>
    <label>摄影机位置<select value={draft.camera.origin} onChange={e=>edit({camera:{...draft.camera,origin:e.target.value as Content['camera']['origin']}})}><option value="">选择位置</option>{selectOptions(state.options.cameraOrigins)}</select></label>
    <label>摄影机朝向<select value={draft.camera.looks} onChange={e=>edit({camera:{...draft.camera,looks:e.target.value as Content['camera']['looks']}})}><option value="">选择朝向</option>{selectOptions(state.options.cameraDirections)}</select></label>
    <label>摄影机高度<select value={draft.camera.height} onChange={e=>edit({camera:{...draft.camera,height:e.target.value as Content['camera']['height']}})}>{selectOptions(state.options.cameraHeights)}</select></label>
    <label>机位用途<textarea value={draft.camera.purpose} maxLength={2000} onChange={e=>edit({camera:{...draft.camera,purpose:e.target.value}})}/></label>
    <fieldset><legend>家具摆位</legend>{draft.dressing.map((d,i)=><fieldset key={d.id}><legend>摆位 {i+1}</legend>
     <label>家具类型<select value={d.kind} onChange={e=>changeDressing(d.id,{kind:e.target.value as Content['dressing'][number]['kind']})}>{selectOptions(state.options.dressingKinds)}</select></label>
     <label>摆位锚点<select value={d.anchor.kind+':'+d.anchor.id} onChange={e=>{const anchor=anchors.find(a=>a.kind+':'+a.id===e.target.value);if(anchor)changeDressing(d.id,{anchor:{kind:anchor.kind,id:anchor.id}});}}>{!anchors.some(a=>a.kind===d.anchor.kind&&a.id===d.anchor.id)&&<option value={d.anchor.kind+':'+d.anchor.id}>原锚点已不可用：{d.anchor.id}</option>}{anchors.map(a=><option key={a.kind+':'+a.id} value={a.kind+':'+a.id}>{a.label}</option>)}</select></label>
     <label>相对位置<select value={d.relation} onChange={e=>changeDressing(d.id,{relation:e.target.value as Content['dressing'][number]['relation']})}>{selectOptions(state.options.relations)}</select></label><label>家具朝向<select value={d.orientation} onChange={e=>changeDressing(d.id,{orientation:e.target.value as Content['dressing'][number]['orientation']})}>{selectOptions(state.options.orientations)}</select></label><label>家具外观<textarea value={d.appearance} maxLength={2000} onChange={e=>changeDressing(d.id,{appearance:e.target.value})}/></label><button type="button" onClick={()=>edit({dressing:draft.dressing.filter(item=>item.id!==d.id)})}>移除此摆位</button>
    </fieldset>)}<button type="button" disabled={!anchors.length||draft.dressing.length>=20} onClick={()=>edit({dressing:[...draft.dressing,{id:'DRESSING-'+crypto.randomUUID(),kind:state.options.dressingKinds[0],anchor:{kind:anchors[0].kind,id:anchors[0].id},relation:state.options.relations[0],orientation:state.options.orientations[0],appearance:''}]})}>添加家具摆位</button></fieldset>
    <label>空间设计依据<textarea value={draft.note} maxLength={2000} onChange={e=>edit({note:e.target.value})}/></label>
   </fieldset><footer><button type="button" disabled={state.readOnly||busy||uncertain||!dirty} onClick={()=>void act('save')}>保存空间草稿</button><button type="button" disabled={state.readOnly||busy||uncertain||dirty||!state.draft||state.blockers.length>0} onClick={()=>void act('preview')}>预览机位与摆位</button></footer>
   {preview&&<section aria-label="局部空间预览"><h4>待发布的局部空间</h4><p>{location?.name} · {location?.zones.find(z=>z.id===draft.zoneId)?.name} · {labels[draft.camera.origin]} · {labels[draft.camera.looks]} · {labels[draft.camera.height]}</p><p>{draft.camera.purpose}</p>{draft.dressing.map(d=><p key={d.id}>{labels[d.kind]} · {d.anchor.id} · {labels[d.relation]} · {labels[d.orientation]} · {d.appearance}</p>)}<p>{draft.note}</p><details><summary>查看精确空间版本依据</summary><pre>{JSON.stringify(preview.view,null,2)}</pre></details><button type="button" disabled={state.readOnly||busy||uncertain||dirty} onClick={()=>void act('publish')}>确认发布局部空间版本</button></section>}
   {state.jobs.map(j=><p key={j.jobId}>空间任务 {j.jobId} · {j.status}{j.error?' · '+j.error:''}</p>)}
   </>}
  </>}{message&&<p role="status">{message}</p>}
 </section>;
}
