import type {InstanceReadUnit,InstanceUnit} from './index.mjs';
import type {DomainGraph,DomainConfiguration,InitializationContent,SourceBinding} from './domain-model.mjs';
export type RelationsState={configuration:DomainConfiguration;releaseId:string;revisionId:string|null;graph:DomainGraph;projection:DomainGraph;draft:{revisionId:string;content:DomainGraph;baseReleaseId:string}|null;defaults:DomainConfiguration;readOnly:boolean};
export type InitializationTask={revisionId:string;taskId:string;state:'REQUESTED'|'RUNNING'|'COMPLETED'|'FAILED';baseReleaseId:string;draftRevisionId:string;contentHash:string;sourceBindings:SourceBinding[];capability:'DRAFT_INITIALIZATION_ONLY';observedMedia:unknown[];error?:string;resultDraftRevisionId?:string};
export type InitializationState={releaseId:string;state:'NOT_STARTED'|'DRAFT'|'READY';sourceCount:number;draft:{revisionId:string;content:InitializationContent;baseReleaseId:string}|null;published:{revisionId:string;content:Record<string,unknown>}|null;aiTask:InitializationTask|null;defaults:DomainConfiguration;readOnly:boolean};
export type DomainPreview={previewHash:string;draftRevisionId:string;baseReleaseId:string;impact:ReturnType<typeof import('./domain-model.mjs').graphImpact>;checks:string[];formalAdoptionPerformed:false;changedGroups?:string[];uncertainties?:string[];sourceCount?:number};
export type PublishInput={draftRevisionId:string;previewHash:string;requestId:string};
export function getRelations(tx:InstanceReadUnit,filters?:{requirementId?:string;familyId?:string;entityId?:string}):Promise<RelationsState>;
export function saveRelationsDraft(tx:InstanceUnit,input:{expectedReleaseId:string;expectedDraftRevisionId:string|null;graph:DomainGraph}):Promise<{revisionId:string;releaseId:string;content:DomainGraph}>;
export function previewRelations(tx:InstanceReadUnit,draftRevisionId:string):Promise<DomainPreview>;
export function publishRelations(tx:InstanceUnit,input:PublishInput):Promise<Record<string,unknown>>;
export function getInitialization(tx:InstanceReadUnit):Promise<InitializationState>;
export function prepareInitialization(tx:InstanceUnit,input:{expectedReleaseId:string}):Promise<{revisionId:string;content:InitializationContent;releaseId?:string;existing?:boolean;aiAnalysisPerformed?:false}>;
export function saveInitializationDraft(tx:InstanceUnit,input:{expectedReleaseId:string;expectedDraftRevisionId:string|null;content:InitializationContent;origin?:string}):Promise<{revisionId:string;releaseId:string;content:InitializationContent}>;
export function previewInitialization(tx:InstanceReadUnit,draftRevisionId:string):Promise<DomainPreview>;
export function publishInitialization(tx:InstanceUnit,input:PublishInput):Promise<Record<string,unknown>>;
export function requestInitializationTask(tx:InstanceUnit,input:{expectedReleaseId:string;draftRevisionId:string}):Promise<InitializationTask>;
export function claimInitializationTask(tx:InstanceUnit,input:{expectedTaskRevisionId:string;workerId:string}):Promise<{task:InitializationTask&{claimToken:string};content:InitializationContent;sources:import('./domain-sources.mjs').SourceSummary[]}|null>;
export function submitInitializationTask(tx:InstanceUnit,input:{taskId:string;claimToken:string;content?:InitializationContent;error?:string;providerEvidence?:Record<string,unknown>}):Promise<Record<string,unknown>>;

export function failInterruptedInitializationTask(tx:InstanceUnit,input?:{workerId?:string;reason?:string}):Promise<{changed:boolean;taskId?:string;state?:'FAILED'}>;
