export type DomainProductionSlice = {
  entities: Array<Record<string, unknown>>;
  states: Array<Record<string, unknown>>;
  representations: Array<Record<string, unknown>>;
  requirements: Array<Record<string, unknown>>;
  relations: Array<Record<string, unknown>>;
  referencePolicies: Array<{relationId: string; policy: unknown}>;
  representationPolicies: Array<{representationId: string; policy: unknown}>;
};
export type DomainMetadataApproval = {entityId:string; beforeRecordHash:string; afterRecordHash:string; confirmed:true; reason:string; authorizationRef:string; scope:'NARRATIVE_DESCRIPTION_ONLY'};
export type DomainCompatibilityClassification = {compatible:boolean; kind:string; beforeSliceHash?:string; afterSliceHash?:string; changes:Array<{collection:string; id:string; kind:string; beforeHash:string; afterHash:string}>; reasons:string[]};
export type DomainCompatibilityOccurrence = {index:number; hash:string; familyId:string; previousHash:string; currentHash:string};
export type DomainCompatibilityInput = {familyId:string; versionId:string; sha256:string};
export type DomainRequirementCompatibilityBinding = {requirementId:string; beforeHash:string; afterHash:string; representationId:string; representationHash:string; beforeDemand:Record<string,unknown>; afterDemand:Record<string,unknown>};
export type DomainVersionCompatibilityBinding = {familyId:string; versionId:string; sha256:string; domainContextHash:string; occurrenceIndexes:number[]; inputBindings:DomainCompatibilityInput[]; executionDefinitionId?:string; executionDefinitionHash?:string; reviewEventId?:string; reviewContextHash?:string; reviewEventHash?:string};
export type DomainProductionCompatibilityRecord = {schemaVersion:'DOMAIN_PRODUCTION_COMPATIBILITY_V1'; compatibilityId:string; instanceId:string; runtimeEpoch:string; beforeGraphRef:{revisionId:string; sha256:string}; afterGraphRef:{revisionId:string; sha256:string}; beforeSlice:DomainProductionSlice; afterSlice:DomainProductionSlice; metadataApprovals:DomainMetadataApproval[]; occurrences:DomainCompatibilityOccurrence[]; requirementBindings:DomainRequirementCompatibilityBinding[]; versionBindings:DomainVersionCompatibilityBinding[]; approval:{confirmed:true; reason:string}; proofHash:string; createdAt?:string; contractAudit?:unknown};
export type ValidatedDomainProductionCompatibility = {record:DomainProductionCompatibilityRecord; classification:DomainCompatibilityClassification; requirementBindings:DomainRequirementCompatibilityBinding[]; currentRequirementBindings:DomainRequirementCompatibilityBinding[]; versionBindings:DomainVersionCompatibilityBinding[]; currentVersionBindings:DomainVersionCompatibilityBinding[]};
export type DomainCompatibilityOptions = {instanceId:string; runtimeEpoch?:string; requireCurrentEpoch?:boolean; versions?:Map<string,unknown>; executionDefinitions?:unknown[]};
export type IndexedDomainVersionCompatibility = DomainVersionCompatibilityBinding & {compatibilityId:string; proofHash:string; occurrences:DomainCompatibilityOccurrence[]};
export type IndexedDomainRequirementCompatibility = DomainRequirementCompatibilityBinding & {compatibilityId:string; proofHash:string; eligibility:'CURRENT'|'HISTORICAL_ONLY'};
export type DomainProductionCompatibilityIndex = {records:ValidatedDomainProductionCompatibility[]; byVersion:Map<string,IndexedDomainVersionCompatibility[]>; byRequirement:Map<string,IndexedDomainRequirementCompatibility[]>};
export type DomainCompatibilityException = {familyId:string; versionId:string; sha256:string; domainContextHash:string; inputBindings:DomainCompatibilityInput[]; occurrenceHashes:Map<number,string>; compatibilityIds:string[]};
export type DomainRequirementCompatibilityQuery = {requirementId:string; beforeHash:string; afterHash:string; representationId:string; representationHash:string; instanceId:string; runtimeEpoch?:string; compatibilityId?:string; proofHash?:string};
export type DomainRequirementCompatibilityBridge = IndexedDomainRequirementCompatibility & {links:Array<DomainRequirementCompatibilityBinding & {compatibilityId:string; proofHash:string}>};
export function classifyDomainProductionCompatibility(beforeSlice:unknown,afterSlice:unknown,options?:{metadataApprovals?:DomainMetadataApproval[]}):DomainCompatibilityClassification;
export function domainProductionCompatibilityProofHash(record:unknown):string;
export function validateDomainProductionCompatibilityRecord(record:unknown,options:DomainCompatibilityOptions & {model:unknown}):ValidatedDomainProductionCompatibility|null;
export function buildDomainProductionCompatibilityIndex(model:unknown,options:DomainCompatibilityOptions):DomainProductionCompatibilityIndex;
export function findCompatibleRequirementBinding(model:unknown,query:DomainRequirementCompatibilityQuery):DomainRequirementCompatibilityBridge|null;
export function findHistoricalCompatibleRequirementBinding(model:unknown,query:DomainRequirementCompatibilityQuery):DomainRequirementCompatibilityBridge|null;
export function domainCompatibilityExceptions(index:DomainProductionCompatibilityIndex):Map<string,DomainCompatibilityException>;
export function findCompatibleReviewBinding(index:DomainProductionCompatibilityIndex,query:{familyId:string;versionId:string;sha256:string;reviewEventId:string;reviewContextHash:string;reviewEventHash:string}):(IndexedDomainVersionCompatibility & {eligibility:'CURRENT'})|null;
