export type Authority = 'F' | 'A' | 'L' | 'U';
export type Evidence = { sourceId: string; revisionId: string; sha256: string; quote?: string; locator?: string };
export type DomainScope = { scopeType: 'PROJECT' | 'EPISODE' | 'SCENE' | 'SHOT'; scopeId: string; revisionId?: string };
export type DomainEntity = { id: string; type: string; name: string; aliases: string[]; description: string; authority: Authority; evidence: Evidence[] };
export type DomainState = { id: string; entityId: string; label: string; dimensions: Record<string,string>; scope: DomainScope[]; authority: Authority; evidence: Evidence[] };
export type DomainRepresentation = { unresolved?:string[]; id: string; entityId: string; stateId: string | null; type: string; label: string; dimensions: Record<string,string>; assetFamilyIds: string[]; requirementIds: string[]; authority: Authority; evidence: Evidence[] };
export type DomainNode = { kind: 'ENTITY' | 'STATE' | 'REPRESENTATION'; id: string };
export type DomainRelation = { id: string; type: string; from: DomainNode; to: DomainNode; label: string; purpose: string; inherit: string[]; exclude: string[]; scope: DomainScope[]; authority: Authority; evidence: Evidence[]; referencePolicyId?: string; status: 'PROPOSED' | 'CONFIRMED' | 'UNKNOWN'; historicalOnly?: boolean };
export type DomainRequirement = { id: string; title: string; representationId: string; mediaType: 'IMAGE' | 'AUDIO' | 'VIDEO' | 'TEXT'; category: string; scope: DomainScope[]; evidence: Evidence[]; acceptanceCriteria: string[]; reuseScope: string; composition?:import('./material-requirement-composition.mjs').RequirementComposition };
export type DomainGraph = { schemaVersion: '1.0'; entities: DomainEntity[]; states: DomainState[]; representations: DomainRepresentation[]; relations: DomainRelation[]; requirements: DomainRequirement[] };
export type DomainConfiguration = { entityTypes: Array<{id:string;label:string}>; relationTypes: Array<{id:string;label:string;class:'STORY'|'CONTINUITY'|'REFERENCE'|'COMPOSITION';directed:boolean;acyclic:boolean}>; representationTypes: Array<{id:string;label:string;mediaType:string;dimensions:string[]}>; stateDimensions: Array<{id:string;label:string}>; referencePolicies: Array<{id:string;label:string;purposes:string[];requireApprovedVersion:boolean;maxDerivedGenerations:number;allowIdentityTransfer:boolean}> };
export type SourceBinding = { sourceId: string; revisionId: string; sha256: string };
export type InitializationContent = { schemaVersion:'1.0'; title:string; summary:string; configuration:import('./configuration-model.mjs').Configuration; graph:DomainGraph; uncertainties:string[]; sourceBindings:SourceBinding[] };
export function defaultDomainConfiguration(): DomainConfiguration;
export function emptyDomainGraph(): DomainGraph;
export function validateDomainConfiguration(value: unknown): DomainConfiguration;
export function validateDomainGraph(value: unknown, options?: {configuration?:DomainConfiguration;sourceBindings?:SourceBinding[];knownFamilyIds?:string[];knownRequirementIds?:string[];knownCompositionRequirementIds?:string[]}): DomainGraph;
export function validateInitializationContent(value: unknown): InitializationContent;
export function domainHash(value: unknown): string;
export function graphImpact(previous:DomainGraph,next:DomainGraph): {added:number;changed:number;removed:number;affectedRepresentationIds:string[];referenceCount:number;unknownCount:number};
