import type {InstanceReadUnit,InstanceUnit} from './index.mjs';
import type {EntityBusinessFacts,LocationVisual} from './domain-reading.mjs';
import type {DomainGraph,DomainConfiguration} from './domain-model.mjs';
export type DomainOwner='SETTINGS'|'MATERIAL';
export type DomainCollection='entities'|'states'|'representations'|'relations'|'requirements';
export type DomainRow=DomainGraph[DomainCollection][number];
export type DomainChange={collection:DomainCollection;id:string;beforeHash:string|null;value:DomainRow|null};
export type Ownership=Record<string,{owner:DomainOwner|'UNCERTAIN';reason:string;recordHash:string}>;
export type SpatialEvidence={version?:string;sourceRef?:string;sourceSha256?:string;orientation?:string;locations?:Array<{id:string;name:string;zone?:string;fact?:string;lock?:string;entrance?:string;pos?:number[]}>;mapCards?:Array<{id:string;label:string;note?:string;imageUrl?:string;locationIds?:string[]}>;locationPackages?:Array<{locationId?:string;id?:string;name?:string;zones?:unknown[];cameras?:unknown[]}>;sceneRouteLocks?:unknown[]};
export type WorkspaceProjection={businessFacts:Record<string,EntityBusinessFacts>;locationVisuals:Record<string,LocationVisual[]>;snapshotId:string;graph:DomainGraph;ownership:Ownership;configuration:DomainConfiguration;owner:DomainOwner;requirements:Array<{id:string;title:string;mediaType?:string;category?:string;scopeBindings:unknown[];entityRef?:string;representationRef?:string;assetFamilyRefs:string[]}>;spatial:SpatialEvidence|null;context:{candidateRevisionId:string|null;currentEpisodePlanRevisionId:string|null};counts:Record<DomainCollection,number>;uncertainCount:number};
export type WorkspaceState=WorkspaceProjection&{releaseId:string;revisionId:string|null;readOnly:boolean;draft:{revisionId:string;baseReleaseId:string;changes:DomainChange[]}|null;draftHeadRevisionId:string|null;legacyDrafts:Array<{kind:string;revisionId:string}>};
export function workspaceProjection(snapshot:unknown,graph:DomainGraph,owner:string):WorkspaceProjection;
export function getDomainWorkspace(tx:InstanceReadUnit,owner:string):Promise<WorkspaceState>;
export function saveDomainWorkspace(tx:InstanceUnit,input:{owner:string;expectedReleaseId:string;expectedDraftRevisionId:string|null;changes:unknown}):Promise<{revisionId:string;releaseId:string;formalAdoptionPerformed:false}>;
export function previewDomainWorkspace(tx:InstanceReadUnit,input:{owner:string;draftRevisionId:string}):Promise<{previewHash:string;impact:{added:number;changed:number;removed:number;affectedRepresentationIds:string[]};checks:string[]}>;
export function publishDomainWorkspace(tx:InstanceUnit,input:{owner:string;draftRevisionId:string;previewHash:string;requestId:string}):Promise<Record<string,unknown>>;
export function confirmDomainOwnership(tx:InstanceUnit,input:{owner:string;expectedReleaseId:string;collection:string;id:string;recordHash:string;reason:string;requestId:string}):Promise<Record<string,unknown>>;
export function transferLegacyDraft(tx:InstanceUnit,input:{owner:string;expectedReleaseId:string;expectedDraftRevisionId:string|null;kind:string;legacyRevisionId:string}):Promise<Record<string,unknown>>;
export function rebaseDomainWorkspace(tx:InstanceUnit,input:{owner:string;expectedReleaseId:string;draftRevisionId:string}):Promise<Record<string,unknown>>;
