import { randomUUID } from 'node:crypto';
import { canonicalJson } from './bytes.mjs';
import { defaultDomainConfiguration,emptyDomainGraph,validateDomainGraph,validateInitializationContent,domainHash,graphImpact } from './domain-model.mjs';
import { listDomainSources,sourceBindingsFor,verifySourceBindings } from './domain-sources.mjs';
import { relationProjection } from './domain-projection.mjs';
import { getConfiguration,previewConfiguration } from './configuration-service.mjs';

const fail=(message,code='DOMAIN_CONFLICT')=>{throw Object.assign(new Error(message),{code});};
const read=r=>r?JSON.parse(r.bytes):null;
const save=(tx,namespace,key,value,expectedRevisionId)=>tx.putAux({namespace,key,bytes:Buffer.from(canonicalJson(value)),expectedRevisionId,mediaType:'application/json'});
const requireRelease=(view,id)=>{if(!view.releaseId||id!==view.releaseId)fail('当前发布已变化，请刷新后重新预览');};
const evidenceBindings=graph=>[...new Map(['entities','states','representations','relations','requirements'].flatMap(k=>graph[k].flatMap(r=>r.evidence||[])).map(e=>[`${e.sourceId}:${e.revisionId}`,{sourceId:e.sourceId,revisionId:e.revisionId,sha256:e.sha256}])).values()];
async function verifyQuotes(tx,graph){for(const row of ['entities','states','representations','relations','requirements'].flatMap(k=>graph[k]))for(const e of row.evidence||[])if(e.quote){const doc=await tx.readDocumentRevision(e.revisionId);if(!doc||!Buffer.from(doc.bytes).toString('utf8').includes(e.quote))fail(`来源引用无法精确回读：${row.id}`);}}
async function currentGraph(tx,view){const ref=view.snapshot?.productionModel?.domainGraphRef;if(!ref)return {graph:emptyDomainGraph(),revisionId:null};const record=await tx.getAux('domain-graph','current',{revisionId:ref.revisionId});if(!record||record.sha256!==ref.sha256)fail('已发布素材关系不可用');return {graph:read(record),revisionId:record.revisionId};}
const identityOf=(kind,row)=>kind==='entities'?{type:row.type}:kind==='states'?{entityId:row.entityId}:kind==='representations'?{entityId:row.entityId,type:row.type}:kind==='relations'?{type:row.type,from:row.from,to:row.to}:{representationId:row.representationId,mediaType:row.mediaType};
export {currentGraph, evidenceBindings, verifyQuotes, validateIdentities};
async function validateIdentities(tx,graph,view,{register=false}={}){const previous=(await currentGraph(tx,view)).graph;for(const kind of ['entities','states','representations','relations','requirements'])for(const row of graph[kind]){const key=`${kind}:${row.id}`,record=await tx.getAux('domain-identities',key),prior=previous[kind].find(r=>r.id===row.id),identity=identityOf(kind,row);if(prior&&domainHash(identityOf(kind,prior))!==domainHash(identity)||record&&domainHash(read(record))!==domainHash(identity))fail(`永久身份不能换绑，请为新对象创建身份：${row.id}`);if(record&&!prior)fail(`已退场的永久身份不能复用：${row.id}`);if(register&&!record)await save(tx,'domain-identities',key,identity,null);}}
export async function getRelations(tx,filters={}){const view=await tx.readView(),current=await currentGraph(tx,view),draft=await tx.getAux('domain-drafts','relations');return{releaseId:view.releaseId,...current,projection:relationProjection(current.graph,filters),draft:draft?{revisionId:draft.revisionId,content:read(draft).graph,baseReleaseId:read(draft).baseReleaseId}:null,defaults:defaultDomainConfiguration(),configuration:view.snapshot.productionModel.systemConfiguration?.config?.domain||defaultDomainConfiguration(),readOnly:false};}
export async function saveRelationsDraft(tx,input){const view=await tx.readView();requireRelease(view,input.expectedReleaseId);const config=await getConfiguration(tx);validateDomainGraph(input.graph,{configuration:config.configuration.domain||defaultDomainConfiguration()});const bindings=evidenceBindings(input.graph);const graph=validateDomainGraph(input.graph,{configuration:config.configuration.domain||defaultDomainConfiguration(),sourceBindings:bindings,knownFamilyIds:view.snapshot.productionModel.assetFamilies.map(r=>r.id),knownRequirementIds:(view.snapshot.productionModel.materialRequirements||[]).map(r=>r.id)});await verifySourceBindings(tx,bindings,{allowLegacy:true});await verifyQuotes(tx,graph);await validateIdentities(tx,graph,view);const draft=await save(tx,'domain-drafts','relations',{schemaVersion:'1.0',baseReleaseId:view.releaseId,graph,sourceBindings:bindings},input.expectedDraftRevisionId);return{revisionId:draft.revisionId,content:graph,releaseId:view.releaseId};}
export async function previewRelations(tx,draftRevisionId){const view=await tx.readView(),draft=await tx.getAux('domain-drafts','relations');if(!draft||draft.revisionId!==draftRevisionId)fail('关系草稿已变化');const content=read(draft);requireRelease(view,content.baseReleaseId);await verifySourceBindings(tx,content.sourceBindings,{allowLegacy:true});await verifyQuotes(tx,content.graph);const previous=await currentGraph(tx,view);const impact=graphImpact(previous.graph,content.graph);const body={draftRevisionId,baseReleaseId:view.releaseId,graphHash:domainHash(content.graph),sourceBindings:content.sourceBindings,impact};return{...body,previewHash:domainHash(body),checks:['主体与表现身份完整','引用来源与原句已精确核对','参考用途与依赖无环','既有审阅、媒体及权利事实保持'],formalAdoptionPerformed:false};}
export async function publishRelations(){fail('旧整图发布已停用，请使用所属业务工作区独立确认','DOMAIN_INVALID');}
export async function getInitialization(tx){const view=await tx.readView(),draft=await tx.getAux('initialization-drafts','current'),publishedRef=view.snapshot?.productionModel?.initialization?.revisionId,published=publishedRef?await tx.getAux('initialization','current',{revisionId:publishedRef}):null,task=await tx.getAux('initialization-tasks','current'),sources=await listDomainSources(tx);const publicTask=read(task);if(publicTask)delete publicTask.claimToken;return{releaseId:view.releaseId,state:published?'READY':draft?'DRAFT':'NOT_STARTED',sourceCount:sources.sources.length,draft:draft?{revisionId:draft.revisionId,content:read(draft).content,baseReleaseId:read(draft).baseReleaseId}:null,published:published?{revisionId:published.revisionId,content:read(published)}:null,aiTask:task?{revisionId:task.revisionId,...publicTask}:null,defaults:defaultDomainConfiguration(),readOnly:false};}
export async function prepareInitialization(tx,input){const view=await tx.readView();requireRelease(view,input.expectedReleaseId);const old=await tx.getAux('initialization-drafts','current');if(old){const task=read(await tx.getAux('initialization-tasks','current'));if(task&&['REQUESTED','RUNNING'].includes(task.state))fail('AI task is active; source refresh must wait');const previous=read(old).content;const currentSources=await sourceBindingsFor(tx);const sourceBindings=[...new Map([...previous.sourceBindings,...currentSources].map(b=>[b.sourceId,b])).values()];const content={...previous,sourceBindings};await verifySourceBindings(tx,sourceBindings,{allowLegacy:true});if(domainHash(sourceBindings)===domainHash(previous.sourceBindings)&&read(old).baseReleaseId===view.releaseId)return{revisionId:old.revisionId,content,existing:true,releaseId:view.releaseId,aiAnalysisPerformed:false};const updated=await save(tx,'initialization-drafts','current',{baseReleaseId:view.releaseId,content,origin:'SOURCES_REFRESH_PRESERVE_DRAFT'},old.revisionId);return{revisionId:updated.revisionId,content,existing:true,releaseId:view.releaseId,aiAnalysisPerformed:false};}const sources=await sourceBindingsFor(tx);if(!sources.length)fail('先导入故事原始资料，再准备初始化草稿','DOMAIN_INVALID');const config=await getConfiguration(tx),current=await currentGraph(tx,view);const configuration={...config.configuration,schemaVersion:'2.0',domain:config.configuration.domain||defaultDomainConfiguration()};const content={schemaVersion:'1.0',title:view.profile.storyTitle,summary:'',configuration,graph:current.graph,uncertainties:['发行平台、受众与未确认制作规格仍需用户补充。','来源尚未由AI整理；当前草稿仅包含已登记资料和系统默认配置。'],sourceBindings:sources};const record=await save(tx,'initialization-drafts','current',{baseReleaseId:view.releaseId,content,origin:'SYSTEM_DEFAULTS_ONLY'},null);return{revisionId:record.revisionId,content,releaseId:view.releaseId,aiAnalysisPerformed:false};}
export async function saveInitializationDraft(tx,input){const view=await tx.readView();requireRelease(view,input.expectedReleaseId);const content=validateInitializationContent(input.content);await verifySourceBindings(tx,content.sourceBindings,{allowLegacy:true});await verifyQuotes(tx,content.graph);await validateIdentities(tx,content.graph,view);const record=await save(tx,'initialization-drafts','current',{baseReleaseId:view.releaseId,content,origin:input.origin||'USER_EDIT'},input.expectedDraftRevisionId);return{revisionId:record.revisionId,content,releaseId:view.releaseId};}
export async function previewInitialization(tx,draftRevisionId){const view=await tx.readView(),record=await tx.getAux('initialization-drafts','current');if(!record||record.revisionId!==draftRevisionId)fail('初始化草稿已变化');const draft=read(record);requireRelease(view,draft.baseReleaseId);const content=validateInitializationContent(draft.content);await verifySourceBindings(tx,content.sourceBindings,{allowLegacy:true});await verifyQuotes(tx,content.graph);validateDomainGraph(content.graph,{configuration:content.configuration.domain,sourceBindings:content.sourceBindings,knownFamilyIds:view.snapshot.productionModel.assetFamilies.map(r=>r.id),knownRequirementIds:(view.snapshot.productionModel.materialRequirements||[]).map(r=>r.id)});const current=await getConfiguration(tx);const configInput={configuration:content.configuration,expectedReleaseId:view.releaseId,expectedConfigurationRevisionId:current.revisionId,upgradeKeys:[]};const configPreview=await previewConfiguration(tx,configInput);const previous=await currentGraph(tx,view);const body={draftRevisionId,baseReleaseId:view.releaseId,contentHash:domainHash(content),configurationPreviewHash:configPreview.previewHash,changedGroups:configPreview.changedGroups,impact:graphImpact(previous.graph,content.graph),uncertainties:content.uncertainties,sourceCount:content.sourceBindings.length};return{...body,previewHash:domainHash(body),checks:['来源版本和精确引用可回读','系统规则与关系将同次确认','现有对象冻结规则保留','不创建审阅放行、模型执行或正式制作分母'],formalAdoptionPerformed:false,configInput};}
export async function publishInitialization(){fail('旧初始化整包发布已停用，系统规则与业务内容须分别确认','DOMAIN_INVALID');}
export async function requestInitializationTask(tx,input){const view=await tx.readView();requireRelease(view,input.expectedReleaseId);const draft=await tx.getAux('initialization-drafts','current');if(!draft||draft.revisionId!==input.draftRevisionId)fail('先保存当前初始化草稿');const old=await tx.getAux('initialization-tasks','current');if(old&&['REQUESTED','RUNNING'].includes(read(old).state))fail('已有初始化整理任务，不能重复提交');const content=read(draft);requireRelease(view,content.baseReleaseId);await verifySourceBindings(tx,content.content.sourceBindings,{allowLegacy:true});const task={schemaVersion:'1.0',taskId:`initialize_${randomUUID()}`,state:'REQUESTED',baseReleaseId:view.releaseId,draftRevisionId:draft.revisionId,contentHash:domainHash(content.content),sourceBindings:content.content.sourceBindings,requestedAt:new Date().toISOString(),capability:'DRAFT_INITIALIZATION_ONLY',observedMedia:[],formalAdoptionPerformed:false};const saved=await save(tx,'initialization-tasks','current',task,old?.revisionId||null);return{...task,revisionId:saved.revisionId};}
/** Maintenance/worker only. Explicitly claim once; no model execution occurs in this module. */
export async function claimInitializationTask(tx,input){const record=await tx.getAux('initialization-tasks','current'),task=read(record);if(!record||record.revisionId!==input.expectedTaskRevisionId||task.state!=='REQUESTED')fail('初始化任务不能领取');if(typeof input.workerId!=='string'||!input.workerId.trim())fail('缺少工作器身份','DOMAIN_INVALID');const currentDraft=await tx.getAux('initialization-drafts','current');if((await tx.getMetadata()).releaseId!==task.baseReleaseId||currentDraft?.revisionId!==task.draftRevisionId){await save(tx,'initialization-tasks','current',{...task,state:'FAILED',error:'来源或草稿已变化，未调用模型。请刷新后发起新任务。',completedAt:new Date().toISOString(),providerEvidence:{status:'NOT_CALLED'}},record.revisionId);return null;}const claimToken=randomUUID();const next={...task,state:'RUNNING',workerId:input.workerId,claimToken,startedAt:new Date().toISOString()};const saved=await save(tx,'initialization-tasks','current',next,record.revisionId);const draft=read(await tx.getAux('initialization-drafts','current',{revisionId:task.draftRevisionId}));const sources=await listDomainSources(tx,{includeText:true});return{task:{...next,revisionId:saved.revisionId},content:draft.content,sources:sources.sources};}
export async function submitInitializationTask(tx,input){const record=await tx.getAux('initialization-tasks','current'),task=read(record);if(!record||task.state!=='RUNNING'||task.taskId!==input.taskId||task.claimToken!==input.claimToken)fail('初始化任务归属或状态不匹配');if(input.error){const saved=await save(tx,'initialization-tasks','current',{...task,state:'FAILED',error:String(input.error).slice(0,2000),providerEvidence:input.providerEvidence||{status:'UNKNOWN'},completedAt:new Date().toISOString()},record.revisionId);return{revisionId:saved.revisionId,state:'FAILED'};}const view=await tx.readView();requireRelease(view,task.baseReleaseId);const draft=await tx.getAux('initialization-drafts','current');if(draft?.revisionId!==task.draftRevisionId)fail('用户已修改草稿，AI结果不能覆盖');const content=validateInitializationContent(input.content);if(domainHash(content.sourceBindings)!==domainHash(task.sourceBindings))fail('AI不能替换冻结来源绑定');const saved=await saveInitializationDraft(tx,{expectedReleaseId:task.baseReleaseId,expectedDraftRevisionId:task.draftRevisionId,content,origin:'AI_DRAFT_ONLY'});await save(tx,'initialization-tasks','current',{...task,state:'COMPLETED',resultDraftRevisionId:saved.revisionId,completedAt:new Date().toISOString(),providerEvidence:input.providerEvidence||{status:'UNKNOWN'}},record.revisionId);return{state:'COMPLETED',draftRevisionId:saved.revisionId,formalAdoptionPerformed:false};}

/** Worker startup recovery records an interrupted attempt; it never restarts model work. */
export async function failInterruptedInitializationTask(tx,{workerId,reason='工作器中断；请求结果未知，未自动重试'}={}){const record=await tx.getAux('initialization-tasks','current'),task=read(record);if(!record||task.state!=='RUNNING')return {changed:false};if(workerId&&task.workerId!==workerId)return {changed:false};const next={...task,state:'FAILED',error:reason,executionOutcome:'UNKNOWN',completedAt:new Date().toISOString()};await save(tx,'initialization-tasks','current',next,record.revisionId);return{changed:true,taskId:task.taskId,state:'FAILED'};}
