// PostgreSQL 18 authority. Original bytes remain BYTEA; query projections are derived.
export const POSTGRES_SCHEMA_VERSION = 1;
export const BUSINESS_TABLES = ['repository_meta','record_revisions','record_heads','document_aliases','releases','domain_events','media_versions','media_aliases'];
export const POSTGRES_SCHEMA = `
CREATE TABLE repository_meta (singleton integer PRIMARY KEY CHECK(singleton=1), instance_id text NOT NULL, runtime_epoch text NOT NULL, repository_revision bigint NOT NULL DEFAULT 0, current_release_id text, created_at text NOT NULL);
CREATE TABLE record_revisions (revision_id text PRIMARY KEY, namespace text NOT NULL, record_key text NOT NULL, revision_number integer NOT NULL CHECK(revision_number>0), previous_revision_id text, content_bytes bytea NOT NULL, content_sha256 text NOT NULL CHECK(content_sha256 ~ '^[a-f0-9]{64}$'), media_type text NOT NULL, metadata_json text NOT NULL, deleted integer NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)), created_at text NOT NULL, UNIQUE(namespace,record_key,revision_number));
CREATE TABLE record_heads (namespace text NOT NULL, record_key text NOT NULL, revision_id text NOT NULL REFERENCES record_revisions(revision_id) DEFERRABLE INITIALLY DEFERRED, PRIMARY KEY(namespace,record_key));
CREATE TABLE document_aliases (alias text PRIMARY KEY, document_id text NOT NULL);
CREATE TABLE releases (release_id text PRIMARY KEY, snapshot_id text NOT NULL, snapshot_bytes bytea NOT NULL, snapshot_sha256 text NOT NULL, recipes_bytes bytea NOT NULL, recipes_sha256 text NOT NULL, source_revision_ids_json text NOT NULL, profile_revision_id text NOT NULL REFERENCES record_revisions(revision_id) DEFERRABLE INITIALLY DEFERRED, created_at text NOT NULL);
CREATE TABLE domain_events (storage_sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id text NOT NULL UNIQUE, authority_domain text NOT NULL, event_kind text NOT NULL, original_sequence bigint, recorded_at text NOT NULL, event_bytes bytea NOT NULL, event_sha256 text NOT NULL, idempotency_key_hash text, request_hash text, raw_request_hash text, source_ref_json text NOT NULL);
CREATE UNIQUE INDEX domain_event_idempotency ON domain_events(authority_domain,event_kind,idempotency_key_hash) WHERE idempotency_key_hash IS NOT NULL;
CREATE INDEX domain_event_kind ON domain_events(authority_domain,event_kind,original_sequence,recorded_at,event_id);
CREATE INDEX record_revision_identity ON record_revisions(namespace,record_key,revision_number DESC);
CREATE TABLE media_versions (media_id text NOT NULL, version_id text NOT NULL, relative_path text, sha256 text NOT NULL, byte_size bigint NOT NULL CHECK(byte_size>=0), availability text NOT NULL CHECK(availability IN ('PRESENT','MISSING_HISTORY')), metadata_json text NOT NULL, created_at text NOT NULL, PRIMARY KEY(media_id,version_id));
CREATE INDEX media_path ON media_versions(relative_path);
CREATE TABLE media_aliases (alias text NOT NULL, media_id text NOT NULL, version_id text NOT NULL, PRIMARY KEY(alias,media_id,version_id), FOREIGN KEY(media_id,version_id) REFERENCES media_versions(media_id,version_id) DEFERRABLE INITIALLY DEFERRED);
CREATE VIEW aux_current AS SELECT substr(r.namespace,5) AS namespace,r.record_key,r.revision_id,r.revision_number,r.previous_revision_id,r.content_bytes,r.content_sha256,r.media_type,r.metadata_json,r.deleted,r.created_at FROM record_heads h JOIN record_revisions r ON r.revision_id=h.revision_id WHERE r.namespace LIKE 'aux:%';
CREATE FUNCTION reject_immutable_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable business record' USING ERRCODE='23000'; END; $$;
${['record_revisions','domain_events','releases','media_versions','document_aliases','media_aliases'].map(t=>`CREATE TRIGGER ${t}_immutable BEFORE UPDATE OR DELETE ON ${t} FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();`).join('\n')}
CREATE TRIGGER instance_identity_immutable BEFORE UPDATE OF instance_id ON repository_meta FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();
CREATE TABLE repository_schema (singleton integer PRIMARY KEY CHECK(singleton=1), version integer NOT NULL, application_id integer NOT NULL, schema_sha256 text NOT NULL);
`;
