import type {InstanceReadUnit,InstanceUnit,InstanceRepository} from './index.mjs';
export {selectShotRecipeInputFamilies,shotRecipeProductionBasis,shotRecipeDefinitionBindingReasons} from './shot-production-recipe-basis.mjs';
export const SHOT_RECIPE_NS:{drafts:string;jobs:string;requests:string};
export type ShotRecipeContent = {model:string;prompt:string;negativePrompt:string;parameters:Record<string,unknown>};
export type ShotRecipeInput = {order:number;path:string;assetFamilyRef:string;assetVersionRef:string;sha256:string;label:string};
export type ShotRecipeExpectedOutput = Record<string,unknown> & {id:string;familyId:string;targetPath:string;plannedVersionLabel:string;expectationState:string;realizedVersionId:string|null};
export type ShotRecipeDefinition = {
  id:string;title:string;pipelineStageCode:string;executorKind:'MODEL_CALL';definitionStatus:'DEFINED';workItemRef:string;currentRevisionId:string;
  upload:{rawText:string;items:Array<Omit<ShotRecipeInput,'label'>>};model:{branch:string;rawRule:string;resolution:string};
  parameters:Record<string,unknown>;parametersRaw:string;prompt:{main:string;negative:string;negativeApplication:'APPLY_WITH_MAIN_PROMPT'|'NONE'};
  output:{path:string;mediaType:string;assetFamilyRef:string;expectedOutputRef:string};declaredGate:'READY_TO_START';rawSourceBlock:string;
  authoringContent:ShotRecipeContent;productionBasis:Record<string,unknown>;productionBasisHash:string;parentVersionId:string|null;
  definitionHashSchemaVersion:string;definitionHash:string;
};
export type ShotRecipePreview = {workItemId:string;draftRevisionId:string;expectedReleaseId:string;basisHash:string;definition:ShotRecipeDefinition;expectedOutput:ShotRecipeExpectedOutput;previousDefinitionId:string|null;previewHash:string;modelCalls:0};
export type ShotRecipeWorkspace = {
  workItemId:string;releaseId:string|null;draftHeadRevisionId:string|null;
  draft:{workItemId:string;content:ShotRecipeContent;baseReleaseId:string;basisHash:string;revisionId:string}|null;
  current:{definitionId:string;content:ShotRecipeContent}|null;defaults:ShotRecipeContent;inputs:ShotRecipeInput[];
  output:ShotRecipeExpectedOutput|null;blockers:string[];basis:Record<string,unknown>;basisHash:string;readOnly:false;
  jobs:Array<{jobId:string;status:string;error?:string}>;
};
export type ShotRecipeDraftInput = {workItemId:string;expectedReleaseId:string;expectedDraftRevisionId:string|null;content:unknown};
export type ShotRecipePreviewInput = {workItemId:string;draftRevisionId:string};
export type ShotRecipePublishInput = ShotRecipePreviewInput & {previewHash:string;requestId:string};
export type ShotRecipeJobResult = {releaseId:string;definitionId:string;definitionHash:string;modelCalls:0};
export function validateShotRecipeContent(value:unknown):ShotRecipeContent;
export function shotRecipeExpectedOutput(model:unknown,sourceModel:unknown,familyId:string):ShotRecipeExpectedOutput|null;
export function compileShotRecipePreview(context:unknown,content:unknown,options:{draftRevisionId:string}):ShotRecipePreview;
export function getShotRecipeWorkspace(tx:InstanceReadUnit,input:{workItemId:string;api:unknown}):Promise<ShotRecipeWorkspace>;
export function saveShotRecipeDraft(tx:InstanceUnit,input:ShotRecipeDraftInput,options:{api:unknown}):Promise<{revisionId:string;formalAdoptionPerformed:false}>;
export function previewShotRecipe(tx:InstanceReadUnit,input:ShotRecipePreviewInput,options:{api:unknown}):Promise<ShotRecipePreview>;
export function enqueueShotRecipe(tx:InstanceUnit,input:ShotRecipePublishInput,options:{api:unknown}):Promise<{jobId:string;status:'QUEUED';modelCalls:0}>;
export function applyShotRecipeJob(tx:InstanceUnit,input:{jobId:string;api:unknown}):Promise<ShotRecipeJobResult>;
export function runShotRecipeIteration(input:{repository:InstanceRepository;api:unknown}):Promise<{processed:false}|({processed:true;status:'SUCCEEDED'}&ShotRecipeJobResult)|{processed:true;jobId:string;status:'FAILED'}>;
