import {spawn} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const target=process.env.REVIEW_BUILD_TARGET||'node';
if(!['node','sites'].includes(target))throw Error('REVIEW_BUILD_TARGET must be node or sites');
if(target==='sites'&&(!process.env.REVIEW_EXPORT_DIR||process.env.REVIEW_NODE_RUNTIME==='1'))throw Error('Sites requires an explicit verified export and cannot use the Node target');
const env={...process.env,REVIEW_BUILD_TARGET:target,REVIEW_NODE_RUNTIME:target==='node'?'1':'0'};
if(target==='sites')env.REVIEW_REMOTE_READ_ONLY='1';
else if(env.REVIEW_EXPORT_DIR)throw Error('Node software builds are neutral; use the explicit Sites target for a hosted export');
const run=(command,args)=>new Promise((resolve,reject)=>{const p=spawn(command,args,{cwd:root,env,stdio:'inherit'});p.on('error',reject);p.on('exit',(code,signal)=>code===0?resolve():reject(new Error(`Build command failed: ${command} (exit=${code}, signal=${signal})`)));});
await run(process.execPath,['scripts/prepare-hosted-runtime.mjs']);
await run(process.execPath,['node_modules/vinext/dist/cli.js','build']);
