/** Exact-owner SQLite -> PostgreSQL cutover. `plan` never stops or writes an instance. */
import {readFile,writeFile,lstat,realpath,rm} from 'node:fs/promises';
import path from 'node:path';
import {parseArgs} from 'node:util';
import {pathToFileURL} from 'node:url';
import {canonicalJson,sha256} from '../host/instance-runtime/bytes.mjs';
import {resolveStorageOwner,runInstanceCli} from '../host/instance-runtime/transport.mjs';
import {applicationRoot,instanceComposeProject} from './instance-profile.mjs';
import {runMaintenanceProcess} from './instance-maintenance.mjs';
import {docker,pgBootstrap,ensurePostgres} from './instance-postgres.mjs';
import {dockerHostPath} from '../host/instance-runtime/docker-path.mjs';
import {stableRootInputs,switchStableRoot,restoreStableRoot,probeStableRoot,frozenSqliteFiles} from './instance-cutover-files.mjs';
import {verifyFreezeProof,authorizeFrozenStart,clearFreezeMarker} from './instance-freeze-proof.mjs';

const check=(ok,message)=>{if(!ok)throw new Error(message);};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const safeDiagnostic=value=>String(value||'').replace(/(Bearer\s+)[^\s"']+/gi,'$1[REDACTED]').replace(/\bsk-[A-Za-z0-9_-]+/g,'[REDACTED]').replace(/([a-z][a-z0-9+.-]*:\/\/)[^/\s:@]+:[^@\s/]+@/gi,'$1[REDACTED]@').replace(/((?:password|api[_-]?key|token)\s*[=:]\s*)[^\s,;"']+/gi,'$1[REDACTED]').slice(0,8192);
async function absent(filename){try{await lstat(filename);throw new Error('A cutover target already exists: '+filename);}catch(e){if(e.code!=='ENOENT')throw e;}}
async function regular(filename){const info=await lstat(filename);check(info.isFile()&&!info.isSymbolicLink()&&await realpath(filename)===filename,'Cutover input must be a canonical regular file');return readFile(filename);}
async function allContainers(){const ids=(await docker(['ps','-aq'])).toString().trim().split('\n').filter(Boolean);return ids.length?JSON.parse(await docker(['inspect',...ids])):[];}
const labels=c=>c.Config?.Labels||{};
const bound=(c,root)=>c.Mounts?.some(m=>m.Type==='bind'&&m.Destination==='/instance/instance.json'&&dockerHostPath(m.Source)===path.join(root,'instance.json'));
const published=(c,port)=>Object.values(c.HostConfig?.PortBindings||c.NetworkSettings?.Ports||{}).flat().some(p=>p&&p.HostPort===String(port));
const brief=c=>({id:c.Id,name:c.Name.replace(/^\//,''),imageId:c.Image,service:labels(c)['com.docker.compose.service']||null,running:Boolean(c.State.Running),instanceRoot:dockerHostPath(c.Mounts?.find(m=>m.Destination==='/instance/instance.json')?.Source)?.replace(/\/instance\.json$/,'')||null});
const metadata=x=>Object.fromEntries(['instanceId','runtimeEpoch','repositoryRevision','releaseId','profileRevisionId','snapshotId'].map(k=>[k,x[k]]));
const safeEnv=()=>Object.fromEntries(Object.entries(process.env).filter(([key])=>['PATH','HOME','LANG','LC_ALL','TMPDIR','TZ','DOCKER_HOST','DOCKER_CONTEXT','DOCKER_CONFIG','DOCKER_TLS_VERIFY','DOCKER_CERT_PATH'].includes(key)));
async function processes(){return (await runMaintenanceProcess('ps',['-axo','pid=,ppid=,command='],{env:safeEnv()})).stdout.split('\n').map(line=>{const m=line.trim().match(/^(\d+)\s+(\d+)\s+(.+)$/);return m?{pid:Number(m[1]),parentPid:Number(m[2]),command:m[3]}:null;}).filter(Boolean);}
async function hostProcesses(root){
 const rows=await processes(),selected=new Map();
 for(const row of rows)if(row.command.includes(root)&&/instance-(?:bridge|maintenance-worker)\.mjs|codex_conversation_bridge\.py/.test(row.command))selected.set(row.pid,row);
 for(const name of ['runtime/assistant/public/.bridge.lock','runtime/locks/maintenance-host.json']){try{const content=(await regular(path.join(root,name))).toString(),pid=name.endsWith('.json')?JSON.parse(content).pid:Number(content.split('\n')[0]),row=rows.find(r=>r.pid===pid);if(row){check(/codex_conversation_bridge\.py|instance-maintenance-worker\.mjs/.test(row.command),'A runtime lock points to an unrelated live process');selected.set(pid,row);}}catch(e){if(e.code!=='ENOENT')throw e;}}
 // Descendants of these verified bridge/maintenance processes belong to their
 // runtime, never to another localhost service selected by its port number.
 let grew;do{grew=false;for(const row of rows)if(selected.has(row.parentPid)&&!selected.has(row.pid)){selected.set(row.pid,row);grew=true;}}while(grew);
 return [...selected.values()].map(row=>({pid:row.pid,parentPid:row.parentPid,commandSha256:sha256(row.command),role:/maintenance-worker/.test(row.command)?'MAINTENANCE':/bridge/.test(row.command)?'BRIDGE':'OWNED_CHILD'}));
}
async function backupManifest(root){const manifest=JSON.parse(await regular(path.join(root,'backup-manifest.json'))),{manifestSha256,...body}=manifest;check(body.schemaVersion==='1.0'&&body.kind==='REVIEW_INSTANCE_BACKUP'&&sha256(canonicalJson(body))===manifestSha256,'A verified SQLite backup manifest is required');check(manifest.database?.path==='data/review.sqlite','Cutover backup must bind its SQLite database');const database=await regular(path.join(root,manifest.database.path));check(database.length===manifest.database.bytes&&sha256(database)===manifest.database.sha256,'Frozen SQLite backup bytes differ from their verified manifest');return manifest;}
export async function planCutover({instance,stage,backup,archive,port=3000,softwareCommit='UNVERSIONED',freeze}){
 check(Number.isInteger(Number(port))&&Number(port)>0&&Number(port)<65536,'Use a valid local runtime port');
 const sourceRoot=await realpath(path.resolve(instance)),stageRoot=await realpath(path.resolve(stage)),backupRoot=await realpath(path.resolve(backup)),archiveRoot=path.resolve(archive);await absent(archiveRoot);
 check(sourceRoot!==stageRoot&&path.dirname(sourceRoot)===path.dirname(stageRoot)&&path.dirname(sourceRoot)===path.dirname(archiveRoot)&&await realpath(path.dirname(archiveRoot))===path.dirname(archiveRoot),'Source, PostgreSQL stage and new archive must be canonical sibling directories');
 check(softwareCommit==='UNVERSIONED'||/^[a-f0-9]{40,64}$/.test(softwareCommit),'Use a full software commit identity');
 const sourceBoot=JSON.parse(await regular(path.join(sourceRoot,'instance.json'))),pg=await pgBootstrap(stageRoot),stageBoot=pg.bootstrap;
 check(sourceBoot.schemaVersion==='1.0'&&sourceBoot.instanceId===stageBoot.instanceId,'Cutover requires the same story identity and an existing SQLite authority');
 await absent(path.join(stageRoot,'runtime/storage-owner.json'));
 const frozenProof=freeze?await verifyFreezeProof(freeze,{sourceRoot,port}):null;
 const owner=await resolveStorageOwner(sourceRoot,{allowStopped:Boolean(frozenProof)}),current=await runInstanceCli(sourceRoot,['host-profile'],{allowStoppedReadOnly:Boolean(frozenProof)}),staged=await runInstanceCli(stageRoot,['host-profile']),manifest=await backupManifest(backupRoot);
 check(owner&&(owner.running||frozenProof)&&!owner.readOnly&&manifest.instanceId===current.instanceId&&manifest.repositoryRevision===current.repositoryRevision&&manifest.releaseId===current.releaseId,'Live SQLite authority has drifted from the migration backup');
 if(frozenProof)check(canonicalJson(metadata(current))===canonicalJson(metadata(frozenProof.metadata)),'Frozen source watermark changed');
 const restoreProof=JSON.parse(await regular(path.join(stageRoot,'data/restore-proof.json')));check(restoreProof.status==='RESTORED_VERIFIED'&&restoreProof.originalBytesPreserved===true&&restoreProof.businessIdsPreserved===true&&restoreProof.runtimeEpoch===staged.runtimeEpoch&&restoreProof.instanceId===current.instanceId&&restoreProof.releaseId===manifest.releaseId&&restoreProof.repositoryRevision===manifest.repositoryRevision+1,'PostgreSQL stage lacks its exact restore proof');
 const containers=await allContainers(),web=containers.find(c=>c.Id===owner.containerId);check(web&&published(web,port)&&bound(web,sourceRoot),'The selected runtime is not the exact requested local port owner');
 const project=labels(web)['com.docker.compose.project'];check(project,'The SQLite owner has no Compose identity');
 const workers=containers.filter(c=>labels(c)['com.docker.compose.project']===project&&['comment-polish-worker','material-review-worker'].includes(labels(c)['com.docker.compose.service']));check(workers.every(c=>bound(c,sourceRoot)),'A selected worker is bound to another instance');
 const protectedContainers=containers.filter(c=>[3000,3001,8787,4189].filter(p=>p!==Number(port)).some(p=>published(c,p)));check(![web,...workers].some(c=>protectedContainers.some(p=>p.Id===c.Id)),'An unrelated protected local service entered the cutover set');
 const activeWorkers=workers.filter(c=>frozenProof?frozenProof.oldContainers.find(old=>old.id===c.Id)?.running:c.State.Running),keySources=[...new Set(activeWorkers.flatMap(c=>c.Mounts.filter(m=>m.Destination==='/run/secrets/openai_api_key').map(m=>dockerHostPath(m.Source))))],caSources=[...new Set(activeWorkers.flatMap(c=>c.Mounts.filter(m=>m.Destination==='/run/certs/provider-ca.pem').map(m=>dockerHostPath(m.Source))))];
 check(activeWorkers.length===0||activeWorkers.length===2&&keySources.length===1,'Preserve either the disabled AI state or both healthy configured workers');
 check(keySources.length<=1&&caSources.length<=1&&keySources.every(p=>p===path.join(sourceRoot,'runtime/private/provider/openai_api_key')),'Provider credential bindings differ across the selected workers');for(const filename of [...keySources,...caSources])await regular(filename);
 const caSourcePath=caSources[0]||null,caCopyRelativePath=null,caFile=caSourcePath,caSha256=caSourcePath?sha256(await regular(caSourcePath)):null;
 const pgContainer=containers.find(c=>c.Name==='/'+pg.container);check(pgContainer&&pgContainer.Mounts.some(m=>m.Type==='volume'&&m.Name===pg.volume),'The stage PostgreSQL volume owner is missing');
 const body={schemaVersion:'2.0',strategy:'STABLE_ROOT_LOCATOR',stableFiles:await stableRootInputs(sourceRoot,stageRoot),freeze:frozenProof?{file:frozenProof.file,proofSha256:frozenProof.proofSha256}:null,mode:'PLAN_ONLY',createdAt:new Date().toISOString(),sourceRoot,stageRoot,archiveRoot,backupRoot,port:Number(port),softwareRoot:applicationRoot,softwareCommit,instanceId:current.instanceId,projectId:current.profile.projectId,source:metadata(current),stage:metadata(staged),sourceOwnerHash:owner.markerSha256,sourceBackupManifestSha256:manifest.manifestSha256,sourceDatabaseSha256:manifest.database.sha256,oldComposeProject:project,newComposeProject:instanceComposeProject(stageBoot,sourceRoot),oldContainers:frozenProof?frozenProof.oldContainers:[web,...workers].map(brief),hostProcesses:await hostProcesses(sourceRoot),frozenHostProcesses:frozenProof?.hostProcesses||[],protectedContainers:protectedContainers.map(brief),providerKeyRelativePath:keySources.length?'runtime/private/provider/openai_api_key':null,caSourcePath,caCopyRelativePath,caFile,caSha256,postgres:{container:pg.container,containerId:pgContainer.Id,volume:pg.volume,network:pg.network},steps:['BUILD_EXACT_IMAGES_BEFORE_FREEZE','STOP_EXACT_HOST_AND_SQLITE_OWNERS','VERIFY_FROZEN_REVISION_AND_BACKUP','ARCHIVE_SQLITE_CONTROLS_KEEP_PROVIDER_MEDIA_AND_BIND_INODES','SWITCH_LOCATOR_IN_PLACE','VERIFY_DAEMON_BOOTSTRAP_DATA_MEDIA_SECRET_BYTES','RECREATE_ONLY_POSTGRES_CONTAINER_KEEP_VOLUME','START_NEW_COMPOSE_GENERATION_AND_VERIFY','KEEP_OLD_CONTAINERS_AND_ARCHIVE_FOR_ROLLBACK'],modelCalls:0,mutationPerformed:false};
 return {...body,planSha256:sha256(canonicalJson(body))};
}
async function stopHostProcesses(planned){const rows=await processes();for(const item of planned){const current=rows.find(r=>r.pid===item.pid);if(!current)continue;check(sha256(current.command)===item.commandSha256,'Host PID was reused by another command');try{process.kill(item.pid,'SIGTERM');}catch(error){if(error.code!=='ESRCH')throw error;}}for(let i=0;i<100;i++){const live=await processes();if(!planned.some(p=>live.some(r=>r.pid===p.pid&&sha256(r.command)===p.commandSha256)))return;await sleep(100);}throw new Error('An owned host process did not stop; no forced unknown-process termination was attempted');}
export async function executeCutover(plan,planFile){
 const{planSha256,...body}=plan;check(plan.schemaVersion==='2.0'&&plan.strategy==='STABLE_ROOT_LOCATOR'&&plan.mode==='PLAN_ONLY'&&sha256(canonicalJson(body))===planSha256,'Cutover plan changed');check(/^[a-f0-9]{40,64}$/.test(plan.softwareCommit),'Execution requires an exact final software commit, not UNVERSIONED');check(applicationRoot===plan.softwareRoot,'Execute from the exact planned software directory');
 const journalFile=path.resolve(planFile)+'.execution.json';await absent(journalFile);let phase='PREFLIGHT',stopped=Boolean(plan.freeze);const fileState={};
 const journal={schemaVersion:'2.0',strategy:'STABLE_ROOT_LOCATOR',planSha256,startedAt:new Date().toISOString(),status:'IN_PROGRESS',phase};const save=async(extra={})=>{Object.assign(journal,{phase,fileState:{...fileState},...extra});await writeFile(journalFile,JSON.stringify(journal,null,2)+'\n',{mode:0o600});};
 const verifyFreshPlan=async()=>{const fresh=await planCutover({instance:plan.sourceRoot,stage:plan.stageRoot,backup:plan.backupRoot,archive:plan.archiveRoot,port:plan.port,softwareCommit:plan.softwareCommit,freeze:plan.freeze?.file});for(const key of ['freeze','stableFiles','source','stage','sourceOwnerHash','oldContainers','hostProcesses','frozenHostProcesses','protectedContainers','postgres','oldComposeProject','newComposeProject','projectId','sourceBackupManifestSha256','sourceDatabaseSha256','providerKeyRelativePath','caSourcePath','caCopyRelativePath','caFile','caSha256'])check(canonicalJson(fresh[key])===canonicalJson(plan[key]),'Cutover preflight changed: '+key);};
 const verifyFrozenOwner=async()=>{if(plan.freeze)await verifyFreezeProof(plan.freeze.file,{sourceRoot:plan.sourceRoot,port:plan.port});const owner=await resolveStorageOwner(plan.sourceRoot,{allowStopped:true});check(owner&&!owner.running&&owner.markerSha256===plan.sourceOwnerHash&&owner.containerId===plan.oldContainers.find(c=>c.service==='review-site')?.id,'SQLite owner changed during the freeze; another deployment must be reconciled before cutover');check((await hostProcesses(plan.sourceRoot)).length===0,'A new bridge or maintenance process appeared during the freeze');};
 await verifyFreshPlan();
 const hasGit=Boolean(await lstat(path.join(applicationRoot,'.git')).catch(()=>null));let packageManifestSha256;
 const verifySoftware=async()=>{
  if(hasGit){const version=await runMaintenanceProcess('git',['-C',applicationRoot,'rev-parse','HEAD'],{env:safeEnv()});check(version.stdout.trim()===plan.softwareCommit,'Checkout differs from the planned software commit');check(!(await runMaintenanceProcess('git',['-C',applicationRoot,'status','--porcelain'],{env:safeEnv()})).stdout.trim(),'Cutover software checkout is dirty');return;}
  const manifestBytes=await regular(path.join(applicationRoot,'software-manifest.json')),manifestHash=sha256(manifestBytes),manifest=JSON.parse(manifestBytes);
  check(manifest.kind==='STORY_NEUTRAL_SOFTWARE'&&manifest.copiedBusinessData===false&&manifest.softwareCommit===plan.softwareCommit&&Array.isArray(manifest.files),'Packaged software identity differs');
  if(packageManifestSha256)check(manifestHash===packageManifestSha256,'Software manifest changed during cutover');else packageManifestSha256=manifestHash;
  for(const file of manifest.files){check(typeof file.path==='string'&&!path.isAbsolute(file.path)&&file.path.split('/').every(part=>part&&part!=='.'&&part!=='..'),'Packaged software path is invalid');check(sha256(await regular(path.join(applicationRoot,file.path)))===file.sha256,'Packaged software changed: '+file.path);}
  check(sha256(await regular(path.join(applicationRoot,'software-manifest.json')))===packageManifestSha256,'Software manifest changed during verification');
 };
 await verifySoftware();
 await save();
 try{
  phase='BUILD_EXACT_IMAGES';await save();const buildEnv={...safeEnv(),REVIEW_SOFTWARE_COMMIT:plan.softwareCommit,REVIEW_INSTANCE_ID:plan.newComposeProject.slice('review-'.length),REVIEW_PROJECT_ID:plan.projectId,REVIEW_INSTANCE_ROOT:plan.stageRoot,REVIEW_PORT:String(plan.port),REVIEW_OPENAI_API_KEY_FILE:'/dev/null'};const services=plan.providerKeyRelativePath?['review-site','comment-polish-worker','material-review-worker']:['review-site'];await runMaintenanceProcess('docker',['compose','--project-name',plan.newComposeProject,'--file',path.join(applicationRoot,'compose.yaml'),'--profile','assistant-ai','build','--no-cache',...services],{env:buildEnv});for(const service of services){const built=JSON.parse(await docker(['image','inspect',plan.newComposeProject+'-'+service]))[0];check(built.Config.Labels?.['org.opencontainers.image.revision']===plan.softwareCommit,'Prebuilt image differs from the final software commit');}await verifySoftware();await save({softwareManifestSha256:packageManifestSha256||null});
  // A build may take minutes. Recheck exact owners, all instance watermarks and
  // protected services before the first stop, rather than trusting an old plan.
  await verifyFreshPlan();
  phase='FREEZE';await save();await stopHostProcesses(plan.hostProcesses);stopped=true;for(const c of [...plan.oldContainers].reverse())if(c.running)await docker(['stop','--time','30',c.id]);await verifyFrozenOwner();
  const frozen=await runInstanceCli(plan.sourceRoot,['host-profile'],{allowStoppedReadOnly:true});check(frozen.repositoryRevision===plan.source.repositoryRevision&&frozen.releaseId===plan.source.releaseId&&frozen.runtimeEpoch===plan.source.runtimeEpoch,'Source changed while stopping workers; rebackup and remigrate before retrying');
  const frozenBackup=journalFile+'.frozen-backup';await absent(frozenBackup);await runMaintenanceProcess(process.execPath,[path.join(applicationRoot,'scripts/instance-backup.mjs'),'--instance',plan.sourceRoot,'--output',frozenBackup],{env:safeEnv()});const frozenManifest=await backupManifest(frozenBackup);check(frozenManifest.database.sha256===plan.sourceDatabaseSha256,'Final frozen SQLite bytes differ from the migrated backup');fileState.sourceDataFiles=await frozenSqliteFiles(plan.sourceRoot);await save({frozenBackup,frozenManifestSha256:frozenManifest.manifestSha256});
  if(plan.caSourcePath)check(sha256(await regular(plan.caSourcePath))===plan.caSha256,'Provider CA changed after planning');
  phase='SWITCH_STABLE_ROOT';await save();await verifyFrozenOwner();await verifySoftware();await switchStableRoot(plan,fileState,save,verifyFrozenOwner);await save({providerAndPrivatePathsRetained:true,mediaPathsRetained:true,activeSchedulerCopied:false});
  phase='VERIFY_DAEMON_BIND_VIEW';await save();await save({bindProbe:await probeStableRoot(plan,{fileState})});
  phase='RECREATE_DATABASE_OWNER';await save();const currentPg=JSON.parse(await docker(['inspect',plan.postgres.containerId]))[0];check(currentPg.Id===plan.postgres.containerId&&currentPg.Mounts.some(m=>m.Type==='volume'&&m.Name===plan.postgres.volume),'PostgreSQL owner changed before rebinding');await docker(['rm','-f',plan.postgres.containerId]);await ensurePostgres(plan.sourceRoot);
  phase='START_POSTGRES_RUNTIME';await save();await authorizeFrozenStart(plan);const env={...safeEnv(),REVIEW_SOFTWARE_COMMIT:plan.softwareCommit,...(plan.providerKeyRelativePath?{REVIEW_OPENAI_API_KEY_FILE:path.join(plan.sourceRoot,plan.providerKeyRelativePath)}:{})};const args=[path.join(applicationRoot,'scripts/instance-start.mjs'),'--instance',plan.sourceRoot,'--port',String(plan.port),'--no-build',...(plan.freeze?['--freeze',plan.freeze.proofSha256]:[]),...(!plan.providerKeyRelativePath?['--offline']:[]),...(plan.caFile?['--ca-file',plan.caFile]:[])];await runMaintenanceProcess(process.execPath,args,{env});
  const result=await(await fetch(`http://127.0.0.1:${plan.port}/api/instance/runtime`,{signal:AbortSignal.timeout(30000)})).json();check(result.instanceId===plan.instanceId&&result.releaseId===plan.stage.releaseId&&result.runtimeEpoch===plan.stage.runtimeEpoch&&result.storageMode==='SINGLE_INSTANCE_POSTGRESQL','New formal runtime differs from the staged authority');
  for(const protectedOwner of plan.protectedContainers){const c=JSON.parse(await docker(['inspect',protectedOwner.id]))[0];check(c.State.Running===protectedOwner.running,'An unrelated local service changed state');}
  if(plan.freeze)await clearFreezeMarker(plan.sourceRoot,plan.freeze.proofSha256);
  phase='COMPLETE';await save({status:'CUTOVER_VERIFIED',completedAt:new Date().toISOString(),runtime:{instanceId:result.instanceId,releaseId:result.releaseId,runtimeEpoch:result.runtimeEpoch},oldContainersRetained:true,rollbackArchive:plan.archiveRoot,bridgeRestartRequired:[...plan.hostProcesses,...(plan.frozenHostProcesses||[])].some(p=>p.role==='BRIDGE')});return journal;
 }catch(error){
  await save({status:'ROLLBACK_IN_PROGRESS',failedPhase:phase,error:safeDiagnostic(error.message),errorCode:safeDiagnostic(error.code),errorDetail:safeDiagnostic(error.detail||error.stderr)});let rollbackError=null;
  try{
   if(fileState.locatorChanged){await stopHostProcesses(await hostProcesses(plan.sourceRoot));const created=(await allContainers()).filter(c=>labels(c)['com.docker.compose.project']===plan.newComposeProject&&bound(c,plan.sourceRoot));for(const c of created)await docker(['rm','-f',c.Id]);let pc;try{pc=JSON.parse(await docker(['inspect',plan.postgres.container]))[0];}catch(e){if(e.code!=='POSTGRES_DOCKER_FAILED')throw e;}if(pc){check(pc.Mounts.some(m=>m.Type==='volume'&&m.Name===plan.postgres.volume),'Rollback PostgreSQL volume differs');await docker(['rm','-f',pc.Id]);}const marker=path.join(plan.sourceRoot,'runtime/storage-owner.json');let saved;try{saved=JSON.parse(await regular(marker));}catch(e){if(e.code!=='ENOENT')throw e;}if(saved&&sha256(await regular(marker))!==plan.sourceOwnerHash){check(saved.schemaVersion==='2.0'&&saved.instanceId===plan.instanceId&&saved.hostRoot===plan.sourceRoot&&saved.composeProject===plan.newComposeProject,'Rollback runtime marker differs');await rm(marker);}}
   if(fileState.archiveCreated){await restoreStableRoot(plan,fileState);await save({rollbackBindProbe:await probeStableRoot(plan,{postgres:false,fileState})});}
   if(stopped){for(const c of plan.oldContainers)if(c.running)await docker(['start',c.id]);let restored=false;for(let attempt=0;attempt<60;attempt++){try{const response=await fetch(`http://127.0.0.1:${plan.port}/api/instance/runtime`,{signal:AbortSignal.timeout(2000)}),runtime=await response.json();restored=response.ok&&runtime.instanceId===plan.instanceId&&runtime.releaseId===plan.source.releaseId&&runtime.runtimeEpoch===plan.source.runtimeEpoch;if(restored)break;}catch{}await sleep(500);}check(restored,'Original SQLite runtime failed rollback health verification');if(plan.freeze)await clearFreezeMarker(plan.sourceRoot,plan.freeze.proofSha256);}
   if(await lstat(path.join(plan.stageRoot,'instance.json')).catch(()=>null))await ensurePostgres(plan.stageRoot);
  }catch(e){rollbackError=safeDiagnostic(e.message);await save({rollbackErrorCode:safeDiagnostic(e.code),rollbackErrorDetail:safeDiagnostic(e.detail||e.stderr)});}
  phase='FAILED';await save({status:rollbackError?'ROLLBACK_REQUIRES_ATTENTION':'ROLLED_BACK',rollbackError,hostProcessesRequireRestart:plan.hostProcesses.length+(plan.frozenHostProcesses||[]).length>0,completedAt:new Date().toISOString()});throw new Error(`Cutover failed; ${journal.status}. Inspect ${journalFile}`);
 }
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const{values,positionals}=parseArgs({allowPositionals:true,options:{instance:{type:'string'},stage:{type:'string'},backup:{type:'string'},archive:{type:'string'},port:{type:'string'},'software-commit':{type:'string'},output:{type:'string'},plan:{type:'string'},freeze:{type:'string'}}});check(positionals.length===1&&['plan','execute'].includes(positionals[0]),'Use plan or explicitly authorized execute');if(positionals[0]==='plan'){check(values.instance&&values.stage&&values.backup&&values.archive&&values.output,'plan requires --instance --stage --backup --archive --output');const plan=await planCutover({instance:values.instance,stage:values.stage,backup:values.backup,archive:values.archive,port:values.port||3000,softwareCommit:values['software-commit']||'UNVERSIONED',freeze:values.freeze});await writeFile(values.output,JSON.stringify(plan,null,2)+'\n',{flag:'wx',mode:0o600});console.log(JSON.stringify(plan,null,2));}else{check(values.plan,'execute requires --plan');const file=await realpath(values.plan);console.log(JSON.stringify(await executeCutover(JSON.parse(await regular(file)),file),null,2));}}
